### ISSUE TITLE
多级目录的缩进太短

### ISSUE THREAD

**Issue by leiwei2094** [volantis-x/hexo-theme-volantis#101]
多级目录之间的缩进太短了，根本无法区分目录级别。见下面的截图：

![image](https://user-images.githubusercontent.com/2031602/65328053-f6706480-dbe7-11e9-877d-922e7950dd9e.png)

**Comment by xaoxuu** [comment]
这是因为你的目录中有层级跳跃的情况，渲染出错了，建议目录层级按顺序来。
<img width="257" alt="QQ20191011-142606@2x" src="https://user-images.githubusercontent.com/16400144/66629064-38168d00-ec33-11e9-9d98-d54a56708a47.png">

**Comment by leiwei2094** [comment]
我的目录没有跳跃，是按照一级，二级的顺序。
同时我看到https://mxclub.github.io/test/elements/这个Demo中的目录缩进也不对。一级和二级目录缩进太短。
![image](https://user-images.githubusercontent.com/2031602/66704087-a2baec00-ed4b-11e9-9bff-bb53a91a9820.png)

**Comment by YujieShui** [comment]
> 这是因为你的目录中有层级跳跃的情况，渲染出错了，建议目录层级按顺序来。
> <img alt="QQ20191011-142606@2x" width="257" src="https://user-images.githubusercontent.com/16400144/66629064-38168d00-ec33-11e9-9d98-d54a56708a47.png">

没有层级跳跃，一级标题和二级标题之间就是离得很近。

**Comment by xaoxuu** [comment]
@vangoleo @YujieShui 哦是这样的，一级和二级确实离得很近，因为设计的时候出于SEO优化角度考虑没有考虑显示一级标题H1，文章内部的子标题从H2开始，一个页面唯一的一个H1级标题是文章的大标题。建议修改一下从H2开始，也可以等我在后续的更新中优化一下。
