### ISSUE TITLE
请问名章名字右边的小图片如何设置？？

### ISSUE THREAD

**Issue by gaoyanliang** [volantis-x/hexo-theme-volantis#105]
请问名章名字右边的小图片如何设置？？
效果图如下
![image](https://user-images.githubusercontent.com/33021341/66106409-5efc1000-e5f0-11e9-95a4-3b203f652d4c.png)

**Comment by xaoxuu** [comment]
文档：https://xaoxuu.com/wiki/material-x/pages/index.html#Front-matter

<img width="748" alt="image" src="https://user-images.githubusercontent.com/16400144/66629205-a8251300-ec33-11e9-837a-b9dc8cf9f259.png">
