### ISSUE TITLE
本地字体无法加载

### ISSUE THREAD

**Issue by HaleShaw** [volantis-x/hexo-theme-volantis#106]
添加自定义本地字体，是直接将字体文件放在`source\fonts\`目录下吗？
_font.less里面已经添加了字体定义:

```
@fontfamily_title: 'HYSunWanMinCaoShuW';
```
css里面都已经添加好了，在页面上查看DOM的属性里面，`font-family`都是生效了的。
应该是网站找不到字体文件吧。

求解，谢谢！

**Comment by xaoxuu** [comment]
字体放哪里都一样，你需要把字体路径引入进去：

<img width="731" alt="image" src="https://user-images.githubusercontent.com/16400144/66629366-19fd5c80-ec34-11e9-9c83-66566d29e879.png">
