### ISSUE TITLE
缩小标题间空格

### ISSUE THREAD

**Issue by MicDZ** [volantis-x/hexo-theme-volantis#109]
![](https://i.loli.net/2019/10/19/n4KfivHXIsu2J5h.png)
建议缩短标题间的空格。空格太大影响整体美感。

**Comment by xaoxuu** [comment]
我还特意加大了段落间距，看起来条理更清晰一点。

**Comment by MicDZ** [comment]
额，好吧。空格大一些条理确实清晰一点。
