### ISSUE TITLE
请求增加打赏功能

### ISSUE THREAD

**Issue by Roger-WIN** [volantis-x/hexo-theme-volantis#114]
希望允许文章开启打赏功能，放置在文章底部。比较简单的方案是，放几个收款二维码图片。例如这样：
![image](https://user-images.githubusercontent.com/25821208/69306306-f6312b80-0c61-11ea-945a-c052996cb860.png)

**Comment by xaoxuu** [comment]
1.2.6版本新增了文章footer功能，支持markdown语法，你更新一下看看

**Comment by Roger-WIN** [comment]
图片不能显示。
![image](https://user-images.githubusercontent.com/25821208/69637808-5bd34c80-1094-11ea-9c3e-8c61fbff921e.png)
![image](https://user-images.githubusercontent.com/25821208/69637834-6988d200-1094-11ea-84b5-d8c3f4346598.png)
![image](https://user-images.githubusercontent.com/25821208/69637999-cc7a6900-1094-11ea-9761-0f0fa7efb2e2.png)

**Comment by xaoxuu** [comment]
你少了半边的`<fancybox>`

**Comment by xaoxuu** [comment]
加`<fancybox>`是为了方便一行放多个图片的，如果你是只有一个图片的话，不需要`<fancybox>`

**Comment by Roger-WIN** [comment]
奇了怪了，我不知道为什么还是不能显示。
![image](https://user-images.githubusercontent.com/25821208/69638743-44955e80-1096-11ea-9c80-693246b3cbfd.png)
![image](https://user-images.githubusercontent.com/25821208/69638797-5d057900-1096-11ea-90d9-f9c2fb3dfb1d.png)
![image](https://user-images.githubusercontent.com/25821208/69638701-2891bd00-1096-11ea-89db-ae14199a301c.png)

**Comment by xaoxuu** [comment]
不换行试试

**Comment by HaleShaw** [comment]
相同的问题，试了加换行或者不要换行，都不行。感觉就是markdown语法在解析成html的时候，没解析对。
看了这次新增的另外一个功能，plain侧边栏，都能正常解析，就没搞懂这个为啥不行。估计和多了一个`<center>`标签有关，影响了markdown解析成html。
最终我没用`![]()`这种方式了，直接用的html语法`<img src=""/>`

**Comment by Roger-WIN** [comment]
我在 plain 侧边栏里给文字加上了 `<center>` 标签，能正常解析。

**Comment by Roger-WIN** [comment]
> 相同的问题，试了加换行或者不要换行，都不行。感觉就是 markdown 语法在解析成 html 的时候，没解析对。
> 看了这次新增的另外一个功能，plain 侧边栏，都能正常解析，就没搞懂这个为啥不行。估计和多了一个 `<center>` 标签有关，影响了 markdown 解析成 html。
> 最终我没用 `![]()` 这种方式了，直接用的 html 语法 `<img src=""/>`

直接用 HTML 语法的话，意义就不大了吧。😂

**Comment by HaleShaw** [comment]
> > 相同的问题，试了加换行或者不要换行，都不行。感觉就是 markdown 语法在解析成 html 的时候，没解析对。
> > 看了这次新增的另外一个功能，plain 侧边栏，都能正常解析，就没搞懂这个为啥不行。估计和多了一个 `<center>` 标签有关，影响了 markdown 解析成 html。
> > 最终我没用 `![]()` 这种方式了，直接用的 html 语法 `<img src=""/>`
> 
> 直接用 HTML 语法的话，意义就不大了吧。😂

主要是用markdown语法折腾不出来了，麻烦。

**Comment by xaoxuu** [comment]
@Roger-WIN @HaleShaw  https://mxclub.github.io/example/top/ 你们看看示例

**Comment by Roger-WIN** [comment]
@xaoxuu  配置文件里的这部分就算保持默认、不做改动，还是不能正常解析。@HaleShaw 在前面已经说得很清楚了。
![image](https://user-images.githubusercontent.com/25821208/69695786-82d36200-1118-11ea-818c-28feb3bf7cc1.png)
![image](https://user-images.githubusercontent.com/25821208/69695808-95e63200-1118-11ea-95ff-5e64aa888401.png)

**Comment by HaleShaw** [comment]
博主的确实正常解析出来了。但是我们俩的都不行。难道是本地环境有什么差异？我是在window环境

**Comment by HaleShaw** [comment]
这是我的package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-lazyload-image": "^1.0.4",
    "hexo-related-popular-posts": "^3.0.6",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}
```

我尝试过把所有版本都升级到最新的，结果解析直接出错了。
下面是升级后的json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^2.1.1",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-json-content": "^4.1.6",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-lazyload-image": "^1.0.4",
    "hexo-related-popular-posts": "^3.0.6",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "lodash": "^4.17.15",
    "googleapis": "^45.0.0"
  },
  "devDependencies": {
    "hexo-deployer-git": "^2.1.0"
  }
}
```

**Comment by Roger-WIN** [comment]
> 这是我的 package.json
> 
> ```
> {
>   "name": "hexo-site",
>   "version": "0.0.0",
>   "private": true,
>   "hexo": {
>     "version": "3.9.0"
>   },
>   "dependencies": {
>     "hexo": "^3.9.0",
>     "hexo-deployer-git": "^1.0.0",
>     "hexo-generator-archive": "^0.1.5",
>     "hexo-generator-category": "^0.1.3",
>     "hexo-generator-feed": "^1.2.2",
>     "hexo-generator-index": "^0.2.1",
>     "hexo-generator-json-content": "^4.1.6",
>     "hexo-generator-search": "^2.4.0",
>     "hexo-generator-tag": "^0.2.0",
>     "hexo-helper-qrcode": "^1.0.2",
>     "hexo-lazyload-image": "^1.0.4",
>     "hexo-related-popular-posts": "^3.0.6",
>     "hexo-renderer-ejs": "^0.3.1",
>     "hexo-renderer-less": "^1.0.0",
>     "hexo-renderer-marked": "^1.0.1",
>     "hexo-renderer-stylus": "^0.3.3",
>     "hexo-server": "^0.3.3"
>   }
> }
> ```
> 
> 我尝试过把所有版本都升级到最新的，结果解析直接出错了。
> 下面是升级后的 json
> 
> ```
> {
>   "name": "hexo-site",
>   "version": "0.0.0",
>   "private": true,
>   "hexo": {
>     "version": "4.0.0"
>   },
>   "dependencies": {
>     "hexo": "^4.0.0",
>     "hexo-generator-archive": "^0.1.5",
>     "hexo-generator-category": "^0.1.3",
>     "hexo-generator-feed": "^2.1.1",
>     "hexo-generator-index": "^0.2.1",
>     "hexo-generator-json-content": "^4.1.6",
>     "hexo-generator-search": "^2.4.0",
>     "hexo-generator-tag": "^1.0.0",
>     "hexo-helper-qrcode": "^1.0.2",
>     "hexo-lazyload-image": "^1.0.4",
>     "hexo-related-popular-posts": "^3.0.6",
>     "hexo-renderer-ejs": "^1.0.0",
>     "hexo-renderer-less": "^1.0.0",
>     "hexo-renderer-marked": "^2.0.0",
>     "hexo-renderer-stylus": "^1.1.0",
>     "hexo-server": "^1.0.0",
>     "lodash": "^4.17.15",
>     "googleapis": "^45.0.0"
>   },
>   "devDependencies": {
>     "hexo-deployer-git": "^2.1.0"
>   }
> }
> ```

那我还是别升级包了吧。😂

**Comment by xaoxuu** [comment]
目前还没有升级到hexo4，新版本可能不兼容一些老的语法

**Comment by xaoxuu** [comment]
最新版本1.3.1对应Hexo4.2，建议再升级一下看看。

**Comment by Roger-WIN** [comment]
如果放了多张图片，当图片大到一定程度时，侧边栏处的「打赏」部件会出现图片“溢出”的情况。因此这里的图片我觉得还是纵向排列的好，没必要跟文章页脚一样是横向排列。

**Comment by xaoxuu** [comment]
侧边栏纵向排布的需求你可以用text组件实现，支持md，一行放一个。
