### ISSUE TITLE
阅读全文渲染逻辑问题

### ISSUE THREAD

**Issue by BFDZ** [volantis-x/hexo-theme-volantis#118]
我这篇文章没有`<!--more-->`标签，也没有`excerpt`字段，按照文档说明应该会在文章页显示全文，实际文章列表只显示标题，并且仍有阅读全文的按钮，我使用老版本的 material-x 没有这个问题。

![QQN0DP.jpg](https://s2.ax1x.com/2019/12/04/QQN0DP.jpg)
![QQNwut.jpg](https://s2.ax1x.com/2019/12/04/QQNwut.jpg)
![QQNBHf.jpg](https://s2.ax1x.com/2019/12/04/QQNBHf.jpg)

**Comment by xaoxuu** [comment]
现在默认不显示内容了
