### ISSUE TITLE
博客搜索 algolia 的使用问题

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#119]
文档中没有太涉及到这儿，网上搜了一些似乎也不太理想

**Comment by inkss** [comment]
查看了一下此处的代码，这儿不知为何，就没有获取到值

![image](https://user-images.githubusercontent.com/31947043/70123704-2d65fa80-16ae-11ea-9896-7ce24c166ebf.png)

**Comment by xaoxuu** [comment]
目前不支持algolia

**Comment by inkss** [comment]
咳咳，研究了一阵子，改了一些 `js` 文件，主要是一些变量命名的问题。

然后现在有另外一个问题，这个搜索结果的列表展示上不是很友好，前端不是很熟，需要要修改的话需要改什么？因为 `algolia` 的检索结果只有没有看到文章内容，只有文章名称、时间、标签什么的，如果我想利用这些结果该如何修改模板文件？

![image](https://user-images.githubusercontent.com/31947043/70305976-a7c68400-1840-11ea-9c6c-afbde661c9ca.png)

**Comment by inkss** [comment]
另外一个原因，主要是认为搜索结果的展示不是很好看，这些滚动栏有些影响美观 

![image](https://user-images.githubusercontent.com/31947043/70307842-faa23a80-1844-11ea-9f02-69e7675c5560.png)

**Comment by inkss** [comment]
我尽力了，设计样式什么的，太难了  ...
![image](https://user-images.githubusercontent.com/31947043/70313277-40183500-1850-11ea-91de-86374fbf727f.png)
