### ISSUE TITLE
作者sama你好, 我的博客原来是在Ubuntu上搭建的, 后来换了manjaro, 除了主题文件, 其他的都用坚果云同步过来了, 发现文章的阅读数一直处于加载状态, 无法显示, 救救孩子

### ISSUE THREAD

**Issue by Mark-ThinkPad** [volantis-x/hexo-theme-volantis#12]
具体情况是这样的, 坚果云没有把主题的source文件夹同步过来. 所以我的做法是把主题重新git clone了一下, 其他的功能没有问题, 但是文章阅读数却无法显示, 救救孩子QAQ T_T

**Comment by MainGuo** [comment]
我也是 这是我的博客链接https://blog.mainguo.top

**Comment by MainGuo** [comment]
npm i -S hexo-generator-search hexo-generator-feed hexo-renderer-less hexo-autoprefixer hexo-generator-json-content hexo-recommended-posts 

问题已解决，在本地执行上面这条命令，安装依赖后 clean一下就恢复正常了@Mark-ThinkPad

**Comment by xaoxuu** [comment]
@MainGuo @Mark-ThinkPad 阅读统计插件作者更换了域名，现在已经解决，你更新一下主题就好了。
