### ISSUE TITLE
请问如何添加文章头图？

### ISSUE THREAD

**Issue by iChrAlpha** [volantis-x/hexo-theme-volantis#125]
请问能否允许一种操作使得可以指定页面添加一个在标题上方的「头图」。感觉缩略图不能很好地表达。

大概这个样式：

![MKD_20200112_211618](https://user-images.githubusercontent.com/56496965/72219436-0f2ecc80-3581-11ea-8848-b3b2caa896f7.png)

然后再主页上也能有个稍微大一点的体现。

望采纳。

**Comment by xaoxuu** [comment]
目前没有这个功能，以后会考虑加上的

**Comment by Reqwey** [comment]
我的博客已经实现了这个功能, 如果需要的话我提个PR?
