### ISSUE TITLE
Bug:5级和6级标题在TOC中没有区别

### ISSUE THREAD

**Issue by iChrAlpha** [volantis-x/hexo-theme-volantis#126]
文章页面 -> [https://chralpha.com/post/use-tt-rss-to-build-your-own-rss-service.html](https://chralpha.com/post/use-tt-rss-to-build-your-own-rss-service.html) 

如题，我在「定时更新」这个 5 级标题下写了「cron 更新」及「deamon 更新」两个 6 级标题，在正文内部是能够正常渲染的。

<img width="812" alt="屏幕快照 2020-01-27 下午5 16 53" src="https://user-images.githubusercontent.com/56496965/73162656-3eb90980-4129-11ea-8346-09d80275d58b.png">

但是旁边的「TOC」中就成为了并列关系，没有分层。

<img width="313" alt="屏幕快照 2020-01-27 下午5 13 37" src="https://user-images.githubusercontent.com/56496965/73162748-788a1000-4129-11ea-9425-21efe229193d.png">

<img width="239" alt="屏幕快照 2020-01-27 下午5 13 29" src="https://user-images.githubusercontent.com/56496965/73162835-a40cfa80-4129-11ea-8eea-8c6524f71022.png">

以下是这篇文章此部分的 Markdown 源码：(中间的 「\`」 使用反斜线转义)
```
##### 定时更新

###### 使用 cron 实现：

由于 Tiny Tiny RSS 无法 root 运行，我们不能使用宝塔计划任务。这里要手动添加定时任务。

\`\`\`
# 设置每 240 分钟 (4 个小时) 更新一次
echo "*/240 * * * * www /www/server/php/56/bin/php /www/wwwroot/domain/update.php --feeds --quiet" >> /var/spool/cron/www

# 赋予 www 文件权限
chmod 600 /var/spool/cron/www

# 重新加载／启动
service crond reload
service crond restart
\`\`\`

可以通过一下命令检查是否运行：

\`\`\`
tail -f /var/log/cron
\`\`\`

如果报错，就检查一下目录是否正确。

P.S. (2020-1-27 更新) 博主用上面的方法不是很成功，换了以下方法：

\`\`\`
# 在 root 账户下
echo "*/240 * * * * su -m www -c \"/www/server/php/56/bin/php /www/wwwroot/myrss.1amblog.ml/update.php --feeds --quiet\"" >> /var/spool/cron/root

# 剩下的赋予权限及重载与上面的类似
chmod 600 /var/spool/cron/root
service crond reload
service crond restart
\`\`\`

###### 使用 daemon 配合  systemd 更新 (官方推荐) ：

在 `/etc/systemd/system/` 创建一个 `ttrss.service` ，输入：

\`\`\`
[Unit]
Description=ttrss_backend
After=network.target mysql.service postgresql.service

[Service]
User=www
ExecStart=/www/wwwroot/domain/update_daemon2.php

[Install]
WantedBy=multi-user.target
\`\`\`

注意将路径改为自己的。

然后使用命令启动：

\`\`\`
systemctl daemon-reload
systemctl enable ttrss
systemctl start ttrss
\`\`\`

查看服务状态：

\`\`\`
systemctl status ttrss
\`\`\`
```

**Comment by iChrAlpha** [comment]
还有就是一级、二级标题的上下间距是不是太大了？感觉不是很自然。

**Comment by xaoxuu** [comment]
因为toc宽度有限，所以只区别显示二三四五级标题，一级标题同二级，六级同五级。（一级标题一般认为是文章或者网页标题，所以toc中是从二级标题开始的。）

**Comment by iChrAlpha** [comment]
> 因为toc宽度有限，所以只区别显示二三四五级标题，一级标题同二级，六级同五级。（一级标题一般认为是文章或者网页标题，所以toc中是从二级标题开始的。）

了解。所以5、6级因为 TOC 拦宽度问题无法区分，以后会注意的。

然后我的意思是二级标题的上下间距有点大，感觉隔开太多了。

还有就是markdown语法里的「引用」部分里面的间距太小了，而且换行的间距没有突出

比如在 typora 里预览是这样的：

<img width="609" alt="屏幕快照 2020-02-08 下午3 26 12" src="https://user-images.githubusercontent.com/56496965/74081209-66906180-4a87-11ea-95c6-783ed2ee7bb1.png">

可是hexo渲染出来的效果却是：

<img width="792" alt="屏幕快照 2020-02-08 下午3 25 22" src="https://user-images.githubusercontent.com/56496965/74081216-7e67e580-4a87-11ea-8344-065798da8eb1.png">

我手动加上 `<br>` html 语法换行后可读性才有所提升；

<img width="779" alt="屏幕快照 2020-02-08 下午3 24 09" src="https://user-images.githubusercontent.com/56496965/74081227-98a1c380-4a87-11ea-9151-a786c5d6799b.png">

可能引用部分字体变小是一方面，字体大小、间距和换行间距希望能再考虑一下。

最后，仍不忘感谢作者的辛勤付出，给我们提供这样一套已经很完美的hexo主题得以选择，感激！

**Comment by xaoxuu** [comment]
更新了：[<i class="fas fa-code-branch fa-fw"></i>1.2.7](https://github.com/xaoxuu/hexo-theme-material-x/releases/tag/1.2.7)

引用段落中段间距的BUG已经修复，二三级标题行高现在可以自己修改了。
