### ISSUE TITLE
keywords 会使生成器出错

### ISSUE THREAD

**Issue by BFDZ** [volantis-x/hexo-theme-volantis#13]
填写 config 里面的 keywords 后，在生成时会出错

![](https://i.loli.net/2018/10/20/5bcb39bfb7ab0.png)

**Comment by xaoxuu** [comment]
@BFDZ 考虑到现在SEO优化已经不需要写固定的description和keywords了，所以我删了这一行代码，不再生成description和keywords。
现在你更新一下主题就好了。

**Comment by xaoxuu** [comment]
@BFDZ 考虑到现在SEO不需要写明description和keywords了，所以我删掉了这两行代码，你重新更新一下主题就可以了。
