### ISSUE TITLE
cloudflare 的 js 链接会拖慢网页加载速度

### ISSUE THREAD

**Issue by BFDZ** [volantis-x/hexo-theme-volantis#130]
这个 js 文件在国内有时加载需要长达 5s 的时间，因为 cloudflare 的访问有时快有时慢，所以可以把这个 js 放到本地或者换用 jsdrive 吗？
https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js

**Comment by melodyjerry** [comment]
这个是干嘛的脚本

**Comment by xaoxuu** [comment]
理论上可以啊，我修改一下稍后更新

**Comment by xaoxuu** [comment]
已更新👌
