### ISSUE TITLE
怎么实现卡片半透明？？？？

### ISSUE THREAD

**Issue by melodyjerry** [volantis-x/hexo-theme-volantis#131]
怎么实现卡片半透明？？？？

**Comment by TRHX** [comment]
> 怎么实现卡片半透明？？？？

在 `_color.less` 文件里面，修改 `@theme_cardbg` 的值为 `rgba(x,x,x,x)` 的形式，其中最后一个值表示透明度，取值在 0~1 之间，例如 `rgba(255,255,255,0.8)` 就表示透明度为 0.8 的白色。

**Comment by melodyjerry** [comment]
@TRHX 我将`@theme_cardbg: white;`修改成`rgba(255,255,255,0.8)`，然后`hexo clean``hexo g``hexo s`后，没有任何改变。修改成0.45也是没有。请问这个是怎么回事？

**Comment by TRHX** [comment]
> @TRHX 我将`@theme_cardbg: white;`修改成`rgba(255,255,255,0.8)`，然后`` hexo clean``hexo g``hexo s ``后，没有任何改变。修改成0.45也是没有。请问这个是怎么回事？

看主题是否用了cdn

**Comment by melodyjerry** [comment]
@TRHX 这个怎么看？能教一下我吗，麻烦你了

**Comment by TRHX** [comment]
> @TRHX 这个怎么看？能教一下我吗，麻烦你了

博客根目录的配置文件有没有添加 `use_cdn: true`，有的话去掉，或者注释掉主题配置文件 `cdn` 下面的 `css` 选项，主题文档有说明：https://xaoxuu.com/wiki/material-x/advanced-settings/index.html#%E4%BD%BF%E7%94%A8CDN

**Comment by melodyjerry** [comment]
已经解决，谢谢解答。辛苦啦 @TRHX
