### ISSUE TITLE
search 能否设置只搜索标题

### ISSUE THREAD

**Issue by HenryTSZ** [volantis-x/hexo-theme-volantis#132]

**Comment by xaoxuu** [comment]
目前还没有提供这样的选项，你可能需要自己修改代码。

**Comment by HenryTSZ** [comment]
@xaoxuu 大佬, 那个 `/content.json` 是如何生成的?

**Comment by HenryTSZ** [comment]
找到了, `hexo-generator-json-content` 这个插件生成的. 我搜索改成使用 `hexo-generator-search` 这个插件了. 自己修改代码设置只搜索标题了
