### ISSUE TITLE
你好，我是切换成你的主题的。我原本是yilia主题，现在再加了一个你的主题，切换成你这个的时候为什么有下面的错误呢？怎样解决，谢谢

### ISSUE THREAD

**Issue by suzhigao** [volantis-x/hexo-theme-volantis#134]
ERROR D:\Hexo\blog\themes\material-x\layout\post.ejs:2
    1| <div class='l_main<%- page.sidebar == false ? ' no_sidebar' : '' %>'>
 >> 2|   <%- partial('_partial/article', {post: page, index: false}) %>
    3| </div>
    4| <%- partial('_partial/side') %>
    5| <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>

D:\Hexo\blog\themes\material-x\layout\_partial\article.ejs:15
    13|       <% if(post.layout == 'post'){ %>
    14|         <br>
 >> 15|         <%- partial('meta', {post: post, position: 'footer'}) %>
    16|       <% } %>
    17|       <% if(post.prev || post.next){ %>
    18|           <div class="prev-next">

D:\Hexo\blog\themes\material-x\layout\_partial\meta.ejs:66
    64|       <% (bottomMetas).forEach(function(meta){ %>
    65|         <% if(meta != 'title'){ %>
 >> 66|           <%- partial('../_meta/' + meta, {post: post, isPostList: isPostList}) %>
    67|         <% } %>
    68|       <% }) %>
    69|     </div>

D:\Hexo\blog\themes\material-x\layout\_meta\share.ejs:2
    1| <% if (theme.share) { %>
 >> 2|   <%- partial('../_third-party/share') %>
    3| <% } %>
    4|

**Comment by Reqwey** [comment]
很难说，如果你的hexo版本在4.0以上可能会与主题出现一些不兼容的错误，建议`npm uninstall hexo-cli` 和 `npm uninstall hexo` 后安装 `npm install hexo@3.9.0`

然后还有就是可能你的 Node.js 版本过低也会出错（我当时好像就是这个）建议去官网下最新版

其它就不清楚了，如果还有疑问就问 @xaoxuu 大佬吧

**Comment by suzhigao** [comment]
嗯好谢谢，但是有时候没出错，还有就是node. js版本要多少以上-------- 原始邮件 --------发件人： Hankun Lin <notifications@github.com>日期： 2020年2月12日周三 22:21收件人： xaoxuu/hexo-theme-material-x <hexo-theme-material-x@noreply.github.com>抄送： suzhigao <1763489853@qq.com>, Author <author@noreply.github.com>主    题： Re: [xaoxuu/hexo-theme-material-x] 你好，我是切换成你的主题的。我原本是yilia主题，现在再加了一个你的主题，切换成你这个的时候为什么有下面的错误呢？怎样解决，谢谢 (#134)很难说，如果你的hexo版本在4.0以上可能会与主题出现一些不兼容的错误，建议npm uninstall hexo-cli 和 npm uninstall hexo 后安装 npm install hexo@3.9.0

然后还有就是可能你的 Node.js 版本过低也会出错（我当时好像就是这个）建议去官网下最新版

其它就不清楚了，如果还有疑问就问 @xaoxuu 大佬吧

**Comment by Reqwey** [comment]
@suzhigao 这个去 [hexo官网](https://hexo.io) 上看吧

**Comment by xaoxuu** [comment]
@Linhk1606 @suzhigao 都升级到最新的吧，1.3.1版本对应的环境配置如下：
```
hexo: 4.2
hexo-cli: 3.1.0
node: 12.16.0
npm: 6.13.4
```
