### ISSUE TITLE
[BUG] 文章目录问题

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#139]
## 描述

Material-X主题V1.5的post文章目录显示好像有点问题，只能显示一级标题一下的（二级标题及以下）的标题

## 重现
网址：随便放一个吧：https://blog.lhkstudio.me/2020/01/28/algorithm-lca/
截图：

## 环境
Hexo版本：
`package.json`文件：
根目录的`_config.yml`文件：（敏感数据请替换为****）
主题的`_config.yml`文件：

如我同一天发布的另一个BUG Issue

**Comment by xaoxuu** [comment]
不要什么都提BUG啊，你看看文档啊： 组件库里面toc那部分的设置。

<img width="811" alt="image" src="https://user-images.githubusercontent.com/16400144/75088061-08817500-5583-11ea-9274-7a6c5da6fdf5.png">

**Comment by xaoxuu** [comment]
如果你一定要从H1开始，只需要把主题配置文件那里的`2`改成`1`就可以了。

但是H1标题在TOC中和H2标题缩进一样，因为侧边栏宽度有限，显示太多层级的话会很丑，所以UI上只对H2到H5这4个层级作出区分。

**Comment by Reqwey** [comment]
@xaoxuu 明白了，对不起
