### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by BFDZ** [volantis-x/hexo-theme-volantis#142]
评论框里面的  link: "完整链接" ，看起来有些奇怪，我觉得这是手滑了吧，正确应该是 网站链接

**Comment by xaoxuu** [comment]
我刻意强调的，因为总有人只写后面的，例如 `xaoxuu.com`， 被认为是个相对地址，结果就是在当前页面后面拼接一个 `/xaoxuu.com`。

**Comment by xaoxuu** [comment]
我在valine官网测试了一下： https://valine.js.org

![](https://user-images.githubusercontent.com/16400144/75090032-bc8dfa80-5599-11ea-8aa8-5e672a057dc9.png)

![QQ20200222-173917@2x.png](https://i.loli.net/2020/02/22/OR46u8gStEeT1NJ.png)



网址那里只写 `baidu.com`，点击回复。
然后在评论中点击名字就跳转到了 `https://valine.js.org/baidu.com`。

**Comment by xaoxuu** [comment]
我去 valine 提 issue 了

https://github.com/xCss/Valine/issues/232

**Comment by sxyugao** [comment]
@xaoxuu 这个Bug我在半年前和作者提过

https://i.loli.net/2020/02/23/MF41ifD7Yp3JmZo.png

结果作者表示：

https://i.loli.net/2020/02/23/UqEm8BAfuwJcg2O.png

**Comment by xaoxuu** [comment]
这个设定太反人类了。。。无奈之下只能暗示【完整的链接】，即便如此还是会收到一些不带http的链接。。

**Comment by BFDZ** [comment]
@xaoxuu 之前我用的一个修改的版本不会这样

**Comment by xaoxuu** [comment]
我以前没有改过valine这部分的代码，刚刚改了，加了一个判断。最新版本把我之前加的那些图片表情都去掉了。`1.5.3`

**Comment by xaoxuu** [comment]
@BFDZ @sxyugao 好消息，我给他们提交的修改通过了，估计下次更新就没有这个问题了。

https://github.com/xCss/Valine/pull/235

当然现在更新主题到 `1.5.3`以后的版本也可以，最近几个版本新增了很多功能。
