### ISSUE TITLE
Todo: 未来导航栏的变动

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#143]
导航栏不再分为上下两行切换了，也不再回到顶部看到封面时自动隐藏了。

未来的导航栏将会：

- 位置和内容永远固定。
- 回到顶部看到封面时导航栏背景变为透明。
- 支持下拉二级菜单。

**Comment by inkss** [comment]
导航栏切换挺好看的呀

**Comment by Reqwey** [comment]
那估计搜索框下面的那些东西就得删了

**Comment by xaoxuu** [comment]
上下切换导航栏做不了二级菜单，容量就有限。如果做pjax，导航栏需要增加容量，就必须要有二级菜单。
搜索框下面有两个按钮，一个定位到评论框，直接舍弃，一个toc，在桌面端也不需要，在移动端打算放到导航栏下面（对应现有的Menu按钮正下方）

**Comment by Reqwey** [comment]
我是说那个封面的搜索框下面不是有一排按钮吗. 那个应该就要删了, 因为有导航栏

**Comment by xaoxuu** [comment]
嗯
