### ISSUE TITLE
请问在关掉sidebar的情况下如何让页面栏目水平居中呢？

### ISSUE THREAD

**Issue by moegay** [volantis-x/hexo-theme-volantis#146]
在主题config中将sidebar设为空 [ ] 之后，主界面确实只显示posts栏了，但是右边sidebar占据的空间仍在那里，导致posts列表无法居中（其他page页，还有archives等也是一样，主栏无法居中）。

**Comment by xaoxuu** [comment]
哦是个BUG，我只处理了 `front-matter` 中设置 `sidebar: []` 的情况，没有处理主题配置文件里设置 `sidebar: []` 的情况。。。马上修复一下。

**Comment by moegay** [comment]
哈哈，多谢 ［拱手］
