### ISSUE TITLE
url对应问题

### ISSUE THREAD

**Issue by Zhouxf222** [volantis-x/hexo-theme-volantis#147]
## 描述
/_config.yml中配置目录为：
![image](https://user-images.githubusercontent.com/56181189/75222931-51823500-57e0-11ea-9c5b-0c2e4473774d.png)
/themes/volantis/_config.yml中配置文章分类和标签url为：
![image](https://user-images.githubusercontent.com/56181189/75223023-82626a00-57e0-11ea-8357-d0755eb5d659.png)
本地构建之后本地hexo s后打开网页，发现
![image](https://user-images.githubusercontent.com/56181189/75223116-b9d11680-57e0-11ea-8ec2-cc54176dd1f0.png)
点击文章分类和热门标签后报404

## 重现
网址：http://blog.zzzxf.cn
截图：
![image](https://user-images.githubusercontent.com/56181189/75223204-e7b65b00-57e0-11ea-9485-cb1e821334b9.png)
![image](https://user-images.githubusercontent.com/56181189/75223256-04529300-57e1-11ea-8d1f-45c428b6b417.png)

其他url都没问题，发现public/categories/和public/tags/中未生成index.html文件，不知原因，请问该如何设置，谢谢。

## 环境
Hexo版本：4.2.0
`package.json`文件：链接:https://pan.baidu.com/s/1t2_amHY8oWSODFR15LS_Pg  密码:pmml
根目录的`_config.yml`文件：链接:https://pan.baidu.com/s/1IDGcuL4Dw8-bP4Mp7_fP6Q  密码:rg70
主题的`_config.yml`文件：链接:https://pan.baidu.com/s/1nkiJup5pk2LaPiQSwX0QwQ  密码:69jz

**Comment by xaoxuu** [comment]
需要自己创建文件。

![](https://user-images.githubusercontent.com/16400144/75235066-acbf2200-57f6-11ea-9fe8-265842d85f1e.png)
