### ISSUE TITLE
强烈希望作者添加豆瓣读书页面

### ISSUE THREAD

**Issue by wztlink1013** [volantis-x/hexo-theme-volantis#148]
集成不了添加豆瓣读书页面的功能，自己尝试过改代码，但是实力有限，技术有限，希望这座更改一下

**Comment by xaoxuu** [comment]
好的

**Comment by xaoxuu** [comment]
好像是有现成的插件啊

**Comment by wztlink1013** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        嗯嗯，有现成的插件，但是这个插件好像只适用于next主题的，我尝试添加next的代码在主题中但是没有生效：）
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2550374815
                            
                    
                        
                            
                                    2550374815@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年2月26日 22:12，Mr. X<notifications@github.com> 写道： 


好像是有现成的插件啊



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by wztlink1013** [comment]
@xaoxuu 嗯嗯，有现成的插件，但是这个插件好像只适用于next主题的，我尝试添加next的代码在主题中但是没有生效：

**Comment by so1ve** [comment]
因为next代码是swig volantis是ejs啊

**Comment by xaoxuu** [comment]
https://hexo.io/plugins/ 这里搜索的是 hexo 插件，不是 next 插件，所有主题都可以用。

<blockquote><div><img src="/icon/favicon-32x32.png" height="14"> Hexo</div><div><strong><a href="https://hexo.io/plugins/">Plugins</a></strong></div><div>Hexo is a fast, simple & powerful blog framework powered by Node.js.</div></blockquote>

**Comment by MHuiG** [comment]
https://github.com/YuyingWu/hexo-tag-douban

**Comment by MHuiG** [comment]
https://github.com/YuyingWu/hexo-tag-douban

![image.png](https://upimage.alexhchu.com/2020/08/18/d048a1e608bde.png)

在Next主题中同样不生效，插件上一次commint是在8 Jan 2019，目测是api接口失效导致

![image.png](https://upimage.alexhchu.com/2020/08/18/a370c326b23e1.png)

<blockquote><img src="https://avatars3.githubusercontent.com/u/7309680?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/YuyingWu/hexo-tag-douban">YuyingWu/hexo-tag-douban</a></strong></div><div>live demo: http://www.wuyuying.com/blog/archives/growth-hacker/ - YuyingWu/hexo-tag-douban</div></blockquote>

**Comment by xaoxuu** [comment]
你知道新的API吗？

**Comment by xaoxuu** [comment]
https://www.douban.com/group/345245/

<blockquote><img src="https://img9.doubanio.com/favicon.ico" width="48" align="right"><div><strong><a href="https://www.douban.com/group/345245/">豆瓣api开放小组</a></strong></div></blockquote>
