### ISSUE TITLE
weiget中的text属性

### ISSUE THREAD

**Issue by yinuxy** [volantis-x/hexo-theme-volantis#149]
请问content支持js代码吗

**Comment by xaoxuu** [comment]
不支持，你要引入js的话，用文档中「站点」那部分说的import方式能满足需求吗？

**Comment by yinuxy** [comment]
我试试

**Comment by yinuxy** [comment]
谢谢大佬翻牌

**Comment by yinuxy** [comment]
![image](https://user-images.githubusercontent.com/42272333/75423040-e3bd4100-5978-11ea-96de-98a7deaa1637.png)还有一个问题：我自定义了页脚的这些文字，我想删掉他们，但是删完了还是有，请问怎么完全删掉

**Comment by yinuxy** [comment]
已解决！
