### ISSUE TITLE
在搜索栏键入tab出现奇怪问题

### ISSUE THREAD

**Issue by MicDZ** [volantis-x/hexo-theme-volantis#15]
当在searchform中键入tab时会从

> nav-main container container--flex

自动跳到class为 

> nav-sub container container--flex

**Comment by MicDZ** [comment]
@xaoxuu

**Comment by ghost** [comment]
很简单，只是按了tab键后被其他元素获得了焦点，解决办法就是通过js屏蔽tab按键

**Comment by wushile** [comment]
代码如下：
`    function HandleTabKey(evt) {
        if (evt.keyCode == 9) {
             if (evt.preventDefault) { evt.preventDefault(); }
            else { evt.returnValue = false; }
        }
    }`

**Comment by xaoxuu** [comment]
@wushile 多谢指教，已经修复
