### ISSUE TITLE
计划取消深色主题

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#152]
目前主题可以通过修改 `_color.less` 中的定义快速设置为深色主题，由此产生了很多工作量，所有UI元素的颜色都要考虑，例如正文字体，要考虑如果卡片背景是深色的，文字颜色应该是白色。
另外代码框、评论系统对深色背景的兼容性也很差，都要逐个手动去适配。
加了毛玻璃和图片背景之后情况更加复杂，图片上显示的文字颜色（如首页大标题、网站页脚）取决于图片背景是深色还是浅色，卡片上的文字颜色又要取决与卡片背景是深色还是浅色。。。

**然而实际使用深色卡片的用户很少。**

所以计划不再兼容深色卡片，固定为浅色卡片+深色文字，只可以在小范围内微调。这样UI方面工作量骤减。

**Comment by Charlie-zzy** [comment]
~~真香（~~
