### ISSUE TITLE
qrcode链接指向错误

### ISSUE THREAD

**Issue by qpmcool** [volantis-x/hexo-theme-volantis#154]
## 描述
页面分享链接部分，二维码和微信都是启用的qrcode
qrcode生成二维码链接地址指向https://yoursite.com/页面地址,无法打开。

## 重现
网址：https://qpmcool.github.io/2020/02/28/HEXO%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C/
截图：
![image](https://user-images.githubusercontent.com/20516420/75595583-99a88e00-5a52-11ea-9920-37f2fcaca09a.png)
# 环境
Hexo版本：4.2.0
`package.json`文件：
根目录的`_config.yml`文件：（敏感数据请替换为****）
主题的`_config.yml`文件：

**Comment by xaoxuu** [comment]
这是个bug，不过我也没办法，如果非常需要二维码分享，建议安装第三方分享插件

**Comment by xaoxuu** [comment]
`1.7.1` 版本目前应该是修复好了，你看我的博客的二维码分享正常不

**Comment by xaoxuu** [comment]
我安装了 `hexo-offline` 插件，所以你需要打开浏览器彻底清除缓存再刷新才行。
