### ISSUE TITLE
1.5.3~1.6.2版本wordcount.ejs语句没有对应_config.yml

### ISSUE THREAD

**Issue by ideallove** [volantis-x/hexo-theme-volantis#155]
## 描述
在迭代版本1.5.3的时候主题_config.yml添加的service开关（到最新的1.6.2改成了plugins）中的wordcount失效。在主题layout/_meta/wordcount.ejs中的if条件忘记改成(theme.plugins.wordcount)了。（格式没对应，添加一下就好了。其他的开关我也没有检查。）
（小萌新最近才开始用hexo的，发现作者更新超级迅速。。真的非常喜欢这个主题。）

## 重现
截图：
![image](https://user-images.githubusercontent.com/20013535/75600417-12a6f480-5aea-11ea-960e-74bf08019aed.png)

## 环境
Hexo版本：4.2.0

**Comment by xaoxuu** [comment]
修复好了👌没发版本，你直接更新到master最新就行
