### ISSUE TITLE
关于英文分词及行内代码的排版建议

### ISSUE THREAD

**Issue by ChrAlpha** [volantis-x/hexo-theme-volantis#156]
众所周知，英文等众多拉丁语系与中文有一个很显著的差别——有无明确的分词标记。在英文中，明确以「空格」分隔单个单词这最小的表达单位；虽然中文中词语也是最小的单位，但是一句话中没有明确界限，也不能就单个字进行拆分，这样往往会丧失原本的意思。既然中文分词问题如此棘手，那么对中文而言，不管分词直接排到行末、若位置不够就换行排这种处理方法是无可厚非的。但是英文就不这么见得了，当存在空格这种明确的分界符，如果按照字符来排，行末位置不够就排到下一行，带来词的分裂会使体验大打折扣。类似的，Markdown 语法中的「行内代码」这种整体性较强的内容也应考虑。

![bug-material-x](https://user-images.githubusercontent.com/53332481/75627345-3d886a00-5c0a-11ea-8168-36ecac815c03.PNG)

所以建议将英文单词单独识别并保留整体换行，同样适用于行内代码。

**Comment by xaoxuu** [comment]
以前是出于我写代码经常会出现一大串一大串连起来的英文，不强制换行很丑，但是最近几次更新我取消了强制换行，不会切断单词了。

**Comment by ChrAlpha** [comment]
> 
> 
> 以前是出于我写代码经常会出现一大串一大串连起来的英文，不强制换行很丑，但是最近几次更新我取消了强制换行，不会切断单词了。

了解了，抽空跟进版本。

感谢作者!
