### ISSUE TITLE
关于全屏幕封面的UI建议

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#161]
## 您的功能要求与问题有关吗？ 请描述。
我感觉封面开了全屏幕以后背景太空了

## 描述您想要的解决方案
1. 在封面页的靠下中间添加一个"向下"的按钮(可以写"开始阅读"啥的), 按下去直接往下走到body区
2. 感觉搜索框以及下面那些导航按钮在全屏幕下显得太小了, 看起来很奇怪, 建议把它们改大一点吧

## 描述您考虑过的替代方案
蛤?

**Comment by xaoxuu** [comment]
我想做一个箭头浮动，可是不知道动画怎么做。

个人博客还是建议用半屏高的封面，全屏幕的适合做项目文档主页。

**Comment by Reqwey** [comment]
@xaoxuu 好像[butterfly主题](https://github.com/jerryc127/hexo-theme-butterfly)就有那种东西

**Comment by xaoxuu** [comment]
我看看能看懂的话给抄过来😂

**Comment by xaoxuu** [comment]
箭头已经加上了：`1.7.4`，别的不考虑改。你想改的话，在 `source/less/_base.less` 第198行。
