### ISSUE TITLE
音乐插件

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#162]
## 您的功能要求与问题有关吗？ 请描述。
还是想提一下，音乐播放器插件放在底部footer实在感觉不方便
1. 感觉不太雅观，在手机上底部占用空间。不简洁
2. 如果默认播放，PC端不知道位置的，估计要被吓一跳，暂停播放需要拉到最底部。
3. 上个主题的侧边栏音乐播放器觉得不错，符合主题整体风格，侧边栏容易发现

## 描述您想要的解决方案

想要恢复 侧边栏音乐播放插件。

## 描述您考虑过的替代方案
主要我还不太会修改主题文件。没办法自己搞，嘿嘿！

**Comment by xaoxuu** [comment]
主要还是为兼容pjax做的妥协，放在侧边栏每次切换页面都会被重载。
现在音乐体验本身就很不好，每换个页面就重新播放。。。

**Comment by xaoxuu** [comment]
现阶段可以先设置 `fixed: true` 让音乐固定在屏幕下方。

**Comment by Reqwey** [comment]
> 主要还是为兼容pjax做的妥协，放在侧边栏每次切换页面都会被重载。
> 现在音乐体验本身就很不好，每换个页面就重新播放。。。

呃那为啥网易云音乐换个页面也会继续播放呢

**Comment by Charlie-zzy** [comment]
> > 主要还是为兼容pjax做的妥协，放在侧边栏每次切换页面都会被重载。
> > 现在音乐体验本身就很不好，每换个页面就重新播放。。。
> 
> 呃那为啥网易云音乐换个页面也会继续播放呢

应该是用了锚点...你看页面都没跳转过，所以才能持续播放，要是为了它而改主题的话估计得用好几个肝...
