### ISSUE TITLE
文章分享功能二维码图标发现一个小问题

### ISSUE THREAD

**Issue by zjcscut** [volantis-x/hexo-theme-volantis#166]
## 描述
文章分享功能发现一个小BUG，qrcode类型的<img>标签里面的src被替换成二维码的内容，理论上应该是wechat的logo。

## 重现

网址：
http://throwable.club/2020/03/07/canal-kafka-mysql-binlog-sync-guide/

截图：

![image](https://user-images.githubusercontent.com/13879735/76157127-b83c1280-613f-11ea-8484-5f6002b66b67.png)

## 环境
Hexo版本：4.2
主题版本：1.7.4
`package.json`文件：
根目录的`_config.yml`文件：（敏感数据请替换为****）
主题的`_config.yml`文件：
  share:
    - id: qq
      name: QQ好友
      img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qq.png
    - id: qzone
      name: QQ空间
      img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/qzone.png
    - id: qrcode # 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
      name: 微信
      img: https://cdn.jsdelivr.net/gh/xaoxuu/assets@19.1.9/logo/128/wechat.png
    - id: weibo
      name: 微博
      img: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/logo/128/weibo.png

**Comment by xaoxuu** [comment]
我没有办法做成微信logo点开变成二维码的效果，就直接显示二维码了。所以qrcode那行设置img没用。

**Comment by xaoxuu** [comment]
做了导航栏二级菜单后，我仿照类似的方法实现了鼠标放上去就弹出窗口显示二维码。
所以现在又可以显示微信logo了
