### ISSUE TITLE
自定义的CSS应该插入在哪里

### ISSUE THREAD

**Issue by yinuxy** [volantis-x/hexo-theme-volantis#167]
博主你好，我、今天我想加一个自定义的css文件，就加在了`layout/_partial/head.ejs`里面
![image](https://user-images.githubusercontent.com/42272333/76196624-8c935800-6225-11ea-8891-476984b8d45e.png)
加完以后每一列都变宽了，如下图：
![image](https://user-images.githubusercontent.com/42272333/76196738-b9476f80-6225-11ea-9543-844c588af215.png)
请问我应该将css放置在什么位置

**Comment by xaoxuu** [comment]
你放的位置是对的

**Comment by yinuxy** [comment]
但是放置了之后就变成那样了，使用的主题是1.7.3，是不是要更新一下主题

**Comment by xaoxuu** [comment]
说明你引入的css跟我的css冲突了。

**Comment by yinuxy** [comment]
好得
