### ISSUE TITLE
请问版本2可以使用吗？

### ISSUE THREAD

**Issue by xingkongyj2** [volantis-x/hexo-theme-volantis#168]
## 描述
清楚简明地描述问题是什么。
对您期望发生的事情的简洁明了的描述。

## 重现
网址：
截图：

## 环境
Hexo版本：
`package.json`文件：
根目录的`_config.yml`文件：（敏感数据请替换为****）
主题的`_config.yml`文件：

**Comment by xaoxuu** [comment]
可以啊

**Comment by xingkongyj2** [comment]
> 可以啊

已经升级，很喜欢这个主题。赞

**Comment by xaoxuu** [comment]
谢谢支持😊

**Comment by xingkongyj2** [comment]
能不能加下你qq或微信，在配置主题，有点疑问





------------------ 原始邮件 ------------------
发件人: Mr. X <notifications@github.com&gt;
发送时间: 2020年3月10日 11:23
收件人: xaoxuu/hexo-theme-volantis <hexo-theme-volantis@noreply.github.com&gt;
抄送: xingkongyj2 <2580130642@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xaoxuu/hexo-theme-volantis] 请问版本2可以使用吗？ (#168)




谢谢支持😊
