### ISSUE TITLE
手机导航栏问题

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#169]
## 描述
动画过渡问题

## 重现
网址：https://cdn.jsdelivr.net/gh/wbig/ebigPic/file/bug01.mp4
截图：

## 环境
Hexo版本：
从Marterial-x到最新版本一直都有。

**Comment by xaoxuu** [comment]
你是指动画不流畅？浏览器兼容性问题吧，我在iPhoneSE上看都没有这种情况，你换个Chrome看看。

**Comment by ghost** [comment]
但是，你看视频最后的文章目录过渡动画就很流畅。导航目录过渡的不流畅。

**Comment by xaoxuu** [comment]
好吧，那我找个安卓手机调调

**Comment by xaoxuu** [comment]
你看看2.0.2怎么样

**Comment by ghost** [comment]
刚刚试了一下，已经修复，博主辛苦！
