### ISSUE TITLE
导航栏菜单下方指示条不能灵活跟随

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#17]
用鼠标在导航栏菜单之间来回指向，下方的指示条不能很灵活的跟随，特别是需要调大菜单间距后鼠标从其他位置移到菜单上，指示条还是依旧停留在上一个菜单位置，只有点击菜单后指示条才显示到点击的菜单下方

**Comment by xaoxuu** [comment]
这个问题我也很头疼

**Comment by xaoxuu** [comment]
我看了下你的菜单，是正常的啊，当鼠标在两个菜单中间光标没有变成手的时候说明没有放到按钮上，只有移动到按钮上的时候那个菜单才会变成激活状态
