### ISSUE TITLE
用别的主题没有问题，换了这个主题后，执行hexo s 报错。

### ISSUE THREAD

**Issue by superigbt** [volantis-x/hexo-theme-volantis#170]
## 用别的主题做好的没有问题，用这个主题后出错
‘’‘
  hexo s
’‘’
出错信息如下：
> ERROR Process failed: _posts/***.md
> ValidationError: `slug` is required!

## 环境
Hexo版本：4.2
`package.json`文件：
根目录的`_config.yml`文件：（敏感数据请替换为****）
主题的`_config.yml`文件：

**Comment by Reqwey** [comment]
应该是不同主题的`front-matter`配置不一样吧?

**Comment by xaoxuu** [comment]
建议亲下载文档源码，然后把您的博客md文件放进去使用，这是更换新主题最简单有效的方法。

**Comment by Charlie-zzy** [comment]
检查一下`front-matter`，很大概率是遗留了奇怪的设置...

**Comment by superigbt** [comment]
我重新用生成的目录，用hxo init myblog，重新做，然后把旧的MD文件copy过来的。没有别的主题的残留设置

**Comment by Reqwey** [comment]
`front-matter`就是MD文件开头那一段
```
---
blablabla
---
```

**Comment by xaoxuu** [comment]
那既然你重新 `hexo init` 了，那在原封不动的情况下把主题改成 volantis 运行一下看看。

我以为 `front-matter` 怎么写都不会影响 `hexo s` 的，但是既然出现这种情况，那就只可能是 `front-matter` 写法的问题了。

**Comment by superigbt** [comment]
是的，我册掉我所有的*.md文件，只保留原始的hello.md就正常了。多谢！
