### ISSUE TITLE
Mathjax在使用时报错

### ISSUE THREAD

**Issue by AGJackie** [volantis-x/hexo-theme-volantis#171]
## 描述
在typora中可以使用的部分mathjax公式在volantis 2.0.2主题中使用时报错。
如以下代码，第一段和第三段代码无法正常显示公式。第二段和第四段代码可以显示但是原本是多行公式显示成了一行。

$$
\mbox{积累因子}=\left\{
\begin{aligned}
1+ni & \mbox{单利}\\
(1+i)^n & \mbox{复利}
\end{aligned}
\right.
$$

$$
\mbox{积累因子}=\begin{cases}
1+ni & \mbox{单利}\\
(1+i)^n & \mbox{复利}
\end{cases}
$$

$$
\mbox{贴现因子}=\left\{\begin{array}{cc}
{1-nd} & {\mbox{单贴现率}}\\
{(1-d)^n} & {\mbox{复贴现率}}
\end{array}
\right.
$$

$$\begin {aligned}
 &800(1+0.04t)=1000\\
  &\Rightarrow n=6.25years
 \end{aligned}$$

## 重现
网址：https://actuarygarden.cn/Time-value-of-money/
截图：https://imgkr.cn-bj.ufileos.com/648d4c85-f0c0-4764-ae0f-33bb9d22f44f.jpg

## 环境
hexo: 4.2.0
hexo-cli: 3.1.0
os: Windows_NT 10.0.17134 win32 x64
node: 12.16.1
volantis: 2.0.2
mathjax配置部分，按照https://volantis.js.org/advanced-settings/的说明卸载默认的 hexo-renderer-marked，安装 hexo-renderer-markdown-it和相关插件，以及修改配置文件blog/_config.yml

**Comment by xaoxuu** [comment]
mathjax 我不懂，用的第三方插件渲染的
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>
```

**Comment by xaoxuu** [comment]
你看哪个主题处理得好给我我借鉴一下。😊

**Comment by xaoxuu** [comment]
@AGJackie  
我 `hexo inint` ，然后下载了最热门的NexT主题，开启mathjax：

<img width="288" alt="截屏2020-03-1214 54 08" src="https://user-images.githubusercontent.com/16400144/76495200-55b18200-6471-11ea-9f6e-00e77c43a365.png">

把你发的公式放进去，显示是这样的：

<img width="1251" alt="截屏2020-03-1214 52 59" src="https://user-images.githubusercontent.com/16400144/76495106-2d298800-6471-11ea-94ed-a5d6086d77bc.png">

**Comment by Reqwey** [comment]
确实用Typora的时候有些mathjax语法好像到了主题里面会渲染错
比如`$\color{red}$`不过现在不是有了多彩的文字了吗，所以也没啥影响

**Comment by Reqwey** [comment]
不过这个截图里面显示的好奇怪啊，怎么$符号都弄出来了

**Comment by AGJackie** [comment]
@xaoxuu 你的截图我加载不出来，可能网络不行。mathjax的配置似乎是在\themes\volantis\layout\_partial\mathjax.ejs 里修改。别的hexo主题我没用过。不过我排版公众号文章时候用的一个也是和hexo一样基于node.js和markdown-it的一个开源的编辑器mdnice，粘贴到这个里面也是正常显示的。https://www.mdnice.com/
开发者文档https://docs.mdnice.com/
项目地址https://github.com/mdnice/markdown-nice

**Comment by Reqwey** [comment]
@AGJackie 额这个不是你的网络问题, 是GitHub被"墙"了, 建议嗯~ o(*￣▽￣*)o上网

**Comment by AGJackie** [comment]
@xaoxuu 解决了，不是主题的问题，而是hexo本身对markdown中mathjax扩展语法的支持不够好。`\\`会自动转义成`\`
详情可以参考[在Hexo中渲染MathJax数学公式](https://www.cnblogs.com/wangxin37/p/8185688.html)

我最后采用的解决方法是在mathjax公式把所有换行的地方的`\\`换成`\\\\`
并且避免array环境和百分号的使用。
修正后的公式：

```
$$
\mbox{积累因子}=\begin{cases}
1+ni & \mbox{单利}\\\\
(1+i)^n & \mbox{复利}
\end{cases}
$$
```
