### ISSUE TITLE
我更新主题后，那个首页的Read More是没了吗？

### ISSUE THREAD

**Issue by CRainyDay-zz** [volantis-x/hexo-theme-volantis#172]
## 描述
我更新了之后，那个首页的Read More是没了吗？
## 重现
网址：https://crainyday.gitee.io
截图：https://img.vim-cn.com/76/2634a4f3c81c877bdbd6261735203c66b41b80.png 

## 环境

**Comment by Reqwey** [comment]
请仔细阅读主题文档, 在主题的`_config.yml`中有一个`readmore`开关, 默认为`false`, 改为`true`即可

**Comment by xaoxuu** [comment]
2.0 以后是删了

**Comment by Reqwey** [comment]
蛤? 那他为啥把这个给Close了😂

**Comment by CRainyDay-zz** [comment]
(⊙o⊙)…失误失误，不太熟悉操作，用的有点少 😂

**Comment by CRainyDay-zz** [comment]
那怎么配置才OK，
我配置readmore为true后，样式不太对。
你是直接删掉这部分样式了吗？

**Comment by Reqwey** [comment]
呃反正我是1.5+, 在里面把readmore关了, 我觉得关了好看

**Comment by xaoxuu** [comment]
删掉样式了，我觉得标题都可以点进去了，底下再多一个按钮占一行空间有点浪费

**Comment by ghost** [comment]
我认为，应该带着比较好，当用户滑到下方，却不能进入详情，还需滑到上面标题点击。也是不好的体验。除非，整个卡片也能进入，不只是标题。

**Comment by Reqwey** [comment]
额这倒也是, 这样确实还会让读者产生误解, 认为文章就这么一点, 就不点进去看了😅

**Comment by xaoxuu** [comment]
好吧，我加上了，重新发了一遍 `2.1.2`

**Comment by bugj** [comment]
> 好吧，我加上了，重新发了一遍 `2.1.2`

搞了一个通宵，没找到解决办法
