### ISSUE TITLE
首页sidebar 侧边栏，显示在页面最下面，不是在右边

### ISSUE THREAD

**Issue by ChemLez** [volantis-x/hexo-theme-volantis#175]
## 描述
清楚简明地描述错误是什么。
对您期望发生的事情的简洁明了的描述。

## 重现
网址：
截图：![](https://s1.ax1x.com/2020/03/13/8mXcZD.png)

## 环境
Hexo版本：
`package.json`文件：
根目录的`_config.yml`文件：（敏感数据请替换为****）
主题的`_config.yml`文件：

**Comment by ChemLez** [comment]
由于有这个bug，所以暂时没部署

**Comment by ChemLez** [comment]
![](https://s1.ax1x.com/2020/03/13/8nkpaq.png)

**Comment by xaoxuu** [comment]
请问您按照图中说法自行查找问题了吗
![IMG_0008](https://user-images.githubusercontent.com/16400144/76581155-631c4a00-650d-11ea-8df3-35a50e714e98.jpeg)

**Comment by ChemLez** [comment]
> 请问您按照图中说法自行查找问题了吗
> ![IMG_0008](https://user-images.githubusercontent.com/16400144/76581155-631c4a00-650d-11ea-8df3-35a50e714e98.jpeg)

还没有，晚上试试

**Comment by ChemLez** [comment]
貌似找到原因了，好像和我过去写的博客文档有关系，我全删了，然后重新生成了一篇文章，就回去了；把原来一部分添加回去，就又跑下面了...
