### ISSUE TITLE
开启relative_link无法编译

### ISSUE THREAD

**Issue by HaleShaw** [volantis-x/hexo-theme-volantis#176]
## 描述
在博客根目录的`_config.yml`中开启`relative_link`后，无法`hexo g`。

如果在`package.json`中移除`hexo-all-minifier`，则可以`hexo g`成功。

但是依然有其他问题，`_config.yml`里面定义的很多js和css文件都加载不了，网页上抓出的url会带域名前缀：`http://localhost:4000/https:/cdn.jsdelivr.net/npm/aplayer@1.10/dist/APlayer.min.js`
导致评论组件只能显示`评论`两个字，下面的框加载不出来，或还有其他问题没发现。
如果将`relative_link`设为`false`就可恢复。
且`package.json`中不要`hexo-all-minifier`亦可正常编译运行。

## 重现
relative_link: true
用博主原代码，改一行即可。故没推上自己的server了。

## 环境
Hexo版本：4.2.0
`package.json`文件：楼主原文件
根目录的`_config.yml`文件：楼主原文件，[修改第46行为true](https://github.com/xaoxuu/volantis-docs/blob/master/_config.yml#L46)
主题的`_config.yml`文件：楼主原文件

**Comment by xaoxuu** [comment]
那你能解释一下为什么要这样做吗

**Comment by xaoxuu** [comment]
我特地去看了一下 NexT ，如果你设置了ture，js文件里会再次把它设置为false来避免路径错误和未知风险，我把相关代码删掉一样会出现这种问题。

**Comment by HaleShaw** [comment]
> 那你能解释一下为什么要这样做吗

呃……我认为这是开启`相关文章`的开关，想在博客中开启这个功能。

**Comment by xaoxuu** [comment]
不是的。。。你在文档里搜相关文章就知道怎么开了，需要安装插件，而且每次修改文章内容之后都会报错需要重新 `hexo s`。

**Comment by HaleShaw** [comment]
> 不是的。。。你在文档里搜相关文章就知道怎么开了，需要安装插件，而且每次修改文章内容之后都会报错需要重新 `hexo s`。

好吧，闹乌龙了……折腾了好久才找到升级失败的原因卡在这儿。
