### ISSUE TITLE
文章标题的快速定位

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#178]
这个功能很多**markdown**博客都有的, 我觉得挺不错, 希望能加入

> Post文件里面有一些标题, 如`## Title`
>
> 通过`https://域名.com/post/文章名#Title`就可以快速定位到这个标题下的内容

**Comment by xaoxuu** [comment]
有的，但是会被导航栏挡住，曾经为了修复这个问题发过更新，但是又会导致标题上方一定区域的文本无法被选中，所以现在还是处于有点「错位」的情况。

例如：

https://volantis.js.org/getting-started/#下载与安装

**Comment by xaoxuu** [comment]
😅外行技术有限

**Comment by Reqwey** [comment]
额好吧, 其实也没有那么必要, 主要是为了外面链接调用

**Comment by Reqwey** [comment]
这个问题是很难避免

**Comment by Reqwey** [comment]
其实是因为其它主题它把类似导航栏的东西全搬到文章旁边去了(有点像你那个简历主题)

但是这个主题导航栏是亮点啊, 怎么忍心砍掉😅

**Comment by xaoxuu** [comment]
那个主题以前是有导航栏的，而且也不会遮挡，但是我不知道是哪些代码的作用

https://cn.vuejs.org/v2/guide/#起步

**Comment by Linhk1606** [comment]
这个导航栏不会消失啊

**Comment by Reqwey** [comment]
哎我看你的博客里面已经改的好好的啦

**Comment by Linhk1606** [comment]
在 https://xaoxuu.com/share/music/ 里

**Comment by Reqwey** [comment]
不对, 好像有点奇怪, 就是刷新的时候

**Comment by xaoxuu** [comment]
你现在看看文档的效果正常不， `2.1.4` 了。。

**Comment by xaoxuu** [comment]
是这个参数起到了决定性的作用： https://developer.mozilla.org/zh-CN/docs/Web/CSS/pointer-events

<img width="682" alt="截屏2020-03-1322 26 29" src="https://user-images.githubusercontent.com/16400144/76629729-b926d700-6579-11ea-8fba-8f1ff8f4c139.png">

**Comment by Reqwey** [comment]
现在好了, 真棒
