### ISSUE TITLE
建议更正 Mathjax 3的配置

### ISSUE THREAD

**Issue by AGJackie** [volantis-x/hexo-theme-volantis#179]
我看到你把 Mathjax 2 的加载项更新到了 Mathjax 3, 但是 Mathjax 3的配置没有进行调整，可能你平常不太用公式不太了解，所以来建议一下~ Mathjax 3的配置写法和Mathjax 2有较大差异。详细可参考[ Mathjax 3官方文档](http://docs.mathjax.org/en/latest/)。要把配置项从Mathjax 2更新到Mathjax 3，可以通过[v2 to v3 Configuration Converter](https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html)

这是我更新到最新的volantis 2.1.3以后试验过的解决方案：把整个mathjax.ejs为文件替换为以下代码即可

```
<script async src="<%- theme.plugins.mathjax %>"></script>
<!-- MathJax配置，可通过单美元符号书写行内公式等 -->
<script>
window.MathJax = {
  tex: {
    inlineMath: [ ["$", "$"], ["\\(","\\)"] ],
    displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
    processEscapes: true,
    tags: "ams",
    macros: {
      href: "{}"
    }
  },
  options: {
    ignoreHtmlClass: "tex2jax_ignore|dno",
    skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
  }
};
</script>
```

**Comment by AGJackie** [comment]
用原先mathjax 2的配置写法对mathjax 3来说是不生效的，可以写个简单的行内公式`$t+1=2$`试验一下，是识别不出的。

**Comment by xaoxuu** [comment]
好的，谢谢

**Comment by xaoxuu** [comment]
非常感谢，已经更新了，你看看正确不

**Comment by AGJackie** [comment]
mathjax公式没问题了。不过刚刚发现折叠区域有的代码，能够使得点击展开的点击范围比较小？以下帖子里的两个折叠区域，思路的点击范围为整个蓝框，是正常的；但是解的点击范围只有红框部分，框的下半部分无法触发点击。
[【CM1】 Chapter 4 货币的时间价值](https://actuarygarden.cn/CM1-time-value-of-money/)

截图：
https://imgkr.cn-bj.ufileos.com/2bdd128e-545b-4ead-8aa6-c4b5952a4150.jpg
代码
```
### 例题 4.1 (CT1 September 2011 Q1)

A 91-day treasury bill is issued by the government at a simple rate of discount of 8% per annum.

Calculate the annual effective rate of return obtained by an investor who purchases the bill at issue.
{% raw %}
<details>
<summary>
思路：
</summary>
{% endraw %}

  根据题意，直接列式：
$$
1-nd=(1+i)^{-n}
$$
  其中，期限 $n=\tfrac{91}{365}$, 单贴现率 $d=0.08$. 求等价的复利 $i$.


{% raw %}</details>{% endraw %}


{% raw %}
<details>
<summary>
解：
</summary>
{% endraw %}

$$
\begin{aligned}
&(1-\frac{91}{365} \times 0.08)=(1+i)^{-\frac{91}{365}} \\\\
&0.980055=(1+i)^{-\frac{91}{365}} \\\\
&1+i=1.08416 \Rightarrow i=0.08416
\end{aligned}
$$

{% raw %}</details>{% endraw %}
```

**Comment by xaoxuu** [comment]
😂 这个是上一条commit产生的bug，不过已经刚刚修复上传了

https://github.com/xaoxuu/hexo-theme-volantis/commit/2ed37121ce098b43a57b00b786691925134dc2fe

**Comment by xaoxuu** [comment]
刚刚是在解决这个问题： https://github.com/xaoxuu/hexo-theme-volantis/issues/178

**Comment by AGJackie** [comment]
刚刚更新了一下，果然解决了hh。给你点赞

**Comment by xaoxuu** [comment]
😊
