### ISSUE TITLE
CNAME设置请教

### ISSUE THREAD

**Issue by HaleShaw** [volantis-x/hexo-theme-volantis#180]
我知道怎么在域名上配置解析，指向自己的github.io。
但是自己github下的另一个仓库，也上传了博客文件。这时这个仓库没有github.io的指向，请问怎么将域名解析到这个仓库呢？

比如你的xaoxuu.com指向的是xaoxuu.github.io这个仓库。
你的这个域名volantis.js.org，是怎么指向volantis.js.org这个仓库的呢？

**Comment by Charlie-zzy** [comment]
如果不是Github Pages，那么就直接在网址后面加上仓库名即可，如https://xaoxuu.github.io/volantis.js.org

**Comment by HaleShaw** [comment]
> 如果不是Github Pages，那么就直接在网址后面加上仓库名即可，如https://xaoxuu.github.io/volantis.js.org

比如正常解析到name.github.io的流程是这样的：
1.主机记录：www
  记录类型：CNAME
  记录值：name.github.io
2.主机记录：@
  记录类型：A
  记录值：185.199.108.151
同时添加两条类型解析。

我现在要解析到我名下的另一个仓库：good
1.主机记录：www
  记录类型：CNAME
  记录值：name.github.io/good  （这儿报错，提示**CNAME记录的记录值为域名形式（如abc.example.com）**。应该是不能有斜杠）
2.主机记录：@
  记录类型：A
  记录值：185.199.108.151  （**同时这儿也不知道这个仓库的IP是多少**）

**Comment by HaleShaw** [comment]
已经看到博主用的是js.org这个域名的开放二级域名。去js.org这个网站即可看到相关信息。
 @Charlie-zzy 热心朋友的方式也是成功的，在不使用域名的情况下可以访问其他仓库。谢谢！
