### ISSUE TITLE
请问懒加载的图片，插件下载好了，博主提供的懒加载的图片，是需要下载下来，保存在本地博客路径，还是可以直接引用地址就行了，我貌似都试了，还是不行，不知道是不是保存格式等方面有没有错误

### ISSUE THREAD

**Issue by ChemLez** [volantis-x/hexo-theme-volantis#182]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

**Comment by xaoxuu** [comment]
懒加载插件的项目地址：
https://github.com/Troy-Yang/hexo-lazyload-image

**Comment by ChemLez** [comment]
> 懒加载插件的项目地址：
> https://github.com/Troy-Yang/hexo-lazyload-image

我试了，并且用了默认配置（配置在博客根目录下）,还是出不来
这是我的地址 https://www.liizhi.cn

**Comment by ChemLez** [comment]
默认的可以了，请问如果想使用博主您提供的，直接引用你给的图片地址，还是需要下载下来，存放在配置里说的文件夹。因为，这配置完，需要一定时间才能反应出效果。

**Comment by ChemLez** [comment]
可以了，直接本地 hexo s，看出来了，直接引用地址即可。
