### ISSUE TITLE
2.1.4 版的关于页面，导航栏标题会被遮住

### ISSUE THREAD

**Issue by BFDZ** [volantis-x/hexo-theme-volantis#183]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. 安装2.1.4版
2. 按照文档建立关于页面

![8l7mRA.png](https://s1.ax1x.com/2020/03/14/8l7mRA.png)

其他独立页面没这个问题

我设置了 sidebar: [category] 以后导航栏标题就正常了，这应该是无侧边栏的时候标题大小设置有问题。

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

## Other Information 

https://www.bfdz.ink/

**Comment by xaoxuu** [comment]
这是宽度不够了，建议像我那样把分类标签归档合并到一起，毕竟：
1. 已经支持了N级子菜单
2. 这3个都属于索引文章的方式

> 目前为了美观，导航栏实际使用的区域宽度和下面内容的宽度是一样的，没有侧边栏时就会窄一点。属于和实用方面的取舍问题。如果需要平铺很多标题，建议在主题配置文件中把 `max_width` 设置宽一点。

**Comment by xaoxuu** [comment]
或许下个版本我会考虑加入个选项，不限制导航栏内容宽度，类似于GitHub这样，不管屏幕拉多宽，导航栏上的内容始终从最左到最右。

**Comment by xaoxuu** [comment]
<img width="499" alt="截屏2020-03-1423 14 11" src="https://user-images.githubusercontent.com/16400144/76684767-a4b20f80-6649-11ea-84e1-ef7df8587094.png">

这样的方案你觉得怎么样，屏幕过窄时logo不压缩，菜单压缩或者支持横向滑动显示，可以的话我一会就更新一下

**Comment by BFDZ** [comment]
压缩菜单文字只留 logo 我觉得可以

**Comment by Reqwey** [comment]
我觉得实在不行搞成Overflow的也行啊, 像GitHub这样

**Comment by xaoxuu** [comment]
GitHub或者是很多网站都是自己已经知道有多少按钮，根据按钮多少采用合适的布局，但是博客主题不确定用户到底放多少按钮，按钮多了适合GitHub这样的，但是按钮少了这样就显得中间很空旷。所以最好的方案还是给用户个选择，居中还是分散。

<img width="2032" alt="截屏2020-03-1512 38 40" src="https://user-images.githubusercontent.com/16400144/76695414-f0040680-66b9-11ea-8390-81aca441ab46.png">
