### ISSUE TITLE
brower is not defined

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#184]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Steps to reproduce the behavior 
1.正在配置_config.yml测试.
2. 不知道改动了哪里。就出错了。
3. 回退了所有改动，还是出错。

### Node.js and NPM Information

```
[root@VM_0_17_centos hexo]# node -v
v13.11.0
[root@VM_0_17_centos hexo]# npm -v
6.13.7
```

### Package dependencies Information

```
[root@VM_0_17_centos hexo]# npm ls --depth 0
hexo-site@0.0.0 /root/hexo
├── hexo@4.2.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-json-content@4.1.6
├── hexo-generator-search@2.4.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
└── hexo-wordcount@6.0.1
```

### 报错信息
```
Uncaught (in promise) ReferenceError: browser is not defined
    at pagehelper.js:1
    at pagehelper.js:1
(anonymous) @ pagehelper.js:1
(anonymous) @ pagehelper.js:1

```

> 问题，第二行。browser is not defined。

```js
"use strict"; (async() = >{
    const e = navigator.userAgent.includes("Chrome") ? chrome: browser;
    window === window.top && e.runtime.onMessage.addListener((t, n, r) = >{
        if ("cmd_get_title" === t.cmd) {
            const t = "https://www.google.com/s2/favicons?domain=" + encodeURIComponent(location.origin),
   
       ... ... .... ....
})();
```
> 测试了几次，回退了到了最初的状态，刷新还是有，不知道问题。是这个js文件错了么？

**Comment by xaoxuu** [comment]
你贴的这段代码我搜不到啊

**Comment by ghost** [comment]
我也一直找，找不到。但是就是在那。好像是分页的js。我刚刚又下了一遍，一个个改的。发现改完_config.yml 中的导航栏部分。然后就出错了。回退也没用。我想是不是N级导航那里？

**Comment by xaoxuu** [comment]
你先按照这里的方法自己找一下问题所在： https://volantis.js.org/faqs/

**Comment by ghost** [comment]
嗯，我再试试。还有这个不是控制台报错，是浏览器中的控制台。

**Comment by ghost** [comment]
大佬，你的网站也有，我刚刚刷新了一下，刚刚进去并没有，点了一篇文章后浏览器控制台就报错了，并且一直存在。

**Comment by xaoxuu** [comment]
我这里看是没有报错的

**Comment by ghost** [comment]
大佬还没睡呢，我这录了屏。难道说我的浏览器问题么？

**Comment by ghost** [comment]
：https://img.vim-cn.com/72/5218b273c1b9a6e86f492d611cb4da255494ac.gif

**Comment by xaoxuu** [comment]
https://img.vim-cn.com/1c/34bb9739be0ff7dd38615e6f622623eea6f687.mov

**Comment by ghost** [comment]
好吧。可能还是我自己的问题吧。辛苦大佬了！
