### ISSUE TITLE
未在文档中找到有关于点击加载图片的功能(不跳转界面)

### ISSUE THREAD

**Issue by wz-wong** [volantis-x/hexo-theme-volantis#190]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.
-----------------------------------

文档中展示的懒加载, 点击按钮后会新开一个页面显示,体验不太友好.
请问有那种点击按钮后在本界面直接加载图片的功能吗,
目前没有在文档中找到类似功能,
奇怪的是网上也没搜到相关的,
这个功能应该算刚需啊,尤其是对博客这种带宽不高的,阅读起来也简洁

**Comment by xaoxuu** [comment]
请问为什么需要点击加载图片的功能呢？默认自动加载不好吗？

**Comment by wzzxx-wang** [comment]
写博客的时候,有时会需要多张图片, 像那种资讯类的,一句话配一张图, 

主要问题在于   信息密度低 和 占用带宽高(尤其是GIF图)

信息密度低这个挺难受, 你博客里用的图片不多,有用到的也是有必要显示的,

如果一篇博客用来写一周的资讯那种, 一段话配两张图,默认自动加载的话就会导致一个屏幕只能显示了一段话和一张图片, 阅读起来就得不停的滑滚轮, 费鼠标, 阅读体验也不太好, 
而且有些图片是有针对人群的, 有些读者对它有兴趣,会看,有些读者对它没兴趣,就会快速划过, 我是想着, 有点击加载这个功能的话, 可以让每条资讯或每个段落能够更整洁,阅读体验更好

**Comment by xaoxuu** [comment]
你是想让图片默认折叠起来？

**Comment by xaoxuu** [comment]
你可以用折叠框来实现啊：

```
{% raw %}
<details>
<summary>
查看图片
</summary>
{% endraw %}

![](https://i.loli.net/2020/03/18/f5PQlWisvm9zbgK.jpg)

{% raw %}</details>{% endraw %}
```

**Comment by xaoxuu** [comment]
<img width="745" alt="截屏2020-03-1921 35 51" src="https://user-images.githubusercontent.com/16400144/77073088-a99c0800-6a29-11ea-8eb1-a12571c48878.png">

我想你可能理解错了，文档这部分讲的是如何实现一个折叠框。而折叠框里面的一句话则是示例，“图片地址”那是一个普通的连接，不是“懒加载图片”，懒加载插件是让页面加载的时候不考虑图片是否加载完成，直到图片进入显示区域内才开始加载图片资源，在此之前显示的是占位图。

**Comment by wzzxx-wang** [comment]
折叠框理解, 将点击加载设置成折叠框那种,凑合能成.

只是那种状态, 即使我对折叠的图片不感兴趣,但它实际上也是耗费了流量加载了吧,
而且GIF图的问题,抱歉我对流量挺敏感, 网速慢, 如果没点击图片加载功能的话,
GIF图以目前功能来说是没有那种 动图上边有个gif的图标,点了那个图标,它才会加载,才会动起来,
如果一篇博客里面有多张动图的话, 那岂不是要等挺久才能看到它动起来么.

点击加载图片也是可以解决 GIF 占用带宽大的问题

**Comment by xaoxuu** [comment]
如果一个页面图片太多确实没办法，懒加载插件其实已经挺不错的了，至少图片加载前页面就已经可以看了。

**Comment by wzzxx-wang** [comment]
按需加载 这个功能没办法实现吗,是需要第三方插件还是hexo框架的局限, 刚搜了一下,可以通过js和css实现, 只是这个博客是用maskdown编译成的网页文件,改生成的网页也没用,下次生成又覆盖了, 有没有更好的方法, 关于 GIF图的, 点击才让它加载

**Comment by xaoxuu** [comment]
这个我不会做，你可以找找有没有相关的hexo插件。

**Comment by wzzxx-wang** [comment]
好的,谢谢解答
