### ISSUE TITLE
"关于"的导航栏的字样显示不全

### ISSUE THREAD

**Issue by AGJackie** [volantis-x/hexo-theme-volantis#191]
已更新至2.1.6版本

在“关于”界面的导航栏的标题只能显示一个字，如图：
https://imgkr.cn-bj.ufileos.com/dab7aee0-b1d5-48bb-80d6-36218b114fbb.jpg

复现的例子https://actuarygarden.cn/about/

**Comment by Charlie-zzy** [comment]
页面宽度的问题，可以试试增加一下侧边栏什么的，不然只能在配置里面改宽度了。

**Comment by AGJackie** [comment]
好的，谢谢！

**Comment by xaoxuu** [comment]
在2.1.6以前，同样宽度下，被压缩的不是菜单，而是logo。

**Comment by xaoxuu** [comment]
导航栏菜单比较多时最好的方法是使用层级菜单，也就是嵌套起来，不要全部平铺。

**Comment by AGJackie** [comment]
是的，之前在关于界面里logo会压缩。我试试层级菜单
