### ISSUE TITLE
请调整评论颜色配置

### ISSUE THREAD

**Issue by Charlie-zzy** [volantis-x/hexo-theme-volantis#192]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

------
Volantis评论的颜色可以与主题配置的颜色同步吗？详见![这里](https://s1.ax1x.com/2020/03/20/8guYHe.png)

**Comment by xaoxuu** [comment]
已经更新了👌

**Comment by Charlie-zzy** [comment]
感谢😀
