### ISSUE TITLE
导航栏切换时的 Bug

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#193]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.

***

手机端下，文章页面中，激活搜索状态，当搜索框展开时，屏幕下滑，文章标题没有切换出来。

![](https://s1.ax1x.com/2020/03/20/8gakmd.png)

**Comment by inkss** [comment]
不如在下滑的时候顺便把搜索给关了吧，`z_search-open`，另外，鼠标在点击这几个按钮时看到了轻微的抖动。

**Comment by xaoxuu** [comment]
我已经更新了，你看看ok不

**Comment by inkss** [comment]
👌

**Comment by xaoxuu** [comment]
滚动的时候关闭搜索框不行，手机上一点击搜索就会因为弹出输入法而滚动。。。

**Comment by inkss** [comment]
好像有点不对，我测试的角度也不太正确，PC下测试时是用滚轮滑动的，没有触摸点击

**Comment by inkss** [comment]
引用一下这个：

> 在点击这几个按钮时看到了轻微的抖动。

我仔细观察了下，你的官网 2.2 版本，搜索激活后，在别的空白处点一下，确实有一个轻微的抖动，以前好像是老版本的主题鼠标放在图标上就抖个不停，现在是离开后才有这个抖动。

给样式加了行这个就消失了，虽然我不知道为啥 (´ｰ∀ｰ`)

```css
.l_header .switcher>li a {
  line-height: inherit;
}
```

现象：

![](https://s1.ax1x.com/2020/03/21/8RE5uD.gif)

**Comment by xaoxuu** [comment]
看上去还挺有意思的😂

**Comment by xaoxuu** [comment]
应该是涟漪效果导致的，那个插件自带了一套样式，行高、padding之类的，在hover和active的时候就会变

**Comment by inkss** [comment]
我想起为啥我会特别留意这个了，是 PC  端界面，鼠标移过时出现的抖动，嗯，应该是 hover 无疑了。


![](https://s1.ax1x.com/2020/03/21/8RZpQK.gif)
