### ISSUE TITLE
旧版的写作文档有没有了，例如折叠框，新的写法不兼容老版，老版的写法又忘了...

### ISSUE THREAD

**Issue by ChemLez** [volantis-x/hexo-theme-volantis#194]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

**Comment by Charlie-zzy** [comment]
这是[历史版本](https://github.com/xaoxuu/volantis-docs/blob/c46d2e3f64d1d6583328d8a2fc7c021e5780c26a/source/tag-plugins/index.md)，会错位... @xaoxuu 不如把各个大版本的文档分别放在子域名下？

**Comment by Charlie-zzy** [comment]
当然这么看也是可以的

**Comment by ChemLez** [comment]
> 这是[历史版本](https://github.com/xaoxuu/volantis-docs/blob/c46d2e3f64d1d6583328d8a2fc7c021e5780c26a/source/tag-plugins/index.md)，会错位... @xaoxuu 不如把各个大版本的文档分别放在子域名下？

感谢

**Comment by AGJackie** [comment]
我刚也发现了，比如表格滚动 overflow 之类的写法在文档里被删除了。不过似乎overflow的写法在更新到2.2以后仍然适用。是不是旧版的文档的功能在新版也适用来着？

**Comment by Charlie-zzy** [comment]
是的，我以前的overflow仍然能用qwq

________________________________
发件人: AGJackie <notifications@github.com>
发送时间: 2020年3月22日 18:26
收件人: xaoxuu/hexo-theme-volantis <hexo-theme-volantis@noreply.github.com>
抄送: Charlie <neycbs@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [xaoxuu/hexo-theme-volantis] 旧版的写作文档有没有了，例如折叠框，新的写法不兼容老版，老版的写法又忘了... (#194)


我刚也发现了，比如表格滚动 overflow 之类的写法在文档里被删除了。不过似乎overflow的写法在更新到2.2以后仍然适用。是不是旧版的文档的功能在新版也适用来着？

―

**Comment by xaoxuu** [comment]
已经是默认效果了

**Comment by AGJackie** [comment]
默认效果是指，表格默认横向滚动，不用写overflow？

**Comment by xaoxuu** [comment]
不用
