### ISSUE TITLE
win下如何更新主题，现有脚本仅linux可用

### ISSUE THREAD

**Issue by wz-wong** [volantis-x/hexo-theme-volantis#195]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Other Information 
你好，你博客上留的安装脚本，经测试，仅linux可用，目前本地更新主题的方式是，
备份配置文件
下载代码压缩包
覆盖
替换配置文件，

服务器上简单 hexo.sh，u 就直接更新了，
本地虽说步骤不多，但架不住你更新频繁...
今天看到有个 folding 标签可用，一使就报错，提示没这个标签，得更新，
能有个本地用的主题更新的 bat 脚本就好了

`echo '自动更新主题'`
`下载文件`
`cd volantis`
`copy _config_bak.yml  _config.yml`
`pause`

一个半成品,这样更新后,本地依旧无法使用 folding
`Unhandled rejection Nunjucks Error:  [Line 1, Column 4] unknown block tag: folding`
提示没这个标签, 能给些参考吗

**Comment by wzzxx-wang** [comment]
刚对比了2.0和2.2.0的配置文件, 内容有新增, 不能靠单纯的备份替换解决, 本地的话,请问要怎么更新主题?

**Comment by wzzxx-wang** [comment]
fancybox 的语法也改了...  报 folding 一样的错，没这个标签，
`Nunjucks Error:  [Line 61, Column 4] unknown block tag: fancybox`
我没切换新语法 ` {% fancybox  %}` 的时候还是正常的，只是没放大按钮，切换后就报错了，
我也有更新主题啊， 难道是我主题没更新好吗

**Comment by xaoxuu** [comment]
fork主题仓库到 `wzzxx7/hexo-theme-volantis` 然后把 `wzzxx7/hexo-theme-volantis` 添加为博客仓库的子模块， 然后进行修改使用。
更新的时候把 `xaoxuu/hexo-theme-volantis` 的最新代码 merge 到 `wzzxx7/hexo-theme-volantis` 中。具体步骤搜索一下关键词 [fork 更新]

**Comment by xaoxuu** [comment]
https://www.jianshu.com/p/8ab6ef7ce5e3

**Comment by Charlie-zzy** [comment]
我都是直接拿VScode对比前后两个版本的`_config.yml`，然后看修改了什么，没有的话就把除了版本差别以外的地方复制粘贴...

或者想多留几个主题版本的话可以修改主题文件夹名称啊，比如说`volantis 2.1.6`，`volantis 2.2.0`之类的，方便回滚。但是文章中的语法有变化就没办法了

**Comment by xaoxuu** [comment]
使用git管理代码可以随时回退到任何一次修改

**Comment by Charlie-zzy** [comment]
但是我不会用啊qwq

VScode集成的git倒是很好用

________________________________
发件人: Mr. X <notifications@github.com>
发送时间: 2020年3月24日 11:16
收件人: xaoxuu/hexo-theme-volantis <hexo-theme-volantis@noreply.github.com>
抄送: Charlie <neycbs@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [xaoxuu/hexo-theme-volantis] win下如何更新主题，现有脚本仅linux可用 (#195)


使用git管理代码可以随时回退到任何一次修改

―
