### ISSUE TITLE
文章目录无法显示

### ISSUE THREAD

**Issue by jiahao-jayden** [volantis-x/hexo-theme-volantis#196]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
不知道什么原因文章目录无法显示，好像其他部件也没有出来
![image](https://cdn.jsdelivr.net/gh/mrhuanhao/cdn/problem/screenshot2020-03-23_19-04-05.png)

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

**Comment by Charlie-zzy** [comment]
？？？

**Comment by Charlie-zzy** [comment]
所以说解决了吧😓
