### ISSUE TITLE
我自建的404页面被主题渲染了

### ISSUE THREAD

**Issue by jiahao-jayden** [volantis-x/hexo-theme-volantis#199]
## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
我自己创建的404页面好像被渲染了
![image](https://cdn.jsdelivr.net/gh/mrhuanhao/cdn/problem/screenshot2020-03-24_09-08-24.png)
![image](https://cdn.jsdelivr.net/gh/mrhuanhao/cdn/problem/screenshot2020-03-24_09-08-34.png)
这是我跳过渲染的设置
![image](https://cdn.jsdelivr.net/gh/mrhuanhao/cdn/problem/screenshot2020-03-24_09-10-40.png)

**Comment by xaoxuu** [comment]
已在2.2.1版本中修复了
