### ISSUE TITLE
没有做SEO

### ISSUE THREAD

**Issue by ic3evi1** [volantis-x/hexo-theme-volantis#20]
没有做SEO这块，渲染的页面没有keywords，希望各位大神有空做一下。

**Comment by xaoxuu** [comment]
SEO可以自己去hexo官网搜搜安装几个现成的插件， 
keywords现在是删掉了，详见 #13

**Comment by ic3evi1** [comment]
我已经提交了代码，老大可以看看，能不能行，我自己测试了几次都是好的。

**Comment by xaoxuu** [comment]
好的，看你这么热情，我merge了，不过做了一点修改，不然会有undefined出现。
