### ISSUE TITLE
Aplayer加载问题(可复现)

### ISSUE THREAD

**Issue by Charlie-zzy** [volantis-x/hexo-theme-volantis#206]
## Issue Checklist 
- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Expected behavior 
Aplayer未按预期加载

## Actual behavior 

- [Links to demo site with this issue](https://cgarlie-zzy.github.io)
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. Ctrl+F5
2. Aplayer未加载
3. 重新F5有大概率加载

## Other Information 
Browser:`Edge Dev 83.0.461.1`

**Comment by Charlie-zzy** [comment]
![image.png](https://i.loli.net/2020/03/30/kaigjxY8D3pvnZ1.png)

**Comment by Charlie-zzy** [comment]
https://i.loli.net/2020/03/30/kaigjxY8D3pvnZ1.png

**Comment by Charlie-zzy** [comment]
https://i.loli.net/2020/03/30/hVZeX5r2RMuKfjn.png

刷新缓存后上图未显示Aplayer，F5刷新后显示了：

https://i.loli.net/2020/03/30/ckS4ZMYjsU6JdVA.png

**Comment by xaoxuu** [comment]
你更新一下主题看看 d7064838752cdf69f8aa23417826c08bc0acfb4c
