### ISSUE TITLE
自定义donate里的两个

### ISSUE THREAD

**Issue by MaskXman** [volantis-x/hexo-theme-volantis#207]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.v

***

## Describe your question 
你好，请问我在github里建了一个cdn的j库用来放资源，然后更改主题里的_config.ym地址发现资源加载不出来是为什么呀
，已检查代码没有问题，资源地址没写错
我的博客https://maskxman.github.iohttps://maskxman.github.io

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

**Comment by xaoxuu** [comment]
你加载的是本地的呀

**Comment by MaskXman** [comment]
问题已解决。 是realease的问题。。。。而且大佬说的也对我本地资源有问题。
感谢
