### ISSUE TITLE
使用 2.3.2 版本的 video 无法自动缩小到文章内宽度

### ISSUE THREAD

**Issue by Tikas** [volantis-x/hexo-theme-volantis#209]
假设文章页面宽 800 px，视频是 1920 宽的话，使用 {% video 视频链接 %} ，视频显示好大！

超出 文章内宽了

**Comment by xaoxuu** [comment]
不要假设，你截图证明啊
我看主题文档里的示例视频以及你的博客中的视频宽度都是挺正常的啊

**Comment by Tikas** [comment]
没有假设，是真的，我的网站使用了 iframe 标签，自定义宽高，你可以用 

{% video https://cdn.jsdelivr.net/gh/tikas/cdn@1.1/video/MapleStory720.mp4 %} 

试试看

**Comment by xaoxuu** [comment]
主题文档中有示例
