### ISSUE TITLE
2.4 preview 导航栏UI问题

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#210]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

## Other Information 

![GJFyE4.png](https://s1.ax1x.com/2020/04/02/GJFyE4.png)

**Comment by xaoxuu** [comment]
刚发布了正式版

**Comment by Reqwey** [comment]
还是有问题啊, 那个"搜索文档"会跑到左边

**Comment by Reqwey** [comment]
还有一个小建议, 移动端的导航栏多级菜单改成折叠框(Folding)的形式, 毕竟移动端显示范围有限

**Comment by xaoxuu** [comment]
显示范围有限就少放点啊

**Comment by Reqwey** [comment]
那好吧，我的问题就是移动端下导航栏的搜索框会有BUG，会跑到左边把标题遮了

**Comment by xaoxuu** [comment]
本来就是啊，不然你想让它显示到哪

**Comment by xaoxuu** [comment]
不光要把标题遮住，还要把整个导航栏遮住。。

**Comment by Reqwey** [comment]
不是啊, 是搜索框没有展开的时候...

**Comment by Reqwey** [comment]
正常情况下是没有那个东西的, 你可以看我上面的截图

**Comment by xaoxuu** [comment]
现在正式版不存在这个bug了吧

**Comment by Reqwey** [comment]
还是有啊, 你可以把你的浏览器窗口缩小就可以看的很清楚

**Comment by Reqwey** [comment]
就是弄出移动端的导航栏

**Comment by Reqwey** [comment]
很奇怪, 按F12然后手动改成移动端都没有这个bug, 但是你桌面模式把窗口缩小就有这个bug了

**Comment by xaoxuu** [comment]
以真机为准吧

**Comment by xaoxuu** [comment]
我知道哪的问题了，一会更新一下

**Comment by xaoxuu** [comment]
我知道哪的问题了，一会更新一下

**Comment by Reqwey** [comment]
嗯感觉现在没问题了
