### ISSUE TITLE
升级到2.40后，生成页面报错

### ISSUE THREAD

**Issue by wz-wong** [volantis-x/hexo-theme-volantis#211]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***
你好，昨天我从 2.30 更新到了2.40，（下载最新代码，对比更新配置文件）
然后执行  `hexo g` 生成网页的时候，提示报错，个别网页创建错误
`INFO  Start processing`
`INFO  Files loaded in 288 ms`
`ERROR Render HTML failed: 404.html`
`TypeError: xxxxxx\themes\hexo-theme-volantis-master\layout\layout.ejs:5`
`    3| <%- partial('_partial/head') %>`
`    4| <body>`
` >> 5|   <%- partial('_partial/cover') %>`
`    6|   <div class="l_body<%- page.cover ? '' : ' nocover' %>">`
 `   7|     <div class='body-wrapper'>`
 `   8|       <%- body %>`
![image](https://user-images.githubusercontent.com/38744714/78320610-6f3f7880-759c-11ea-811e-099ee63e3cdc.png)
`ERROR Render HTML failed: about/index.html`
`ERROR Render HTML failed: categories/index.html`
`ERROR Render HTML failed: friends/index.html`
`ERROR Render HTML failed: mylist/index.html`
...
报的错都类似这样，然后我将主题恢复到 2.20 就正常了（2.3被我删掉了，没法恢复）
注：写的文章均挪到其他地方，生成的文件不会包含文章
基本可以确定是主题问题

另外，
查看插件安装 `npm ls --depth 0` 提示依赖有问题
 `+-- UNMET PEER DEPENDENCY hexo@4.2.0`
`npm ERR! peer dep missing: hexo@^3.2.2, required by hexo-offline@1.0.0`
不过 2.20 是正常的，那就不是插件问题，供参考

有空麻烦帮分析下出错原因

**Comment by xaoxuu** [comment]
因为2.4的导航栏菜单有变动，和旧版本不兼容，你需要进行修改。
[#设置导航栏](https://volantis.js.org/theme-settings/#%E8%AE%BE%E7%BD%AE%E5%AF%BC%E8%88%AA%E6%A0%8F)

**Comment by wzzxx-wang** [comment]
谢谢，已经正常， 还有一个小bug， 导航栏哪里有一个logo图片，测试发现它并不是固定大小，我换了一张大图，立马将整个导航栏顶错位了，如下图所示
![image](https://user-images.githubusercontent.com/38744714/78334570-8ee79880-75be-11ea-98b4-dd190b18663c.png)


----------
顺便问一下，文章后面的   上一篇/下一篇   里面的显示内容可以用 `<!-- more -->` 来限制吗，它会连floding里的文字都显示，这并不美观
![image](https://user-images.githubusercontent.com/38744714/78335233-ce62b480-75bf-11ea-8360-8982011e0439.png)

**Comment by xaoxuu** [comment]
好的，第一个问题刚修复了
第二个问题，这个框里的内容是纯文本的，不会进行md渲染，否则过于复杂了，而且占用的空间也会大很多。

**Comment by wzzxx-wang** [comment]
好的，测试没问题了，
关于第二个问题，无法进行md渲染的话，我想在每篇文章`<!-- more -->`后面加一行空格来填充字数，防止后面的正文被读到(但现在的设定是不将空格算作字数，可以设置将空格也算作字数吗)

**Comment by xaoxuu** [comment]
这规则是hexo定的

**Comment by xaoxuu** [comment]
不建议一开头就放语法，一般博客开篇都有引言，即便是技术博客也需要有引言。
例如： https://onevcat.com/#blog 他的博客阅读体验就很好。

**Comment by wzzxx-wang** [comment]
![image](https://user-images.githubusercontent.com/38744714/78421396-c40ced00-7689-11ea-8d56-b7530813f51f.png)

当然我的意思并非不要引言，从上图可以看到，引言和正文内容混在一起了，而且没有明显分割。
hexo虽然规定不能用语法，但是是可以设定一些规则的吧，起码它屏蔽了标签被读取，
在它算字数上有操作空间吗，例如让空格或者标签也算字数，这样就可以在前言的下一行放一整行空格或者不会被显示的标签。让它只能显示前言，不会显示正文，避免混乱

**Comment by xaoxuu** [comment]
没你想的那么复杂，他的文章开头是有一大段文字描述的。
我所说的引言不是格式上的引言部分，而是文章开篇的一段文字 [#引言](https://baike.baidu.com/item/%E5%BC%95%E8%A8%80)。

**Comment by xaoxuu** [comment]
针对本 issue 话题「升级到2.40后，生成页面报错」来说这不是个 bug ，此 issue 已关闭。如有其它问题请单独创建 issue 。

**Comment by wzzxx-wang** [comment]
好的，明白了，谢谢
