### ISSUE TITLE
主题问题

### ISSUE THREAD

**Issue by Yafine** [volantis-x/hexo-theme-volantis#214]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.
我在原有的导航栏的配置再加更多的N级导航栏报错，menu.yml文件配置，大佬能否将这块的配置文件截图发下呀，我没看懂示例咋写？谢谢
![image](https://user-images.githubusercontent.com/31881437/78416566-1800dd00-765c-11ea-9923-1696e37f4941.png)

**Comment by xaoxuu** [comment]
我升级了版本之后改动的位置的配置文档都会更新，并且更新日志中也会提到。

**Comment by xaoxuu** [comment]
<img width="815" alt="截屏2020-04-04 13 21 37" src="https://user-images.githubusercontent.com/16400144/78419321-39bb8d80-7677-11ea-890a-bce11a24c83d.png">

**Comment by Yafine** [comment]
> 我升级了版本之后改动的位置的配置文档都会更新，并且更新日志中也会提到。

好的，谢谢

**Comment by Yafine** [comment]
> 我升级了版本之后改动的位置的配置文档都会更新，并且更新日志中也会提到。

![code](https://user-images.githubusercontent.com/31881437/78422516-6335e280-7692-11ea-8fc6-61d909bfc3a5.png)
zhe'yang'xie
这样写menu.yml格式对吗？我这样写报错，而且更多的导航栏也显示不出来

**Comment by xaoxuu** [comment]
<img width="235" alt="截屏2020-04-04 17 33 20" src="https://user-images.githubusercontent.com/16400144/78423661-7ea4eb80-769a-11ea-88de-150dbc9b63c2.png">

**Comment by Yafine** [comment]
非常感谢，已解决问题
另外，我有一点建议，可不可以将这个继续变窄
![image](https://user-images.githubusercontent.com/31881437/78424527-d8101900-76a0-11ea-9dd9-ef22701d32ff.png)
修改为这中的
![image](https://user-images.githubusercontent.com/31881437/78424661-a186ce00-76a1-11ea-8683-71465e57ec44.png)
我不知道怎么修改，可以作为下一计划的更新吗？

**Comment by inkss** [comment]
手机端的导航栏播放器有比较好的解决方法吗 @xaoxuu 
看主题的文档是用 menu.yml 配置的，似乎没有能力区分 PC 端和手机端呀

![image](https://user-images.githubusercontent.com/31947043/78749189-553cd600-79a0-11ea-92c0-1a8c30ba714e.png)

**Comment by inkss** [comment]
这种类型的呢？首页滑动到最上面的时候 @xaoxuu 

![image](https://user-images.githubusercontent.com/31947043/78762796-f040aa80-79b6-11ea-8381-0bfb59eca13c.png)

**Comment by xaoxuu** [comment]
已改👌
