### ISSUE TITLE
[公告] 关于主题与文档的更新

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#215]
由于主题目前仍处于青少年阶段，更新迭代速度比较快，所以不会保留旧版本的文档，如果需要查看旧版本的文档，请下载主题文档的源码，回退到旧版本，本地运行查看。

计划 `2.x` 的最后一个版本的文档会保留至 `5.0` 发布时，即最终会同时维护3个大版本的文档。

当主题稳定后会提供英文文档。

**Comment by 0x01x0** [comment]
更新2.4.2以后 aplayer挂了

**Comment by xaoxuu** [comment]
证据呢 
![](https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/aru/161.png)

**Comment by xaoxuu** [comment]
<img width="739" alt="截屏2020-04-05 11 18 39" src="https://user-images.githubusercontent.com/16400144/78466015-44d1f480-772f-11ea-80ed-4de315e1b866.png">

**Comment by 0x01x0** [comment]
😳😳昨天晚上我连你博客的播放器都看不到 估计我的浏览器炸了吧 不过我手机也看不到 可能是我网炸了吧😂😂

**Comment by xaoxuu** [comment]
那可能是昨天停止一切娱乐活动的政策原因吧

**Comment by 0x01x0** [comment]
多谢大佬提供这么好的主题！

**Comment by jiahao-jayden** [comment]
大佬，你更新地也太快了吧！
