### ISSUE TITLE
我在本地测试的时候点击tags和categories 都经常；但是上传以后有些tags和categories 404了 ；不知道怎么回事；

### ISSUE THREAD

**Issue by uyplayer** [volantis-x/hexo-theme-volantis#217]
下面的两个404了  
https://uyplayer.pw/tags/Thread/
https://uyplayer.pw/categories/Python/

我发现一个问题我把Thread和Python的首字母小写以后经常了 
https://uyplayer.pw/tags/thread/
https://uyplayer.pw/categories/python/

**Comment by xaoxuu** [comment]
https://hexo.io/zh-cn/docs/configuration

**Comment by xaoxuu** [comment]
Duplicate of #181
