### ISSUE TITLE
Valine评论问题

### ISSUE THREAD

**Issue by jiahao-jayden** [volantis-x/hexo-theme-volantis#223]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
好像2.5或者2.5.1更新之后，valine的验证码无法使用了，不知道是什么原因
然后valine官方已经更新到1.4.1，希望作者更新valine版本！

**Comment by xaoxuu** [comment]
https://valine.js.org/changelog.html

**Comment by xaoxuu** [comment]
- [x] 已经更新 `2.6.0` 对应 valine 版本是 `1.4.2`
