### ISSUE TITLE
建议加入横向选中CheckBox

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#224]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

我看你加入了多彩的CheckBox和Radio, 但是没有加入横向选中的CheckBox, 我觉得这个是最好玩的😂
https://blog.lhkstudio.me/2020/04/11/use-checkbox-in-volantis/#%E5%A4%8D%E6%9D%82%E7%89%88-HTML

**Comment by xaoxuu** [comment]
我不知道有什么用

**Comment by Reqwey** [comment]
大概相当于半对什么的, 我也不知道, 反正就是好玩😁

**Comment by Reqwey** [comment]
或者比如说新增功能用`√`, 删掉的功能用`-`, 未完成的不填

**Comment by Reqwey** [comment]
反正增加了一个选项嘛

**Comment by xaoxuu** [comment]
那就增加个 `x` 好了

**Comment by xaoxuu** [comment]
全都安排上了 ![](https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/tieba/%E6%BB%91%E7%A8%BD.png)

**Comment by Reqwey** [comment]
哇一次安排了这么多 👍

**Comment by Reqwey** [comment]
太强大了
