### ISSUE TITLE
页头导航栏如何设置不缩进

### ISSUE THREAD

**Issue by gaoyanliang** [volantis-x/hexo-theme-volantis#225]
![image](https://user-images.githubusercontent.com/33021341/79058765-a270be80-7ca4-11ea-901c-5cfeb32b32d9.png)

如上图，请教一下，有没有什么配置可以设置页头部分的导航 文字不缩进

**Comment by xaoxuu** [comment]
1. 菜单过多时使用多级菜单
2. 导航栏宽度由 auto 修改为 max

**Comment by gaoyanliang** [comment]
好嘞，谢谢
