### ISSUE TITLE
source/_data/menu.yml不生效

### ISSUE THREAD

**Issue by jiahao-jayden** [volantis-x/hexo-theme-volantis#227]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Describe your question 
之前一直把menu放在配置文件里面，太长了，现在想把他单独放在`source/_data/menu.yml`里面，但是不知道为什么没有生效，图片中我使用了docs里面的样例
然后`layout`以及`widget`文件都生效了，不知道menu为什么不生效
**左边为主题配置文件**
**右边为`_data/menu.yml`**
![screenshot2020-04-13_09-18-05.png](https://i.loli.net/2020/04/13/N6w1IHMD9aBLUOF.png)
这是最后的效果，并没有生效menu
![screenshot2020-04-13_09-12-55.png](https://i.loli.net/2020/04/13/UJ8hE1Mw3taDIQC.png)

**Comment by xaoxuu** [comment]
文件名多了个下划线

**Comment by jiahao-jayden** [comment]
原来如此，瞎了瞎了，谢谢！
