### ISSUE TITLE
想请问原来的字体链接是哪个呢...我觉得原来的字体圆一点好看些

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#228]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

**Comment by xaoxuu** [comment]
https://github.com/xaoxuu/hexo-theme-volantis/blob/bab70e3e192dd8765bf8529b8a7ded6e16586583/_config.yml#L70
