### ISSUE TITLE
在摘要之前如果有比正文标题号小的标题的话,文章目录渲染错误

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#230]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

![image](https://user-images.githubusercontent.com/44713252/79095960-6b76d780-7d8e-11ea-846c-6ec8bd528870.png)
![image](https://user-images.githubusercontent.com/44713252/79095983-76ca0300-7d8e-11ea-92c0-9586d84e5723.png)
修改'欧拉'标题号为段落
渲染正确
![image](https://user-images.githubusercontent.com/44713252/79096090-b690ea80-7d8e-11ea-85f5-74c1719de1e6.png)

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

**Comment by ghost** [comment]
还有不明原因的渲染错误
![image](https://user-images.githubusercontent.com/44713252/79096161-eb04a680-7d8e-11ea-8cb1-f23ea06050f6.png)
![image](https://user-images.githubusercontent.com/44713252/79096190-01126700-7d8f-11ea-8390-ad6a41a29274.png)
在老版本上是没有这个问题的,,,md文件一摸一样的

**Comment by xaoxuu** [comment]
确实是这样子的，如果你认为这样不合理的话可以给 hexo 提。

**Comment by ghost** [comment]
主要是之前2.4的版本没有这些问题呢😂

**Comment by xaoxuu** [comment]
toc生成器跟我没有一点点关系的，完全是 hexo 解析的。

**Comment by ghost** [comment]
谢谢了!不过真是奇怪...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mr. X"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午2:08
收件人:&nbsp;"xaoxuu/hexo-theme-volantis"<hexo-theme-volantis@noreply.github.com&gt;;
抄送:&nbsp;"咖喱羊羊羊"<1017975501@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xaoxuu/hexo-theme-volantis] 在摘要之前如果有比正文标题号小的标题的话,文章目录渲染错误 (#230)





 
toc生成器跟我没有一点点关系的，完全是 hexo 解析的。

**Comment by Reqwey** [comment]
@xaoxuu 有没有可能是你`<ul>`标签渲染错了, 应该需要把某个`list-style: initial;`改成`none`
因为我看它标题显示成功了, 就是CSS坏了 😄
