### ISSUE TITLE
网站自定义图标失败

### ISSUE THREAD

**Issue by rChunYoung** [volantis-x/hexo-theme-volantis#234]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。
# 网站图标，更多尺寸等图标请使用import方式批量导入
favicon: https://github.com/rChunYoung/rChunYoung.github.io/logo.png

您好我是用样例可以 但自己的连接不行，如果使用本地图片该怎么用呀？
另外如何更改背景和设置个人图像在首页呀？
感谢！！
## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

**Comment by Reqwey** [comment]
你链接本来就是错的, 换成`/logo.png`试试

**Comment by rChunYoung** [comment]
您的意思时不加连接，读取本地吗？请问图片存哪个目录呀

**Comment by Reqwey** [comment]
我看你的图片就是存在你网站的根目录啊

**Comment by Reqwey** [comment]
要从链接读取有特定的方式的

**Comment by rChunYoung** [comment]
那就是直接方网站上 然后/logo.png对吧？
另外如果文件在本地硬盘，应该放哪里怎么读
谢谢

**Comment by Reqwey** [comment]
就算你直接从GitHub读取也得用 https://raw.githubusercontent.com/rChunYoung/rChunYoung.github.io/master/logo.png, 不过这种方式和直接读取本地一样慢, 甚至可能被墙

**Comment by Reqwey** [comment]
> 那就是直接方网站上 然后/logo.png对吧？
> 另外如果文件在本地硬盘，应该放哪里怎么读
> 谢谢

本地硬盘??传到GitHub仓库才能读取(除非你的电脑是服务器

**Comment by rChunYoung** [comment]
我的意思图片在本地应该放那个文件夹，怎么读？
谢谢

**Comment by Reqwey** [comment]
比如说你放在img文件夹就读取`/img/logo.png`

**Comment by Reqwey** [comment]
不过这样太慢了, 推荐你用CDN的方式 https://cdn.jsdelivr.net/gh/rChunYoung/rChunYoung.github.io@master/logo.png 这样最快, 而且不会被墙

**Comment by rChunYoung** [comment]
好的谢谢 我试试是放博客的image还是theme里的 哈哈

**Comment by Reqwey** [comment]
> 比如说你放在img文件夹就读取`/img/logo.png`

这里是指hexo根目录里`/source`文件夹里自己再建一个`/img`其它地方hexo不会读取

**Comment by Reqwey** [comment]
不是放theme里

**Comment by Reqwey** [comment]
反正直接丢`/source`里就对了

**Comment by rChunYoung** [comment]
好的 感谢您

**Comment by rChunYoung** [comment]
ok感谢大佬

**Comment by Reqwey** [comment]
不用谢. hexo会把/source文件夹里的所有东西(除了有下划线开头的)copy到上传的文件夹里

**Comment by Reqwey** [comment]
@xaoxuu 他应该OK了
