### ISSUE TITLE
关于文章图片的一些建议

### ISSUE THREAD

**Issue by ericclose** [volantis-x/hexo-theme-volantis#235]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

以下是我的3点建议

* 给文章图片边缘加上阴影效果，以增加层次感。
* 添加点击文章图片放大的功能
* 给文章图片添加幻灯片的功能（这个功能的话感觉不是很有必要 :smile:）

类似这个样子：
![deepin-screen-recorder_Select area_20200414114835](https://user-images.githubusercontent.com/34526560/79184346-6ecd9a00-7e46-11ea-8bd0-6444c7486649.gif)

**Comment by xaoxuu** [comment]
文档地址： https://volantis.js.org/tag-plugins/#Fancybox
这个功能早在2019年3月28日之后就有了。 b7abf6a72c6be4194ba38535ed58a7761be1cae7

![image](https://user-images.githubusercontent.com/16400144/79191488-48fdc080-7e59-11ea-8fc2-7a891f9a255c.png)

**Comment by xaoxuu** [comment]
关于图片加阴影的建议我觉得不妥。如果卡片本身也有阴影，会造成试图纵深层级过多影响观感，况且图片多的时候，图片之间的阴影相互重叠也很影响观感。

![image](https://user-images.githubusercontent.com/16400144/79191577-81050380-7e59-11ea-8d65-f9b501623957.png)

**Comment by ericclose** [comment]
> 文档地址： https://volantis.js.org/tag-plugins/#Fancybox
> 这个功能早在2019年3月28日之后就有了。 [b7abf6a](https://github.com/xaoxuu/hexo-theme-volantis/commit/b7abf6a72c6be4194ba38535ed58a7761be1cae7)
> 
> ![image](https://user-images.githubusercontent.com/16400144/79191488-48fdc080-7e59-11ea-8fc2-7a891f9a255c.png)

:joy_cat: 我的错，没仔细看文档。Σ(ﾟДﾟ)

打扰了

**Comment by xaoxuu** [comment]
`2.6.1` 版本新增了一个 `image` 标签（是 fancybox 针对单图片场景的参数简化功能增强版）[#Image](https://volantis.js.org/tag-plugins/#Image)

**Comment by ericclose** [comment]
> `2.6.1` 版本新增了一个 `image` 标签（是 fancybox 针对单图片场景的参数简化功能增强版）[#Image](https://volantis.js.org/tag-plugins/#Image)

感谢！已知晓 :smile:
