### ISSUE TITLE
导航栏播放器的小问题

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#236]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

## Other Information 

如果导航栏播放器设定为自动播放, (如 https://volantis.js.org/tag-plugins) 想把它关掉的时候, 去导航栏上找到它时, 会发现它显示未播放状态, 需要点两下(先播放, 再暂停)才能把它关了

**Comment by xaoxuu** [comment]
播放状态的问题应该是插件自己的问题

**Comment by Reqwey** [comment]
我猜是它在导航栏里面界面没有一开始就加载出来造成的, 那该放哪里合适呢

**Comment by xaoxuu** [comment]
你放页脚看看

**Comment by Reqwey** [comment]
我一直就是在页脚, 因为我的版本太老了, 没有导航栏播放器 😆

**Comment by xaoxuu** [comment]
那我试一下

**Comment by xaoxuu** [comment]
就放在页脚吧

**Comment by Reqwey** [comment]
我这几天刚倒腾出导航栏播放器的来着

**Comment by inkss** [comment]
设置自动播放不可控呀，起码收到这样的报错两次：

```js
DOMException: The play() request was interrupted by a call to pause().
```

起码此两处的播放器会互相冲突，我觉得手机端可以去掉导航栏播放器部分。

![image](https://user-images.githubusercontent.com/31947043/80395871-6a918a00-88e6-11ea-8a1a-ffc700fb6b9f.png)

Pjax 部分，我完成了一半吧，现在还差你的 app.js 里的这些代码没处理，这次提交：[查看链接](https://github.com/inkss/volantis/commit/fe50cf6b25b94ab27b6f676b4e5accdf50e06772)

**Comment by xaoxuu** [comment]
这个问题 @inkss

**Comment by inkss** [comment]
@xaoxuu  提交了

**Comment by Reqwey** [comment]
其实我觉得吧手机端还是应该有独立的导航栏的, 手机端搞多级菜单真的有点奇怪, 况且手机上的浏览器大部分都比较垃圾, 除了Safari之外真没看到哪个能够把Aplayer成功显示出来的

**Comment by Linhk1606** [comment]
![Screenshot_20200428_173711.jpg](https://i.loli.net/2020/04/28/jbZwdOi85S4Kl91.jpg)

上面是Android(EMUI)9中最新版Edge(Chromium内核)的显示效果

**Comment by inkss** [comment]
**下**图这个哈哈哈，音乐播放器没加载出来时的样式没写好呀  @xaoxuu

**Comment by Reqwey** [comment]
![](https://camo.githubusercontent.com/426cea8a641bcd61e73d9893d0ddad76161d4bf5/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30342f32382f6a625a77644f69383553344b6c39312e6a7067)

上面是Android(EMUI)9中最新版Edge(Chromium内核)的显示效果

**Comment by Reqwey** [comment]
刚刚不小心把上面这条删了, 重新发一遍

**Comment by Reqwey** [comment]
> 图上这个哈哈哈，音乐播放器没加载出来时的样式没写好呀 @xaoxuu

但是Safari它可以

**Comment by inkss** [comment]
@Linhk1606  好奇 我没见过

**Comment by xaoxuu** [comment]
布局 3.0 再改

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/81786849-c8eb7900-9532-11ea-84ee-fcee669afb98.png)

这里不能调音量是什么情况呀

**Comment by hihihiwuhu** [comment]
> ![image](https://user-images.githubusercontent.com/38281581/81786849-c8eb7900-9532-11ea-84ee-fcee669afb98.png)
> 
> 这里不能调音量是什么情况呀

+1 想调音量，直接就静音了，还弄不上去了。

**Comment by inkss** [comment]
~~存在封面的页面，此处的音乐控制失效~~，看看什么影响的？



滚动造成的问题，如果是页面顶端的导航栏，控制是可以生效的。

播放器应该固定在某个位置？

**Comment by aner1001** [comment]
您好！，请问导航栏的音乐播放器怎么设置。有教程吗？

**Comment by xaoxuu** [comment]
现在不支持了

**Comment by inkss** [comment]
> 现在不支持了

https://github.com/volantis-x/hexo-theme-volantis/blob/1279c38992f84dafa71a56a4a4376be1bf5fbabf/layout/_partial/header.ejs#L44


but 这个判断还在 U•ェ•*U

**Comment by MHuiG** [comment]
https://volantis.js.org/theme-settings/navbar/#播放器

**Comment by xaoxuu** [comment]
那就是我记错了
