### ISSUE TITLE
导航栏字体样式

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#240]
## Issue Checklist

- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.
- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.

------

更多下的导航字体与位于导航栏上的字体之间的对比度是不是有点大了？

![image](https://user-images.githubusercontent.com/31947043/79551883-e14fab80-80cc-11ea-94c6-6a4c3d6e21af.png)

**Comment by xaoxuu** [comment]
可能是字体的原因吧

**Comment by xaoxuu** [comment]
对于主题默认的字体，我觉得加醋一点好：

当前的样式（菜单字重为 `bold`）：
![image](https://user-images.githubusercontent.com/16400144/79585460-686b4680-8102-11ea-823d-b1e11d68ad5f.png)

改为标准字重：
![image](https://user-images.githubusercontent.com/16400144/79585421-5ab5c100-8102-11ea-9880-1c759a8f181b.png)

**Comment by inkss** [comment]
可以的，不过我是准备各种纤细一点的，所以才觉得有点突兀来着  刚刚更新了，哈哈哈

**Comment by Reqwey** [comment]
@inkss 哇你也买了FontAwesome Pro的字体啊hhh

**Comment by inkss** [comment]
@Linhk1606 咳咳，说来惭愧，并没有买，只是太想用纤细的图标了，本来我是想用羽毛这套图标的：[feather](https://github.com/feathericons/feather) ，但是有点不太会用 js 操作 svg 图标 尴尬，然后就。。。。。。。。。。。 其实需要的图标本来也不多，也就只有几个   😅

**Comment by Reqwey** [comment]
@inkss 给你看个更...的东西 https://github.com/Linhk1606/fontawesome-cdn
Font Awesome 5.13.0 Pro的镜像...可以直接jsDelivr调用

**Comment by inkss** [comment]
Awesome 的许可证好像是一次付费，永久拥有吗，只是订阅到期后不能更新了？

**Comment by Reqwey** [comment]
不知道耶, 反正我也是从别人那里坑来的, 光是上传到GitHub花了半个小时😂
反正现在直接`https://cdn.jsdelivr.net/gh/Linhk1606/fontawesome-cdn@5.13.0/css/all.min.css`就能随便调用了

**Comment by inkss** [comment]
哈哈哈，我也是网上搜索到的，压缩文件里第一个就是说这是一份商业授权云云。其实，我是最初准备整个换掉所有图标，然后使用羽毛的图标，但是换过去后图标的大小位置全乱了，调整着太累就用了这个，不过话说起来，feather 的图标更好看一些哎：
![image](https://user-images.githubusercontent.com/31947043/79638044-17b52580-81b6-11ea-82d8-4fa9941d2e12.png)

**Comment by Reqwey** [comment]
emm正常人都不会好心到把自己辛辛苦苦买的图标拿去放GitHub上吧

**Comment by inkss** [comment]
依旧是老生常谈的商业授权问题吧，商业行为都得付费
