### ISSUE TITLE
近期不再更新了

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#241]
经过若干次迭代，`2.6.x` 已经达到 `2.x` 的理想状态，如果没有重要 bug ，近期不会再更新了。旧版本的朋友们可以升级了。。。

下次大改计划是实现 pjax ，个人能力有限，希望有相关方面的大佬提供帮助，感激不尽！

**Comment by Reqwey** [comment]
GitHub Actions太搞笑了🤣🤣🤣

**Comment by BFDZ** [comment]
终于稳定点了，每次更新都要把默认配置改成我自己的设定，需要改动的地方有点多

**Comment by ghost** [comment]
> @BFDZ 终于稳定点了，每次更新都要把默认配置改成我自己的设定，需要改动的地方有点多

用 Hexo 的 [theme-config](https://hexo.io/zh-cn/docs/configuration#%E8%A6%86%E7%9B%96%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE) 可以不用改 :smile:
