### ISSUE TITLE
关于 pjax 的开发

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#242]
个人能力有限，希望有相关方面的大佬提供帮助，感激不尽！

如果有大佬提交与 pjax 相关的实现代码，请 fork 在 pjax 分支进行修改，然后 pr 提交到 pjax 分支。
如果此期间主题有更新也不会受影响，更新的内容我自己合并到 pjax 分支中。

导航栏和页脚是不随页面变化的。
有些页面有封面，有些页面没有封面，如果这方面不好兼容，可以舍弃掉一部分的自由度，或者调整封面的布局位置。

**Comment by inkss** [comment]
话说能不能把导航栏和封面分离，header 从 cover 抽出来，另外，介不介意补一个带注释版本的 app.js 呀 🔥

**Comment by xaoxuu** [comment]
可以，这些改动我都提交到 pjax 分支

**Comment by inkss** [comment]
setTabs()  生效于什么阶段？什么地方？

**Comment by xaoxuu** [comment]
页面加载的时候需要设置，使点击 tab 的时候能够切换内容

**Comment by inkss** [comment]
https://github.com/inkss/volantis/blob/da40d39f06d97814f9c1e0ac3aa5ad2a349e8ce3/source/js/app.js#L66

**Comment by xaoxuu** [comment]
可以，过几天我试试

**Comment by xaoxuu** [comment]
我把 hexo-offline 卸载掉

**Comment by inkss** [comment]
这个我记得我处理了呀，不方便获取的参数 [pjaxData.ejs](https://github.com/inkss/volantis/blob/master-theme/layout/_partial/pjaxData.ejs) 主要就是为了处理这些页面特有的自定义值的 

https://github.com/xaoxuu/hexo-theme-volantis/projects/1#card-37473134

**Comment by inkss** [comment]
Volantis Doc 的 Pjax 测试地址：https://theme-volantis.github.io

**Comment by xaoxuu** [comment]
我刚更新了一下，pjax又没有了

网址后面没有那一串id是不是代表pjax没有生效？

**Comment by inkss** [comment]
ID 不清楚。我这边有呀。

感觉又是 hexo-offline 的锅

![image](https://user-images.githubusercontent.com/31947043/80919703-1848e100-8d9e-11ea-848b-994047b9902e.png)

**Comment by inkss** [comment]
我看你重新编译了些，主题我有些改了，没推上去，

**Comment by inkss** [comment]
重新部署了一版，你的 TODO 里这几个解决了：

- [X] Valine 评论共用一个 path 的设置没有生效
- [X] 导航栏以及侧边的高亮状态没有了

确认更新的标志：输入框里特效开了

**Comment by xaoxuu** [comment]
大佬辛苦了 ![](https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/valine/qq/qq-62.gif)

2.6.5 也才出没多少天，不用着急，五一好好放松放松吧，我会把发现的问题都写到todo里，有时间慢慢改。

**Comment by inkss** [comment]
哈哈，太闲了，没发出去玩儿

**Comment by inkss** [comment]
切换页面时，这个激活的菜单怎么用 js 关掉啊？

![image](https://user-images.githubusercontent.com/31947043/81267556-3f8eff00-9079-11ea-8e9e-5594c0040b5b.png)

**Comment by xaoxuu** [comment]
是这一段代码：
```js
function setHeaderMenuSelection() {
	var $headerMenu = $('body .navigation');
	// 先把已经激活的取消激活
	$headerMenu.find('li a.active').removeClass('active');
	// var $underline = $headerMenu.find('.underline');
	function setUnderline($item) {
		// if (!transition) $underline.addClass('disable-trans');
		if ($item && $item.length) {
			$item.addClass('active').siblings().removeClass('active');
		}
	}
	//set current active nav
	var $active_link = null;
	// replace '%' '/' '.'
	var idname = location.pathname.replace(/\/|%|\./g, "");
	if (idname.length == 0) {
		idname = "home";
	}
	var page = idname.match(/page\d{0,}$/g);
	if (page) {
		page = page[0];
		idname = idname.split(page)[0];
	}
	var index = idname.match(/index.html/);
	if (index) {
		index = index[0];
		idname = idname.split(index)[0];
	}
	if (idname && $headerMenu) {
		$active_link = $('#' + idname, $headerMenu);
		setUnderline($active_link);
	}
}
```
通过匹配当前页面的url与菜单按钮的链接来设置高亮，我感觉这种方法很low，可是我又想不到更好的方法设置高亮，不知道其它主题是怎么做的。

**Comment by xaoxuu** [comment]
我怎么感觉用了pjax后反而没有以前流畅了
https://theme-volantis.github.io/
https://volantis.js.org/

**Comment by inkss** [comment]
你。。。。主文档站有 cdn ，离线插件在呀  

![image](https://user-images.githubusercontent.com/31947043/81271284-7e738380-907e-11ea-9b05-0e7011739d62.png)

**Comment by Reqwey** [comment]
> 我怎么感觉用了pjax后反而没有以前流畅了
> https://theme-volantis.github.io/
> https://volantis.js.org/

大概是js.org用的是世界第一快的CloudFlare的DNS解析吧🤣

**Comment by xaoxuu** [comment]
我在本地浏览也是非常非常慢，有时候加载1分多钟页面都没切换过去。

**Comment by inkss** [comment]
那不可能是 pjax 的问题，5s 内链接没加载出来会强制走跳转的。

https://github.com/xaoxuu/hexo-theme-volantis/blob/5ad19af077b9014216c96c444ebdf73aa5879c6b/layout/_partial/scripts.ejs#L381

https://github.com/xaoxuu/hexo-theme-volantis/blob/5ad19af077b9014216c96c444ebdf73aa5879c6b/layout/_partial/scripts.ejs#L426

**Comment by xaoxuu** [comment]
我还发现快速切换页面，上个页面没加载完的资源还在后台慢慢加载。

**Comment by inkss** [comment]
整体看过去   时间还正常啊

- 首页打开速度

![image](https://user-images.githubusercontent.com/31947043/81411341-d42a5780-9174-11ea-8a15-8a4a25ac4865.png)

- 阅读第一篇文章

![image](https://user-images.githubusercontent.com/31947043/81411551-1c497a00-9175-11ea-91c3-3254f3c7a492.png)

**Comment by inkss** [comment]
那你那边，访问我的网站呢：[链接](https://inkss.cn)

切换起来？我那边也只是套了一层腾讯云的 CDN

**Comment by xaoxuu** [comment]
你的网站是挺快的

**Comment by xaoxuu** [comment]
我录了视频，你看看
https://xaoxuu.lanzous.com/icefyid

切换页面的时候把没加载完的资源请求cancel掉可以吗

**Comment by inkss** [comment]
我也不知道了，你看看我这边录得视频，我都在纠结打开得是不是同一个网站了 

https://www.jianguoyun.com/p/DSl34bUQuJK6BxiBz5YD

**Comment by xaoxuu** [comment]
过滤一下只看 media 类型，「开始使用」页面只有一个，就是背景音乐；「标签插件」页面则有很多个。对比这两个页面的媒体资源容易控制变量。
从「开始使用」切换到「标签插件」，等待页面出现后会有很多媒体资源开始加载，进入 pending 状态，这时候再切换回「开始使用」，发现「标签插件」页面的那些资源仍然在加载。这样多切换几次页面，那些已经不需要的资源仍然占据着网络带宽，就会变慢变卡，犹如“滚雪球”一般，而你的网站资源比较少，很快就加载完了，没有堆积，就不会影响当前页面的加载。

**Comment by inkss** [comment]
类似于想要这种效果？

![image](https://user-images.githubusercontent.com/31947043/81415619-430aaf00-917b-11ea-856f-3f22adaff50e.png)

**Comment by xaoxuu** [comment]
对，就是这样

**Comment by inkss** [comment]
你改吧，试试，在pjax的send事件里，加这个方法 😀

https://github.com/xaoxuu/hexo-theme-volantis/blob/5ad19af077b9014216c96c444ebdf73aa5879c6b/layout/_partial/scripts.ejs#L385

**Comment by inkss** [comment]
好像是有那么点用处，我这边效果不明显

![image](https://user-images.githubusercontent.com/31947043/81469221-78180f80-9216-11ea-98fe-3cb7380d05ef.png)

**Comment by inkss** [comment]
有个疑问，从导航栏点击和点击导航栏上的图标的处理上，会有什么不同吗？

**Comment by inkss** [comment]
我兼容了封面，算是处理完了吧，但是发现这两个地方的点击行为是不一致的，流程大概是：

进入首页，随便进入一篇文章，然后在文章页点击导航栏的这两处，回到首页的有个滚动的不同，这是目前发现的个问题了。

连接：https://inkss.cn
