### ISSUE TITLE
导航栏问题

### ISSUE THREAD

**Issue by liuchutian09** [volantis-x/hexo-theme-volantis#245]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

## Other Information 

作者大大，这个是什么情况呀，我是从1.6升级到2.6的
![image](https://user-images.githubusercontent.com/44516655/79679012-78834300-8234-11ea-8285-b7d841f97718.png)

**Comment by xaoxuu** [comment]
![截屏2020-04-19 13.00.19.png](https://i.loli.net/2020/04/19/9vUrqhTOVldAxSy.png)

**Comment by xaoxuu** [comment]
我以为上面的毛玻璃是你打的马赛克。。。

https://www.zhengyuanyuan520.com/2020/04/13/structure-of-MAN/

你的网站明显是自己修改出问题了，多个版本的样式杂糅在一起，真正与原版不同的也就一个鼠标光标了，建议重新使用原版修改。

**Comment by liuchutian09** [comment]
哈哈，谢谢作者大大，我重新下载了修改看看

**Comment by liuchutian09** [comment]
我找到原因了，是因为自己在mata文件夹下面写了一个reward.ejs，然后在主题_config.yml的meta里面写了：
reward: 
   title: "请作者喝杯咖啡吧"
，在layout里面写了footer[reward]导致的。删掉就恢复正常了

**Comment by liuchutian09** [comment]
话说在所有的markdown尾部都添加一个自定义的赞赏按钮应该怎么做才是最合适的

**Comment by xaoxuu** [comment]
使用一个独立页面作为组件放在 `article_footer` 中即可。[#通用页面部件](https://volantis.js.org/theme-settings/#%E9%80%9A%E7%94%A8%E9%A1%B5%E9%9D%A2%E9%83%A8%E4%BB%B6)
![QQ20200419-180147@2x.png](https://i.loli.net/2020/04/19/m1a2nyFZ5ldCzVY.png)
