### ISSUE TITLE
只要 md文件大小达 10K，点开文章后会显示不全，导航栏logo点击失效

### ISSUE THREAD

**Issue by wz-wong** [volantis-x/hexo-theme-volantis#251]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

## Other Information 

你好，如题，经测试，只要 md文件大小达 10K，点开文章后，tab 标签无法点击，内容显示不完整。

如下图所示，10K 文本真的不算多，如果文章内含多条链接或包含代码的话，很容易超过10K，这个可以修复吗？或者增大阀值？
-----------------------------

![image](https://user-images.githubusercontent.com/38744714/79962141-47b43f80-84ba-11ea-9ffd-3702447e4888.png)

-----------------------------
![image](https://user-images.githubusercontent.com/38744714/79962040-218e9f80-84ba-11ea-9673-8145774bd597.png)

**Comment by wzzxx-wang** [comment]
版本 2.6.3  `scheme: blog` ，应该不是字数限制，单你博客上  【写作】那一篇就过 10K 了

**Comment by xaoxuu** [comment]
https://volantis.js.org/faqs/
建议先自测一下，估计是有地方格式错误

**Comment by wzzxx-wang** [comment]
多谢，找到原因了，这里错误，能告知下正确写法吗，如果我不要它的话

![image](https://user-images.githubusercontent.com/38744714/79990575-cd001a00-84e3-11ea-8161-8e51ea083566.png)

我测试了，将它注掉，或者删掉变成 `article_footer: `都不行

**Comment by xaoxuu** [comment]
```
article_footer: []
```

**Comment by wzzxx-wang** [comment]
测试结果有点怪，`[ ]` 并没有奏效，经反复测试
- bug 1
`article_footer: [related_repos, copyright, donate]`  这三个缺一不可，只要少一个，均会导致右侧目录栏不显示...

![image](https://user-images.githubusercontent.com/38744714/79993855-c96e9200-84e7-11ea-80f4-490e522db51b.png)

- bug 2
文件过10K后，评论一直是加载状态，如下，且会出现logo点击无效，还在继续测试是哪条配置的问题

![image](https://user-images.githubusercontent.com/38744714/79994434-8b25a280-84e8-11ea-8a31-17d1d222555e.png)

**Comment by wzzxx-wang** [comment]
重新下载的 2.6.3 的包，使用的 **默认配置**
`hexo new 测试文件`   重新新建的文章，
只要文章内容为以下内容，均会导致导航栏问题

```
---
title: 字数多导致导航栏bug
date: 2020-04-22 23:09:38
tags:
---
{% note idea,  
导航栏logo点击无效，且滚轮上滑时，标签栏理应显示文章标题，实际并未显示 %}
<!-- more --> 
## 目录一			目录暂无问题
一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
## 目录二
一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
## 目录三
一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
## 目录四
一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
## 目录五
一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
```

**Comment by wzzxx-wang** [comment]
又经过一些奇奇怪怪没卵用的测试，可以肯定的是，只要文本大小超过 25kb，
**右侧目录栏会不显示**
**导航栏滚轮上滑时不会显示标题**
**若有`tab` ,则会无法切换，网址会变成tab_id** 正常网址不会变化
如下

![image](https://user-images.githubusercontent.com/38744714/80070758-1600ae80-8576-11ea-9274-206f8208a65a.png)

**Comment by xaoxuu** [comment]
![image](https://user-images.githubusercontent.com/16400144/80092809-01cca980-8596-11ea-9538-6c6463b96f9d.png)

**Comment by xaoxuu** [comment]
> 重新下载的 2.6.3 的包，使用的 **默认配置**
> `hexo new 测试文件` 重新新建的文章，
> 只要文章内容为以下内容，均会导致导航栏问题
> 
> ```
> ---
> title: 字数多导致导航栏bug
> date: 2020-04-22 23:09:38
> tags:
> ---
> {% note idea,  
> 导航栏logo点击无效，且滚轮上滑时，标签栏理应显示文章标题，实际并未显示 %}
>  
> ## 目录一			目录暂无问题
> 一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
> ## 目录二
> 一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
> ## 目录三
> 一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
> ## 目录四
> 一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
> ## 目录五
> 一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二三一二
> ```

我用你发的这段测试，没有任何问题。

**Comment by xaoxuu** [comment]
> 又经过一些奇奇怪怪没卵用的测试，可以肯定的是，只要文本大小超过 25kb，
> **右侧目录栏会不显示**
> **导航栏滚轮上滑时不会显示标题**
> **若有`tab` ,则会无法切换，网址会变成tab_id** 正常网址不会变化
> 如下
> 
> ![image](https://user-images.githubusercontent.com/38744714/80070758-1600ae80-8576-11ea-9274-206f8208a65a.png)

主题文档有页面达到 33KB，不存在你说的问题。

**Comment by wzzxx-wang** [comment]
重新安装了，nodejs，hexo `其中nodejs版本由12.16 升级到12.14`
重新安装并减少了不必要插件 `其中 hexo-all-minifier  未能成功安装 `
**问题解决**
目前推测可能 与nodejs 或 hexo-all-minifier 插件有关
插件的可能性较大，于该插件的github上有看到有人提因为压缩导致布局错误的问题

总之问题已解决，谢谢！
