### ISSUE TITLE
如何自定义配置页面音乐

### ISSUE THREAD

**Issue by Colsrch** [volantis-x/hexo-theme-volantis#254]
> @xaoxuu  您好！
配置您的主题已有几个星期，然而我一直未找到配置音乐播放器的音乐的位置，百度及查阅您的帮助文档均未找到方法，在此请教，望您告知，不胜感激！

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

**Comment by Colsrch** [comment]
可能是我不会吧，有没有哪位会的大佬告知一下

**Comment by Colsrch** [comment]
顺便再问下，这个**用户名**怎么改😂😂

**Comment by xaoxuu** [comment]
https://volantis.js.org/theme-settings/#APlayer

**Comment by Colsrch** [comment]
@xaoxuu  谢谢！在这里面我居然没看到😂😂
