### ISSUE TITLE
tab 若设置了图标，切换时只能点文字，点图标无效

### ISSUE THREAD

**Issue by wz-wong** [volantis-x/hexo-theme-volantis#257]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

**你好，如果tab页设置了图标的话，点击时，只有点击文字是有效的，点击图标无法跳转。
如果点击图标也能跳转的话，这样体验会不会好些**

![image](https://user-images.githubusercontent.com/38744714/80297741-9dd5fb00-87b8-11ea-8086-580ae7d8fcfe.png)

**Comment by xaoxuu** [comment]
那就先不要设置图标了吧，这个功能是我从NexT那里原封不动copy过来的，我也看不懂呢

**Comment by wzzxx-wang** [comment]
好的，谢谢解答

**Comment by xaoxuu** [comment]
或者去NexT那里问一下 ![](https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/valine/qq/qq-4.gif)

**Comment by wzzxx-wang** [comment]
问了，他的是可以的... 是不是你复制的不是最新的？
可查看示例    [hexo示例](http://blog.ynxiu.com/2018/hexo-theme-next-test.html)
测试发现，它应该是设置的点击 `tab标题区 ` 就跳转，因为点空白区域也会跳
但本主题是 只有点击图标不会跳，点空白会跳，
下面是渲染后的页面对比，`代码一致`
![image](https://user-images.githubusercontent.com/38744714/80327018-42b21000-886d-11ea-81bb-8c254e3ed723.png)
![image](https://user-images.githubusercontent.com/38744714/80327057-65442900-886d-11ea-9ccb-2ec6237f4acf.png)

**Comment by wzzxx-wang** [comment]
另外补充下，点击图标，调用的元素是不同的
![image](https://user-images.githubusercontent.com/38744714/80327545-0ed7ea00-886f-11ea-80a4-2ef2834b399f.png)
![image](https://user-images.githubusercontent.com/38744714/80327599-48a8f080-886f-11ea-97c0-35464f9c04f5.png)

**Comment by xaoxuu** [comment]
我找到原因了👌

**Comment by xaoxuu** [comment]
你更新一下看看

**Comment by wzzxx-wang** [comment]
测试没问题了，谢谢
