### ISSUE TITLE
在代码块中，如何屏蔽 标签语法

### ISSUE THREAD

**Issue by wz-wong** [volantis-x/hexo-theme-volantis#258]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

你好，在使用中发现，若代码块中包含标签的语法的话，会错误的认为代码块中的代码为 标签，导致显示错误，如图，
目前我的方法是 将` r"{% tabs "+str(name)+"期"+r" %}" ` 
改成  ` r"{"+r"% tabs "+str(name)+"期"+r" %}" ` 
还有更好的屏蔽标签语法的方式吗

![image](https://user-images.githubusercontent.com/38744714/80301046-22824280-87d4-11ea-9845-8faa90ae70ad.png)

**Comment by wzzxx-wang** [comment]
代码块无法屏蔽 
`{% codeblock %}`    和 `{% endtabs %}`
是可以理解的，但代码块中，不可能会使用 `tab `标签或 `tabs` 标签，在代码块判断内容时，
不应在`{% endtabs %}` 前，将 标签语法视为有效的标签语法

**Comment by wzzxx-wang** [comment]
另外还有一个问题是，若代码块中内容过长，向下滚动，会导致右侧的  ` 文章目录` 依旧按照第一个`tab`页的 位置判断，出现阅读位置同目录位置不相符的问题，如下图：

![image](https://user-images.githubusercontent.com/38744714/80301431-ab01e280-87d6-11ea-9a53-964351283762.png)

**Comment by xaoxuu** [comment]
折叠框、tabs等造成页面高度变化都会产生这个问题，目前暂时无法解决

**Comment by xaoxuu** [comment]
代码块中的语法被解析了是md解析器的锅

**Comment by wzzxx-wang** [comment]
明白了，谢谢
