### ISSUE TITLE
文章TOC目录太长会出现问题

### ISSUE THREAD

**Issue by LengSword** [volantis-x/hexo-theme-volantis#26]
文章目录太长会导致目录卡片覆盖遮住友链卡片
就是比如我在一个markdown文件里有很多二级三级标题，这样TOC卡片的长度就会很长，然后你上下移动的时候因为目录是会跟随着你当前阅读的位置移动的，就遮住了友链的那卡片了

**Comment by xaoxuu** [comment]
是的，目前没有解决办法，所以一篇文章不要弄那么多二三级标题

**Comment by LengSword** [comment]
我觉得可以跟友链卡片互换位置

**Comment by xaoxuu** [comment]
以后打算支持自定义顺序，现阶段你可以自己调一下，在`layout/_partial/side.ejs`文件中。

**Comment by LengSword** [comment]
OK,这样简单调节一下就好了,谢了,那我关issue了

**Comment by hchaojie** [comment]
目录太长不能显示滚动条么

**Comment by xaoxuu** [comment]
@hchaojie @LengSword 现在有滚动条了。
@LengSword 现在侧边栏所有控件顺序都可以自定义了，还可以自己新增纯文本和列表类侧边栏控件，详见文档。
