### ISSUE TITLE
更炫酷的代码块

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#261]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

如果文章中有一段超级长的代码(>=100行), 那么如果别人不想看肯定要一直拉滚动条到底部, 很麻烦, 为此我看了别的一些主题, 发现了一些办法

1. 折叠框型, 代码块可折叠, 参考 https://github.com/ppoffice/hexo-theme-icarus
1. 放大型, 这是我最眼馋的, 就是固定代码块的长度小一点, 然后想看代码的用户可以点击代码框使其全屏(见https://github.com/honjun/hexo-theme-sakura/tree/master/themes/Sakura) 为啥说我眼馋呢, 因为我之前不是把代码框改成了Mac窗口了吗, 然后让用户点击放大感觉会非常科幻, 跟真的Mac一样, 这个Sakura主题就采用了这种风格

**Comment by Reqwey** [comment]
不过如果想省事还是直接折叠框型也可以, 只不过看上去不像一个窗口😂

**Comment by Reqwey** [comment]
那个全屏的原理好像跟fancybox差不多, 不过我也~~看不懂~~没仔细看

**Comment by xaoxuu** [comment]
感觉没什么用
如果默认展开的，读者为什么需要把它合上？如果默认是折叠起来的，那么为什么不用折叠框？

**Comment by Reqwey** [comment]
嗯, 的确没啥用, 而且码量还很巨大
