### ISSUE TITLE
我想把作者的valine修改版本移植到非volantis主题中，在以往的valine版本中，都是吧cdn替换为此主题souruse目录下的valine.js，但这次替换出现了code：98的bug，望修复

### ISSUE THREAD

**Issue by KongerBest** [volantis-x/hexo-theme-volantis#262]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

**Comment by xaoxuu** [comment]
以前我修改的内容在新版本中都实现了，所以现在主题中使用的就是原版。

**Comment by xaoxuu** [comment]
source中的valine.js是1.4.7原版，可能原版就有此bug，建议更新。
> 主题使用的是: https://cdn.jsdelivr.net/npm/valine@1.4/dist/Valine.min.js
