### ISSUE TITLE
video标签在显示结果中没有对齐中央

### ISSUE THREAD

**Issue by chrisyy2003** [volantis-x/hexo-theme-volantis#265]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Expected behavior 
在实例中,视频时在中央的
![image](https://user-images.githubusercontent.com/63803385/80823759-c40ff680-8c0f-11ea-9d9b-e5ee0e04d0be.png)

## Actual behavior 

但是当我添加我的链接之后,他时靠左的且不是在中央

![image](https://user-images.githubusercontent.com/63803385/80823826-dd18a780-8c0f-11ea-8f4f-043f0c9c3bf0.png)
我觉得是不是与视频分辨率有关,如果有关能否不一定100%,而只需要中央对齐就好...
- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

**Comment by xaoxuu** [comment]
请附上链接和相关部分的 md 内容，不要截图。

**Comment by chrisyy2003** [comment]
http://blog.chrisyy.top/2020/03/31/%E5%85%AC%E9%92%A5%E5%8A%A0%E5%AF%86%E7%9A%84%E6%80%9D%E6%83%B3%E4%B8%8E%E7%94%B1%E6%9D%A5/

md:
我们不妨用颜色来给出一个直观的说明

{% video https://github.com/chrisyang2003/git_disk/releases/download/v1.0.1/crypto.mp4%}

但是Ellis并没有归纳出一个数学方法去实现这样的一个效果.但是他的想法的确是正确的.

**Comment by xaoxuu** [comment]
可能是我测试用的视频分辨率太高了，没发现这个问题，稍后修复一下。

**Comment by chrisyy2003** [comment]
好的😝
