### ISSUE TITLE
关于文章摘要实现形式的建议

### ISSUE THREAD

**Issue by mofiter** [volantis-x/hexo-theme-volantis#27]
目前主题提供一种在文章正文前面使用 `<!--more-->` 设置摘要的方式，但是摘要内容其实就是文章正文的前一部分，并不是一个单独的摘要，有时候不满足需求，我尝试了一下，给 post 多添加一个字段 description 来专门设置每一篇文章的摘要，这样摘要和文章正文是独立的，有时候可能会更好一点。具体的实现方式是：

- 首先在 `~/layout/_partial/post.ejs` 文件中 19，20 行添加一个对 post.description  的判断，代码如下：
```
        <%- post.excerpt || post.description || post.content %>
        <% if (post.excerpt || post.description) { %>
```
- 然后以后在每一篇文章中就可以在开头使用 description 来为其设置摘要了，比较方便，实例如下：
![](https://coding.net/u/mofiter/p/public_files/git/raw/master/material-x%E4%B8%BB%E9%A2%98.png)

作者可以考虑添加一下

**Comment by mofiter** [comment]
最后实现的效果如下：
![](https://coding.net/u/mofiter/p/public_files/git/raw/master/material-x%E4%B8%BB%E9%A2%98%E6%95%88%E6%9E%9C.png)

**Comment by xaoxuu** [comment]
已添加，感谢您的建议🙏
