### ISSUE TITLE
Note  标题文字能不可选吗

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#270]
## Issue Checklist 

- [ ] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

这些，感觉作为按钮应该是不可选中吧？更符合直觉点

![image](https://user-images.githubusercontent.com/31947043/80915646-44586800-8d86-11ea-93d3-2d3f8db6ab6c.png)

以及为什么我改 note.js  它 不 生 效 ，这是怎么引用的

**Comment by Reqwey** [comment]
xaoxuu.com 里面每一篇文章标题都是可选的，不知道为啥

**Comment by inkss** [comment]
@Linhk1606  滑稽

**Comment by xaoxuu** [comment]
如果想复制标题呢

**Comment by inkss** [comment]
手敲  手动狗头

**Comment by xaoxuu** [comment]
我感觉你要表达的是 tabs 吧

**Comment by inkss** [comment]
嗯嗯 对

**Comment by inkss** [comment]
主要是不太清楚怎么引用的  改了没生效

**Comment by xaoxuu** [comment]
改 tabs.js

**Comment by inkss** [comment]
我给这里加样式 没生效

![image](https://user-images.githubusercontent.com/31947043/80920016-b12c2c00-8d9f-11ea-8699-53cca4085c6b.png)

**Comment by Reqwey** [comment]
我觉得可以当鼠标hover时，把鼠标指针换成点击链接的那种，这样也比较符合直觉
