### ISSUE TITLE
行内代码块样式怎么修改

### ISSUE THREAD

**Issue by hqyHQY** [volantis-x/hexo-theme-volantis#271]
请问如果要标记一小段行内代码，你可以用反引号把它包起来，例如：`acquire（获取）`，这个样式如果要修改请问改哪个CSS文件？？求教

**Comment by xaoxuu** [comment]
![image](https://user-images.githubusercontent.com/16400144/80932414-df3a5c00-8df1-11ea-8a0e-22fe5b72b726.png)
