### ISSUE TITLE
标准Markdown语法的图片描述渲染

### ISSUE THREAD

**Issue by jitwxs** [volantis-x/hexo-theme-volantis#273]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

我想让图片的下方出现图片的描述，我知道使用文档中的 `images` 标签可以实现这一点：

```
{% image 链接, 宽度（可选）, 描述（可选） %}
```

但是我有大量的基于标准 markdown 语法的文章，在该语法下，图片的描述无法被渲染。

```
![描述](image 链接)
```

在查阅主题源码后，并没有找到可供修改的地方。

**Comment by inkss** [comment]
改渲染我不会，但是妥协下换个思路，给 fancybox 追加图片描述信息的显示还是可以做到的：

```js
let LAZY_LOAD_IMAGE = "<%- config.lazyload %>";
$(".article-entry").find("img").each(function () {
  var element = document.createElement("a");
  $(element).attr("data-fancybox", "gallery");
  if (LAZY_LOAD_IMAGE) {
    $(element).attr("href", $(this).attr("data-original"));
  }

  if ($(this).attr('alt')) {
    $(element).attr('data-caption', $(this).attr('alt'));
  }
  if ($(this).next().text()) {
    $(element).attr('data-caption', $(this).next().text());
  }

  $(this).wrap(element);
})
```

**Comment by xaoxuu** [comment]
@jitwxs 下个版本会尝试实现，不过 `![描述](链接)` 这样写的图片是不能够放大预览的，原因如下：

@inkss 主题没有默认全部使用 fancybox 的原因是： 部分图片如行内图片、表情图片等不需要点击进行全屏预览，所以不能把 `![描述](链接)` 解析成被 fancybox 包裹的图片。

**Comment by xaoxuu** [comment]
或者为不需要放大的行内图片单独写一个标签，标准的 md 语法的图片就解析成 fancybox

**Comment by inkss** [comment]
行内图片、表情图片会出现到文章里吗？没太遇到过这种情况。

不过既然都是选择器了，也可以用 .not('xx') 过滤啊。

**Comment by Reqwey** [comment]
很多主题（比如我用过了NexT）都是默认文章图片为 `fancybox` 的
但是我现在加了个外链跳转的插件，似乎 `fancybox` 功能失效了
https://blog.lhkstudio.me/2020/03/08/noi-online-pj/#T1 这里把折叠框打开可以看到我弄了一个fancybox图片，但是加载会失败

**Comment by inkss** [comment]
我刚刚改了点，看看效果：[查看链接](https://inkss.cn/article/linux/b2b02edd.html)。

**Comment by inkss** [comment]
就是玩俄罗斯套娃，哈哈哈，不过是利用 fancybox 的思路改的：[代码](https://github.com/inkss/volantis/blob/master-theme/layout/_third-party/fancybox.ejs)

**Comment by xaoxuu** [comment]
👍🏼效果不错，那就现在改吧，master分支

**Comment by inkss** [comment]
我这是在 fancybox 下改的呀，开了这个才生效的

**Comment by xaoxuu** [comment]
我现在在改master，你要提交一下吗？还是我自己copy？

**Comment by inkss** [comment]
你改吧，@xaoxuu 改了下代码，你重新看下吧，刚才忽略了 hexo 标签的图片已经有描述信息这个了

**Comment by inkss** [comment]
好了，应该改完了

**Comment by xaoxuu** [comment]
例如这种场景：
![image.png](https://i.loli.net/2020/05/06/kcQEZ8RC3jPAWNv.png)

![image.png](https://i.loli.net/2020/05/06/QWSmgHqFx2ztfar.png)

**Comment by inkss** [comment]
用 `not('.thumbnail')` 呢？

**Comment by xaoxuu** [comment]
用 `.inline` 来区分吧

![image](https://user-images.githubusercontent.com/16400144/81192415-c8138e00-8fec-11ea-9417-5ad4b1c2cf16.png)

是这样吧？

**Comment by inkss** [comment]
嗯，不过这样子改的，不开启 fancybox 不就不生效了啊

**Comment by xaoxuu** [comment]
那就改成必须加载 fancybox
