### ISSUE TITLE
折叠框下代码变为单行

### ISSUE THREAD

**Issue by jitwxs** [volantis-x/hexo-theme-volantis#274]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Expected behavior 

使用 `folding` 正常折叠代码

## Actual behavior 

- Links to demo site with this issue: N/A
- Links to repository or source code of the blog: N/A

将代码块放入  `folding`  后，变成了单行代码

## Steps to reproduce the behavior 

源码如下：

![20200505193023.png](https://i.loli.net/2020/05/05/SM15gA8bxjlKdJD.png)

渲染后：

![20200505193110.png](https://i.loli.net/2020/05/05/zIEfwdFTR6jcyN4.png)

### Node.js and NPM Information

```
v12.16.3
```

### Package dependencies Information

```

```

### Hexo Configuration

```yml
Latest
```

### Volantis Configuration

```yml
2.6.5
```

**Comment by xaoxuu** [comment]
看一下您的 package.json

**Comment by jitwxs** [comment]
我有更改过默认的渲染引擎，和这个有关联吗。

`hexo-renderer-marked` -> `hexo-renderer-markdown-it`

```JSON
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-abbrlink": "^2.0.5",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-related-popular-posts": "^4.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it": "^4.1.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-wordcount": "^6.0.1"
  }
}
```

**Comment by xaoxuu** [comment]
这就是渲染器的工作

**Comment by xaoxuu** [comment]
你把出问题的那段代码发一下

**Comment by xaoxuu** [comment]
试一下 marked 渲染器
```
"hexo-renderer-marked": "^2.0.0",
```

**Comment by xaoxuu** [comment]
你是不是用的 hljs 高亮？

**Comment by xaoxuu** [comment]
我用 hljs 复现出了这个问题，但css部分一样，应该是 hljs 跟 details 之间有什么冲突， hexo 自带的高亮就没问题。

**Comment by jitwxs** [comment]
是的，当我关闭掉 hljs 后，就可以正常渲染了，我再想想兼容的办法。

**Comment by ghost** [comment]
@xaoxuu 我也复现了这种情况。
