### ISSUE TITLE
请问如何设置像是官方文档页面的全屏cover，刚接触hexo不是很懂。

### ISSUE THREAD

**Issue by kumi123** [volantis-x/hexo-theme-volantis#275]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [ ] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [ ] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

### Node.js and NPM Information

```

```

### Package dependencies Information

```

```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

**Comment by xaoxuu** [comment]
themes/volantis/_config.yml:
```yaml themes/volantis/_config.yml
cover:
  scheme: docs # docs, blog
```

- docs: 文档方案，全屏封面
- blog: 博客方案，半屏封面

https://github.com/xaoxuu/hexo-theme-volantis/blob/e5d76ba99f672a3b21a87794749f706d47a9572f/_config.yml#L98
