### ISSUE TITLE
目录栏定位按钮的问题

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#28]
经发现，右侧的文章目录右上角的定位按钮在火狐浏览器下点击后，会直接打开新标签页，且在地址栏中显示的内容为``“javascript:void(0)”``。
具体的解决办法是将toc.ejs文件中的``target="_blank"``去掉即可解决该问题。
可能是xaoxuu在开发widget部分的时候粘贴代码时导致的一个失误。
![Uploading 2.gif…]()

**Comment by xaoxuu** [comment]
已更新，谢谢提醒。👌
