### ISSUE TITLE
文章图片取消放大后，图片被隐藏

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#282]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

***

## Actual behavior 

- Links to demo site with this issue: [issue post](https://chenai.life/2020/05/12/blog/java-concurrent-programming-chapter02/)
- Links to repository or source code of the blog: N/A

## Steps to reproduce the behavior 
1. N/A
2. N/A
3. N/A

### Node.js and NPM Information

```
v9.11.1
5.6.0
```

### Package dependencies Information

```
hexo-site@0.0.0 F:\dir
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-qrcode@1.0.2
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

### Hexo Configuration

```yml

```

### Volantis Configuration

```yml

```

**Comment by ghost** [comment]
文档评论里有遇到和我同样问题的。
![](https://ftp.bmp.ovh/imgs/2020/05/b53025ef6ab54e89.png)

**Comment by xaoxuu** [comment]
你的站点的fancybox与主题默认提供的不同，建议先安照帮助步骤进行自检。https://volantis.js.org/faqs/

**Comment by ghost** [comment]
但是我并没有使用fancybox来展示图片，只是普通的markdown语法(`![](images)`)，此外我检查了网站请求的fancybox插件，和最新版本默认提供的是一致的。
![hexo1](https://user-images.githubusercontent.com/59497690/81363580-43bd2a00-9116-11ea-815f-0a243f730caa.png)
![hexo2](https://user-images.githubusercontent.com/59497690/81363584-461f8400-9116-11ea-93c1-493c143756a3.png)

**Comment by xaoxuu** [comment]
有确凿证据表明是不同的：
![](https://i.loli.net/2020/05/08/aFLxXTVwG2RbmqZ.jpg)

演示：https://volantis.js.org/test/images/
源码：https://github.com/xaoxuu/volantis-docs/blob/master/source/_posts/test/images.md

源码截图：
![image.png](https://i.loli.net/2020/05/08/rlYUVE59iMcdkbo.png)

请问您自检进行到第二步了吗？
![image](https://user-images.githubusercontent.com/16400144/81376520-4760a900-9136-11ea-8b32-305de0200bce.png)

**Comment by xaoxuu** [comment]
抱歉，我这边通过关掉图片懒加载插件后复现出来了。

**Comment by xaoxuu** [comment]
您更新一下主题看看好了没

**Comment by ericclose** [comment]
> 您更新一下主题看看好了没

![2020-05-08_17-53](https://user-images.githubusercontent.com/34526560/81394961-6458a480-9155-11ea-9bdb-e422f24fef81.png)

:sweat_smile:  然后我看你的[图片测试页](https://volantis.js.org/test/images/)就出现了**点击图片放大**，显示成懒加载的图了（

**Comment by ericclose** [comment]
> 您更新一下主题看看好了没

![2020-05-08_17-53](https://user-images.githubusercontent.com/34526560/81394961-6458a480-9155-11ea-9bdb-e422f24fef81.png)

@xaoxuu  :sweat_smile:  然后我看你的[图片测试页](https://volantis.js.org/test/images/)就出现了**点击图片放大**，显示成懒加载的图了（

**Comment by xaoxuu** [comment]
有缓存刷新一下

**Comment by ericclose** [comment]
> 有缓存刷新一下

@xaoxuu 试了，有时会，有时又不会。

**Comment by xaoxuu** [comment]
那我再改个保险的方案

**Comment by ghost** [comment]
感谢作者，刚更新了下，问题已经解决。
