### ISSUE TITLE
能否提供更改网站背景图

### ISSUE THREAD

**Issue by MrLiuX** [volantis-x/hexo-theme-volantis#283]
If you delete this template, we may close your issue without conducting an investigation.
如果您删除此模版，我们可能会在不进行调查的情况下关闭您的 Issue。

Please check if your Issue fulfills the following requirements. This will guide you to resolve the issue quickly.
请务必确认您在提交此 Issue 前已经查看并完成了下列检查单中的所有事项。这会指导您快速地解决问题。

## Issue Checklist 

- [x] I am using [the latest](https://github.com/xaoxuu/hexo-theme-volantis/releases/latest) version of Volantis.
- [x] I have reviewed [guidelines for Volantis](https://volantis.js.org), which does not help me.
- [x] I have reviewed the latest Roadmap on GitHub and searched for current issues, which does not help me.

希望能在配置文件中提供更换网站背景图。🙏

**Comment by Reqwey** [comment]
有这个选项啊，就是backstretch.还是幻灯片切换的呢

**Comment by MrLiuX** [comment]
我的意思是，除了fixed之外，能否提供在cover模式下，提供更换背景（cover模式下是白色），比如[这种简单的背景图](https://www.toptal.com/designers/subtlepatterns/let-there-be-sun-pattern/)。就是不想fixed，但又想在网站主体页面更换背景的情况😋

**Comment by xaoxuu** [comment]
![Uploading image.png…]()
能改的

**Comment by MrLiuX** [comment]
> 能改的

麻烦请问怎么改呀，您的图片加载不出来😄
