### ISSUE TITLE
pjax 开启lazyload要自己刷新一遍图片才会出来

### ISSUE THREAD

**Issue by hihihiwuhu** [volantis-x/hexo-theme-volantis#292]
## 自检报告

分类：使用遇到问题（主题文件 ejs、js、css、第三方插件等有修改）

### 第一步 

查看未经修改的主题是否也存在此问题：

- A. 未经修改的主题也存在此问题，请使用 issue 模板「帮助流程A. 使用遇到问题（主题未经修改）」。
- B. 未经修改的主题不存在此问题，在 git 历史中新建分支还原修改，直至找到出问题的地方。

- [x] 我已完成上述操作，结果是：____

### 第二步

这部分内容是否与第三方插件有关？

- A. 是主题文档中提到过的第三方插件（意味着有主动兼容），请在问题描述中描述清楚。
- B. 是主题文档中没有提到过的第三方插件，可能存在没有兼容的情况，请使用 issue 模板「提交一个建议」。

## 问题描述
我用的是volantis的pjax版本，开启了lazyload插件后，图片会一直是处于加载状态，要自己手动刷新一次才会显示，不知道是不是要搞个pjax回调，不过我不会，没弄成功。
lazyload是npm直接装的，然后在hexo的配置文件开启的。

### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by inkss** [comment]
~~重新安装 hexo-lazyload-image~~，<kbd>v1.9.0</kbd> ，添加配置 isSPA: true

**Comment by inkss** [comment]
https://github.com/Troy-Yang/hexo-lazyload-image/issues/21

**Comment by xaoxuu** [comment]
pjax分支还在开发中呢

**Comment by hihihiwuhu** [comment]
> ~重新安装 hexo-lazyload-image~，v1.9.0 ，添加配置 isSPA: true

好像还是不行，要重新安装吗？

**Comment by hihihiwuhu** [comment]
好了，重新安装了一遍就好了。
