### ISSUE TITLE
图片背景问题

### ISSUE THREAD

**Issue by rChunYoung** [volantis-x/hexo-theme-volantis#293]
- [ ] 我要说的内容与帮助或者BUG、建议都无关。（如果有关，请使用相关模板）
请问怎样修改背景图片和头像？谢谢

**Comment by ghost** [comment]
兄弟你对着theme.config修改就行了
官方文档：
- [blogger头像](https://volantis.js.org/v2/theme-settings/#%E5%8D%9A%E4%B8%BB%E4%BF%A1%E6%81%AF%E9%83%A8%E4%BB%B6)
- [幻灯片背景](https://volantis.js.org/v2/theme-settings/#%E5%B9%BB%E7%81%AF%E7%89%87%E8%83%8C%E6%99%AF)

**Comment by rChunYoung** [comment]
> 兄弟你对着theme.config修改就行了
> 官方文档：
> 
> * [blogger头像](https://volantis.js.org/v2/theme-settings/#%E5%8D%9A%E4%B8%BB%E4%BF%A1%E6%81%AF%E9%83%A8%E4%BB%B6)
> * [幻灯片背景](https://volantis.js.org/v2/theme-settings/#%E5%B9%BB%E7%81%AF%E7%89%87%E8%83%8C%E6%99%AF)
好的感谢
