### ISSUE TITLE
当 theme.config.cover.sheme 为 docs 时 封面的 scroll-down 按钮对齐问题

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#294]
## BUG描述

如题

## 问题复现

![image](https://user-images.githubusercontent.com/62688818/81491393-10c48480-9243-11ea-8ba2-5d0fce531a31.png)
![image](https://user-images.githubusercontent.com/62688818/81491395-2174fa80-9243-11ea-9882-8365bc85f543.png)

问题出现在主题样式上，官方文档也有一样的问题。
我是强迫症，感觉按钮往右挪了一点很难受 =>   **左间距比右间距多了21px**

**Comment by ghost** [comment]
抱歉我看不出来问题在哪，我看父元素已经设置了text-align: center; 了。也没有margin padding，非常奇怪

**Comment by ghost** [comment]
我只知道 position：relative 是正常的，但是主题是 absolute

**Comment by xaoxuu** [comment]
好的，我现在修复一下

**Comment by xaoxuu** [comment]
现在好了吧

**Comment by ghost** [comment]
可以 😄

**Comment by ghost** [comment]
你好勤快呀

**Comment by ghost** [comment]
现在顺眼多了，这么明显的bug居然没人发现 ＾▽＾

**Comment by Reqwey** [comment]
这。。。
