### ISSUE TITLE
Mathjax Overflow 问题

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#296]
![image](https://user-images.githubusercontent.com/62688818/81521987-c0f6c380-92fd-11ea-86d2-1c531be3ed2b.png)

如图所示，需要加入 overflow: scroll 属性

**Comment by xaoxuu** [comment]
公式源码发一下

**Comment by MHuiG** [comment]
为啥我这边看着没问题
![image](https://user-images.githubusercontent.com/38281581/81523116-6aca6480-937f-11ea-9fd6-2a17a7779633.png)
源码
```
\int^{t_{0}+T}_{t_{0}}f(x)cos(m\omega x)dx=\int^{t_{0}+T}_{t_{0}}\frac{a_{0}}{2}cos(m\omega x)dx+\int^{t_{0}+T}_{t_{0}}\sum^{+\infty}_{n=1} a_{n}cos(n\omega x)cos(m\omega x)dx+\int^{t_{0}+T}_{t_{0}}\sum^{+\infty}_{n=1}b_{n}sin(n\omega x)cos(m\omega x)dx

```

**Comment by xaoxuu** [comment]
mathjax 2 升级到 3 的时候类名变了，原来的css样式失效了

**Comment by xaoxuu** [comment]
我怀疑是 mathjax 的问题，这么简单一个公式需要嵌套这么多层吗，貌似是无穷层。。。
![image.png](https://i.loli.net/2020/05/11/KyAIGq51xfs4rmM.png)

**Comment by xaoxuu** [comment]
我更新了一版，滚动应该没问题了

**Comment by ghost** [comment]
> 为啥我这边看着没问题
> ![image](https://user-images.githubusercontent.com/38281581/81523116-6aca6480-937f-11ea-9fd6-2a17a7779633.png)
> 源码
> 
> ```
> \int^{t_{0}+T}_{t_{0}}f(x)cos(m\omega x)dx=\int^{t_{0}+T}_{t_{0}}\frac{a_{0}}{2}cos(m\omega x)dx+\int^{t_{0}+T}_{t_{0}}\sum^{+\infty}_{n=1} a_{n}cos(n\omega x)cos(m\omega x)dx+\int^{t_{0}+T}_{t_{0}}\sum^{+\infty}_{n=1}b_{n}sin(n\omega x)cos(m\omega x)dx
> ```

那是因为我自己改了css样式

**Comment by ghost** [comment]
> 我更新了一版，滚动应该没问题了

好的，问题关闭了，BTW，你真勤快呀，好评👌

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/62688818/81529930-b98ee480-9314-11ea-9a0c-5e766db86704.png)

问题解决了，可是会报错耶

还有，你把mathjax的选项从主题config移除了，万一用户不需要mathjax呢？ 😃
