### ISSUE TITLE
文章目录的相关建议

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#297]
### 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

### 一、balabala

文章目录栏支持只激活展示当前所在大类目录分级，像这样：

![image](https://user-images.githubusercontent.com/31947043/81528233-cfd98680-938e-11ea-97ac-c8c615bb3441.png)

因为，如果目录结果很长很长的时候，生成的 TOC 也是很长很长的，像是这个链接：[查看链接](https://inkss.cn/article/linux/c6df61d3.html)

### 二、balabala *2

TOC 滚动条可以跟随着滚动吗，当前页面高度所在的目录结构始终显示出来？

**Comment by xaoxuu** [comment]
很棒，但是这些我都不会做。。。
容器标签会让目录偏移，估计加上这些功能后偏移得更厉害
也许哪一天有时间再学习学习NexT源码

**Comment by inkss** [comment]
加油，你是最肝的!  ![](https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/emoji/valine/weibo/weibo-1.png)
