### ISSUE TITLE
Pjax分支 被我发现的BUG

### ISSUE THREAD

**Issue by hihihiwuhu** [volantis-x/hexo-theme-volantis#298]
## 第一个
pjax分支的文章目录，浏览文章的时候，文章目录没有跟随浏览进度高亮标题。
可能我说的看不懂，我放一张截图。
![文章目录](https://i.loli.net/2020/05/12/vjS23CNMgWilQxG.png)
而且点击目录的时候，没有过渡效果，直接切换到那个标题的画面了。
可能我提的BUG是多余的，嘿嘿。
## 第二个
导航栏切换页面后，他的下划线不会自动跟随。
这个情况只会出现在切换.html文件，如果那个页面是一个文件夹，就不会出现这样的请情况。
![导航栏](https://i.loli.net/2020/05/12/3hHbTZPoS6txmsl.png)
## 第三个
如果是docs或者blog样式的主页，切换文章的时候会保留主页的样式，导致一个没有cover封面的文章出现一个封面。

**Comment by hihihiwuhu** [comment]
好像我这就是多余的，前面有个人提过这个了。

**Comment by xaoxuu** [comment]
pjax分支正在开发中，不建议使用。

**Comment by hihihiwuhu** [comment]
> pjax分支正在开发中，不建议使用。

没事，不是大bug，提出来修一下就好(我菜不会修)

**Comment by xaoxuu** [comment]
现在的完成度连内测都不到，而且后续更新还会有很多改动，建议至少等公测发布后再使用。目前2.x版本结合hexo-offline速度也是很快的。

**Comment by hihihiwuhu** [comment]
> 现在的完成度连内测都不到，而且后续更新还会有很多改动，建议至少等公测发布后再使用。目前2.x版本结合hexo-offline速度也是很快的。

主要是图新鲜，我站流量不大，找找BUG反馈，问题不大。

**Comment by inkss** [comment]
我没有 我不是  我没复现    😏

![image](https://user-images.githubusercontent.com/31947043/81777745-11e80100-9524-11ea-8ca7-e1e8668e57e6.png)

**Comment by inkss** [comment]
今天下午闲着没事，看看能不能用js代码解决封面的问题

**Comment by inkss** [comment]
我尝试处理了下封面，大致兼容了下，链接：[查看链接](https://inkss.cn)

只研究了下半封面的，全屏的应该也不是问题，关于封面的出现条件：

`$('#page-cover').text()` ，只要这个值不等于 `none` 就显示封面。

@xaoxuu @confessioncn

**Comment by xaoxuu** [comment]
厉害 👍🏼

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/82137355-c4cc9d80-9849-11ea-8e19-a7a3f979980d.png)
instant.page预加载失效了。
instant.page预加载到一半，请求突然终止，换作pjax加载。。有些卡顿。

**Comment by inkss** [comment]
@MHuiG  加了 window.stop()

https://github.com/xaoxuu/hexo-theme-volantis/issues/242#issuecomment-625840252

https://github.com/xaoxuu/hexo-theme-volantis/blob/c33d75cb554bcd05056e16df2a233b9384c58de8/layout/_partial/scripts.ejs#L399

**Comment by MHuiG** [comment]
> @MHuiG 加了 window.stop()
> 
> [#242 (comment)](https://github.com/xaoxuu/hexo-theme-volantis/issues/242#issuecomment-625840252)
> 
> https://github.com/xaoxuu/hexo-theme-volantis/blob/c33d75cb554bcd05056e16df2a233b9384c58de8/layout/_partial/scripts.ejs#L399

我先加个延时看看

**Comment by MHuiG** [comment]
@inkss 延时1.5-1.8秒之后不卡顿了，感谢！

**Comment by inkss** [comment]
@MHuiG 发现你那个，普遍 1s 加了，感觉东西也不多呀 

![image](https://user-images.githubusercontent.com/31947043/82138197-2e03df00-9851-11ea-9baa-4aba0b64bad2.png)

**Comment by MHuiG** [comment]
可能是CDN的问题

**Comment by inkss** [comment]
快换个 CDN ,hhhh ，我这里基本是你的一半耗时

![image](https://user-images.githubusercontent.com/31947043/82138260-bedaba80-9851-11ea-9f90-e95631f5e0f3.png)

**Comment by MHuiG** [comment]
> 
> 
> [#242 (comment)](https://github.com/xaoxuu/hexo-theme-volantis/issues/242#issuecomment-625840252)
> 
> https://github.com/xaoxuu/hexo-theme-volantis/blob/c33d75cb554bcd05056e16df2a233b9384c58de8/layout/_partial/scripts.ejs#L399

@xaoxuu 这里需要延时2秒

**Comment by inkss** [comment]
不如改成延迟5s
