### ISSUE TITLE
怎么修改valine自定义的表情

### ISSUE THREAD

**Issue by zyoushuo** [volantis-x/hexo-theme-volantis#299]
## 自检报告

分类：使用遇到问题（主题文件 ejs、js、css、第三方插件等有修改）

### 第一步 

查看未经修改的主题是否也存在此问题：

- A. 未经修改的主题也存在此问题，请使用 issue 模板「帮助流程A. 使用遇到问题（主题未经修改）」。
- B. 未经修改的主题不存在此问题，在 git 历史中新建分支还原修改，直至找到出问题的地方。

- [ ] 我已完成上述操作，结果是：____

### 第二步

这部分内容是否与第三方插件有关？

- A. 是主题文档中提到过的第三方插件（意味着有主动兼容），请在问题描述中描述清楚。
- B. 是主题文档中没有提到过的第三方插件，可能存在没有兼容的情况，请使用 issue 模板「提交一个建议」。

## 问题描述
我在更新最新的valine的js文件，但是显示的表情包还是原主题自带的，请问怎么修改自定义表情

### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by xaoxuu** [comment]
修改方法：https://valine.js.org/emoji.html
相关代码：`layout/_partial/scripts.ejs`

**Comment by zyoushuo** [comment]
> 修改方法：[https](https://valine.js.org/emoji.html)
> : //valine.js.org/emoji.html 相关代码：`layout/_partial/scripts.ejs`

感谢作者大大，已找到！
