### ISSUE TITLE
Mathjax

### ISSUE THREAD

**Issue by antct** [volantis-x/hexo-theme-volantis#3]
之前有发过，最近发现可能还是有一些问题。不知道有没有在https测试过，可能因为引用的js是外链的原因，能否考虑把这部分js移到本地。

**Comment by xaoxuu** [comment]
@96486d9b 引用的外链是https的。由于我目前没有实际应用，所以我也不清楚你遇到的问题，你可以看看这位博主的：https://www.micdz.cn/article/basic-math/

另外，我修复了目录有时无法定位的BUG，顺便优化了上一篇下一篇的显示效果，建议您更新一下主题。
