### ISSUE TITLE
建议增加rss嵌入展示

### ISSUE THREAD

**Issue by movny** [volantis-x/hexo-theme-volantis#300]
### 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [ ] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述
> **对于静态博客来说可能有很大难度，我觉得可以不设置缓存，每次打开重新获取一遍**
### 展示1
<center>
    <img src="https://user-images.githubusercontent.com/58254971/81890398-81b7c380-95d8-11ea-84c9-28b73c26e645.jpg">
</center>

----------

### 展示2
<center>
    <img src="https://user-images.githubusercontent.com/58254971/81890531-c3e10500-95d8-11ea-8e25-27572495b752.jpg">
</center>

----------

### wp设置
<center>
    <img src="https://user-images.githubusercontent.com/58254971/81890429-8bd9c200-95d8-11ea-80ef-884e26ab9906.jpg">
</center>

----------

### typecho设置
<center>
    <img src="https://user-images.githubusercontent.com/58254971/81890437-8f6d4900-95d8-11ea-9a3e-13960c39377e.jpg">
</center>

**Comment by xaoxuu** [comment]
抱歉，这个我做不了
