### ISSUE TITLE
建议增加面包屑 breadcrumb 导航功能

### ISSUE THREAD

**Issue by imcoddy** [volantis-x/hexo-theme-volantis#304]
### 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

建议增加面包屑 breadcrumb 导航功能，方便用户跳转，也有利于 SEO。

类似的功能插件在此：https://www.npmjs.com/package/hexo-breadcrumb

因为需要修改源代码以及调整 CSS，如果主题能够提供会更方便，希望作者考虑一下如何实现成为一个 widget，谢谢。

**Comment by xaoxuu** [comment]
好的，不过要放到3.0以后了，近期不再增加新功能了。

**Comment by imcoddy** [comment]
多谢。话说 3.0 大概什么时候会出来呢？

**Comment by xaoxuu** [comment]
还需要大概3～9个月

**Comment by imcoddy** [comment]
了解了，这样的话，我先自己试试能否弄成功吧

**Comment by Reqwey** [comment]
> 还需要大概3～9个月

这么慢！难道是因为 @xaoxuu 要上班了？

**Comment by xaoxuu** [comment]
@Linhk1606 目前完成度还很低，有很多BUG，与pjax相关的功能我还不会。

**Comment by xaoxuu** [comment]
关于 3.0 开发进度可以关注这里： https://github.com/xaoxuu/hexo-theme-volantis/projects/1

**Comment by Reqwey** [comment]
不知道面包屑导航准备放哪里呢？

**Comment by MHuiG** [comment]
在结构化数据中加入了面包屑导航 5d2d945ff3c2d598b4ad08cdb8f08a17f9914d70

SE大概是这个效果

![image](https://user-images.githubusercontent.com/38281581/129302381-809e153b-9c9a-4192-ae60-5ad2d39edb1e.png)

**Comment by MHuiG** [comment]
https://github.com/msudgh/hexo-breadcrumb/blob/master/index.js

面包屑 breadcrumb 导航 似乎与 _meta/category 和 tags 功能有些重复

<blockquote><img src="https://opengraph.githubassets.com/ca08d2c49cb77b6da246bc401c272da2bcba200ae4920c5cf055089214cdec12/msudgh/hexo-breadcrumb" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/msudgh/hexo-breadcrumb">hexo-breadcrumb/index.js at master · msudgh/hexo-breadcrumb</a></strong></div><div>An useful tool for generate breadcrumb navigation with microdata markup - hexo-breadcrumb/index.js at master · msudgh/hexo-breadcrumb</div></blockquote>

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/133869388-3297e3b7-c770-4501-b9c7-d58bfe648186.png)
