### ISSUE TITLE
Valine 无法加载 bug 以及 mathjax 错误

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#305]
![image](https://user-images.githubusercontent.com/62688818/82020081-4e5b5000-963d-11ea-96aa-f8b582f9d39b.png)
![image](https://user-images.githubusercontent.com/62688818/82020105-5c10d580-963d-11ea-868a-bcf4a22a6af4.png)
![image](https://user-images.githubusercontent.com/62688818/82020152-73e85980-963d-11ea-87da-f59d69eb16c1.png)

如题，两个错误都在我的网页出现了，官方文档也有同样的问题/(ㄒoㄒ)/~~

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/62688818/82020309-b3af4100-963d-11ea-84a1-d82fae33e586.png)

**Comment by xaoxuu** [comment]
昨天晚上还有的，今天就看不了评论了，确实有问题，但不一定就是我代码的bug啊。
由于valine官网的还正常，所以可能是leancloud那边的问题，或者我用到的valine的部分功能依赖的服务有问题。

**Comment by inkss** [comment]
leancloud的泛域名证书今日到期，其实应该是因为时差的原因，国际版嘛，如果在国外，这个点还没过期，等吧

![image](https://user-images.githubusercontent.com/31947043/82024971-35957d80-96c3-11ea-8d9a-9d326da92a6e.png)

**Comment by xaoxuu** [comment]
你更新一下看看 6bc052d67f3847397d4af6a05556fdc69f948446
