### ISSUE TITLE
文章列表中不显示作者头像

### ISSUE THREAD

**Issue by penndu** [volantis-x/hexo-theme-volantis#308]
### 复现地址：
https://dusays.com/
### 截图：
![1.jpg](https://7bu.top/2020/05/16/23efee4ab4f40.jpg)

补充：
另外图片输入[]内会被显示，如何隐藏？

**Comment by xaoxuu** [comment]
这明显不是bug啊，如果没改ejs文件的话请走「帮助流程A」
