### ISSUE TITLE
文章列表中不显示作者头像

### ISSUE THREAD

**Issue by penndu** [volantis-x/hexo-theme-volantis#311]
### 复现地址：
https://dusays.com/
### 截图：
![1.jpg](https://7bu.top/2020/05/16/23efee4ab4f40.jpg)

**Comment by xaoxuu** [comment]
大佬，您就只是换了个标签？模板内容呢？？？

**Comment by xaoxuu** [comment]
![image.png](https://i.loli.net/2020/05/16/A43nXiQgSoCK8Ef.png)

**Comment by penndu** [comment]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步

下载[文档源码](https://github.com/xaoxuu/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：__执行成功，但问题未解决__

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述

文章标题下面的作者头像不显示，通过浏览器排查是空置。

## 环境信息

### 浏览器、操作系统

firefox浏览器；
win10家庭版

### 站点配置文件

只是改了站点标题

### 主题配置文件

未作任何修改

**Comment by xaoxuu** [comment]
只要链接正确，头像是正常显示的啊，你那一定是头像链接有问题
![image.png](https://i.loli.net/2020/05/16/EIbRCNmfUacJMYV.png)

**Comment by penndu** [comment]
我用的是模板自带头像，应该就是你的，还没来得及改！
![](https://7bu.top/2020/05/16/a23eda0118b42.jpg)

**Comment by xaoxuu** [comment]
"文章列表中不显示作者头像"的问题，你确定头像链接是正确的吗？

**Comment by penndu** [comment]
可以确定头像能够正常访问，但就是不显示。
![](https://7bu.top/2020/05/16/9a510df601800.jpg)

**Comment by penndu** [comment]
站点根目录下的_config.yml文件也设置了。
![](https://7bu.top/2020/05/16/e0419fa79b9d2.jpg)

**Comment by xaoxuu** [comment]
你再看看我截的图，跟你截的图是一个地方么

**Comment by penndu** [comment]
我刚想说，这块我也改了。
![](https://7bu.top/2020/05/16/654eb74041edb.jpg)

**Comment by xaoxuu** [comment]
![image.png](https://i.loli.net/2020/05/16/StaVoCn2uyPlr53.png)
这里没问题

**Comment by xaoxuu** [comment]
![image.png](https://i.loli.net/2020/05/16/kpAQDNSxRwVLhZe.png)

**Comment by penndu** [comment]
我这边填上地址了，头像没有显示，但是显示了头像框。

**Comment by xaoxuu** [comment]
既然排查不出来问题，那你试一下第三步：
![image](https://user-images.githubusercontent.com/16400144/82113238-1a8c4180-9787-11ea-9c81-41eafda1bc7e.png)

**Comment by penndu** [comment]
我已经将主题升级到最新版，可能是系统环境的问题，我重装一下系统吧！

**Comment by xaoxuu** [comment]
我发现你的关于页面是正常的：
![image](https://user-images.githubusercontent.com/16400144/82113348-fbda7a80-9787-11ea-84d5-ad4612974bff.png)

**Comment by penndu** [comment]
这应该说明我设置没有问题，可文章内就是显示不出，估计是我环境问题。

**Comment by penndu** [comment]
问题已经解决，我在文章的front-matter区删除作者后，恢复正常！

**Comment by xaoxuu** [comment]
front-matter里面的author优先级高于config，用于多个作者在一个网站中各自发文章的场景。
