### ISSUE TITLE
请问如何调换页面中l_main和l_side的左右顺序？

### ISSUE THREAD

**Issue by wztlink1013** [volantis-x/hexo-theme-volantis#316]
## 自检报告

- [x] 我要说的内容与帮助或者BUG、建议都无关。（如果有关，请使用相关模板）

## 问题描述

想变换页面中l_main和l_side的左右顺序
![](https://cdn.jsdelivr.net/gh/wztlink1013/figure/blogarticle56/Snipaste_2020-05-20_11-41-50.png)

**Comment by xaoxuu** [comment]
那你要改css文件

**Comment by wztlink1013** [comment]
@xaoxuu 相关CSS文件没大找到

**Comment by xaoxuu** [comment]
![image](https://user-images.githubusercontent.com/16400144/82404100-f5534800-9a92-11ea-844b-c93617430c15.png)
![image](https://user-images.githubusercontent.com/16400144/82404115-04d29100-9a93-11ea-8a1a-05d8ee8f6b44.png)
大概就是这几个位置

**Comment by xaoxuu** [comment]
![image](https://user-images.githubusercontent.com/16400144/82404313-8fb38b80-9a93-11ea-8ffc-b66c92aedad4.png)
还要把所有页面的这两个元素顺序都调换一下

![image](https://user-images.githubusercontent.com/16400144/82404393-c689a180-9a93-11ea-87e0-37f4eed812d9.png)
![image](https://user-images.githubusercontent.com/16400144/82404437-de612580-9a93-11ea-96f5-b0dd32a48a9d.png)

**Comment by wztlink1013** [comment]
嗯嗯，成了 _、_

**Comment by wztlink1013** [comment]
有两个小小问题，
# **【问题1】**
## - 描述：那些单独没有sidebar的页面，不能自动居中。
## - 截图：
![](https://cdn.jsdelivr.net/gh/wztlink1013/figure/blogarticle56/20200520132642.png)
## - 实例站点
[https://wztlink1013.com/essay/](https://wztlink1013.com/essay/)

# **【问题2】**
## - 描述：左右交换之后，在app端主页展示的先是控件再是文章，可以仍然保持之前的嘛（控件在最底端）😂

**Comment by xaoxuu** [comment]
主题不支持这样的设置，你要这样改的话全部兼容都要自己做哦

**Comment by wztlink1013** [comment]
好的😄

**Comment by Reqwey** [comment]
能不能搞双侧边栏啊，不然感觉不太对称，尤其是侧边栏太短的情况

**Comment by xaoxuu** [comment]
> 能不能搞双侧边栏啊，不然感觉不太对称，尤其是侧边栏太短的情况

不能，想对称的话就把侧边栏去掉吧

**Comment by inkss** [comment]
你可以试试这个，挺有爱的风格，就是改动量很大，脱离版本

https://lluuiq.com/post/202003171229/
