### ISSUE TITLE
关于group组件固定需求建议

### ISSUE THREAD

**Issue by cshuig** [volantis-x/hexo-theme-volantis#318]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

hi, 可否提供 group组件在文章左侧固定起来。点击左侧group重的item后, 只刷新文章及又测组件。

**Comment by xaoxuu** [comment]
#317
