### ISSUE TITLE
ie11下面，导航条显示有问题

### ISSUE THREAD

**Issue by hchaojie** [volantis-x/hexo-theme-volantis#32]
ie11访问首页，默认响应小屏幕的导航条显示出来了。
虽然ie是要被唾弃的，但是至少页面不要给用户太惊吓。

**Comment by tzloop** [comment]
> 我觉得兼容IE成本太高了，而且周围几乎没人用IE，所以就完全没考虑兼容。。。

但我看IE显示还是基本正常的，只是图片大小全部有问题。
