### ISSUE TITLE
利用permalink引入外部文章，无法访问

### ISSUE THREAD

**Issue by heyjie** [volantis-x/hexo-theme-volantis#320]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [ ] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [ ] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载[文档源码](https://github.com/xaoxuu/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [ ] 我已完成上述操作，结果是：__B__

### 第三步

- [ ] 我已经将主题升级到最新版本。

## 问题描述
利用permalink引入外部文章，链接地址变成：自己网站链接+外部链接，无法访问。

### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by xaoxuu** [comment]
请提供站点配置文件、相关文章的 front-matter

**Comment by heyjie** [comment]
---
title: '[转]Docker部署Zabbix+Grafana'
date: 2020-05-23 12:13:43
tags:
author:
  name: Mashiro
  avatar: https://gravatar.2heng.xin/avatar/cd2b3a164c977539712929f66cad335c?s=96&d=mm&r=g
  url: https://2heng.xin/
permalink: https://2heng.xin/2019/09/10/docker-zabbix-grafana/
---
[_config - 副本.txt](https://github.com/xaoxuu/hexo-theme-volantis/files/4673501/_config.-.txt)

**Comment by xaoxuu** [comment]
我使用您提供的 front-matter 本地测试可行。
