### ISSUE TITLE
在 Chrome 84 环境下 toc 部件功能受阻

### ISSUE THREAD

**Issue by Pinming** [volantis-x/hexo-theme-volantis#323]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载[文档源码](https://github.com/xaoxuu/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：没有改变

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述
首先非常感谢 dalao 做了一个这么优秀的主题！接下来反馈问题。
在 Chrome 84 内核环境下（包括 Chromium 版 Edge），点击 toc 中非首个标题时，页面会回弹至第一个标题且页面滚动受阻碍。

## 环境信息
主题的 `v2.6.6` 及 `v3.0 Beta` 均存在该 bug。
个人使用了 `inkss` 的最新 pjax 版本，出现了这一问题。
示例页面 volantis.js.org 同样有此问题。

### 复现地址
包括作者您的示例页面 volantis.js.org 同样出现异常。

### 截图：
这个……截图表达不了问题啊 发个录屏吧
蓝奏云：https://pinming.lanzous.com/icyvatg （烦请解压，视频在压缩包内）
Console 中有关的报错：
https://tva1.sinaimg.cn/large/0080xEK2ly1gf3yehaecrj31jx0u0000.jpg
https://tva1.sinaimg.cn/large/0080xEK2ly1gf3yejwu1wj31jx0u0qph.jpg

### 浏览器、操作系统
出现问题的浏览器：
> - Chrome 84.0.4147.13 (Dev) 
> - Chrome 版 Edge 84.0.524.0 (Canary)
系统：Windows 10 2004

在 `Win10 + Chrome 72 & 81` 平台上；`安卓 10 + Chrome 81` 平台上测试没有出现该问题。

既然连示例页面都有问题我想不必提供下面的信息了吧……有点懒2333

### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by inkss** [comment]
我刚刚下载了个 Chromium（85.0.4156.0），没复现你这个问题，另外我的 Chrome （83.0.4103.61）和 Edge Beta （83.0.478.37）都是正常哒。

**Comment by inkss** [comment]
想到常年披着 99.9.2333.123 皮的 UA，emmm

**Comment by Pinming** [comment]
> 我刚刚下载了个 Chromium（85.0.4156.0），没复现你这个问题，另外我的 Chrome （83.0.4103.61）和 Edge Beta （83.0.478.37）都是正常哒。

我也下了个 85 的，也不出现这个 Bug 了…… 那应该就是 84 内核的问题 23333
也感谢老哥对 pjax 的支持了 真实全人类感谢你的水平（笑

**Comment by Reqwey** [comment]
您的系统和浏览器为啥都是预览版的。。。Win10 2004不是28号才出吗

**Comment by inkss** [comment]
这是位敢走 Canary  通道的大佬，我是不敢用这种版本

**Comment by Pinming** [comment]
> 您的系统和浏览器为啥都是预览版的。。。Win10 2004 不是 28 号才出吗

我 Insider 通道的啊…… 目前用的 19619（笑
突然发现打错了……不是 2004 了，19619 是 20H2 分支的

**Comment by Pinming** [comment]
> 这是位敢走 Canary 通道的大佬，我是不敢用这种版本

Insider Fast 其实也还好…… 一般情况下也没什么大问题 就是尝尝鲜而已233

**Comment by Reqwey** [comment]
在我的第一个系统还在的时候，我也在Windows预览体验计划......
