### ISSUE TITLE
建议增加首页以更新时间排序，非创建时间

### ISSUE THREAD

**Issue by wz-wong** [volantis-x/hexo-theme-volantis#324]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

你好，目前尚未在主题设置中找到可以设置首页默认排序的设置，
当前默认是  以 `创建时间排序`
-  若旧文章有更新，仍然被排在最后，难以被浏览
-  和`归档` 栏功能重复 

能否增加以更新时间进行排序的选项，或者默认以更新时间排序

**Comment by xaoxuu** [comment]
在站点配置文件中修改：
![image](https://user-images.githubusercontent.com/16400144/85193618-d566ac80-b2fc-11ea-9bb9-58bd2e50dd35.png)

**Comment by xaoxuu** [comment]
这是Hexo原生支持的功能，测试如下：

![image](https://user-images.githubusercontent.com/16400144/85193797-ecf26500-b2fd-11ea-8f37-864e5bf375be.png)

![image](https://user-images.githubusercontent.com/16400144/85193769-dea44900-b2fd-11ea-9482-582bd73fbcf4.png)
![image](https://user-images.githubusercontent.com/16400144/85193874-1e6b3080-b2fe-11ea-905d-f2d9aac5ef0e.png)

**Comment by wzzxx-wang** [comment]
抱歉，没详细查hexo的文档
