### ISSUE TITLE
使用hexo-blog-encrypt解密后右侧目录（侧边栏）为空

### ISSUE THREAD

**Issue by hdxw** [volantis-x/hexo-theme-volantis#327]
有话我就直说的，我使用了hexo插件“hexo-blog-encrypt”来加密文章，但是在输入正确的密码后，文章右侧的目录内容为空。
我看了一下volantis源码，在这里侧边栏（_partial/side）不在“文章内容”部分中
https://github.com/xaoxuu/hexo-theme-volantis/blob/master/layout/post.ejs

应该是hexo-blog-encrypt先加密了文章内容，导致文章锚点“丢失”，所以右侧目录内容为空。
我看了hexo-blog-encrypt的一些说明，感觉是volantis侧边栏toc的生成逻辑的问题。
所以能不能修复一下，或者提供一个可以动态加载侧边栏的javascript放在post的末尾来调用也可以解决这个问题。

volantis和hexo-blog-encrypt我都想使用，下面是我参照[hexo-blog-encrypt文档](https://developer.aliyun.com/mirror/npm/package/hexo-blog-encrypt)的改动方法。
把volantis/layout/_widget/toc.ejs改为如下内容
```js
<%- partial('_pre') %>
<% var realcontent = (page.encrypt == true) ? page.origin : page.content; %>
<% if(realcontent && page.toc != false && toc(realcontent).length > 0){ %>
  <section id="toc-div" class="widget toc-wrapper <%- page.widget_style %> <%- page.widget_platform %>" <% if (page.encrypt == true) { %>style="display:none" <% } %>>
    <%- partial('header', {item: item}) %>
    <div class='content'>
        <%- toc(realcontent, {list_number: item.list_number, min_depth: item.min_depth, max_depth: item.max_depth}) %>
    </div>
  </section>
<% } %>
```

**Comment by NoneFire** [comment]
修改了toc.ejs文件之后，目前看解决了这个问题，希望作者可以看下。

**Comment by xaoxuu** [comment]
请问是这一段吗？
![image](https://user-images.githubusercontent.com/16400144/85193379-9d5e6a00-b2fa-11ea-9aa7-7870955adb36.png)

**Comment by Reqwey** [comment]
你的逻辑有问题，不是应该加密的文章不显示目录吗

**Comment by MHuiG** [comment]
测试了一下木有问题
最多改一下样式
https://github.com/MHuiG/hexo-theme-volantis/blob/master-theme/source/css/_third-party/blog-encrypt.styl

**Comment by Reqwey** [comment]
我是说, 加密的文章就不要显示目录了, 显示了也没用

**Comment by MHuiG** [comment]
> 我是说, 加密的文章就不要显示目录了, 显示了也没用

的空是会侧右，录目示显不果如但，啊样这是来原

**Comment by Reqwey** [comment]
> > 我是说, 加密的文章就不要显示目录了, 显示了也没用
> 
> 的空是会侧右，录目示显不果如但，啊样这是来原

?吗密加是算也话说来过倒

**Comment by hdxw** [comment]
另外，最近发现（我目前使用的版本是volantis2.6.2）
解密后的文章内容article-entry由于hexo-blog-encrypt套了两层div，导致锚点定位出现偏差

经过调试发现是before丢了，修改volantis/source/css/_layout/article.styl（332行左右）
把
```
.article .article-entry>
  h1,h2,h3,h4,h5,h6
```
中的>去掉就好了，但是这样右侧的菜单栏会active错位

**Comment by ghost** [comment]
> > 我是说, 加密的文章就不要显示目录了, 显示了也没用
> 
> 的空是会侧右，录目示显不果如但，啊样这是来原

了以可就不rabedis_on置设接直

**Comment by xaoxuu** [comment]
现在情况怎么样了

**Comment by Reqwey** [comment]
好像已经解决了
