### ISSUE TITLE
btns的标题不能自定义吗

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#329]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

如题, 我还以为能自定义呢, 看了主题代码才知道只能是`repo` `bug` 那几种
后来都是手动改`btns.ejs`很麻烦, 希望能做个优化

**Comment by xaoxuu** [comment]
可以配置的呀

**Comment by Reqwey** [comment]
是页面meta里五颜六色的小按钮，我是没找着自定义的地方，主题里面只能写那几种，我是到源文件里乱改一通 https://blog.lhkstudio.me/friends/

**Comment by xaoxuu** [comment]
在配置文件里改：
![image](https://user-images.githubusercontent.com/16400144/85193546-275b0280-b2fc-11ea-9153-459fa9c9c673.png)

**Comment by Reqwey** [comment]
title可以随便改我知道，但是我看了一下主题代码，发现英文名必须是`edit` `repo` `bugs`那些，感觉有点奇怪

**Comment by xaoxuu** [comment]
这个后面会重构
