### ISSUE TITLE
关于页面底部距离的修改

### ISSUE THREAD

**Issue by Deecyn** [volantis-x/hexo-theme-volantis#332]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载[文档源码](https://github.com/xaoxuu/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：_没有找到答案。___

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述

你好，当关闭 Aplayer 音乐播放器的时候，页面底部 footer 与正文的距离有点大，如图：

![image](https://user-images.githubusercontent.com/33906598/84032064-55ba1300-a9c9-11ea-95c5-3501a3aa6064.png)

**请问该如何修改这个距离？**

### 复现地址：

https://deecyn.com/

### 截图：

![image](https://user-images.githubusercontent.com/33906598/84032221-931ea080-a9c9-11ea-906b-3a4e4c77b368.png)

### 浏览器、操作系统

Mac OS 10.15，Chrome 浏览器

### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by xaoxuu** [comment]
这高度就是设计的高度，主题官网以及我的网站都是这样，你想改紧凑一点可以在 `footer.styl` 中修改 `footer` 的样式
