### ISSUE TITLE
Artitalk

### ISSUE THREAD

**Issue by Drew233** [volantis-x/hexo-theme-volantis#333]
## 自检报告

-  [x]  我已阅读主题文档，确认不存在此功能。
-  [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述
不知道是否愿意将artitalk整合入主题
我也可以整合然后Pr
感觉还是可以作为主题的一个特性的

https://artitalk.js.org/demo.html

**Comment by xaoxuu** [comment]
好的呀，我最近不想更新了，你来提pr吧

**Comment by Drew233** [comment]
嗯嗯

**Comment by Reqwey** [comment]
@Drew233  我之前给你提了那个Issue。。。

**Comment by Drew233** [comment]
> @Drew233 我之前给你提了那个Issue。。。

我回复了呀

**Comment by Reqwey** [comment]
这个先关了啊

**Comment by Drew233** [comment]
嗯嗯
