### ISSUE TITLE
谷歌浏览器 浏览主题网站会很卡 希望优化一下

### ISSUE THREAD

**Issue by NorthStarGo** [volantis-x/hexo-theme-volantis#337]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

**Comment by NorthStarGo** [comment]
部署 mark down图文 在谷歌浏览器上浏览会很卡 希望优化一下

**Comment by xaoxuu** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/16400144/84980289-432ba080-b164-11ea-8a72-60c640198fab.png">

1. 关掉粒子效果
2. 关掉右下角的卡通形象

如果还卡，取消毛玻璃效果，背景图片设为 cover 模式。
