### ISSUE TITLE
目录 如何不以 #标题 来定位文章

### ISSUE THREAD

**Issue by huangshi10492** [volantis-x/hexo-theme-volantis#338]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载[文档源码](https://github.com/xaoxuu/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [ ] 我已完成上述操作，结果是：____

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述

如果以 #标题 来定位文章会导致在返回时会跳到上一次点的标题
但[xaoxuu](https://xaoxuu.com/blog/2019-08-27-prohud/)不会这样
这要怎么修改的
![image](https://user-images.githubusercontent.com/42275197/85219165-11207580-b3d4-11ea-9e59-795493d64962.png)
目前的效果
![image](https://user-images.githubusercontent.com/42275197/85219174-239aaf00-b3d4-11ea-8afe-5fe96a14b854.png)
想要的效果（已点击目录）

### 浏览器、操作系统

**Comment by huangshi10492** [comment]
似乎只有pjax版的才能做到

**Comment by xaoxuu** [comment]
默认就是没有的，两个网站配置没有区别，怀疑是加了音乐导致的，aplayer插件会有一些莫名其妙的问题

**Comment by Reqwey** [comment]
我的博客有类似的定位

**Comment by huangshi10492** [comment]
将aplayer关闭就解决了
