### ISSUE TITLE
Request English Version

### ISSUE THREAD

**Issue by mnabila** [volantis-x/hexo-theme-volantis#34]
I hope if you have more time for develope this themes,  please add english version or add option switch between chinse and english. because every this themes update i always change manually some source-code in your themes
thanks 
_sorry if my english language is bad_

**Comment by MicDZ** [comment]
I have done a little translation.
[en.micdz.cn](https://en.micdz.cn)
but i don't know how to add option switch
@nabil48

**Comment by MicDZ** [comment]
@xaoxuu This isn't a lot of work. BUT it's very important to some user. 

Maybe you could add it into todo list.

**Comment by xaoxuu** [comment]
@nabil48  Maybe you can check again, I have updated Material X with English version yesterday.

**Comment by MicDZ** [comment]
@xaoxuu But, the wiki didn't say how to use.

**Comment by mnabila** [comment]
@xia

> @nabil48 Maybe you can check again, I have updated Material X with English version yesterday.

thank you very much for your hard work :heart: :heart: :+1: :1st_place_medal:
