### ISSUE TITLE
使用diff语言代码块为什么没有代码高亮提示

### ISSUE THREAD

**Issue by zyoushuo** [volantis-x/hexo-theme-volantis#341]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载[文档源码](https://github.com/xaoxuu/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [ ] 我已完成上述操作，结果是：____

### 第三步

- [ ] 我已经将主题升级到最新版本。

## 问题描述
在Markdown上使用diff语言的代码块时还会有代码的高亮提示，但是发布后没有效果。是有什么冲突吗

### 截图：

<img src="https://i.loli.net/2020/06/23/meq9LPwVaYRrOdu.png">
<img src="https://i.loli.net/2020/06/23/XdoraBLZQth7YEe.png">
### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by Reqwey** [comment]
highlightjs它不香吗

**Comment by MHuiG** [comment]
https://github.com/xaoxuu/hexo-theme-volantis/blob/fd07b1aa6638314ac9b28549f4c3c10a6056f54f/source/css/_highlight/index.styl




https://github.com/highlightjs/highlight.js/blob/master/src/languages/diff.js

**Comment by zyoushuo** [comment]
> https://github.com/xaoxuu/hexo-theme-volantis/blob/fd07b1aa6638314ac9b28549f4c3c10a6056f54f/source/css/_highlight/index.styl
> 
> https://github.com/highlightjs/highlight.js/blob/master/src/languages/diff.js

**Comment by zyoushuo** [comment]
> https://github.com/xaoxuu/hexo-theme-volantis/blob/fd07b1aa6638314ac9b28549f4c3c10a6056f54f/source/css/_highlight/index.styl
> 
> https://github.com/highlightjs/highlight.js/blob/master/src/languages/diff.js

请问这个怎么使用

**Comment by zyoushuo** [comment]
> highlightjs它不香吗

使用 highlightjs的话没法在使用codeblock了，而且主题中的Folding会有渲染错误

**Comment by xaoxuu** [comment]
diff就只有这两种高亮的地方吗？我可以兼容一下。

**Comment by zyoushuo** [comment]
> diff就只有这两种高亮的地方吗？我可以兼容一下。

diff语言代码块就是这两个高亮的地方，+、-

**Comment by xaoxuu** [comment]
那已经改好了，在master最新代码上

**Comment by zyoushuo** [comment]
> 那已经改好了，在master最新代码上

OK了

**Comment by zyan1226** [comment]
为什么我的代码高亮需要刷新页面才有效
