### ISSUE TITLE
建议加入isso等免注册匿名评论系统

### ISSUE THREAD

**Issue by BeiyanYunyi** [volantis-x/hexo-theme-volantis#342]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [ ] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

我希望[我的博客](https://stblog.penclub.club)可以拥有一个评论免账号且博主不需与国内服务商打交道的评论系统。valine做到了前者却没做到后者，gitalk/gitment/vssue做到了后者却没做到前者。  
目前我了解的只有[isso](https://github.com/posativ/isso)和[hashover](https://www.barkdull.org/software/hashover)可以做到这一点，虽然都得自己部署后端就是了。  
但正如我博文所言，我珍视互联网的匿名性，尽管我自己在匿名这一点上做得并不好。  
也许几天以后我高考完了会给写个PR，所以作者先生（女士？）应该也不用太急着实现。

**Comment by MHuiG** [comment]
NeoValine

https://github.com/UdUklm/NeoValine

https://www.ohmysites.com/archives/15/

**Comment by lossv** [comment]
https://www.ohmysites.com/archives/15/ 或许你可以看看这个

**Comment by BeiyanYunyi** [comment]
已[pr](https://github.com/theme-volantis/hexo-theme-volantis/pull/362)并通过，故关闭本issue
