### ISSUE TITLE
关于Readmore的一个小意见

### ISSUE THREAD

**Issue by LengSword** [volantis-x/hexo-theme-volantis#35]
现在文章Readmore打开的时候会像超链接那样在新的页面打开这篇文章,而不是点击标题直接在原页面跳转打开.
作者可以在后面的更新里加上对Readmore的这个设置项吗?

**Comment by xaoxuu** [comment]
不是吧，这个链接就是在当前页面打开的。Chrome、Firefox、Safari测试都是正常的。
![image](https://user-images.githubusercontent.com/16400144/50572208-a5b8a180-0df5-11e9-8bec-325059e696ed.png)
你用的是什么浏览器？

**Comment by xaoxuu** [comment]
`target="_blank"`这样的链接才会在新页面打开：

![image](https://user-images.githubusercontent.com/16400144/50572239-4e670100-0df6-11e9-8916-4432e7224e3f.png)

**Comment by xaoxuu** [comment]
会不会是浏览器插件加上的

**Comment by xaoxuu** [comment]
我刚去你的博客看了是正常的，不会从新标签打开。

**Comment by LengSword** [comment]
把浏览器插件全禁了还是这样,我的是QQ浏览器,有毒,用Chrome浏览器的话就正常
还有QQ浏览器换成IE兼容模式也可以...但是我也不可能不用Chrome内核模式呀...
感觉不知道什么地方出了问题:cry:
