### ISSUE TITLE
数据文件问题

### ISSUE THREAD

**Issue by gongdananyou** [volantis-x/hexo-theme-volantis#351]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载[文档源码](https://github.com/xaoxuu/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：____

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述
配置的时候我使用数据文件这种方法
menu和layout都正常覆盖
但是widget就怎么都无法覆盖配置，只能通过config文件修改
我看文档是这三个都可以用数据文件的

## 环境信息
hexo: 4.2.1
hexo-cli: 3.1.0
os: Linux 5.3.0-61-generic linux x64
node: 12.18.1

### 浏览器、操作系统
chrome ubuntu18.04

### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by gongdananyou** [comment]
![微信截图_20200701213055](https://user-images.githubusercontent.com/60178803/86249747-47cf6a80-bbe2-11ea-9d2d-71980e4ff085.png)
我也不是很懂这个  这里是不是判断有问题啊 是不是应该先**判断site**，再判断theme？

**Comment by xaoxuu** [comment]
这里是有问题，我改一下。
