### ISSUE TITLE
是否支持其它代码块的样式呢

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#352]
## 自检报告

- [ ] 我要说的内容与帮助或者BUG、建议都无关。（如果有关，请使用相关模板）

## 问题描述

像是这样的：

![代码样式](https://user-images.githubusercontent.com/59497690/86313812-9b7c9b00-bc58-11ea-891a-1c6a96cb504f.png)

**Comment by xaoxuu** [comment]
文档中有
![image](https://user-images.githubusercontent.com/16400144/86315603-25c6fe00-bc5d-11ea-9b04-f80cc42b8013.jpeg)

**Comment by ghost** [comment]
找到了，多谢
