### ISSUE TITLE
交流群

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#354]
## 解决问题

| 渠道 | 方式 | 用途 |
| :-- | :-- | :-- |
| Issue | [@volantis-x/hexo-theme-volantis](https://github.com/volantis-x/hexo-theme-volantis/issues/) | 和开发者沟通的唯一渠道，用于跟进和解决问题 |

## 交流

| 渠道 | 方式 | 用途 |
| :-- | :-- | :-- |
| 论坛 | [@volantis-x/forum](https://github.com/volantis-x/forum/issues/) | 慢，相对正式，方便检索，可以给其他用户参考 |
| QQ群 | 1146399464 | 非正式，快，易于沟通 |
| 微信群 | - | - |

## 佛系互动

| 渠道 | 方式 | 用途 |
| :-- | :-- | :-- |
| 评论区 | 留言 | 可以测试、灌水、推广自己的博客。 |

**Comment by ghost** [comment]
Oh Yeah！有QQ交流群了:smile:

**Comment by Colsrch** [comment]
https://jq.qq.com/?_wv=1027&k=GSwhKTKu
😏
