### ISSUE TITLE
pjax合并后问题

### ISSUE THREAD

**Issue by qinxs** [volantis-x/hexo-theme-volantis#358]
## BUG描述

1. front-matter设置 `comments: false` 失效（`body: [article]` 仍然有效）
2. 重复点击菜单， click事件不停增加（导致不能 CTRL+鼠标左键 在新标签打开链接）
3. 手机端通过菜单访问新页面 待页面加载完成后 菜单会重新弹出

## 复现报告

分类：反馈一个明确的BUG

- [x] 将主题升级至最新版本。
- [x] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。

### 复现步骤

1. xxx
2. xxx
3. xxx

### 复现地址：

https://volantis.js.org/

### 截图：

![click.png](https://7bu.top/2020/07/07/b0b2254e95161.png)

![menu.png](https://7bu.top/2020/07/07/bd0e171419d9e.png)

### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

**Comment by xaoxuu** [comment]
OK

**Comment by inkss** [comment]
### 2. 解绑事件应该就行了
```
if ($postsBtn.length && $bodyAnchor) {
  $postsBtn.click(e => {
    e.preventDefault();
    e.stopPropagation();
    if ($postsBtn.attr("href") != "/") // TODO: fix it
      scrolltoElement($bodyAnchor);
      e.stopImmediatePropagation();
    });
    $postsBtn.unbind("click");  // <---- 解绑一下
}
// 另外俩类似就行
```

### 3. 移动端菜单的激活
这个菜单你那边是用 css 伪类显示出来的，我用 js 去不掉，除非改变实现的方式。
下面的这种，只能去掉二级菜单的显示，一级还是去不掉。

https://github.com/theme-volantis/hexo-theme-volantis/blob/b053de0010888a9e40ac28f19f143c0311f22b8a/layout/_third-party/pjax.ejs#L62-L63

https://github.com/theme-volantis/hexo-theme-volantis/blob/b053de0010888a9e40ac28f19f143c0311f22b8a/layout/_third-party/pjax.ejs#L91-L92

**Comment by xaoxuu** [comment]
我觉得接收到事件后第一时间给出一个明确的视觉反馈，不然有时候总感觉反应迟钝

**Comment by inkss** [comment]
改改切换的动画？

**Comment by inkss** [comment]
我细品了一下，重复的事件监听确实是个错误，但是和 ctrl+右键 无法跳转无关。

**Comment by qinxs** [comment]
> 
> 
> 我细品了一下，重复的事件监听确实是个错误，但是和 ctrl+右键 无法跳转无关。

是 ctrl+左键 无法跳转， 你那边能跳转么？
最开始能跳转 后面多点几次就不能跳转了

**Comment by inkss** [comment]
> 最开始能跳转 后面多点几次就不能跳转了

有个监听当前激活的菜单按钮的点击事件，有这个在你的ctrl的左键跳转就不生效，然后除了重复监听外，最后导航栏上每点过一个按钮上，就都存在着这么一个监听（重复可能也只是影响下性能）。

那这样，在 send 事件的时候，清空导航栏上按钮的点击监听。

```
$('.menu a').unbind('click');
```

**Comment by inkss** [comment]
@xaoxuu  想起来了，当初改的时候就觉得这串没什么用，链接的跳转已经发生了，scrolltoElement 执不执行没太大意义。

https://github.com/theme-volantis/hexo-theme-volantis/blob/b053de0010888a9e40ac28f19f143c0311f22b8a/source/js/app.js#L33-L62

**Comment by xaoxuu** [comment]
例如点击后让按钮变成不可点击状态

**Comment by inkss** [comment]
那样不太好吧？

**Comment by Reqwey** [comment]
反人类按钮
