### ISSUE TITLE
请问有没有博主自己博客的源码

### ISSUE THREAD

**Issue by mikaelzero** [volantis-x/hexo-theme-volantis#36]
非前端开发,对于自定义有些无力

很喜欢博主开源项目中用到的vue的toc,可惜自己不会添加

能提供渠道吗

**Comment by xaoxuu** [comment]
你是想要那个wiki页面的TOC？wiki页面跟博客是两个主题，wiki页面用的是vue的hexo主题：https://github.com/vuejs/cn.vuejs.org

**Comment by mikaelzero** [comment]
好的 谢谢

**Comment by moyokoo** [comment]
我想把post  博客页面设置成wiki的形式 就是使用 vue主题中 api 的 TOC 样式
能简单说下流程吗

**Comment by xaoxuu** [comment]
两个主题都有对应的开源博客。目前我的博客用了一些key不方便开源。

**Comment by xaoxuu** [comment]
我上传了vue那个主题，希望能帮到你：https://github.com/xaoxuu/hexo-theme-vuex
目前代码挺乱的，凑合着看吧。

**Comment by mikaelzero** [comment]
好，谢谢博主

**Comment by CoderMerlin** [comment]
> 
> 
> 我上传了vue那个主题，希望能帮到你：https://github.com/xaoxuu/hexo-theme-vuex
> 目前代码挺乱的，凑合着看吧。

博主你好，请问如何做到一个域名使用两个不同的hexo 主题的呢？
因为我看到博主的博客和wiki是两个不同的主题，但是是同一个域名
