### ISSUE TITLE
Artitalk功能的一些问题

### ISSUE THREAD

**Issue by penndu** [volantis-x/hexo-theme-volantis#368]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

1. 首先是开启pjax之后，Artitalk的加载，以及从Artitalk跳转其它页面，都会出现加载问题；
2. 其次是fancybox会导致Artitalk页面出现错位。

![Snipaste_2020-07-15_13-37-37.jpg](https://7bu.top/2020/07/15/51b0678bc1074.jpg)

**Comment by inkss** [comment]
> 首先是开启pjax之后，Artitalk的加载，以及从Artitalk跳转其它页面，都会出现加载问题；

Artitalk 和 Valine 等，或者说所有基于 Leancloud 插件，因为 AV 对象是 const 定义，不允许重复实例化，所以他们先天性冲突，这点是无解的（除非是共用 AV 对象）。所以 Pjax 配置项里提供了一个 `banUrl` 的属性，可以屏蔽特定链接的 Pjax 访问。

> 其次是fancybox会导致Artitalk页面出现错位。

这个不清楚，召唤 @Colsrch ，你网站我循环 503 了，gg

**Comment by Colsrch** [comment]
> > 首先是开启pjax之后，Artitalk的加载，以及从Artitalk跳转其它页面，都会出现加载问题；
> 
> Artitalk 和 Valine 等，或者说所有基于 Leancloud 插件，因为 AV 对象是 const 定义，不允许重复实例化，所以他们先天性冲突，这点是无解的（除非是共用 AV 对象）。所以 Pjax 配置项里提供了一个 `banUrl` 的属性，可以屏蔽特定链接的 Pjax 访问。
> 
> > 其次是fancybox会导致Artitalk页面出现错位。
> 
> 这个不清楚，召唤 @Colsrch ，你网站我循环 503 了，gg

来了来了，上面那个fancybox问题貌似是解决了吧 @penndu

**Comment by penndu** [comment]
> > 首先是开启pjax之后，Artitalk的加载，以及从Artitalk跳转其它页面，都会出现加载问题；
> 
> Artitalk 和 Valine 等，或者说所有基于 Leancloud 插件，因为 AV 对象是 const 定义，不允许重复实例化，所以他们先天性冲突，这点是无解的（除非是共用 AV 对象）。所以 Pjax 配置项里提供了一个 `banUrl` 的属性，可以屏蔽特定链接的 Pjax 访问。
> 
> > 其次是fancybox会导致Artitalk页面出现错位。
> 
> 这个不清楚，召唤 @Colsrch ，你网站我循环 503 了，gg

pjax我关了，就可以了！

**Comment by penndu** [comment]
> > > 首先是开启pjax之后，Artitalk的加载，以及从Artitalk跳转其它页面，都会出现加载问题；
> > 
> > 
> > Artitalk 和 Valine 等，或者说所有基于 Leancloud 插件，因为 AV 对象是 const 定义，不允许重复实例化，所以他们先天性冲突，这点是无解的（除非是共用 AV 对象）。所以 Pjax 配置项里提供了一个 `banUrl` 的属性，可以屏蔽特定链接的 Pjax 访问。
> > > 其次是fancybox会导致Artitalk页面出现错位。
> > 
> > 
> > 这个不清楚，召唤 @Colsrch ，你网站我循环 503 了，gg
> 
> 来了来了，上面那个fancybox问题貌似是解决了吧 @penndu

装了你的offline-popop就行了！
