### ISSUE TITLE
建议widget加上个aplayer的class

### ISSUE THREAD

**Issue by Colsrch** [volantis-x/hexo-theme-volantis#369]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

如图

![](https://7bu.top/2020/07/16/446681ffdeff0.png)

如果在这些页面：`blog/title/*` 需要一些特定的音乐并且跨页面播放，使用目前`front-matter`中的`music`字段显然是不能达到想要的效果的，咱既然已经实现了pjax，那这些东西是不是也应该加一下呢。

另外就算不能实现上述所说，那简简单单的在widget加上一个class，类似于`front-matter`中的`music`也可以鸭

（我jio得你们应该懂我得意思![](https://cdn.jsdelivr.net/gh/blogimg/emotion/bili_tv_gif/doge.gif)

**Comment by xaoxuu** [comment]
以前是有的，不能兼容pjax就删掉了。

**Comment by Colsrch** [comment]
> 以前是有的，不能兼容pjax就删掉了。

不能兼容嘛，我说怎么记得以前好像在哪里看到了这个来着

**Comment by xaoxuu** [comment]
侧边栏是动态的，每一页都不一样，所以没办法跨页面存在。

**Comment by xaoxuu** [comment]
不知道 @inkss 巨佬有没有什么办法实现

**Comment by Colsrch** [comment]
> 侧边栏是动态的，每一页都不一样，所以没办法跨页面存在。

那就单页面让它存在呢，这个好像是可以实现的趴

**Comment by Colsrch** [comment]
有过的功能就不要阉割了啦，不能跨页面存在也可以像之前没Pjax的时候嘛

**Comment by inkss** [comment]
如果是更多形式的全局播放器，只得是放在重载区域外面，

![image](https://user-images.githubusercontent.com/31947043/87618472-86216980-c74c-11ea-881b-bbebaca84e00.png)

**Comment by xaoxuu** [comment]
> 如果是更多形式的全局播放器，只得是放在重载区域外面，
> 
> ![image](https://user-images.githubusercontent.com/31947043/87618472-86216980-c74c-11ea-881b-bbebaca84e00.png)

能给它加上一个 class 使它不被重载吗

**Comment by inkss** [comment]
不太能，如果到完全没侧边栏的页面多半会失效，其实主要还是侧边栏太动态了，自定义显示的栏目什么的，如果都一样倒也好说。

**Comment by inkss** [comment]
@Colsrch  有没有兴趣把播放器藏到右键里

**Comment by Colsrch** [comment]
> @Colsrch 有没有兴趣把播放器藏到右键里

有点意思，我旁观怎么样

**Comment by inkss** [comment]
得改一下点击行为，dom 点击后右键就隐藏了，本来右键是参考着导航栏改的

**Comment by Colsrch** [comment]
> 得改一下点击行为，dom 点击后右键就隐藏了，本来右键是参考着导航栏改的

对，这个问题在手机上更为明显

**Comment by inkss** [comment]
你在手机上触发右键干嘛？控制音乐？

**Comment by inkss** [comment]
感觉可以扒个类似这样的右键，有点点像是在线版本的 vscode

![image](https://user-images.githubusercontent.com/31947043/87686951-ba7e3f80-c7b7-11ea-8899-08c1fd14603b.png)

**Comment by xaoxuu** [comment]
放右键里太奇怪了，就老老实实放到页脚吧

**Comment by inkss** [comment]
咳咳，整出个花样

**Comment by Colsrch** [comment]
@inkss 话说这个右键弹窗是不是该弄个检测
![image](https://user-images.githubusercontent.com/58458181/87864492-8b282800-c99b-11ea-9c02-e802944a91ce.png)

**Comment by inkss** [comment]
这个可以有

**Comment by xaoxuu** [comment]
以后会做一个定制版音乐控制器，实现部分功能。
