### ISSUE TITLE
在front-matter中设置comments: false无效

### ISSUE THREAD

**Issue by Colsrch** [volantis-x/hexo-theme-volantis#370]
## 复现报告

分类：反馈一个明确的BUG

- [x] 将主题升级至最新版本。
- [x] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。

### 复现步骤

1. xxx
2. xxx
3. xxx

### 站点配置文件

```yml

```

### 主题配置文件

```yml

```

#### node.js & npm

```

```

#### package.json

```

```

![](https://7bu.top/2020/07/16/7b731ba12b2b7.png)

如图，在`front-matter`中设置`comments: false`后，设置页依旧会显示评论。

 我看到前面 @inkss  也提出了这个问题，不知道什么时候解决呢。

话说我用Pjax2分支用的好好的，换来最新版后，虽然解决了以前的一些问题，但又多了一堆问题😂

**Comment by MHuiG** [comment]
> body: [article] 仍然有效

#358

**Comment by Colsrch** [comment]
> > body: [article] 仍然有效
> 
> #358

 我看了，知道这个还有效，但总不能不修复comments这个吧。🙄

**Comment by xaoxuu** [comment]
那不如把这个 `comments: false` 删掉算了

**Comment by Colsrch** [comment]
我怀疑你想偷懒

**Comment by inkss** [comment]
@xaoxuu 有不少啊

![image](https://user-images.githubusercontent.com/31947043/87618674-047e0b80-c74d-11ea-86ee-bfd58e8998b5.png)

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/f1704e9c5688896654cf0e0a934ab7848f57ef66/layout/_third-party/comments/index.ejs#L1

```
<% if (page.comments && theme.comments.service && theme.comments.service.length > 0) { %>
```

**Comment by inkss** [comment]
pjax 需要处理下，切换页面后拿不到 page.comments 信息，老规矩，建议放到 pjaxdata 里，中转存一下
