### ISSUE TITLE
归档页面可以做成分页嘛？

### ISSUE THREAD

**Issue by XuxuGood** [volantis-x/hexo-theme-volantis#373]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

![image](https://user-images.githubusercontent.com/45960164/87751894-a840e780-c831-11ea-93a9-a9ab7d49eab4.png)

**Comment by xaoxuu** [comment]
技术上是可行的，但是分页有什么意义呢？现有的布局即便是500篇文章全部在一个列表展示下来页面也不会变卡。况且，在一个页面中全部显示出来还可以通过页面内搜索快速定位到内容。

**Comment by XuxuGood** [comment]
也是哈，我竟无言驳回 哈哈哈，那就不做这个玩意啦



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xaoxuu"<notifications@github.com&gt;; 
发送时间: 2020年7月17日(星期五) 中午1:58
收件人: "volantis-x/hexo-theme-volantis"<hexo-theme-volantis@noreply.github.com&gt;; 
抄送: "我是土豆又土又逗&amp;#x1F648;"<22476705@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [volantis-x/hexo-theme-volantis] 归档页面可以做成分页嘛？ (#373)





 
技术上是可行的，但是分页有什么意义呢？现有的布局即便是500篇文章全部在一个列表展示下来页面也不会变卡。况且，在一个页面中全部显示出来还可以通过页面内搜索快速定位到内容。

**Comment by xaoxuu** [comment]
我也看到了很多主题的归档都是分页的，但一直都想不明白有什么意义，为什么大家都那样做。

**Comment by XuxuGood** [comment]
可能就是单纯的为了 一个页面下 一眼就能看到这些东西。有一个地方控制台会报错 undefined ：
&nbsp; &nbsp;路径 ：blog\themes\volantis\layout\_third-party\pjax
&nbsp; &nbsp;下面是我修改完的代码，但是修改完以后会发现，点击浏览器的回退键回到首页 导航条没啦，
&nbsp;（复现操作流程大致 为首页向下滑动至有导航条出现，随便点击一遍文章，再点击浏览器回退键，会出现导航条消失效果，前提是我将代码改为非undefined判断）
&nbsp; &nbsp;我前端学识不够深，没解决，还请大佬看看怎么回事。




第二个问题是文档内容介绍错啦：
这个 front-matter 应该为 pin:true


致谢大佬能提供这么优秀的博客主题。嘻嘻




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xaoxuu"<notifications@github.com&gt;; 
发送时间: 2020年7月17日(星期五) 下午2:02
收件人: "volantis-x/hexo-theme-volantis"<hexo-theme-volantis@noreply.github.com&gt;; 
抄送: "我是土豆又土又逗&amp;#x1F648;"<22476705@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [volantis-x/hexo-theme-volantis] 归档页面可以做成分页嘛？ (#373)





 
我也看到了很多主题的归档都是分页的，但一直都想不明白有什么意义，为什么大家都那样做。

**Comment by xaoxuu** [comment]
文档更新了👌
