### ISSUE TITLE
关于博客主题的建议

### ISSUE THREAD

**Issue by A2Data** [volantis-x/hexo-theme-volantis#375]
希望加入Tree结构。 因为本地现在多情况下都是在Typora下编辑，希望可以i根据目录数结构 来定义一下。 可以参考Tree主题。 这样就不用发多次了。 多谢大佬们 可以技术支持。

**Comment by xaoxuu** [comment]
您好，可以描述详细一点吗？

**Comment by MHuiG** [comment]
https://github.com/wujun234/hexo-theme-tree

https://wujun234.github.io

**Comment by MHuiG** [comment]
感觉有点像分类页的功能
