### ISSUE TITLE
样式覆盖问题

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#377]
## BUG描述

正文下 **首行直接** 使用 ultra 标签，字体大小被覆盖了。

```md
% p center logo ultra, balabala %}
```

https://github.com/volantis-x/hexo-theme-volantis/blob/fe17c9826f8f7dfc5f38a485f6211d6921fc637a/source/css/_layout/article.styl#L365

## 复现报告

分类：反馈一个明确的BUG

- [x] 将主题升级至最新版本。
- [x] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [x] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1. 更新至 [fe17c98](https://github.com/volantis-x/hexo-theme-volantis/commit/fe17c9826f8f7dfc5f38a485f6211d6921fc637a)

### 复现地址：

- https://inkss.cn/info/index.html
- https://inkss.cn/about/index.html

### 截图：

<details><summary>相关截图:</summary>

![image](https://user-images.githubusercontent.com/31947043/87891544-ef66ec80-ca6c-11ea-96d0-50af5eee6f69.png)
![image](https://user-images.githubusercontent.com/31947043/87891716-7b791400-ca6d-11ea-8c9f-171866a0df9d.png)

</details>

### 浏览器、操作系统

Win，Edge

<details><summary>配置文件信息:</summary>

### 站点配置文件

```yml
balabala..
```

### 主题配置文件

```yml
balabala..
```

#### node.js & npm

```
balabala..
```

#### package.json

```
balabala..
```

</details>

**Comment by xaoxuu** [comment]
头疼，一改就出问题。。

**Comment by inkss** [comment]
感觉你可以稍微改一下反馈模板，折叠一下没那么夸张的长。

------

### 一、BUG描述

*尽可能详细地描述您的问题，包括预期与实际表现的区别。（预期效果与实际表现不同未必都是BUG，可能是服务器或者配置问题，在反馈BUG前请务必确定这是主题代码的BUG。*

### 二、复现报告

#### 分类：反馈一个明确的BUG

- [x] 将主题升级至最新版本。
- [x] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [x] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

#### 复现步骤

*如果您无法提供详细的复现步骤，说明您对此不明确，建议走帮助流程。*

### 三、环境信息

<details><summary>环境信息:</summary>

#### 浏览器及操作系统：

- 浏览器：Chromium
- 操作系统：Win

#### 复现地址：

*如果使用文档官网源码本地运行也存在异常，可以不用提供复现地址。*

#### 截图：

*不同系统、浏览器效果可能不同，提供截图有助于发现问题所在。*

</details>

### 四、基础配置信息

<details><summary>基础配置信息:</summary>

#### 站点配置文件

<details><summary>配置文件信息:</summary>

```yml

```

</details>

#### 主题配置文件

<details><summary>主题配置文件:</summary>

```yml

```

</details>

#### 更多信息

<details><summary>Hexo 环境信息:</summary>

##### node.js & npm

```yml

```

##### package.json

```yml

```

</details>

</details>
