### ISSUE TITLE
建议加个夜间模式，最好是根据时间自动切换

### ISSUE THREAD

**Issue by Colsrch** [volantis-x/hexo-theme-volantis#381]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

希望有一个按钮切换日间模式和夜间模式，日间模式就是博主配置的颜色，夜间模式就固定下，背景图也强制改变，我觉得现在主题文档的暗黑模式挺适合做夜间模式的

另外最好还能根据现在的时间自动选择当前所使用的模式

**Comment by MHuiG** [comment]
夜间模式目前是alpha版本 #356
