### ISSUE TITLE
更新了新版本以后图标变小了

### ISSUE THREAD

**Issue by heyjie** [volantis-x/hexo-theme-volantis#384]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载 [文档源码](https://github.com/volantis-x/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：找不到修改的位置

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述

在更新了新版本后图标就变小了

### 截图

<details><summary>相关截图:</summary>

这是原来的
![image](https://user-images.githubusercontent.com/41108496/88356585-f5293e80-cd9a-11ea-954e-8e73c04e5a9a.png)
这是更新后的
![image](https://user-images.githubusercontent.com/41108496/88356623-0eca8600-cd9b-11ea-9c59-cc4cf56e1024.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by MHuiG** [comment]
```
############################### Layout ###############################
cover:
  layout: featured # search (搜索), dock (坞), featured (精选), focus (焦点)
```
search的样式冲突了
换一个layout试试

**Comment by xaoxuu** [comment]
现在应该好了吧

**Comment by Eugene9656** [comment]
好了

**Comment by heyjie** [comment]
> 现在应该好了吧

好了
