### ISSUE TITLE
pjax请求返回的html和dom结构不一致，动态插入的js和css无法生效

### ISSUE THREAD

**Issue by lovelyJason** [volantis-x/hexo-theme-volantis#385]
## 复现报告

分类：反馈一个明确的BUG

- [ ] 将主题升级至最新版本。
- [ ] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [ ] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1. 新建一个独立页面，如history,根据is_current(‘history’)判断在某个页面单独插入css和js
2. 从其他页面进入到独立页面时，xhr返回的html页面包含了history动态插入的css和js，但是dom结构里没有这一段，导致新插的css和js没有去请求
3. 而首次进入这个history页面或者刷新当页时，右键源代码和dom结构是一样的，都包含了上述插入的css和js。不好解决啊

### 截图

<details><summary>相关截图:</summary>

</details>

### 浏览器、操作系统
chrome83 macOS 10.13.3

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by inkss** [comment]
两个尝试方法吧：

1. 放到 Pjax 的重载区域内
2. Pjax 的 comple 事件内

https://github.com/volantis-x/hexo-theme-volantis/blob/b68a71418e670463458ca42878dc91a11faf1b83/layout/layout.ejs#L7

https://github.com/volantis-x/hexo-theme-volantis/blob/b68a71418e670463458ca42878dc91a11faf1b83/layout/_third-party/pjax/index.ejs#L63

**Comment by lovelyJason** [comment]
> 两个尝试方法吧：
> 
> 1. 放到 Pjax 的重载区域内
> 2. Pjax 的 comple 事件内
> 
> https://github.com/volantis-x/hexo-theme-volantis/blob/b68a71418e670463458ca42878dc91a11faf1b83/layout/layout.ejs#L7
> 
> https://github.com/volantis-x/hexo-theme-volantis/blob/b68a71418e670463458ca42878dc91a11faf1b83/layout/_third-party/pjax/index.ejs#L63

是的，这样的话就好多了，之前我是用的你的第一种方案，弊病比较多，比如插入的js依赖于jquery则载入的顺序可能会导致问题。第二种方案就好很多了.不过感觉现在这种pjax的弊病太多了，很多意外情况，如缓存过后，js脚本不会重新执行；或者返回其他页面时，动态插入的元素还在那
