### ISSUE TITLE
本主题从其他页面点击浏览器后退按钮控制台有语法报错没解决

### ISSUE THREAD

**Issue by lovelyJason** [volantis-x/hexo-theme-volantis#388]
## BUG描述
如题,从其他页面点击浏览器后退按钮,控制台console有大片红色语法报错;其实不光是首页,大部分情况下,点击浏览器后退,控制台都报有这种错误,暂未知道是什么原因

js报错可能导致后续的很多问题,脚本被中断,这个问题看下是什么原因

## 复现报告

分类：反馈一个明确的BUG

- [ ] 将主题升级至最新版本。
- [ ] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [ ] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1. 
2. xxx
3. xxx

### 复现地址：

官网也有异常

### 截图
![image](https://user-images.githubusercontent.com/50656459/88457725-3b75bf00-cebb-11ea-8884-4c7df48ec8bb.png)

<details><summary>相关截图:</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by inkss** [comment]
可以尝试修复一下

https://github.com/volantis-x/hexo-theme-volantis/blob/fb8fb87a503c6a6375709fb1c312780820eddbb8/layout/_third-party/pjax/index.ejs#L36

https://github.com/volantis-x/hexo-theme-volantis/blob/fb8fb87a503c6a6375709fb1c312780820eddbb8/source/js/app.js#L280
