### ISSUE TITLE
暗黑色主题下评论框文字和主题背景色一样，输入的文字看不到

### ISSUE THREAD

**Issue by JimmyDiary** [volantis-x/hexo-theme-volantis#39]
暗黑色主题下评论框文字和主题背景色一样，输入的文字看不到，具体如下图所示：
<img width="897" alt="png" src="https://user-images.githubusercontent.com/46603856/51310862-8de24e00-1a82-11e9-8df0-458f2ba067a9.png">
<img width="904" alt="default" src="https://user-images.githubusercontent.com/46603856/51310870-9044a800-1a82-11e9-8a3b-c219d69ed257.png">
我是一个小白，但也经过了半天的时间的问题查找，尝试看主题里的代码，但没有解决，所以烦请作者帮忙解决，很喜欢这个主题，感谢，感谢！

**Comment by xaoxuu** [comment]
是评论系统暂时没有支持暗色模式，我可以在主题里试着去支持一下。

**Comment by xaoxuu** [comment]
我更新了，你再试一下。

**Comment by JimmyDiary** [comment]
> 我更新了，你再试一下。
  我试了，正常了耶！谢谢这么快的支持！@xaoxuu

<img width="885" alt="xnip2019-01-21_12-33-25" src="https://user-images.githubusercontent.com/46603856/51453176-e2cede80-1d78-11e9-9970-cd5ead85682d.png">

**Comment by xaoxuu** [comment]
不客气👌
