### ISSUE TITLE
从文章页面返回主页时导航栏未恢复原状

### ISSUE THREAD

**Issue by Aesrium** [volantis-x/hexo-theme-volantis#391]
## BUG描述

从文章页面用浏览器的转到上一页按钮返回主页时，导航栏未恢复原状

## 复现报告

分类：反馈一个明确的BUG

- [ ] 将主题升级至最新版本。
- [ ] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [ ] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1. xxx
2. xxx
3. xxx

### 复现地址：

官网也有异常

### 截图

<details><summary>相关截图:</summary>

![截图](https://user-images.githubusercontent.com/59996165/88468801-7ad3f800-cf1b-11ea-8949-500224f39408.gif)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by xiao-lin52** [comment]
图片可能有点小问题，我重新贴一张：

![](https://cdn.jsdelivr.net/gh/xiao-lin52/image-upload/20200726084323.gif)

**Comment by Aesrium** [comment]
图片可能有点小问题，我重新贴一张：

[截图](https://cdn.jsdelivr.net/gh/xiao-lin52/image-upload/20200726084323.gif)

**Comment by inkss** [comment]
https://github.com/volantis-x/hexo-theme-volantis/issues/388
