### ISSUE TITLE
Nunjucks模板引擎语法与主题带的标签插件语法冲突

### ISSUE THREAD

**Issue by lovelyJason** [volantis-x/hexo-theme-volantis#392]
## BUG描述

如主题中的这一段插件`{% span 样式参数, 文本内容 %}`.
在markdown中写出这一段,页面确实是有效果,文档404那个页面那几个字就是用的这个标签,那么问题来了.

由于hexo使用的是Nunjucks模板引擎,`{{`, `{%` 这些语法会被Nunjucks识别,持续集成的时候,不能通过ci工具的校验.比如我用github action构建的时候,报了错,见以下截图

想问你们是怎么解决的

## 复现报告

分类：反馈一个明确的BUG

- [ ] 将主题升级至最新版本。
- [ ] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [ ] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1. xxx
2. xxx
3. xxx

### 截图

<details><summary>相关截图:</summary>

![image](https://user-images.githubusercontent.com/50656459/88473229-08304000-cf4e-11ea-8b90-10461babb889.png)

他让我看https://hexo.io/docs/troubleshooting.html
这一段,实际上hexo官方给出的方案是
```
{% raw %}

{% end raw %}
```

然而这个只会将里面的内容当做源码原样输出,根本不是这个问题的解决方案, 我还搜了下说是在{前面加上反斜杠`\`转义,并没有什么用,ci还是不通过
</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by MHuiG** [comment]
使用landscape主题报了相同的错误，很明显不是主题的BUG

https://github.com/MHuiG/qdovo/blob/master/_config.yml#L97


https://github.com/MHuiG/qdovo/actions/runs/183034009

Nunjucks模板引擎语法与主题带的标签插件语法是否冲突无关
