### ISSUE TITLE
文章主题设置外部链接设置（permalink）

### ISSUE THREAD

**Issue by gaohaotian93** [volantis-x/hexo-theme-volantis#394]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [ x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [ x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载 [文档源码](https://github.com/volantis-x/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [ b] 我已完成上述操作，结果是：设置问题还是存在

### 第三步

- [ x] 我已经将主题升级到最新版本。

## 问题描述
我想这是文章主题为外链地址。比如我有一个名为abcd的文章，我想点击abcd转入别的地址。
在文章中页面配置中引入外部文章这个小节
我按照教程还是无法实现
我想实现https://volantis.js.org/test/link-post-without-title/像是这样的效果，点开主题可以转入其他链接

## 环境信息 
环境信息是安装文档中的版本安装的。
### 截图

<details><summary>相关截图:</summary>

![image](https://user-images.githubusercontent.com/51021111/88480440-6b3ec880-cf88-11ea-8988-dee389a04a90.png)

</details>

### 浏览器、操作系统
edge,macos 10.13
### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
permalink: :doc/:title/
permalink_defaults:
  doc: doc
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by xaoxuu** [comment]
主题官网是开源的，您想实现官网的效果直接看源码就行了。

**Comment by xaoxuu** [comment]
```
date: 2013-12-24 23:44:13
link: http://www.google.com/
robots: noindex,nofollow
---

This is a link post without a title. The title should be the link with or without protocol. Clicking on the link should open [Google](http://www.google.com/) in a new tab or window.
```
