### ISSUE TITLE
深色模式下，建议增加参数设置代码块字体颜色

### ISSUE THREAD

**Issue by pdone** [volantis-x/hexo-theme-volantis#397]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

### 目前在深色模式下，代码块字体颜色较深，不易看清楚

![UTOOLS1595835166116.png](https://user-gold-cdn.xitu.io/2020/7/27/1738f3032ccfefdf?w=1680&h=944&f=png&s=99731)

### 禁用博客配置文件中的代码高亮可暂时解决，但同时失去了代码高亮功能
![UTOOLS1595835531089.png](https://user-gold-cdn.xitu.io/2020/7/27/1738f35c4da2d787?w=1680&h=944&f=png&s=1172962)

**Comment by MHuiG** [comment]
深色模式所有的样式都在这里

https://github.com/volantis-x/hexo-theme-volantis/blob/master/source/css/_third-party/darkmode.styl

请先自己改一下

**Comment by pdone** [comment]
> 深色模式所有的样式都在这里
> 
> https://github.com/volantis-x/hexo-theme-volantis/blob/master/source/css/_third-party/darkmode.styl
> 
> 请先自己改一下

好的 谢谢
