### ISSUE TITLE
增加了Pjax以后, 感觉页面的 scroll reveal 过渡动画没了, 切换有点生硬

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#401]
## BUG描述

**RT**

## 复现报告

分类：反馈一个明确的BUG

- [x] 将主题升级至最新版本。
- [x] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [x] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1. xxx
2. xxx
3. xxx

### 截图

<details><summary>相关截图:</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by inkss** [comment]
刷新看看一下我网站  https://inkss.cn

**Comment by xaoxuu** [comment]
现在改的有点晃眼

**Comment by inkss** [comment]
毕竟是滚动过去的，调用的你那个函数

**Comment by xaoxuu** [comment]
不要这个效果

**Comment by inkss** [comment]
不然参考一下butterfly的效果？
