### ISSUE TITLE
Github 的样式

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#404]
## 自检报告

-  [x] 我已阅读主题文档，确认不存在此功能。
-  [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

仿照这个整一个？https://blog.cofess.com/repository/

![image](https://user-images.githubusercontent.com/31947043/88871518-acfe9600-d24a-11ea-9b9a-1bb560595161.png)

------

通过一个 api 获取仓库，然后拿到数据后渲染就行了

**Comment by xaoxuu** [comment]
我早都想要这个了，不知道怎么拿数据

**Comment by inkss** [comment]
```js
$.get("https://api.github.com/users/<%=theme.github.username%>/repos", function(result) {
    //...
});```

**Comment by xaoxuu** [comment]
一个侧边栏控件，可配置指定的 user/repo
一个侧边栏控件，可配置显示最新/最热的 n 个仓库
一个标签插件，可以在任何位置插入指定的 user/repo
至于示例这个全部仓库的列表页面，我觉得没必要。

**Comment by inkss** [comment]
https://docs.github.com/cn/rest/reference/projects
https://docs.github.com/cn/rest/reference/repos

**Comment by inkss** [comment]
https://github.com/akfish/hexo-github
https://github.com/Gisonrg/hexo-github-card

**Comment by xaoxuu** [comment]
<a href="https://github.com/volantis-x/hexo-theme-volantis">
  <img src="https://github-readme-stats.vercel.app/api/pin/?username=volantis-x&repo=hexo-theme-volantis&show_owner=true" />
</a>

有这个现成的接口了
```
https://github-readme-stats.vercel.app/api/pin/?username=volantis-x&repo=hexo-theme-volantis&show_owner=true
```

**Comment by inkss** [comment]
不知道访问速度怎么样？

![](https://github-readme-stats.vercel.app/api?username=inkss&show_icons=true)

**Comment by xaoxuu** [comment]
很快
