### ISSUE TITLE
可否增加阅读更多 引流选项

### ISSUE THREAD

**Issue by A2Data** [volantis-x/hexo-theme-volantis#406]
# 参看 OW插件的配置

希望有个选项可以配置一下，增加引流关注到微信公众号 等其他平台。
或者支持 打赏阅读所有文章。

参考页面。
https://www.liaofuzhan.com/posts/2114475547.html

**Comment by xaoxuu** [comment]
<img width="816" alt="Screen Shot 2020-07-31 at 11 58 02" src="https://user-images.githubusercontent.com/16400144/88998732-48643980-d325-11ea-95d6-ecf3900091b1.png">

把阅读更多那个元素删掉，把文章容器高度限制删掉，全文就可以看了。
<img width="832" alt="Screen Shot 2020-07-31 at 11 58 42" src="https://user-images.githubusercontent.com/16400144/88998743-4dc18400-d325-11ea-8b35-881f08f8a0f4.png">
<img width="1017" alt="Screen Shot 2020-07-31 at 11 58 57" src="https://user-images.githubusercontent.com/16400144/88998749-50bc7480-d325-11ea-84ce-ad0530bbdc0a.png">

所以这个防君子不防小人的“强制”引流不如直接在文章页脚放个二维码友好引流更妥。

**Comment by A2Data** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    # 可以添加加密功能 例如https://www.a2data.cn/posts/64528.html

    
        
    
     

    在2020年7月31日 12:03，xaoxuu<notifications@github.com> 写道： 






把阅读更多那个元素删掉，把文章容器高度限制删掉，全文就可以看了。





所以这个防君子不防小人的“强制”引流不如直接在文章页脚放个二维码友好引流更妥。

**Comment by A2Data** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        #          https://www.a2data.cn/posts/64528.html
    密码 为 datascience如果不知道密码 可以有个弹出框，添加好友 或者 回复关键字获取 等等

    
        
    
     

    在2020年7月31日 16:58，yinjie.feng<yinjie.feng@foxmail.com> 写道： 




    font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    # 可以添加加密功能 例如https://www.a2data.cn/posts/64528.html

    
        
    
     

    在2020年7月31日 12:03，xaoxuu<notifications@github.com> 写道： 






把阅读更多那个元素删掉，把文章容器高度限制删掉，全文就可以看了。





所以这个防君子不防小人的“强制”引流不如直接在文章页脚放个二维码友好引流更妥。

**Comment by xaoxuu** [comment]
静态博客加密也别想了，没用的。
