### ISSUE TITLE
pjax的实现

### ISSUE THREAD

**Issue by sxyugao** [volantis-x/hexo-theme-volantis#41]
我已知您原来的pjax版本问题有：
- toc栏不会更新
- 评论不会更新
- mathjax会失效
- sub header不会更新
- scrollReveal会失效
- 进度条只在第一次加载时会有

我重写了您的pjax代码，修复了mathjax、valine评论和sub header的问题。

其余的评论系统由于没使用过，在我自己魔改版主题里被我去掉了，所以没测试。

剩下2个问题是靠关闭来解决的。

进度条的问题不影响使用就没管。

**[Demo](https://sxyugao.top) ⚠ 未经过移动端测试**

由于我自己的主题已经被我改的面目全非，和原版完全不一样，所以不提pr了。

实现细节可以私聊，联系方式在我博客的“关于"界面里。

**Comment by xaoxuu** [comment]
你好，请问您可以提交个pr吗，只关于pjax的，在主题的`_config.yml`中的`services`字段里添加一个`pjax`，值为`true`的时候就启用pjax，同时关闭不兼容的插件如toc、scrollReveal、进度条。
用这个分支：https://github.com/xaoxuu/hexo-theme-material-x/tree/pjax-beta

**Comment by sxyugao** [comment]
> 你好，请问您可以提交个pr吗，只关于pjax的，在主题的`_config.yml`中的`services`字段里添加一个`pjax`，值为`true`的时候就启用pjax，同时关闭不兼容的插件如toc、scrollReveal、进度条。
> 用这个分支：https://github.com/xaoxuu/hexo-theme-material-x/tree/pjax-beta

我还要先做寒假作业。。有空来弄。。

**Comment by xaoxuu** [comment]
好的，谢谢🤝

**Comment by sxyugao** [comment]
我大概把toc栏弄回来了。。但是播放器模式要修改一下。。

**Comment by inkss** [comment]
我也实现了一版本的 pjax 部署，大致修复的七七八八吧，有一些小问题的部分：诸如文章音乐的这种

> enable: true      # true（文章内和文章列表都显示） internal（只在文章内显示）

对 `internal` 这部分的判断我在主题中没有找到，当然也不排除是我在调试的过程中删除掉了（比如我是想让它只在文章中显示），别的功能上，前面提到的大都修复了：评论、公式、动画、按钮动画等。另：搜索部分，因为有使用不到的，只保留了 hexo 和 algolia ，但是可以确保其正常使用。

然后便是封面部分，在最开始时就整个去除掉了，没做处理，后来在尝试时重新添加时 ，因为 app.js 文件已经被我改的面目全非，暂时没处理好导航栏与之的兼容问题，于是也没加上。

此外，代码块的复制功能，因为觉得用处不大，也没研究修复的事宜，直接去除的。

- 可供参考的地址：[Demo](https://inkss.cn/)
- 可供查阅的代码：[Github](https://github.com/inkss/hexo-theme-material-x)

**Comment by Soohti** [comment]
> 我也实现了一版本的 pjax 部署，大致修复的七七八八吧，有一些小问题的部分：诸如文章音乐的这种
> 
> > enable: true      # true（文章内和文章列表都显示） internal（只在文章内显示）
> 
> 对 `internal` 这部分的判断我在主题中没有找到，当然也不排除是我在调试的过程中删除掉了（比如我是想让它只在文章中显示），别的功能上，前面提到的大都修复了：评论、公式、动画、按钮动画等。另：搜索部分，因为有使用不到的，只保留了 hexo 和 algolia ，但是可以确保其正常使用。
> 
> 然后便是封面部分，在最开始时就整个去除掉了，没做处理，后来在尝试时重新添加时 ，因为 app.js 文件已经被我改的面目全非，暂时没处理好导航栏与之的兼容问题，于是也没加上。
> 
> 此外，代码块的复制功能，因为觉得用处不大，也没研究修复的事宜，直接去除的。
> 
> * 可供参考的地址：[Demo](https://inkss.cn/)
> * 可供查阅的代码：[Github](https://github.com/inkss/hexo-theme-material-x)

我在测试您的网站时发现问题。复现方法：在您的网站中单击一张图片跳出 Fancybox 弹出层，然后点击浏览器的返回按钮，弹出层不会消失且无法关闭。

**Comment by inkss** [comment]
> 我在测试您的网站时发现问题。复现方法：在您的网站中单击一张图片跳出 Fancybox 弹出层，然后点击浏览器的返回按钮，弹出层不会消失且无法关闭。

这个比较好修改，查到一个 API 为 `$.fancybox.close()` ，把它放在 Pjax 的请求事件里就行。

& 在弹出的情况下点击返回按钮，这思路太清奇了，宛如测试组的骚操作啊~

**Comment by Soohti** [comment]
> > 我在测试您的网站时发现问题。复现方法：在您的网站中单击一张图片跳出 Fancybox 弹出层，然后点击浏览器的返回按钮，弹出层不会消失且无法关闭。
> 
> 这个比较好修改，查到一个 API 为 `$.fancybox.close()` ，把它放在 Pjax 的请求事件里就行。
> 
> & 在弹出的情况下点击返回按钮，这思路太清奇了，宛如测试组的骚操作啊~

其实是触控板碰到了。。
个人感觉按返回后只要关掉 fancybox 就可以了，再回到上一页的话动画效果有点诡异
另：能不能请您提一个 pr ？

**Comment by inkss** [comment]
@xaoxuu Pjax 兼容写在这个 issue 里吧，然后我想的是全局播放器这块儿，侧栏上的音乐播放器算是不行的，毕竟不是所有页面都存在，所以能不能将其移动到导航栏，类似： [位于导航栏的播放器](https://szyink.com/) （这个是 Handsome 的主题，它这里的处理就很好）

**Comment by xaoxuu** [comment]
@inkss 可以，先等等，😅

刚发布了`1.4`版本（增加毛玻璃效果选项），现在正在写`1.5`版本。
在`1.5`版本中，可以选择在导航栏右边显示音乐或者搜索框。如果导航栏音乐播放器UI处理不好就先放到页脚。

**Comment by xaoxuu** [comment]
全部更新都在`1.4`版本中了，<s>暂时没有`1.5`了。</s>

还有一大波更新。。。

**Comment by xaoxuu** [comment]
结束了，不改了，。。。

https://xaoxuu.com/wiki/volantis/
