### ISSUE TITLE
Fancybox 异常

### ISSUE THREAD

**Issue by AskeyNil** [volantis-x/hexo-theme-volantis#410]
## 复现报告

分类：反馈一个明确的BUG

- [x] 将主题升级至最新版本。
- [x] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [x] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

添加这个后
![image](https://user-images.githubusercontent.com/20418220/89092794-80cc4c00-d3e7-11ea-85c6-63ab85dbe0b8.png)

出现报错
![image](https://user-images.githubusercontent.com/20418220/89092825-ae18fa00-d3e7-11ea-951b-de979d8e3218.png)

### 截图

<details><summary>相关截图:</summary>

</details>

### 浏览器、操作系统
MacOS
Chrome

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

![image](https://user-images.githubusercontent.com/20418220/89092913-53cc6900-d3e8-11ea-9c5d-7770e29d89d4.png)

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```
![image](https://user-images.githubusercontent.com/20418220/89092922-5fb82b00-d3e8-11ea-9dc3-b6a9193bf3f2.png)

</details>

**Comment by inkss** [comment]
> 2.x 版本的 fancybox 标签在 3.x 版本中被重命名为 gallery 

详见：[升级小助手](https://volantis.js.org/v3/getting-started/#%E5%8D%87%E7%BA%A7%E5%B0%8F%E5%8A%A9%E6%89%8B)

**Comment by AskeyNil** [comment]
v3 的网页打不开，啥也看不了。

**Comment by AskeyNil** [comment]
@inkss

**Comment by xaoxuu** [comment]
https://github.com/volantis-x/hexo-theme-volantis/releases
