### ISSUE TITLE
添加主题设置集合入口

### ISSUE THREAD

**Issue by GaHoWong** [volantis-x/hexo-theme-volantis#412]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述
随着主题功能日益强大，在3.0版本中新添加了许多新功能特性，导致网站的设置按钮分散，比如：自动播放、黑暗模式等，建议添加一个将设置集合的入口：在现在搜索栏的旁边的位置生成下拉菜单或用户高自定义的侧边栏形式。

类似于以下图片：

![image](https://user-images.githubusercontent.com/65532971/89102173-2360eb00-d439-11ea-9ca6-01d5beba43e9.png)

**Comment by MHuiG** [comment]
现在是添加到导航栏里和右键菜单里
