### ISSUE TITLE
右键菜单功能

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#413]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

通用：
- [ ] 检查元素
- [ ] 保存为书签

在图片上点击时：
- [ ] 复制图片
- [x] 复制图片链接
- [ ] 图片另存为

在链接上点击时：
- [x] 复制链接地址
- [x] 在新标签页中打开
- [ ] 在新窗口中打开

**Comment by inkss** [comment]
挺难的，可不可以这样，改成按下 ctrl 时右键，恢复系统默认的右键菜单，这个我能实现

**Comment by inkss** [comment]
不然，也有点费力不讨好，不是很能实现

**Comment by xaoxuu** [comment]
可以啊，我增加了复制图片链接和打印页面的功能

**Comment by inkss** [comment]
囧

**Comment by shiaqiya** [comment]
希望不要去掉检查功能，这个太重要了

**Comment by xaoxuu** [comment]
> 希望不要去掉检查功能，这个太重要了

你可以在配置文件中关掉自定义右键菜单，使用浏览器原生的。

**Comment by 0x01x0** [comment]
> > 希望不要去掉检查功能，这个太重要了
> 
> 你可以在配置文件中关掉自定义右键菜单，使用浏览器原生的。

请问在配置文件的哪个地方关闭呢?

**Comment by xaoxuu** [comment]
剩下那些不做了
