### ISSUE TITLE
添加音乐菜单侧边栏与歌词显示

### ISSUE THREAD

**Issue by GaHoWong** [volantis-x/hexo-theme-volantis#414]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述
希望添加aplayer音乐菜单控制侧边栏功能，由用户决定是否启用。
效果如下：
![image](https://user-images.githubusercontent.com/65532971/89102314-7be4b800-d43a-11ea-8221-e600e82dc227.png)

**Comment by MHuiG** [comment]
#369
