### ISSUE TITLE
添加阅读进度百分比显示

### ISSUE THREAD

**Issue by GaHoWong** [volantis-x/hexo-theme-volantis#415]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

（1）添加类似于next主题的阅读进度百分比显示

**Comment by xaoxuu** [comment]
这个功能大概会在重构 loading 的时候顺便做一下。

**Comment by Tikas** [comment]
之前不知道在那里看到一个非常好看的百分比进度
由于有半年以上的年代了，在此，只能以文字形式描述一下：

它是把回到顶部，做成百分比，中间会显示百分比数字，底部容器会从左向右方向按百分比进行填充，最主要的，在移动端能拖动它到左边（同样是底部）

当时看到之后给我留下了非常深刻的印象，过几天准备在电脑端查看源码时，那个网站竟然关站了，非常可惜！

希望大家复现时此功能时，能给我一个惊喜，XDDDDDDDDDDDDD
