### ISSUE TITLE
页面配置部分的列表页面代码存在错误，list.ejs的判断和循环中应该使用site.posts而非site.pages

### ISSUE THREAD

**Issue by Aexcellent** [volantis-x/hexo-theme-volantis#419]
## BUG描述

页面配置部分的列表页面代码存在错误，按文档在相应位置创建md文件生成index，预期显示所有在front-matter中添加group:mylist的文章，结果并不能显示

## 复现报告

分类：反馈一个明确的BUG

- [x] 将主题升级至最新版本。
- [x] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [ ] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1.页面配置部分的列表页面代码存在错误，layout/list.ejs中的判断、循环应该使用site.posts而非site.pages，根据hexo api文档site.post获取所有文章，site.page获取所有页面，修改文件后可解决提出的问题。

### 截图

<details><summary>相关截图:</summary>

![image](https://user-images.githubusercontent.com/33534276/89248071-5fff3300-d641-11ea-83ad-e5b914853887.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by xaoxuu** [comment]
2995ab1a98bc6c23735d513805087f70ad7805f7
