### ISSUE TITLE
能否开启全局评论

### ISSUE THREAD

**Issue by ZeddYu** [volantis-x/hexo-theme-volantis#42]
看了文档，发现如果要从原博客主题迁移过来比较麻烦，主要是原博客主题只要在`_config.yml`设置评论系统开启，全部文章都可以有评论系统了，不需要额外在post中增加字段。所以想问问是不是该主题能否开启全局评论，而不需要挨个开启。或者文档哪里我没理解仔细。

ps:建议在文档增加指明`_config.yml`的位置，一般其他博客主题都是修改的主题下的`_config.yml`，我在使用的时候也不太分得清楚有些地方的`_config.yml`是指的是哪个文件，直到自己看到了评论才了解。

**Comment by ZeddYu** [comment]
好吧是自己理解错了，`disqus_shortname`需要放在根目录下的`_config.yml`，习惯性放置在主题目录下的`_config.yml`文件了。

还是顺便想问问博主有没有博客主页的配置：）

**Comment by xaoxuu** [comment]
@ZeddYu 目前还不能对主页的布局进行配置，但是已经列在日程中了，请关注后期的更新。详见 [#TODO](https://xaoxuu.com/wiki/material-x/#TODO)

**Comment by ZeddYu** [comment]
@xaoxuu 感谢🙏
另外`import`功能建议可以自定义，比如说我想要加入`instant.page`
```html
<script src="//instant.page/1.1.0" type="module" integrity="sha384-EwBObn5QAxP8f09iemwAJljc+sU+eUXeL9vSBw1eNmVarwhKk2F9vBEpaN9rsrtp"></script>
```
但是`import`功能只会把整段代码加入并加个后缀`.js`，我不得不自己修改末班文件解决，可以自定义加入代码的话这样各种方面也比较方便

**Comment by xaoxuu** [comment]
@ZeddYu 我刚刚更新了主题，在`import`中新增了`script`，你看看能否满足你的需求。
```yaml
import:
  script:
    - src:
      type:
      integrity:
      async:
      charset:
      defer:
```

**Comment by xaoxuu** [comment]
感觉我这样把属性拆开有点多此一举
下个版本考虑简化一下

**Comment by ZeddYu** [comment]
@xaoxuu 个人觉得可以提供一个可以让用户直接引入自己 scirpt 代码的选项，就不需要展开字段了

**Comment by ZeddYu** [comment]
非常感谢作者这么勤劳更新 ：）

**Comment by ZeddYu** [comment]
@xaoxuu 再建议一下友链的friend-name font-family 对英文支持不太友好，字体有点糊，我只能在`_links.less`注释掉了`// font-family: @fontfamily_logo;`

**Comment by xaoxuu** [comment]
logo字体本来就是英文字体。
我去你那里看了，你觉得有点糊实际上是因为有阴影，我给文字加了阴影，为了优化彩色背景+白色文字时的显示效果，而你的背景是纯黑色的，所以建议把阴影效果和加粗效果去掉看看。

**Comment by ZeddYu** [comment]
能否在移动端在文章开头置顶处添加目录呢，个人觉得没有目录不太方便

**Comment by xaoxuu** [comment]
在文章页面导航栏点击右上角按钮显示目录
