### ISSUE TITLE
pjax跳转的页面与封面dock显示的当前页面不同步

### ISSUE THREAD

**Issue by Reqwey** [volantis-x/hexo-theme-volantis#420]
## BUG描述

比如我现在在首页, 跳转到标签页, 但是dock上面我没有放标签页, 则还是会选中在首页

## 复现报告

分类：反馈一个明确的BUG

- [-] 将主题升级至最新版本。
- [-] 下载主题官网源码运行，经过一定的步骤，可以复现此BUG。
- [-] 我已经查看了[Volantis的最新路线图](https://github.com/volantis-x/hexo-theme-volantis/projects)，并搜索了当前的 [issues](https://github.com/volantis-x/hexo-theme-volantis/issues), 但是并不能够帮助我。

### 复现步骤

1. xxx
2. xxx
3. xxx

### 截图

<details><summary>相关截图:</summary>

![image.png](https://i.loli.net/2020/08/04/IrOKGMZYyqlR4DQ.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by inkss** [comment]
不是我主动关的，提交时自动关闭，github 真神奇，@Linhk1606 你验证下吧

**Comment by Reqwey** [comment]
好像Volantis官网还没改, 我先把新代码拉下来自己测吧

**Comment by Reqwey** [comment]
OK了好像
