### ISSUE TITLE
作者您好，请问搜索框的烟花特效如何关闭？

### ISSUE THREAD

**Issue by nobodypengium** [volantis-x/hexo-theme-volantis#422]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x ] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x ] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载 [文档源码](https://github.com/volantis-x/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x  ] 我已完成上述操作，结果是：依旧如此，因为默认模板就是这个样子的。

### 第三步

- [x  ] 我已经将主题升级到最新版本。

### 复现地址：
在文档中Colsrch的示例博客中的搜索框里，也有这样的效果。
https://colsrch.top/
但是在官方文档中的搜索框里，没有这样的效果
https://volantis.js.org/

在cover和navbar中的这种烟花效果都想要取消，但是找不到哪里取消。

### 截图

<details><summary>相关截图:</summary>

![navbar中的烟花效果](https://user-images.githubusercontent.com/13833330/89555074-34976680-d842-11ea-94b7-c3fa972250f0.png)
![cover中的烟花效果](https://user-images.githubusercontent.com/13833330/89555150-48db6380-d842-11ea-83cb-2a2fe4a695fc.png)
</details>

### 浏览器、操作系统
Chrome Win10

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

## 其他信息
发现移除掉"input"的EventListener可以解决掉此问题，但是该JS代码指向一个远程JS地址，无法更改。
![image](https://user-images.githubusercontent.com/13833330/89555838-1da54400-d843-11ea-8e79-6975dd84e796.png)
发现将[themes\volantis\layout\_cover\search.ejs](https://github.com/volantis-x/hexo-theme-volantis/blob/28f48580645f6bc7051efd1a45aa45512760648d/layout/_cover/search.ejs#L17)中17行的type="text"移除，可以关闭搜索框烟花特效。虽然目前没有发现什么其他影响，但是显然这是错误的解决方法。

**Comment by inkss** [comment]
插件：comment_typing ，注释它就可以关闭了

**Comment by nobodypengium** [comment]
多谢~
