### ISSUE TITLE
单张壁纸的优化

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#430]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

现在单张壁纸仍然和多张壁纸使用同样的 backstretch 插件，禁用 backstretch 插件则无法使用壁纸。单张壁纸时没必要加载 backstretch 资源，这里需要优化一下。

**Comment by Reqwey** [comment]
对, 完全可以自己写
