### ISSUE TITLE
开启 scrollreveal 切换页面时，如果布局不变、网速比较快，页面文字会闪一下。

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#431]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

不知道这个能不能优化。

**Comment by MHuiG** [comment]
https://7.dusays.com/2021/01/13/3f07326bfbb10.gif

<blockquote></blockquote>
