### ISSUE TITLE
从 Gitee Issues 加载友链

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#433]
## 自检报告

- [x] 我已阅读主题文档，确认不存在此功能。
- [x] 我已阅读Hexo官方文档，确认不存在此功能。

## 需求描述

API: https://gitee.com/api/v5/swagger#/getV5ReposOwnerRepoIssues

测试1: https://gitee.com/api/v5/repos/xaoxuu/friends/issues?state=open&sort=updated&direction=desc&page=1&per_page=100

### 用 issue 标签决定友链是否通过

例如 `active` 代表友链通过并且是活跃的，`invalid` 代表友链失效了，根据这些状态在页面上作出标记。

### 按 issue 标签分组

例如：

```yaml
---
layout: friends
friend_groups: [aaa, bbb]
---
```

然后就依次请求这几个分组的活跃的友链

https://gitee.com/api/v5/repos/xaoxuu/friends/issues?state=open&labels=aaa%2Cactive&sort=updated&direction=desc&page=1&per_page=100

最后再请求一下标记为失效的链接，放到单独一个分组中：
https://gitee.com/api/v5/repos/xaoxuu/friends/issues?state=open&labels=invalid&sort=updated&direction=desc&page=1&per_page=100

### issue 内容格式

```
<!-- 姓名 -->
<b>姓名</b>

<!-- 标签或者描述 -->
<p>标签</p>
```

博客中添加源码：

```
<div class="btns circle grid5 friends"><div class="loading"><i class="fa fa-cog fa-2x fa-spin"></i></div></div>
{% raw %}
<script>
function loadFriends() {
  $.get("https://gitee.com/api/v5/repos/xaoxuu/friends/issues?state=open&sort=updated&direction=desc&page=1&per_page=100",function(data, status) {
    if (data.length > 0) {
      for (i = 0; i < data.length; i++) {
        let imgTag = '<img src="' + data[i].avatar_url + '>';
        let aTag = '<a class="button" target="_blank" rel="external nofollow noopener noreferrer" href="' + data[i].title + '">' + '<img no-lazy src="' + data[i].user.avatar_url + '">' + data[i].body + '</a>';
        $('.btns.friends').append(aTag);
      }
    }
    $('.btns.friends .loading').remove();
  });
}
document.addEventListener('DOMContentLoaded', function () {
  loadFriends();
});
loadFriends();
</script>
{% endraw %}
```

**Comment by inkss** [comment]
等等，这样做最开始的目的是什么来着？

**Comment by xaoxuu** [comment]
timeline：用leancloud不安全
友链：用issue比改源码方便

**Comment by inkss** [comment]
包括但不限于 issue ？

**Comment by xaoxuu** [comment]
没有比 issue 跟方便的了吧

**Comment by inkss** [comment]
比如，一个正儿八经的数据库，hhhhh

**Comment by xaoxuu** [comment]
那你不光自己要搞一堆登录校验系统，别人来留言也要注册登录，麻烦程度远超改源码啊

**Comment by inkss** [comment]
哦哦哦，理解错了，你是想要一个别人主动提交，然后你这边主动审核是吗

**Comment by inkss** [comment]
Gitee 支不支持定时任务？利用 github api 读 issue，同步到 gitee 仓库？  
这个可以实现吧，毕竟我就没怎么用过 gitee 账户

**Comment by xaoxuu** [comment]
对啊，这样即时走在路上点点手机给 issue 加个 active 标签就可以了，比 改源码 方便

**Comment by xaoxuu** [comment]
这我也不知道，gitee可以同步仓库内容，但是不带issue

**Comment by inkss** [comment]
我记得你以前发过它的文档吧，估计应该可以和 github 一样，利用 api 建立 issue，那如果是利用 github 的 api 读这边仓库的issue，同步 gitee 创建，感觉能实现啊

**Comment by inkss** [comment]
https://gitee.com/api/v5/swagger#/postV5ReposOwnerIssues

https://docs.github.com/cn/rest/reference/issues

**Comment by inkss** [comment]
github action 应该可以监控 issue 的创建，然后同步到 gitee ，很可行呀

**Comment by xaoxuu** [comment]
或许直接用github issues 也行

**Comment by Reqwey** [comment]
https://github.com/Linhk1606/blog-source/edit/master/source/friends/index.md
多么的省事～
