### ISSUE TITLE
异常代码

### ISSUE THREAD

**Issue by zryyyy** [volantis-x/hexo-theme-volantis#434]
## 自检报告

分类：使用遇到问题（主题未经修改）

### 第一步 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步 

下载 [文档源码](https://github.com/volantis-x/volantis-docs/)，然后下载主题源码到 themes/volantis ，执行 `npm install` 安装依赖包，执行 `hexo s` 运行，查看结果是否存在相同的问题。

- A. 如果正常，请一步一步将配置文件修改为您原来的设定，直至找到出问题的地方。
- B. 如果依然存在异常，请检查 Hexo 环境配置，或者重新安装 Hexo。

- [x] 我已完成上述操作，结果是：____未解决

### 第三步

- [x] 我已经将主题升级到最新版本。

## 问题描述
使用命令hexo g时，出现警告
(node:10764) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10764) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:10764) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:10764) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:10764) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:10764) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency

### 截图

<details><summary>相关截图</summary>

</details>

### 浏览器、操作系统
win10
### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```
v14.7.0
6.14.7
#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by xaoxuu** [comment]
第二步结果是A还是B

**Comment by zryyyy** [comment]
> 第二步结果是A还是B

A

**Comment by zryyyy** [comment]
ERROR {
  err: C:\Users\zry\Blog\hexo\node_modules\hexo-theme-volantis\package.json:2
    "_from": "hexo-theme-volantis@^3.0.0-rc.1",
           ^

  SyntaxError: Unexpected token ':'
      at new Script (vm.js:100:7)
      at createScript (vm.js:267:10)
      at runInThisContext (vm.js:315:10)
      at C:\Users\zry\Blog\hexo\node_modules\hexo\lib\hexo\index.js:303:18
      at tryCatcher (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\util.js:16:23)   
      at Promise._settlePromiseFromHandler (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\async.js:86:9)  
      at Async._drainQueues (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\zry\Blog\hexo\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:458:21)
} Plugin load failed: %s hexo-theme-volantis

**Comment by xaoxuu** [comment]
您是通过 npm i hexo-theme-volantis 方式安装的主题吗？

**Comment by xaoxuu** [comment]
这可能是 hexo 官方的 bug 
请把 package.json 中的 hexo 版本改为 5.0.2 然后 `npm i` 再看看

**Comment by zryyyy** [comment]
> 这可能是 hexo 官方的 bug
> 请把 package.json 中的 hexo 版本改为 5.0.2 然后 `npm i` 再看看

好的

**Comment by xaoxuu** [comment]
主题官网的 package.json 
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "5.0.2"
  },
  "dependencies": {
    "hexo": "^5.0.2",
    "hexo-all-minifier": "^0.5.3",
    "hexo-autonofollow": "^1.0.1",
    "hexo-autoprefixer": "^1.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-fs": "^3.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-seo-friendly-sitemap": "0.0.25",
    "hexo-generator-tag": "^1.0.0",
    "hexo-lazyload-image": "^1.0.9",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}
```

运行测试：

```
xaoxuus-MacBook-Pro:volantis-docs dev$ npm i
updated 39 packages and audited 831 packages in 20.899s

22 packages are looking for funding
  run `npm fund` for details

found 213 vulnerabilities (160 low, 53 high)
  run `npm audit fix` to fix them, or `npm audit` for details
xaoxuus-MacBook-Pro:volantis-docs dev$ hexo clean
INFO  Validating config
INFO  Deleted database.
xaoxuus-MacBook-Pro:volantis-docs dev$ hexo s
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
^CINFO  Farewell
xaoxuus-MacBook-Pro:volantis-docs dev$ hexo g
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 395 ms
INFO  Generated: page-sitemap.xml
INFO  Generated: sitemap.xml
INFO  Generated: post-sitemap.xml
INFO  Generated: sitemap.xsl
INFO  Generated: img/algolia.svg
INFO  Generated: CNAME
INFO  Generated: manifest.json
INFO  Generated: robots.txt
INFO  Generated: img/baidu.svg
INFO  Generated: start
INFO  Generated: img/azure.svg
INFO  Generated: archives/2017/index.html
INFO  Generated: archives/2018/index.html
INFO  Generated: archives/2019/index.html
INFO  Generated: archives/2018/07/index.html
INFO  Generated: archives/2019/07/index.html
INFO  Generated: faqs/index.html
INFO  Generated: archives/2020/03/index.html
INFO  Generated: archives/2020/02/index.html
INFO  Generated: archives/2020/07/index.html
INFO  Generated: archives/2020/08/index.html
INFO  Generated: fonts/Monaco.ttf
INFO  Generated: blogs/2020-08-08-issue-timeline/index.html
INFO  Generated: test/2020-03-06-test-url/index.html
INFO  Generated: archives/2020/04/index.html
INFO  Generated: archives/2020/05/index.html
INFO  Generated: js/app.js
INFO  Generated: archives/index.html
INFO  Generated: archives/2017/10/index.html
INFO  Generated: 404.html
INFO  Generated: contributors/index.html
INFO  Generated: v3/theme-settings/cover/index.html
INFO  Generated: js/aplayer.js
INFO  Generated: atom.xml
INFO  Generated: archives/2020/index.html
INFO  Generated: search.xml
INFO  Generated: archives/2013/index.html
INFO  Generated: archives/2013/12/index.html
INFO  Generated: archives/page/2/index.html
INFO  Generated: news/2020-07-03/index.html
INFO  Generated: v2/getting-started/index.html
INFO  Generated: v3/theme-settings/search/index.html
INFO  Generated: blogs/2020-08-08-issue-friends/index.html
INFO  Generated: v3/theme-settings/seo/index.html
INFO  Generated: blogs/2020-05-17-pjax/index.html
INFO  Generated: news/2020-04-04/index.html
INFO  Generated: news/2020-02-21/index.html
INFO  Generated: news/2020-02-25/index.html
INFO  Generated: news/2020-02-22/index.html
INFO  Generated: news/2020-02-19/index.html
INFO  Generated: news/2020-02-20/index.html
INFO  Generated: test/excerpts/index.html
INFO  Generated: test/gallery-post/index.html
INFO  Generated: test/no-title/index.html
INFO  Generated: test/日本語テスト/index.html
INFO  Generated: test/link-post/index.html
INFO  Generated: test/中文測試/index.html
INFO  Generated: test/long-title/index.html
INFO  Generated: test/tags/index.html
INFO  Generated: test/categories/index.html
INFO  Generated: test/images/index.html
INFO  Generated: test/hello-world/index.html
INFO  Generated: archives/2013/page/2/index.html
INFO  Generated: v3/page-settings/front-matter/index.html
INFO  Generated: v3/site-settings/index.html
INFO  Generated: news/2017-10-24/index.html
INFO  Generated: index.html
INFO  Generated: test/link-post-without-title/index.html
INFO  Generated: archives/2020/page/2/index.html
INFO  Generated: tags/foo/index.html
INFO  Generated: v3/advanced-settings/index.html
INFO  Generated: v3/theme-settings/comments/index.html
INFO  Generated: v3/page-settings/body/index.html
INFO  Generated: v3/theme-settings/layout/index.html
INFO  Generated: v3/theme-settings/style/index.html
INFO  Generated: v3/theme-settings/plugins/index.html
INFO  Generated: v3/theme-settings/navbar/index.html
INFO  Generated: v3/theme-settings/footer/index.html
INFO  Generated: archives/2013/12/page/2/index.html
INFO  Generated: v3/theme-settings/meta/index.html
INFO  Generated: news/2020-03-06-2.0-beta/index.html
INFO  Generated: news/2020-03-10-2.0/index.html
INFO  Generated: news/2020-02-18/index.html
INFO  Generated: v2/site-settings/index.html
INFO  Generated: v3/getting-started/index.html
INFO  Generated: v3/theme-settings/index.html
INFO  Generated: js/search.js
INFO  Generated: test/videos/index.html
INFO  Generated: test/elements/index.html
INFO  Generated: v2/advanced-settings/index.html
INFO  Generated: v3/page-settings/layout/index.html
INFO  Generated: archives/page/3/index.html
INFO  Generated: archives/page/4/index.html
INFO  Generated: categories/foo/index.html
INFO  Generated: examples/index.html
INFO  Generated: v3/theme-settings/widget/index.html
INFO  Generated: test/tag-plugins/index.html
INFO  Generated: page/2/index.html
INFO  Generated: tags/baz/index.html
INFO  Generated: page/4/index.html
INFO  Generated: test/markdown/index.html
INFO  Generated: test/code-highlight/index.html
INFO  Generated: tags/bar/index.html
INFO  Generated: categories/foo/bar/baz/index.html
INFO  Generated: v2/page-settings/index.html
INFO  Generated: page/3/index.html
INFO  Generated: categories/foo/bar/index.html
INFO  Generated: v2/tag-plugins/index.html
INFO  Generated: v3/tag-plugins/index.html
INFO  Generated: v2/theme-settings/index.html
INFO  Generated: content.json
INFO  Generated: css/style.css
INFO  Generated: fonts/Skranji-Regular.ttf
INFO  Generated: fonts/Ubuntu-Regular.ttf
INFO  Generated: js/valine.js
INFO  115 files generated in 3.44 s
```

**Comment by inkss** [comment]
在执行以下命令后，收到了如图中所示的内容：

```sh
hexo init
npm i hexo-theme-volantis
hexo s
```

![image](https://user-images.githubusercontent.com/31947043/89881606-4d17d000-dbf8-11ea-915d-915cb82703f6.png)

**接着按照文档设置 `theme: volantis`**，重新执行：

```
hexo clean
hexo s
```

一切正常，是个全新的主题~

**Comment by xaoxuu** [comment]
您好， 5.0.2 可以吗？

**Comment by zryyyy** [comment]
> 您好， 5.0.2 可以吗？

我好像本来就是5.0.2

**Comment by zryyyy** [comment]
> 在执行以下命令后，收到了如图中所示的内容：
> 
> ```shell
> hexo init
> npm i hexo-theme-volantis
> hexo s
> ```
> 
> **接着按照文档设置 `theme: volantis`**，重新执行：
> 
> ```
> hexo clean
> hexo s
> ```
> 
> 一切正常，是个全新的主题~

这个好像不行啊..............还是报错

**Comment by MHuiG** [comment]
上面那个配置文件填一下，你给我们看的是错误，这能看出什么

**Comment by zryyyy** [comment]
> 上面那个配置文件填一下，你给我们看的是错误，这能看出什么

配置文件我就改了主题的那个，原来想测试一下的，结果报错了

**Comment by MHuiG** [comment]
npm ls --depth 0       输出的信息

**Comment by zryyyy** [comment]
> npm ls --depth 0 输出的信息

+-- hexo@5.0.2
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.0.0
+-- hexo-renderer-pug@1.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
`-- hexo-theme-volantis@3.0.0-rc.1

**Comment by MHuiG** [comment]
博客根目录中_config.yml文件

**Comment by MHuiG** [comment]
> **接着按照文档设置 `theme: volantis`**，重新执行：


~这里是不是应该设置theme:hexo-theme-volantis~

**Comment by zryyyy** [comment]
> 这里是不是应该设置theme:hexo-theme-volantis
..................？

**Comment by zryyyy** [comment]
> 这里是不是应该设置theme:hexo-theme-volantis
我看看

**Comment by xaoxuu** [comment]
是 `theme: volantis` 

https://blog.skk.moe/post/hexo-5/

**Comment by MHuiG** [comment]
重新运行一下npm install

**Comment by xaoxuu** [comment]
> 重新运行一下npm install

自检第二步结果是A，修改了配置之后出错的，应该不是包的问题了。

**Comment by MHuiG** [comment]
> 自检第二步结果是A，修改了配置之后出错的，应该不是包的问题了。

那修改的配置是什么

**Comment by MHuiG** [comment]
hexo -v输出信息

**Comment by xaoxuu** [comment]
先 `hexo clean` 再 `hexo s`

**Comment by MHuiG** [comment]
@zryyyy 能否提供一份可以复现问题的源码
例如https://github.com/Linhk1606/blog-source

**Comment by inkss** [comment]
这串警告，我倒是复现了出来，不过警告wu'shang无伤大雅

```log
(node:10764) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
(node:10764) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:10764) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:10764) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:10764) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:10764) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
```

![image](https://user-images.githubusercontent.com/31947043/90100664-c128b400-dd6f-11ea-8ad1-4bd1b81ab7b7.png)

**Comment by zryyyy** [comment]
我好像知道了..................貌似是node14造成的

**Comment by xaoxuu** [comment]
打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

**Comment by zryyyy** [comment]
我又试了一下，用nodev12就没有问题，但是用v14就有问题了

**Comment by zryyyy** [comment]
应该是node的问题

**Comment by zryyyy** [comment]
谢谢开发者的帮助😘😘😘
