### ISSUE TITLE
主题配置加载失败（ERROR Theme config load failed.）

### ISSUE THREAD

**Issue by tzblog** [volantis-x/hexo-theme-volantis#435]
您好，两台电脑（mac和Windows），mac问题：
开始能够正常本地浏览和部署远端，但是在本地修改时，修改配置内容经常出错（按照教程，在win上不会出错，即使出错恢复原状就可解决，但是在Mac上却不行），出错时显示代码为（截取前后，中间内容太多）：
## 开头
![image.png](https://upimage.alexhchu.com/2020/08/13/7e0519985d8c4.png)
## 结尾
![image.png](https://upimage.alexhchu.com/2020/08/13/5d46cabd05168.png)
如需查看全部代码辛苦联系一下 :whee:

**Comment by xaoxuu** [comment]
`_config.yml` 修改出错了，建议不要一次改那么多东西，一次改一点，报错了就知道改的格式不对。

**Comment by tzblog** [comment]
@xaoxuu 好的，那请问一下出现这种情况怎么办呢？之前都是直接把整个blog文件删了把以前备份的拿来重新弄

**Comment by xaoxuu** [comment]
把主题的 _config.yml 还原就行

**Comment by tzblog** [comment]
@xaoxuu 
更换了之后hexo g出现这种情况
![image](https://user-images.githubusercontent.com/61815620/90089619-6766c080-dd54-11ea-99f5-76bc108bca18.png)

如果无视，继续hexo s出现的还是之前的问题

**Comment by tzblog** [comment]
ERROR TypeError: /Users/qakj-04/tzblog/themes/volantis/layout/index.ejs:1
 >> 1| <%- partial('_pre') %>
    2| <div class='l_main<%- page.sidebar == false ? ' no_sidebar' : '' %>'>
    3|   <%- partial('_partial/archive') %>
    4| </div>

**Comment by xaoxuu** [comment]
建议先走一遍自检流程：重新提一下 issue 按照 issue 模版里的提示操作一遍定位问题。

**Comment by xaoxuu** [comment]
https://github.com/volantis-x/hexo-theme-volantis/issues/new/choose

**Comment by tzblog** [comment]
好的，谢谢了
