### ISSUE TITLE
我是使用的应该是2.0版本，在使用{% span red, 红色%}有的时候渲染不出来

### ISSUE THREAD

**Issue by shiaqiya** [volantis-x/hexo-theme-volantis#437]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

A. 能正常运行，代表主题和当前环境配置都没有问题。
B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

- [ ] 测试结果是：A or B

### 截图

<details><summary>相关截图</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by MHuiG** [comment]
`有的时候`是指什么

**Comment by shiaqiya** [comment]
在同一篇博客中，上面还能正常显示红色，接着下一个就不是了，同一篇中，有的时候都能渲染，有的时候只有个别能渲染成功

**Comment by shiaqiya** [comment]
https://codeaqi.top/2020/07/20/mysql-zhi-shi-dian-chuan-lian/index.html?_sw-precache=1159cfa83a4b13567c9ace3fa36173e4
就比如这个，第二个标题，操作数据库

**Comment by MHuiG** [comment]
检查一下是不是少了换行符

**Comment by shiaqiya** [comment]
> 检查一下是不是少了换行符

{% span red, 红色%} 我记得解释文档中没有提到换行符，我去试试

**Comment by shiaqiya** [comment]
> 检查一下是不是少了换行符

还是没有渲染成功，新版本我还没有用不知道会不会出这样的小问题

**Comment by MHuiG** [comment]
可以提供一下markdown版本的原始文章（.md文件）吗

**Comment by shiaqiya** [comment]
当然可以

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: H<mailto:notifications@github.com>
发送时间: 2020年8月13日 22:29
收件人: volantis-x/hexo-theme-volantis<mailto:hexo-theme-volantis@noreply.github.com>
抄送: 阿琪<mailto:shiaqiya@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [volantis-x/hexo-theme-volantis] 我是使用的应该是2.0版本，在使用{% span red, 红色%}有的时候渲染不出来 (#437)


可以提供一下原始文章的markdown版本

―

**Comment by shiaqiya** [comment]
> 可以提供一下markdown版本的原始文章（.md文件）吗

我发给你了，不知道你有没有收到

**Comment by MHuiG** [comment]
额😓，你可以上传到一个开源的github仓库里

**Comment by MHuiG** [comment]
> > 可以提供一下markdown版本的原始文章（.md文件）吗
> 
> 我发给你了，不知道你有没有收到

没有收到

**Comment by shiaqiya** [comment]
> > > 可以提供一下markdown版本的原始文章（.md文件）吗
> > 
> > 
> > 我发给你了，不知道你有没有收到
> 
> 没有收到

能给我你的qq邮箱吗，我发到你邮箱里面，微软的邮箱没用过，没发过去

**Comment by MHuiG** [comment]
thepie@foxmail.com

**Comment by shiaqiya** [comment]
发过去了

**Comment by MHuiG** [comment]
收到了，我回去测试一下

**Comment by shiaqiya** [comment]
> 收到了，我回去测试一下

麻烦您了

**Comment by MHuiG** [comment]
https://volantis.js.org/scp/scp-437/
放到官网中测试，{% span red, 红色%}标签是正常的

**Comment by shiaqiya** [comment]
> https://volantis.js.org/scp/scp-437/
> 放到官网中测试，{% span red, 红色%}标签是正常的

嗯，我看到了，有机会的话，我用新版主题吧

**Comment by xaoxuu** [comment]
1. 写法上： %} 前后都要有空格
2. 在上方贴出 package.json 内容

**Comment by shiaqiya** [comment]
> 1. 写法上： %} 前后都要有空格
> 2. 在上方贴出 package.json 内容

$ npm ls --depth 0
hexo-site@0.0.0 C:\blog
+-- aplayer@1.10.1
+-- UNMET PEER DEPENDENCY hexo@4.2.1
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-offline@1.0.0
+-- hexo-permalink-pinyin@1.1.0
+-- hexo-prism-plugin@2.3.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-tag-aplayer@3.0.4
+-- hexo-wordcount@6.0.1
`-- live2d-widget-model-shizuku@1.0.5

npm ERR! peer dep missing: hexo@^3.2.2, required by hexo-offline@1.0.0

**Comment by shiaqiya** [comment]
> https://volantis.js.org/scp/scp-437/
> 放到官网中测试，{% span red, 红色%}标签是正常的

好了，刚刚我安装了

**Comment by shiaqiya** [comment]
刚刚，我尝试了你们的3.0版本，在本地已经渲染成功了！

**Comment by xaoxuu** [comment]
好的，最好 hexo 也升级到 5.0.2
