### ISSUE TITLE
我找到了一个代码高亮的插件prism_plugin，但有的时候行号渲染不成功

### ISSUE THREAD

**Issue by shiaqiya** [volantis-x/hexo-theme-volantis#438]
### 第一步：查阅文档 

- [ ] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [ ] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档 中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

A. 能正常运行，代表主题和当前环境配置都没有问题。
B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

- [ ] 测试结果是：A or B

### 截图

<details><summary>相关截图</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by Reqwey** [comment]
highlightjs他不香吗

**Comment by shiaqiya** [comment]
说的也是，highlightjs就很好
