### ISSUE TITLE
n.0 极速模式

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#440]
n.0 版本以优化和重构为主。

https://github.com/volantis-x/hexo-theme-volantis/projects/4

**Comment by inkss** [comment]
（4.0 上天模式 🚀

**Comment by xaoxuu** [comment]
这个放在「导航栏」「封面」重构之后

**Comment by xaoxuu** [comment]
合并到 6.0 的计划中
