### ISSUE TITLE
list的layout无法正常渲染，页面列表的文章为空

### ISSUE THREAD

**Issue by zjcscut** [volantis-x/hexo-theme-volantis#442]
## 如何复现这个问题

- [x] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。
- [x] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

1. 新建一个目录`source/Spring专栏`
2. 新建一篇文章`hexo new post 测试Spring专栏`
3. `测试Spring专栏.md`里面的`front-matter`添加`group: Spring专栏`
4. `hexo clean & hexo g & hexo s`重启后发现`localhost:4000/Spring专栏`的文章列表为空

下面截图是我拷贝了list.ejs新建了一个新的layout叫album，不过功能和内容是一样的。

### 截图

<details><summary>相关截图:</summary>

![bug](https://user-images.githubusercontent.com/13879735/90305494-0bd43880-def6-11ea-8629-dce2f98007d1.png)

![20200815124842](https://user-images.githubusercontent.com/13879735/90305498-1098ec80-def6-11ea-9f1c-423e15076576.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件
```yml
在这里粘贴 `blog/_config.yml` 中修改过的部分
```

#### 主题配置文件
```yml
在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分
```

#### node.js & npm
```
在这里粘贴 `node -v && npm -v` 输出的信息
```

#### package.json
```
在这里粘贴 `npm ls --depth 0` 输出的信息
```

</details>

**Comment by zjcscut** [comment]
大致原因找到了，site.posts变量没有拿到所有的文章，原因未知：

![20200815130431](https://user-images.githubusercontent.com/13879735/90305735-0841b100-def8-11ea-9e12-1b7209b1e9db.jpg)

**Comment by inkss** [comment]
你图中圈红线的是 `site.pages` 所有分页呀

**Comment by zryyyy** [comment]
我的分类页标签页好像也不能渲染

**Comment by xaoxuu** [comment]
1. 你的操作只能证明 “album” 无法显示 spring专栏 文件夹下的页面，跟 list 是否有bug无关联。建议走帮助流程
2. 你需要把用于显示列表的那个md放到正确的位置。
3. 你需要检查一下有多少md 的 front-matter 中有 group: Spring专栏
4. list 曾经有过bug并修复了，和你提的这个无关，不过可以看到你用的这个是旧的版本

**Comment by zjcscut** [comment]
@xaoxuu 好
