### ISSUE TITLE
想要一个极简的基于Leancloud的访问统计功能

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#444]
## busuanzi

busuanzi的速度不稳定，时不时就会突然变得很慢。

## Leancloud

leancloud用来统计页面和全站访问数应该是有优势的，一方面速度比较快，另一方面也可以自己修改数据，不用因为改一下地址就一切从头开始。

## Valine

Valine 中已经集成了页面统计功能，但是：

1. 和评论耦合起来了，必须使用Valine才可以统计，必须评论加载了才可以统计。
2. 缺失了全站统计。

所以变成了很鸡肋的功能。

希望有大佬可以做一个功能完备且没有冗余的基于Leancloud的访问统计插件。

**Comment by inkss** [comment]
> https://github.com/fluid-dev/hexo-theme-fluid/blob/master/layout/_partial/plugins/leancloud.ejs

这种写法和引入 AV 对象那种有什么区别啊？

<blockquote><img src="https://avatars2.githubusercontent.com/u/55058393?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/fluid-dev/hexo-theme-fluid">fluid-dev/hexo-theme-fluid</a></strong></div><div>:ocean: 一款 Material Design 风格的 Hexo 主题 / An elegant Material-Design theme for Hexo - fluid-dev/hexo-theme-fluid</div></blockquote>

**Comment by inkss** [comment]
@MHuiG 这只机器人？？？ `edited by unfurl-links`   迷惑行为

**Comment by xaoxuu** [comment]
这个少引用一个js吧
