### ISSUE TITLE
最新版本的主题 好像有点问题

### ISSUE THREAD

**Issue by 82kg** [volantis-x/hexo-theme-volantis#45]
https://mi20.top/article/20190130docker_centos.html  请看此文章，

多了很多的 [object Object] [object Object]

**Comment by xaoxuu** [comment]
请看 [1.1.0](https://github.com/xaoxuu/hexo-theme-material-x/releases) 版本更新日志。

**Comment by 82kg** [comment]
@xaoxuu 好啦，谢谢
