### ISSUE TITLE
请问这个文章怎么设置阅读量的?

### ISSUE THREAD

**Issue by XiaoYaoXiaoYao** [volantis-x/hexo-theme-volantis#458]
### 在配置中都有设置了
![](https://fffffffffffffffffffffff.oss-cn-beijing.aliyuncs.com/Snipaste_2020-08-24_11-36-20.png)

还请大佬帮我看一看

**Comment by XiaoYaoXiaoYao** [comment]
![](https://fffffffffffffffffffffff.oss-cn-beijing.aliyuncs.com/Snipaste_2020-08-24_11-41-02.png)

**Comment by Reqwey** [comment]
去官网找关键词：meta

**Comment by xaoxuu** [comment]
这部分功能还在变动中，可以看更新日志，前几个版本中加入了不依赖valine的访问统计功能。更新到 master 最新代码，默认已经开启了。
