### ISSUE TITLE
关于 Disqus 反代

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#462]
不知道有没有大佬会

> https://blog.ichr.me/post/use-disqus-conveniently/
> https://blog.skk.moe/post/prevent-disqus-from-slowing-your-site/

**Comment by inkss** [comment]
DisqusJS 做到的是国内区域能浏览评论内容，但也只能浏览。*又不能回复还不如压根不看*

---

现有代码，判断 Disqus 可用性这个，是抄 DisqusJS 的，hhh~

**Comment by xaoxuu** [comment]
我觉得能看就好啊，大部分也就是看看不说话
