### ISSUE TITLE
建议封面加入视差滚动效果

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#463]
## 需求描述

https://www.jianshu.com/p/ea8867b25fe5

## 参考链接

https://github.com/pixelcog/parallax.js

**Comment by MHuiG** [comment]
这里需要一个封面切换过渡，现在是一闪一闪的

http://volantis-x.js.org/

<blockquote><img src="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon.ico" width="48" align="right"><div><strong><a href="http://volantis-x.js.org/">Volantis</a></strong></div><div>Volantis is a feature-rich and highly modular Hexo blog theme. Thanks to its powerful modularity, you can easily build a minimalist style blog, or you can build a large-scale comprehensive blog with multi-person collaboration and document modules based on the official website.</div></blockquote>
