### ISSUE TITLE
导航栏时不时闪烁

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#468]
## 如何复现这个问题

- [x] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。
- [x] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

### 复现地址：

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

- https://xaoxuu.com
- https://volantis.js.org

### 截图

<details><summary>相关截图:</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by inkss** [comment]
这里说的闪烁，是发生在页面跳转的时候吗？

**Comment by xaoxuu** [comment]
放在那里不动就会一直闪

**Comment by xaoxuu** [comment]
问题还是存在呀：
https://7.dusays.com/2020/10/14/c50379b5fe28d.mp4

**Comment by xaoxuu** [comment]
现在还多了个「导航栏上的文字出来有延迟」的问题，即先显示空白导航栏，然后才显示导航栏上的内容。

> 这个问题可能是网速慢导致的

**Comment by MHuiG** [comment]
https://7.dusays.com/2021/01/13/7ccbe069bbd58.gif

<blockquote></blockquote>
