### ISSUE TITLE
所有的小部件都不显示，是什么原因呢？

### ISSUE THREAD

**Issue by hongtanhao** [volantis-x/hexo-theme-volantis#47]
如果你发现 无法使用 或者效果与示例有较大区别，可以使用hexo官方提供的用于单元测试的博客应用本主题查看样式是否正常，对比_config.yml文件排查问题。

## 下载单元测试：

Hexo官方的单元测试博客： [https://github.com/hexojs/hexo-theme-unit-test.git](https://github.com/hexojs/hexo-theme-unit-test.git)。
如果你的系统是macOS，则可以使用hexo.sh脚本一键完成测试。

## 提问前请先认真阅读文档

文档：[https://xaoxuu.com/wiki/material-x/](https://xaoxuu.com/wiki/material-x/)

**Comment by xaoxuu** [comment]
与博客相关内容要写在博客主目录的配置文件里
文档：https://xaoxuu.com/wiki/material-x/
源码：https://github.com/xaoxuu/blog-example
