### ISSUE TITLE
文章目录定位有问题

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#470]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

文章页面的目录列表，点击其中的一个标题，没有正确的滑动到该标题所在的位置，而是滑到某个地方停止了。

### 复现地址

https://zoyua.cn/2016/09/08/blog/java/jvm/jvm-02/#%E6%9C%AC%E5%9C%B0%E6%96%B9%E6%B3%95%E6%A0%88%EF%BC%88Native-Method-Stacks%EF%BC%89

**注意我用红框标注的信息**

### 截图

<details><summary>相关截图</summary>

![Snipaste_2020-09-03_10-25-12](https://user-images.githubusercontent.com/59497690/92064291-c9ed3280-edcf-11ea-86ac-41b9767a47de.png)

</details>

### 浏览器、操作系统

Chrome、Windows10

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```
v12.16.3
6.14.4
```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```
hexo-site@0.0.0 C:\Users\Administrator\Desktop\zoyua.cn
+-- hexo@5.1.1
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-json-content@4.2.3
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-qrcode@1.0.2
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.1.0
+-- hexo-renderer-stylus@2.0.0
`-- hexo-server@2.0.0
```

</details>

**Comment by inkss** [comment]
图片懒加载导致 dom 高度发生了变化

**Comment by xaoxuu** [comment]
这 bug 一直都有，以前没懒加载的时候也有，我也不知道怎么办

折叠框、 tab 都会导致这个问题

如果不使用平滑滚动，不加任何处理，直接由浏览器定位到相应的 hook 位置，会不会正常呢？

**Comment by inkss** [comment]
会，你看我现在的网站，定位还行。但是也可以试试兼容 [链接](https://inkss.cn/article/linux/481358a6.html#%E5%9B%9B%E3%80%81%E5%90%8E%E7%BB%AD)

**Comment by xaoxuu** [comment]
挺好的，那就去掉滚动定位吧

**Comment by inkss** [comment]
顺便，优化一下 app.js ，仅 scroll 的监听就 5 个了

**Comment by ghost** [comment]
@xaoxuu @inkss 请问这个问题大约多久能修复呢？现在用着体验确实不好。。

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/commit/9a79f5b703e41454fe49b02b326b91fb3e82d4a3
