### ISSUE TITLE
增加小图标建议

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#474]
## 需求描述

![Snipaste_2020-09-04_10-08-41](https://user-images.githubusercontent.com/59497690/92191615-ccff2600-ee96-11ea-8eb8-32336f7cc19d.png)

site_footer 里的 social 图标能否再多几个国内的，比如网易云，微信，QQ，Bilibili，微博，知乎，抖音等

**Comment by xaoxuu** [comment]
那个是示例。。。

**Comment by xaoxuu** [comment]
图标是可以自己任意加的。为了避免误解，已经把示例从主题配置文件中删除了。

**Comment by ghost** [comment]
@xaoxuu 主要是我觉得这几个图标的样式挺好看的，不知道在哪里能找到其它类似的图标

**Comment by xaoxuu** [comment]
https://www.flaticon.com/

**Comment by ghost** [comment]
多谢！
