### ISSUE TITLE
优化 app.js

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#476]
- [ ] 去掉目录定位的平滑滚动效果
- [x] 去掉无关紧要的滚动监听
- [x] 去掉 nprogress

**Comment by inkss** [comment]
能不能通过屏幕宽度，简单区分是否移动端。`< 500` ，好比如桌面端的时候，无需处理移动端的事件绑定，反之亦然。

https://github.com/volantis-x/hexo-theme-volantis/blob/f2a0400c6eebc6d47e7117f1ee0f20ec9ba577a6/source/js/app.js#L206-L231

另外，在现有的 pjax 兼容思路中，因为无法处理到 front-matter 的值，使用的是 data.ejs 这个文件。可不可以尝试一下将这里遍历构建成对象呢，统一处理，Pjax 兼容时不再主动取值，而且直接读取对象。

```js
const front-matter = {
  layout: '<%= page.layout %>',
  title: '<%= page.title %>',
  update: '<%= page.update %>'
  //...
}


const {layout} = front-matter;


// 或者，能直接取 page 吗？

```

而在其它插件的兼容方面，重写为插件主动兼容 pjax ，按照独立的事件监听来处理。

然后，app.js 那边，pjax 造成影响主要是重载区域内的的监听事件丢失，但是如果简单粗暴的调用现有的函数，又会造成重载区域外的事件监听，多花了些功夫去重写解绑，这部分还是得重新写下，函数封装这方面。

------

**Comment by inkss** [comment]
另外，在现有的 pjax 兼容思路中，因为无法处理到 front-matter 的值，使用的是 data.ejs 这个文件。可不可以尝试一下将这里遍历购件成对象呢，统一处理，Pjax 兼容时不再主动取值，而且直接操作对象。

```js
const front-matter = {
  layout: 'page',
  title: 'xxx'
  //...
}

```

**Comment by xaoxuu** [comment]
我觉得可以
