### ISSUE TITLE
友链头像显示不全

### ISSUE THREAD

**Issue by novaELLIAS** [volantis-x/hexo-theme-volantis#477]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

pjax和懒加载冲突(推测)导致友链头像加载不全

## 环境信息 

``` plain
hexo: 5.1.1
hexo-cli: 4.2.0
os: Windows_NT 10.0.18363 win32 x64
node: 14.8.0
v8: 8.4.371.19-node.12
uv: 1.38.1
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 83
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0
```

### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by guguliu** [comment]
我发的这个底下有解决办法：
https://github.com/volantis-x/hexo-theme-volantis/issues/475

使用的主题版本：4.0.0-rc.2

**Comment by novaELLIAS** [comment]
> 我发的这个底下有解决办法：
> #475
> 
> 使用的主题版本：4.0.0-rc.2

这样一来就必须使用占位图片, 并且没有模糊加载效果.. 如果像 `onlyypost` 选项那样加一个例外似乎能好一点, 能在 `front-matter` 里面加入此页是否使用懒加载的字段就更好了..

**Comment by xaoxuu** [comment]
请更新最新的代码看看

**Comment by novaELLIAS** [comment]
博客代码4.0.0
更新后没什么变化

**Comment by xaoxuu** [comment]
最新的代码是  https://github.com/volantis-x/hexo-theme-volantis/commits/master
