### ISSUE TITLE
首页排版异常

### ISSUE THREAD

**Issue by AnotiaWang** [volantis-x/hexo-theme-volantis#478]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [ ] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述
主页的 网站名 字体偏大，手机上出现排版异常：网站名称占用很大空间、Dock 栏遮挡文章列表。

## 环境信息 

Hexo、nodejs 等皆为最新版
静态网页：Coding Pages

### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [x] 文档官网源码本地运行不存在异常。复现地址：blog.anotia.top

### 截图

<details><summary>相关截图</summary>

![Screenshot_20200905-215903946~2](https://user-images.githubusercontent.com/62269186/92306652-5744a880-efc3-11ea-94a0-ed0d7229224f.jpg)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by xaoxuu** [comment]
nodejs 建议的版本是 最新的 LTS 版本，即 `12.18.3` 太新的版本也可能会有问题。

**Comment by AnotiaWang** [comment]
> nodejs 建议的版本是 最新的 LTS 版本，即 `12.18.3` 太新的版本也可能会有问题。

我正在使用的是最新版本
```
$ node -v
v12.18.3
```

**Comment by AnotiaWang** [comment]
看样子是缺少volantis 的 npm依赖，不过我是从GitHub clone 下来的，应该问题不大吧
```
$ npm ls --depth 0
hexo-site@0.0.0 /data/data/com.termux/files/home/Blog
├── core-js@3.6.5
├── hexo@5.1.1
├── hexo-algoliasearch@0.4.2
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-indexed@1.2.1
├── hexo-generator-json-content@4.2.3
├── hexo-generator-search@2.4.0
├── hexo-generator-searchdb@1.3.2
├── hexo-generator-sitemap@2.1.0
├── hexo-generator-tag@1.0.0
├── hexo-html-minifier@1.0.0
├── hexo-lazyload-image@1.0.9
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-pug@1.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
├── UNMET DEPENDENCY hexo-theme-volantis@4.0.0-rc.2
├── hexo-uglify@1.1.0
├── hexo-wordcount@6.0.1
├── minimatch@3.0.4
└── npm@6.14.8

npm ERR! missing: hexo-theme-volantis@4.0.0-rc.2, required by hexo-site@0.0.0
```

**Comment by xaoxuu** [comment]
如果是 clone 的，建议把 package.json 中的 volantis 去掉

**Comment by AnotiaWang** [comment]
> 如果是 clone 的，建议把 package.json 中的 volantis 去掉

已经去掉了
排版的问题怎么解决呢

**Comment by xaoxuu** [comment]
这就是在帮您查找排版问题的原因呀，去掉了之后还不行吗？

**Comment by AnotiaWang** [comment]
> 这就是在帮您查找排版问题的原因呀，去掉了之后还不行吗？

不行

**Comment by xaoxuu** [comment]
![image](https://user-images.githubusercontent.com/16400144/92549255-69586c80-f28b-11ea-972e-cd6b4b27a00e.png)

这个是 logo 字体过大导致的，可以更新到最新的主题代码看看。

> 您现在使用的主题是 4.0.0-rc.2 版本，在新版中已经调小了。 a88755dd865ff3ca1cf715cf59ced987e7af3c02

**Comment by AnotiaWang** [comment]
> ![image](https://user-images.githubusercontent.com/16400144/92549255-69586c80-f28b-11ea-972e-cd6b4b27a00e.png)
> 
> 这个是 logo 字体过大导致的，可以更新到最新的主题代码看看。
> 
> > 您现在使用的主题是 4.0.0-rc.2 版本，在新版中已经调小了。 a88755dd865ff3ca1cf715cf59ced987e7af3c02

我重新 clone 了一遍，在 hexo cl && hexo g 的时候报错了，信息有点长，放在这里： https://note.ms/volantis
我是在手机上操作的，出错之后用电脑又试了一遍，也报错了

**Comment by xaoxuu** [comment]
@Colsrch 你看看是不是还有问题啊

**Comment by Colsrch** [comment]
在我手机上还是排版异常

**Comment by xaoxuu** [comment]
@Colsrch https://note.ms/volantis

<blockquote><img src="https://note.ms/meta/app.png" width="48" align="right"><div><img src="https://note.ms/meta/favicon.png" height="14"> Note.ms</div><div><strong><a href="https://note.ms/volantis">Note.ms</a></strong></div><div>Take notes easily</div></blockquote>

**Comment by Colsrch** [comment]
这个啊，我后面改了鸭

**Comment by Colsrch** [comment]
#493

**Comment by AnotiaWang** [comment]
解决了，谢谢大佬~
