### ISSUE TITLE
some advice

### ISSUE THREAD

**Issue by ZeddYu** [volantis-x/hexo-theme-volantis#48]
建议集成文章【字数统计】、【阅读时长】的功能

**Comment by xaoxuu** [comment]
我感觉这没什么用啊

**Comment by ZeddYu** [comment]
> 我感觉这没什么用啊

个人觉得这是个非常友好且人性化的提示，至少能预估大概多少分钟读完，特别是现在时代人们碎片化的时间管理，就比较需要对自己看的内容有个大致的估计，个人非常喜欢看以下文章有没有这类提示，有的话预估一下时间，看什么时候比较适合阅读，有这类提示的文章就显得格外的友好。
纯属个人意见哈～

**Comment by xaoxuu** [comment]
要是有人提交代码我可以合并进来，但是我自己懒得做了
