### ISSUE TITLE
能否分享一下作者个人博客的_config.yml，很喜欢作者博客的简约风格

### ISSUE THREAD

**Issue by zuruncai** [volantis-x/hexo-theme-volantis#483]
请问能否分享一下作者个人博客的_config.yml，很喜欢作者博客的简约风格，十分感谢 ：）

**Comment by xaoxuu** [comment]
[_config.volantis.yml.zip](https://github.com/volantis-x/hexo-theme-volantis/files/5180686/_config.volantis.yml.zip)

**Comment by zuruncai** [comment]
> [_config.volantis.yml.zip](https://github.com/volantis-x/hexo-theme-volantis/files/5180686/_config.volantis.yml.zip)

我将_config.volantis.yml复制到了_conifg.yml旁边，但hexo serve看，样式没有变化，按理说_config.volantis.yml的优先级不是高吗？是我操作出了问题吗？

**Comment by xaoxuu** [comment]
需要 Hexo 5.0 以上，并且 Volantis 的 master 分支最新代码。

**Comment by zuruncai** [comment]
> 需要 Hexo 5.0 以上，并且 Volantis 的 master 分支最新代码。

我的hexo是最新的5.1.1，然后用的mac的脚本"curl -s https://volantis.js.org/start | bash"搭建，用脚本会自动抓取volantis的最新代码吗？

<blockquote></blockquote>

**Comment by xaoxuu** [comment]
那个安装的是稳定版的，应该是没问题的。

**Comment by xaoxuu** [comment]
你看看 package.json 中的 volantis 版本是多少

**Comment by Colsrch** [comment]
theme_config的优先级最高，其次是_config.volantis.yml

**Comment by zuruncai** [comment]
> theme_config的优先级最高，其次是_config.volantis.yml

原来如此，谢谢啦
