### ISSUE TITLE
nav-bar的width能否100% && 阅读文章(向下滚动)时，nav-bar能否隐藏/提高透明度 && 阅读文章时，侧边栏本文目录能够选择开启or隐藏

### ISSUE THREAD

**Issue by zuruncai** [volantis-x/hexo-theme-volantis#485]
## 需求描述
nav-bar的width能否100% && 
阅读文章(向下滚动)时，nav-bar能否隐藏or提高透明度 && 
阅读文章时，侧边栏本文目录能够选择开启or隐藏

**Comment by xaoxuu** [comment]
设置为 max 可以像 vuejs.org 那样 100% 宽度布局
