### ISSUE TITLE
主题文档刷新时回退到了v2版本

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#487]
@xaoxuu 访问主题文档 [https://volantis.js.org/](https://volantis.js.org/) 的时候，有时候会进入到 v2 版本的页面，ctrl+F5 有回到 v4 版本，有一段时间都是这样，我一直以为是我浏览器的问题

**Comment by Colsrch** [comment]
请打开主题文档网站后，打开`开发人员工具`，选择`应用程序` → `清除存储` ，将缓存清除即可

**Comment by ghost** [comment]
@Colsrch 你的意思不还是和ctrl+f5强刷一样嘛，问题是清掉缓存访问正常后为啥刷新又进到v2的页面了呢

**Comment by ghost** [comment]
[https://drive.google.com/file/d/1NM7PJgv7CNG1U4tYLqeotWnE4C_MBye_/view?usp=sharing](https://drive.google.com/file/d/1NM7PJgv7CNG1U4tYLqeotWnE4C_MBye_/view?usp=sharing)

<blockquote><img src="https://lh5.googleusercontent.com/Ixy-6tYmQv-rzHFXcMx0GhMYQm2Vc8s-LpVVWh_1yQItpjHo1qRkukX7cgIhaMA=w1200-h630-p" width="48" align="right"><div>Google Drive</div><div><strong><a href="https://drive.google.com/file/d/1NM7PJgv7CNG1U4tYLqeotWnE4C_MBye_/view?usp=sharing&usp=embed_facebook">bug.mp4</a></strong></div></blockquote>

**Comment by Colsrch** [comment]
尝试清除缓存后，重新打开主题文档

**Comment by Colsrch** [comment]
![image](https://user-images.githubusercontent.com/58458181/92459508-644add00-f1f9-11ea-8190-7ab01d113af2.png)

**Comment by ghost** [comment]
嗯，生效了
