### ISSUE TITLE
[已解决]Mathjax不支持pjax加载

### ISSUE THREAD

**Issue by AK-DREAM** [volantis-x/hexo-theme-volantis#488]
启用了pjax，但是只有第一个进入的页面能渲染公式 后面pjax加载的页面就不渲染公式了

**Comment by inkss** [comment]
@Linhk1606 这位小屁孩的 [博客](https://blog.lhkstudio.me/) 中，公式正常的，建议自测一下吧。

------

### 测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [ ] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

**Comment by AK-DREAM** [comment]
我刚才又试了一下，如果直接使用原来的 blog/themes/volantis/layout/_third-party/pjax/index.ejs 的话 我这边pjax加载是无法加载出mathjax的，要刷新才有

当然也不排除我之前什么时候改了些不该改的东西给它整坏了

我是在上面那个index.ejs的文件里这个函数`document.addEventListener('pjax:complete', function ()`
里面自己写了个加载mathjax的函数来解决的 就可以正常加载了

但是不知道为什么原本的加载不出来

**Comment by AK-DREAM** [comment]
又试了一下 似乎是因为有时候加载速度比较慢 我误以为是没有加载或者加载失败了。。。原本的确实是可以加载出来的 看来是我这边出问题了

**Comment by AK-DREAM** [comment]
blog/themes/volantis/layout/_third-party/math/mathjax/script.ejs 中第47行的`MathJax.startup.document.state(0);` 显示为`undefined`

**Comment by Reqwey** [comment]
...?

**Comment by Reqwey** [comment]
我的版本可旧了,建议用 @MHuiG 这位~~大屁孩~~的 [博客](https://blog.mhuig.top/posts/xa6297acc.html)

**Comment by Reqwey** [comment]
话说, 他不会比我还旧吧

**Comment by AK-DREAM** [comment]
原因已经找到，因为我在hexo中启用了`hexo-renderer-mathjax`插件，导致mathjax发生冲突，出现问题

卸载插件后mathjax即可正常运行

**Comment by MHuiG** [comment]
> 我的版本可旧了,建议用 @MHuiG 这位~大屁孩~的 [博客](https://blog.mhuig.top/posts/xa6297acc.html)

我直接卸载了主题的mathjax，还记得吧

**Comment by Reqwey** [comment]
不记得了
