### ISSUE TITLE
更好的donate样式 [捐赠按钮页修改建议]

### ISSUE THREAD

**Issue by novaELLIAS** [volantis-x/hexo-theme-volantis#489]
## 需求描述

更好的 `donate` 样式:
[https://github.com/Kaiyuan/sponsor-page](https://github.com/Kaiyuan/sponsor-page)
非常地好看且直接, 没有必要在同时使用几个二维码的情况下为每个图片配字.
在 `material-x` 中易于实现但在新版主题中样式和导航栏冲突(推测), 希望能在下一个版本中整合一下.

## 参考链接

[https://www.itrhx.com/](https://www.itrhx.com/)

#554

可参考开源项目[sponsor-page](https://github.com/Kaiyuan/sponsor-page)，该项目支持两种捐赠按钮样式。

1、simple
![](https://camo.githubusercontent.com/81b5a58e19fdb3a278e49bf7520970ed5a5b91240e9070e9889a342029a3e428/68747470733a2f2f692e696d6775722e636f6d2f4179414d6b6a522e676966)

2、Drinks
![](https://camo.githubusercontent.com/9cff31a8a217b9cbd82b160fd4a18f9cb30a6e455bae19fcad02d139dac93211/68747470733a2f2f692e696d6775722e636f6d2f4430516578426c2e676966)

https://kelecn.top/posts/34795/

**Comment by heson525** [comment]
这个好，开整。

**Comment by xaoxuu** [comment]
哪里冲突了
