### ISSUE TITLE
建议新增本文目录中的伸缩功能

### ISSUE THREAD

**Issue by XuanMichael** [volantis-x/hexo-theme-volantis#496]
目前版本的本文目录是展开的，如果加入很多多级标题，会显得很乱。
所以建议新增伸缩功能。

**Comment by Deecyn** [comment]
+1。还有「支持只激活展示当前所在大类目录分级 [#297](https://github.com/volantis-x/hexo-theme-volantis/issues/297)」的功能。❤️
