### ISSUE TITLE
希望新增 根据目录自动生成分类以及标签

### ISSUE THREAD

**Issue by A2Data** [volantis-x/hexo-theme-volantis#497]
## 需求描述
1、hexo new post -p Python/Anaconda/xxxx "Anaconda"

希望可以自动生成 如图所示
![image](https://user-images.githubusercontent.com/39373008/92882950-fa257880-f442-11ea-8773-a640d7a732ae.png)

**Comment by A2Data** [comment]
补充参考链接:
https://7.dusays.com/2020/09/11/489e18ffc7fee.png

<blockquote></blockquote>

**Comment by MHuiG** [comment]
@A2Data hexo new post 这个命令与主题无关。

你需要到这里提feature request

https://github.com/hexojs/hexo/issues

<blockquote><img src="https://avatars0.githubusercontent.com/u/6375567?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/hexojs/hexo">hexojs/hexo</a></strong></div><div>A fast, simple & powerful blog framework, powered by Node.js. - hexojs/hexo</div></blockquote>
