### ISSUE TITLE
建议相关文章显示文章的：headimg，这样会让我特意配的文章图更有意义

### ISSUE THREAD

**Issue by Tikas** [volantis-x/hexo-theme-volantis#498]
## 需求描述

现在的相关文章显示的预览图，是取文章内容的首个图片

然而，我特意为这文章所以设计的 headimg 配图，却没有显示在 “相关文章” 里。

每当我查看到相关文章时，都会显示杂乱了些

感谢大大的主题，感谢所有的开发者们，如果你们是女的，我一定会追求你们！

**Comment by xaoxuu** [comment]
是可以的
https://github.com/tea3/hexo-related-popular-posts/issues/29

Edit in `blog/_config.yml`:
```yaml
popularPosts:
  eyeCatchImageAttributeName: headimg
```

**Comment by Tikas** [comment]
太棒了！转链接点进去一看，竟然是全英文交流！强大的 xaoxuu，支撑了我全面的内心满足感！因为我只需要拿来应用就行了，感谢 tea ！

**Comment by xaoxuu** [comment]
🤝
