### ISSUE TITLE
floatable卡片样式效果不明显，希望增强

### ISSUE THREAD

**Issue by gyf9835** [volantis-x/hexo-theme-volantis#504]
## 需求描述
卡片设置为floatable样式时，必须搭配shadow样式才能看出浮出效果，如果没有shadow样式什么都看不到
对于设置了背景图片的页面，浮出效果基本无法察觉
希望可以增强浮出样式的效果

**Comment by xaoxuu** [comment]
默认是简约风格，如不喜欢请自行定制：

https://github.com/volantis-x/hexo-theme-volantis/blob/e5888626eccb03e85496a6401fef16a0237c0634/source/css/_defines/effect.styl#L4
