### ISSUE TITLE
md文件生成后渲染在网页留有空白

### ISSUE THREAD

**Issue by cvenwu** [volantis-x/hexo-theme-volantis#506]
## Expected and actual performance

自己编写md文件并使用`hexo s`本地预览，页面显示中有很多空白 比如自己部署的[博客](www.sivan.tech)也有很多空白。打开了vscode将很多空白行去掉之后也没有作用，

## How to reproduce this problem

1. ![sMZF6h](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/sMZF6h.png)
2. ![J2hHhq](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/J2hHhq.png)

自己在vscode中编辑之后的文件：
![r4OwVy](https://cdn.jsdelivr.net/gh/sivanWu0222/ImageHosting@master/uPic/r4OwVy.png)

- [ ] No related issues can be searched in Issues.
- [ ] Upgrade the theme to the latest version.
- [ ] This problem also exists on the official website; or download the source code of the theme’s official website and run it. After certain steps, this problem can be reproduced.

**Steps to reproduce**

- [ ] Detailed reproduction steps

1. xxx
2. xxx
3. xxx

- [ ] Specific code location

- [ ] Great, I can provide bug patches

### URL

- [ ] There is an exception in the local operation of the official source code of the document.
- [ ] There is no exception in the local operation of the official source code of the document. Please give the duplicate address and source code repository address _________________

### Screenshots

<details><summary>Screenshots</summary>

</details>

### Configuration file 
<details><summary>Configuration Files</summary>

#### Site Config

Paste here the modified part in `blog/_config.yml`

```yml


```

#### Theme Config

Paste here the modified part in `themes/volantis/_config.yml`

```yml


```

#### node.js & npm

Paste the output by `node -v && npm -v`

```


```

#### package.json

Paste the output by `npm ls --depth 0` here

```


```

</details>

**Comment by xaoxuu** [comment]
**您可以随便打开一个主流网站，看看它们的标题和段落有没有留白。**

例如：https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/

![image](https://user-images.githubusercontent.com/16400144/93991674-21733280-fdbf-11ea-964f-0e348bbbddc1.png)

又如：https://vuejs.org/v2/cookbook/

![image](https://user-images.githubusercontent.com/16400144/93991822-4cf61d00-fdbf-11ea-8b0c-1c0508860dc2.png)


<blockquote><img src="/favicon.ico?51002006191" width="48" align="right"><div><strong><a href="https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/">Themes - iOS - Human Interface Guidelines - Apple Developer</a></strong></div><div>Learn about designing apps for iOS.</div></blockquote>
<blockquote><img src="https://vuejs.org//images/logo.png" width="48" align="right"><div><strong><a href="https://vuejs.org/v2/cookbook/">Introduction — Vue.js</a></strong></div><div>Vue.js - The Progressive JavaScript Framework</div></blockquote>

**Comment by cvenwu** [comment]
👌，我以为是bug
