### ISSUE TITLE
点击文章元数据区域中的评论统计，无法进行跳转到评论区

### ISSUE THREAD

**Issue by XuxuGood** [volantis-x/hexo-theme-volantis#511]
## 问题描述
点击文章元数据区域中的评论统计，无法进行跳转到评论区

### 截图

![image](https://user-images.githubusercontent.com/45960164/95549543-11538800-0a3a-11eb-8b97-880039bab635.png)

**Comment by xaoxuu** [comment]
我看了下你的文章是可以跳转的呀

**Comment by XuxuGood** [comment]
是我自己调了调，也不太友好，源码是不好用的

**Comment by MHuiG** [comment]
经测试这个功能是正常的，例如这个页面

https://w4j1e.xyz/friends/#comments

https://colsrch.cn/posts/9eae9d7b/#comments

<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://w4j1e.xyz/friends/#comments">优质友链 - W4J1e's blog</a></strong></div></blockquote>
<blockquote><img src="https://cdn.jsdelivr.net/gh/Colsrch/CDN@master/favicon.webp" width="48" align="right"><div><strong><a href="https://colsrch.cn/posts/9eae9d7b/#comments">给你的博客实现自动夜间模式 - Colsrch'Blog</a></strong></div><div>Volantis主题用户可完全参照本文进行修改，其它主题用户看着改吧😂</div></blockquote>
