### ISSUE TITLE
持续集成 + 服务器

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#513]
## 现在遇到的问题

源码仓库A：
https://github.com/volantis-x/community

静态文件仓库B：
https://github.com/xaoxuu/volantis.js.org

静态文件仓库C：
git@xaoxuu.com:xaoxuu/volantis.git

GitHub Action 从 A -> B 正常，把对应的 deployKey 换成 C 的， A - C 就一直失败，提示没有权限。 https://github.com/volantis-x/community/runs/1251931440?check_suite_focus=true

```
ssh: connect to host ***.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
FATAL {
  err: Error: Spawn failed
      at ChildProcess.<anonymous> (/github/workspace/node_modules/hexo-deployer-git/node_modules/hexo-util/lib/spawn.js:51:21)
      at ChildProcess.emit (events.js:315:20)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
    code: 128
  }
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```

> 难道是 GitHub Action 只能 deploy 到 GitHub 的仓库吗？

## 其它的解决思路

依然 A -> B ，但是配置 hook 使得 B 发生更新的时候 C 自动同步（ B -> C ）。

**Comment by code004Accepted** [comment]
疑似connection timeout?

```
ssh: connect to host ***.com port 22: Operation timed out
fatal: Could not read from remote repository.
```
我这里ping xaoxuu.com 丢包率有个10%左右。。。

**Comment by code004Accepted** [comment]
Actions VM的结果：

![QQ截图20201111000623](https://user-images.githubusercontent.com/36566134/98699128-c4086480-23b1-11eb-839c-0fd9c9903e44.png)

emmm...或许您可以检查下github连过去的速度

**Comment by xaoxuu** [comment]
那是香港的服务器

**Comment by code004Accepted** [comment]
那就不清楚了😂

不过无论是站长工具的国际Ping还是我自己挂各国代理的速度都很快，所以应该不是您这边的问题😓

**Comment by xaoxuu** [comment]
CI 已修复，放弃使用服务器，继续使用 vercel.app 提供的托管服务。
