### ISSUE TITLE
题主是把fancybox去掉了吗

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#517]

**Comment by xaoxuu** [comment]
仍然支持，但不再是默认的了，需要使用gallery标签

**Comment by ghost** [comment]
不太理解是出于什么考虑，我觉得默认fancybox用着很方便，每次都要加标签太麻烦了

**Comment by xaoxuu** [comment]
默认图片自带 fancybox 会失去灵活性，并且大部分网站都没有这样做，例如苹果官网、vue官网等等。

平台型博客（简书、掘金等）是默认自带放大的，但是那类博客功能太少，原本就没有灵活性，所以不具有可比性。

主题相比那些平台的灵活性在于：
- 支持图片和视频框架，例如 https://xaoxuu.com/blog/2020-09-27-heartrate/
- 支持行内图片
- 支持插入按钮，并用图片作为按钮外观，例如 `[![](图片链接)](按钮链接)`
- 支持强大的 gallery 标签 https://volantis-x.js.org/tag-plugins/gallery/
- 支持懒加载

**大部分图片不需要放大也看得清，如果默认支持 fancybox 会使上述功能的实现代码变得异常复杂，得不偿失。**
