### ISSUE TITLE
友链无法起作用

### ISSUE THREAD

**Issue by uyplayer** [volantis-x/hexo-theme-volantis#519]
---
layout: links     # 必须
title: 友链   # 可选，这是友链页的标题
cover: true
links:
  - group: Programming
    icon: fas fa-user-tie
    desc: programming | technique
    items:
    - name: Tenleon      # 博客名
      avatar: https://cdn.jsdelivr.net/gh/izchin/TenLeonfiles@master/tenleon/imglogo01.png   # 头像链接
      url: http://tenleon.space      # 博客链接
      backgroundColor: '#3E74C9' # 卡片背景颜色
      textColor: '#fff'  # 卡片文字颜色
      tags: [Programming, Technique]    # 标签
      desc:
    - name: xaoxuu
      url: https://xaoxuu.com
      avatar: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-assets/avatar/avatar.png
      backgroundColor: '#87977F'
      textColor: '#EFEFEF' 
      tags: [Web,Design] 
    - name: volantis
      url: https://volantis.js.org/
      avatar: 
      backgroundColor: '#87977F'
      textColor: '#EFEFEF' 
      tags: [Web,Design]       
  - group: Paper
    icon: fas fa-user-tie
    desc: Academic paper | Paper
    items:
    - name: Paperweekly      
      avatar: http://www.paperweekly.site/static/img/logo.ce3391b.png   # 头像链接
      url: http://www.paperweekly.site      # 博客链接
      backgroundColor: '#3E74C9' # 卡片背景颜色
      textColor: '#fff'  #
      tags: [Paper]    
      desc:
    - name: Paperswithcode
      url: https://paperswithcode.com
      avatar: 
      backgroundColor: '#87977F'
      textColor: '#EFEFEF' 
      tags: [Paper]    # 标签
    - name: Readcube
      url: https://www.readcube.com
      avatar: https://green.readcube-cdn.com/assets/logos/large@2x-395291e0cf3047d38b928cbf18fb5708b0415c1adb2480953bcb2b6b5200721a.png
      backgroundColor: '#87977F'
      textColor: '#EFEFEF' 
      tags: [Paper]    # 标签            
---

> name : uyplayer
> avatar : https://s1.ax1x.com/2020/03/28/GktMjg.jpg
> url : https://uyplayer.pw
> tags : Python | NLP | ML | Linux | Web
> backgroundColor : #87977F
> textColor : #EFEFEF

**Comment by MHuiG** [comment]
https://volantis-x.github.io/page-settings/layout/#%E5%8F%8B%E9%93%BE%E9%A1%B5%E9%9D%A2

<blockquote><img src="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon.ico" width="48" align="right"><div><strong><a href="https://volantis-x.github.io/page-settings/layout/#%E5%8F%8B%E9%93%BE%E9%A1%B5%E9%9D%A2">Volantis: 页面布局模板 - Volantis</a></strong></div></blockquote>
