### ISSUE TITLE
最新版本文档仓库

### ISSUE THREAD

**Issue by MHuiG** [volantis-x/hexo-theme-volantis#521]
原来的文档仓库CI崩溃了,详见 #513。

新的文档仓库地址：https://github.com/volantis-x/volantis-x.github.io

最新版本文档链接： https://volantis-x.js.org

[v4](https://volantis-x.github.io/v4/getting-started/) ｜ [v3](https://volantis-x.github.io/v3/getting-started/) ｜ [v2](https://volantis-x.github.io/v2/getting-started/)

本地浏览：

```shell
git clone --recursive https://github.com/volantis-x/volantis-x.github.io.git && cd volantis-x.github.io && npm i && hexo s
```

===================================================================================

以下链接为4.1.2及以下版本,暂时停更。

https://volantis.js.org/

https://vlts.cc/

https://volantis.vercel.app/

**Comment by xaoxuu** [comment]
@MHuiG  我希望能在支持 CI 的同时用服务器提高官网 volantis.js.org 的访问速度，你知道怎么弄吗？

**Comment by xaoxuu** [comment]
CI 已修复，放弃使用服务器，继续使用 vercel.app 提供的托管服务。
