### ISSUE TITLE
建议_config.yml加入自定义代码功能

### ISSUE THREAD

**Issue by MCSeekeri** [volantis-x/hexo-theme-volantis#525]
## 需求描述
准确的说,建议在_config.yml开辟一个区域,放置一些需要自定义的代码。
毕竟轻度的自定义需要修改的文件也就那么几个,基本都是加入一行代码就完事。
比如
customhead: [代码]
customfooter: [代码]
这样既可以实现轻度自定义又不需要每次更新都手动改文件

## 参考链接
没有

**Comment by xaoxuu** [comment]
import可以实现
自己新加的代码写在单独的文件里，通过import字段引入。

**Comment by MCSeekeri** [comment]
我重新理了理思路...
应该是类似Butterfly的inject功能
https://butterfly.js.org/posts/ceeb73f/#Inject

比如我想加入谷歌字体API,之前唯一的方法是clone之后修改head.ejs,而加入这个功能之后就可以使用npm安装并只更改_config.ym

<blockquote><img src="https://cdn.jsdelivr.net/gh/jerryc127/CDN/img/Butterfly-docs-04-cover.png" width="48" align="right"><div>Butterfly</div><div><strong><a href="https://butterfly.js.org/posts/ceeb73f/">Butterfly 安裝文檔(四) 主題配置-2</a></strong></div><div>Butterfly安裝文檔-主題配置-2</div></blockquote>

**Comment by xaoxuu** [comment]
不是回答过你了么， `import` 可以实现：

![image](https://user-images.githubusercontent.com/16400144/104169414-81f3b180-543a-11eb-88b0-112e7629b5e1.png)
![image](https://user-images.githubusercontent.com/16400144/104169437-8ae48300-543a-11eb-840c-bfa0955c9726.png)

你告诉我你要的 Butterfly 的 `inject` 的哪个功能 Volantis 的 `import` 实现不了？除了名字不一样、 `import` 分类多一个，还有什么区别？

<hr>

另外，据 Butterfly 文档所述，`inject` 功能是在 [2.3.0](https://github.com/jerryc127/hexo-theme-butterfly/releases/tag/2.3.0) 后加入的，发布时间是**2020年4月28号**。Volantis 从更新日志可以看到，在 [1.1.0](https://github.com/volantis-x/hexo-theme-volantis/releases/tag/1.1.0) 版本就已经对 `import` 进行过一次简化（就是最后一次修改），发布时间是**2019年2月27号**。

**Comment by MCSeekeri** [comment]
所以我发现之后默默的关了...抱歉...
