### ISSUE TITLE
首次加载网页时Aplayer加载失败

### ISSUE THREAD

**Issue by W4J1e** [volantis-x/hexo-theme-volantis#534]
## 预期与实际表现的区别

预期正常加载Aplayer插件 

## 如何复现这个问题

 hexo s或者hexo d之后，首次加载博客页面，或者使用Ctrl+F5强制刷新会出现 

- [ x] 在 Issues 中搜索不到相关问题。
- [x ] 将主题升级至最新版本。
- [ ] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

1. hexo clean
2. hexo s
3. 打开本地博客地址，Aplayer插件不显示。

### 复现地址：

- [x ] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图:</summary>

![aplayer](https://user-images.githubusercontent.com/74824162/100577202-a9733c80-331a-11eb-9b69-485c1bd9b79a.jpg)

</details>

### 浏览器、操作系统
Chrome windows 10
### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by MHuiG** [comment]
网速慢导致的，按照xaoxuu的逻辑需要等十秒

https://github.com/volantis-x/hexo-theme-volantis/blob/92f6322890f47fc3e1430389e9c98366e4d65fbd/source/js/aplayer.js#L162

<blockquote><img src="https://avatars3.githubusercontent.com/u/68142033?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/hexo-theme-volantis">volantis-x/hexo-theme-volantis</a></strong></div><div>A Wonderful Theme for Hexo  https://volantis.js.org - volantis-x/hexo-theme-volantis</div></blockquote>

**Comment by ghost** [comment]
升级到最新，同样复现
