### ISSUE TITLE
文档错误信息提提示

### ISSUE THREAD

**Issue by wdmzjxzl** [volantis-x/hexo-theme-volantis#535]
## 需求描述

文档5-1   ——   内置标签插件（*23）     ——     多媒体类      ——      相册、组图        ——     tag-plugins: gallery

一行多个图片（不换行）
这块的效果演示及代码  界面出现乱码     布局乱了

## 参考链接
[https://volantis.js.org/tag-plugins/gallery](url)

![6Z@B4{SJ4YW11$C`(56%7DV](https://user-images.githubusercontent.com/36881585/100821028-81a2e680-348a-11eb-8bb8-9024e3620597.png)

**Comment by MHuiG** [comment]
https://volantis-x.js.org/tag-plugins/gallery/

<blockquote><img src="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon.ico" width="48" align="right"><div><strong><a href="https://volantis-x.js.org/tag-plugins/gallery/">Volantis: - Volantis</a></strong></div></blockquote>
