### ISSUE TITLE
请求MiniValine配置处加入对Waline的支持

### ISSUE THREAD

**Issue by MCSeekeri** [volantis-x/hexo-theme-volantis#541]
## 需求描述
请求在主题Valine和MiniValine配置处加入对Waline的支持

## 参考链接
https://waline.js.org/client/other.html
https://minivaline.js.org/docs/cn/#/Options

**Comment by MHuiG** [comment]
MiniValine配置项是支持的，有问题到https://github.com/lizheming/waline     提issues

**Comment by MHuiG** [comment]
```
https://github.com/lizheming/waline/issues/57#issuecomment-743969031
```
