### ISSUE TITLE
文章一级目录不显示

### ISSUE THREAD

**Issue by dearxujiee** [volantis-x/hexo-theme-volantis#551]
## 问题截图
![image](https://user-images.githubusercontent.com/50271246/102477115-e79c8a00-4096-11eb-821d-2fb210b3f48b.png)

##代码
![image](https://user-images.githubusercontent.com/50271246/102477575-80330a00-4097-11eb-9951-68c411d5a169.png)

**Comment by xaoxuu** [comment]
文档中有，可以设置的

**Comment by xaoxuu** [comment]
好像是不支持h1，你改下试试

<img width="836" alt="image" src="https://user-images.githubusercontent.com/16400144/102565711-f9267600-4118-11eb-8296-bfb80e98f8c4.png">

> 不过不建议使用 h1

**Comment by dearxujiee** [comment]
@xaoxuu 您好，您的意思是说，这个文章目录最顶层 只能从二级目录开始写吗，即 ## 就是最顶层目录？

**Comment by dearxujiee** [comment]
我试过了，mix_depth改成1确实可以看到一级目录，感谢  @xaoxuu

**Comment by dearxujiee** [comment]
我试过了，min_depth改成1确实可以看到一级目录，感谢 @xaoxuu

**Comment by dearxujiee** [comment]
但当鼠标滑过目录的时候，目录的展开与收缩似乎有些卡顿
