### ISSUE TITLE
请问可以对新增waline提pr吗？

### ISSUE THREAD

**Issue by W4J1e** [volantis-x/hexo-theme-volantis#556]
## 需求描述

此前没关注pr，看更新日志没有以为就没有。

## 参考链接
https:

**Comment by MHuiG** [comment]
你应该去看看聊天记录

![](https://user-images.githubusercontent.com/38281581/103299455-8a5dec80-4a37-11eb-92f7-fd48c97ba656.jpg)

**Comment by MHuiG** [comment]
Thanks for your contribution!
