### ISSUE TITLE
Aplayer播放器有时无法加载问题解决

### ISSUE THREAD

**Issue by iamlujue** [volantis-x/hexo-theme-volantis#57]
您好。

关于Aplayer播放器页面刷新有时无法加载的问题，发现是由异步加载js文件引起。

将主题目录下 `layout/_third-party/aplayer.ejs`文件中的加载js文件的`async`属性去除。如图示：
![image](https://user-images.githubusercontent.com/16284860/54981529-71fbab00-4fe3-11e9-8540-e16d5d8181e1.png)

即修改成以下即可解决该问题：
```javascript
<script src="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/meting@1.1.0/dist/Meting.min.js"></script>
```
望采纳~

**Comment by xaoxuu** [comment]
好的谢谢
