### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#571]
### 一、移动端菜单按钮无（事件监听）法激活

![image](https://user-images.githubusercontent.com/31947043/106078398-4fda9300-614e-11eb-8604-27cf5c643a22.png)

### 二、导航类文章标题  `'` 被转义为 `&#39;`

![image](https://user-images.githubusercontent.com/31947043/106078578-9d570000-614e-11eb-8dbe-00801d713766.png)

**Comment by inkss** [comment]
我是在 f2e288191c460b6fc7ad02e2e91ebad25586167c 的基础上修改的： db1dfb5a29a93669e48d4eabb43cff4cdc3bc066

不过按理来说，没有怎么动页面实现 🐷

**Comment by MHuiG** [comment]
移动端菜单按钮：

先打开控制台，再打开页面

![image](https://user-images.githubusercontent.com/38281581/106081646-2f153c00-6154-11eb-96d8-7821e5718506.png)

**Comment by inkss** [comment]
> 移动端菜单按钮：
> 
> 先打开控制台，再打开页面

知道了 ，`isMobile` 我这边拿到的是 false ，我觉得应该以布局尺寸来判断，`500px` 后显示了移动端导航栏的布局

**Comment by inkss** [comment]
`$('#l_header .m-phone li')`  可以换成 `$('.m-phone li:has(.list-v)')` ，没有下级菜单的不需要监听

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/106083154-f7f45a00-6156-11eb-8593-cd28f6c60a13.png)

`' `不转义 生成页面时会报错

https://github.com/volantis-x/volantis-x.github.io/runs/1767655348?check_suite_focus=true


<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 56 million people use GitHub to discover, fork, and contribute to over 100 million projects.</div></blockquote>

**Comment by MHuiG** [comment]
怀疑这里好像转义了两次

**Comment by inkss** [comment]
转义这个有点眼熟，我找找资料
