### ISSUE TITLE
建议增加通知功能

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#572]
## 需求描述

支持自定义消息，可保存已读状态或者选项的选择结果。

消息内容可通过数据文件来读取：

https://github.com/volantis-x/community/blob/master/source/_data/notification.yml

你先按照你已经实现的那些功能去支持上述字段就可以了。

## 参考链接

https://colsrch.cn/

**Comment by Colsrch** [comment]
![image](https://user-images.githubusercontent.com/58458181/106282528-adb8c900-627b-11eb-8188-f7d12081b7f0.png)
这个里面的内容是js写的，如何使用<%-  %>传值 @xaoxuu

**Comment by Colsrch** [comment]
我查到了

**Comment by xaoxuu** [comment]
感谢各位大佬👌
