### ISSUE TITLE
建议增加swiper标签 集成swiper的功能

### ISSUE THREAD

**Issue by pdone** [volantis-x/hexo-theme-volantis#579]
## 需求描述
建议增加swiper标签 集成swiper的功能

## 参考链接
https://www.swiper.com.cn/

https://github.com/Akilarlxh/hexo-butterfly-swiper

https://github.com/xaoxuu/hexo-theme-stellar/search?q=swiper

**Comment by inkss** [comment]
https://github.com/volantis-x/hexo-theme-volantis/commit/17e9a56e20fc5205252c52ebfa85fb00c32a1da2
