### ISSUE TITLE
想要一个web端代码编辑器插件

### ISSUE THREAD

**Issue by tcp404** [volantis-x/hexo-theme-volantis#589]
有时候写代码，希望能附带一个代码编辑器在网页上，这样浏览的人可以随手自己跑一跑。
对于浏览的人来说非常有用

**Comment by MHuiG** [comment]
https://github.com/Xecades/hexo-tag-tiy

<blockquote><img src="https://avatars.githubusercontent.com/u/33767256?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Xecades/hexo-tag-tiy">Xecades/hexo-tag-tiy</a></strong></div><div>hexo 内嵌 HTML 代码调试器. Contribute to Xecades/hexo-tag-tiy development by creating an account on GitHub.</div></blockquote>
