### ISSUE TITLE
图片放大功能实现

### ISSUE THREAD

**Issue by iamlujue** [volantis-x/hexo-theme-volantis#59]
您好。

个人目前基于fancybox插件实现了图片放大功能，只针对文章中的图片进行了选择放大处理(避免了头像、emoji表情、分享链接图片的放大)，效果如下图所示，：
![image](https://user-images.githubusercontent.com/16284860/55092491-9ba0f900-50ed-11e9-9dc2-6df4f6879a9e.png)

### 自定义js
在主题的js文件目录下创建名为 `fancybox-use.js` 的文件，内容如下：
```javascript
// 集成fancybox, 只为文章中所有img元素添加父元素
$(".article-entry").find("img").each(function () {
    var element = document.createElement("a");
    $(element).attr("data-fancybox", "gallery");
    $(element).attr("href", $(this).attr("src"));
    $(this).wrap(element);
});
```
如图所示：
![image](https://user-images.githubusercontent.com/16284860/55128278-ef432f00-514d-11e9-8894-28aff520cd8d.png)

### 引入所需文件
我这里将图片放大所需文件引入标签(包括上述自定义js文件，以及官网demo所需文件)放置主题`layout/_partial/scripts.ejs`文件中：
```html
<script src="/js/fancybox-use.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
```
如图所示
![image](https://user-images.githubusercontent.com/16284860/55092103-eec67c00-50ec-11e9-99eb-9addc1552c79.png)

[Pull request](https://github.com/xaoxuu/hexo-theme-material-x/pull/60)已提交，望采纳~

### 关于图片懒加载放大只显示加载图片问题

图片懒加载的话一般图片标签内会有个属性名来存放图片的真实地址，比如 `data-original` ，那么以上代码可以修改为如下代码(这里根据自己定义的属性名进行替换)：

```javascript
// 集成fancybox, 只为文章中所有img元素添加父元素
$(".article-entry").find("img").each(function () {
    var element = document.createElement("a");
    $(element).attr("data-fancybox", "gallery");
    $(element).attr("href", $(this).attr("data-original"));  
    $(this).wrap(element);
});
```

**Comment by xaoxuu** [comment]
太棒了，完美兼容😄
