### ISSUE TITLE
关于4.x版本中的标签云

### ISSUE THREAD

**Issue by Deecyn** [volantis-x/hexo-theme-volantis#593]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

最近在试用 4.3.1 版本的 volantis 主题，关于标签 tags 的使用有一些问题：

- 标签页面的展示，现在改成了「列表」的形式，虽然和之前的「热点标签」的形式相比各有好处，但还是觉得热点标签的形式要好一点，能否支持配置自己选择使用那个吗？
- 在文章列表页面的文章卡片中，现在只显示日期和分类，能否配置显示标签等内容吗？
- 侧边栏的 tagcloud 组件，不能设置最大高度，这样当标签比较多的时候展示是不是不太美观哦。

**Comment by W4J1e** [comment]
1、2看开发者；3可以尝试设置标签字体大小试试。
