### ISSUE TITLE
建议添加百度统计，腾讯分析等等

### ISSUE THREAD

**Issue by imjason** [volantis-x/hexo-theme-volantis#603]
## 需求描述

建议添加百度统计，腾讯分析等等

## 参考链接

next配置
# Google Analytics
google_analytics:
  tracking_id: # <>
  # By default, NexT will load an external gtag.js script on your site.
  # If you only need the pageview feature, set the following option to true to get a better performance.
  only_pageview: false

# Baidu Analytics
baidu_analytics: # <>

**Comment by inkss** [comment]
![image](https://user-images.githubusercontent.com/31947043/112797022-62fdd680-909d-11eb-9043-c07ed22e7228.png)
