### ISSUE TITLE
标题中带有空格的话会显示 &amp; ？

### ISSUE THREAD

**Issue by LiYanan2004** [volantis-x/hexo-theme-volantis#61]
如果你发现 无法使用 或者效果与示例有较大区别，可以使用hexo官方提供的用于单元测试的博客应用本主题查看样式是否正常，对比_config.yml文件排查问题。

## 下载单元测试：

Hexo官方的单元测试博客： [https://github.com/hexojs/hexo-theme-unit-test.git](https://github.com/hexojs/hexo-theme-unit-test.git)。
如果你的系统是macOS，则可以使用hexo.sh脚本一键完成测试。

## 提问前请先认真阅读文档

文档：[https://xaoxuu.com/wiki/material-x/](https://xaoxuu.com/wiki/material-x/)

**Comment by LiYanan2004** [comment]
![35564EA7-2998-47B8-A445-DF0712008C7D](https://user-images.githubusercontent.com/37542129/55270918-09ad1200-52e0-11e9-8fcc-5a98b5bcb274.jpeg)

**Comment by xaoxuu** [comment]
我的就不会啊，让我看一下你这篇文章的front-matter

**Comment by LiYanan2004** [comment]
---
title: watchOS 5.2.1 Beta && iOS 12.3 Beta 体验报告
toc: true
tags: [Beta,体验报告]
categories: [Apple Beta 体验计划]
---

**Comment by xaoxuu** [comment]
好了，现在已经修复了，你更新一下看看

**Comment by LiYanan2004** [comment]
成功了，更新主题的时候有什么方便点的方法吗，因为我自定义的主题，好多文件都要重新设定。

**Comment by xaoxuu** [comment]
[#更新主题](https://xaoxuu.com/wiki/material-x/help/index.html#%E6%9B%B4%E6%96%B0%E4%B8%BB%E9%A2%98)
