### ISSUE TITLE
Gallery标签支持分别设置ID

### ISSUE THREAD

**Issue by ghost** [volantis-x/hexo-theme-volantis#610]
目前可能无论添加几个{% gallery %}标签，放大查看时所有图片都会混在一起。
希望像tabs标签一样，一个页面里面可以拥有若干个不同的Gallery，放大查看时不同Gallery可以分别查看。

想象中的公式:
{% gallery 参数, 列数 galleryId(最好可以重复，相同id的gallery中的图片放大时可以合并显示) %}
![1-1](1-1.jpg)
![1-2](1-2.jpg)
{% endgallery %}

**Comment by inkss** [comment]
```ejs
{% gallery 参数, 列数, 分组 %}

{% endgallery %}

```
