### ISSUE TITLE
文章头图动画错误

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#615]
https://github.com/volantis-x/hexo-theme-volantis/blob/616a2aaa9f445f96f6c84518f36eaa6a93ef8e82/source/css/_defines/func.styl#L43-L47

https://github.com/volantis-x/hexo-theme-volantis/blob/616a2aaa9f445f96f6c84518f36eaa6a93ef8e82/source/css/_layout/posts.styl#L90

这个函数下，最终生成的结果是：

```css
transition: transform 3s ease-out opacity .5s ease-out ease-out;
```

**Comment by inkss** [comment]
最后多的 `ease-out` 是因为函数头部对 `transition` 的重写吧：

https://github.com/volantis-x/hexo-theme-volantis/blob/616a2aaa9f445f96f6c84518f36eaa6a93ef8e82/source/css/_defines/func.styl#L3-L8

第三个参数默认成了 `ease-out`：
![image](https://user-images.githubusercontent.com/31947043/114145202-bfd47900-9948-11eb-9120-d86dfe5faa18.png)

这个动画是不是写的有问题。

**Comment by MHuiG** [comment]
我打赌你没跑过这段代码

**Comment by xaoxuu** [comment]
我加那个有问题，去掉吧

**Comment by MHuiG** [comment]
> https://github.com/volantis-x/hexo-theme-volantis/blob/616a2aaa9f445f96f6c84518f36eaa6a93ef8e82/source/css/_defines/func.styl#L43-L47
> 
> https://github.com/volantis-x/hexo-theme-volantis/blob/616a2aaa9f445f96f6c84518f36eaa6a93ef8e82/source/css/_layout/posts.styl#L90
> 
> 这个函数下，最终生成的结果是：
> 
> ```css
> transition: transform 3s ease-out opacity .5s ease-out ease-out;
> ```

官网不是最新的dev

**Comment by inkss** [comment]
> 我打赌你没跑过这段代码

那必须的 哈哈哈哈哈哈

**Comment by MHuiG** [comment]
> 最后多的 `ease-out` 是因为函数头部对 `transition` 的重写吧：
> 
> https://github.com/volantis-x/hexo-theme-volantis/blob/616a2aaa9f445f96f6c84518f36eaa6a93ef8e82/source/css/_defines/func.styl#L3-L8
> 
按照这个逻辑 transition 套 transition 是不是还应该有个堆栈溢出。。。
