### ISSUE TITLE
建议5.0搞个新的相册功能。

### ISSUE THREAD

**Issue by W4J1e** [volantis-x/hexo-theme-volantis#616]
## 需求描述
需求原因：看到某位博主在博客晒了自己的亲子照片，在想以后要是 **结** **婚** **生** **子** 了会不会也用博客来记录生活和孩子的成长。目前的volantis可以手动添加照片做成相册，但是因为是静态，每次都要手动挨个添加，略麻烦。
参考方案：看到的解决方案有一个是通过每次deploy时将对应仓库内的图片生成一个json。优点：相对方便。缺点：也不是很快。
所以我在想，能不能通过api调用的方式来实现呢，配置好路径后，我只需要把照片上传到云存储，每次加载网页就会通过api来获取内容。目前volantis有许多api调用的场景，这个应该可以实现。 优点：实时、方便、快捷。 缺点：要麻烦大佬了。

## 参考链接
第一个方案的参考链接：https://www.cnblogs.com/xljzlw/p/5137622.html

**Comment by W4J1e** [comment]
@xaoxuu @MHuiG @inkss 烦请大佬们看看能否实现。

**Comment by inkss** [comment]
你这样说，那不就是现有的友链思路，从 issue 读取。简单来说提供 `src` `alt` `name` 就足够了。
进一步分组，自定义样式（宽高）啥的，剩下就是提供一个前端样式什么的。

```js
{
 src: '',
 name: '',
 alt: '',
 width: '',
 height: '',
 group: '',
 //...
}
```

**Comment by W4J1e** [comment]
@inkss 我的理解是两者有点差异…友链issue是特定的格式写的，而图片上传到比如对象存储中的话就不一样了。如果每个照片都要按照一定的格式来弄也比较麻烦。不知道我的理解有没有出错。
