### ISSUE TITLE
首页顶部是否考虑增加banner

### ISSUE THREAD

**Issue by CL0610** [volantis-x/hexo-theme-volantis#62]

**Comment by xaoxuu** [comment]
已经在计划内了。

**Comment by CL0610** [comment]
> 已经在计划内了。

博主真的好赞呀，本来想研究下，另外感觉banber在视觉上不好设计，目前博客太宽了。博主计划啥时候上线

**Comment by CL0610** [comment]
博主，你那个wiki模板怎么使用呢？也想用你的产品

**Comment by xaoxuu** [comment]
现在已经有封面了，可以设置封面背景图片，以后再增加卡片式banner
