### ISSUE TITLE
文章导航栏评论按钮定位失效，点击按钮无反应

### ISSUE THREAD

**Issue by Colsrch** [volantis-x/hexo-theme-volantis#620]
## 如何复现这个问题

- [x] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。您当前使用的volantis版本为：___5.0______________
- [ ] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

1. 随便点击一篇文章
2. 点击导航栏评论按钮
3. xxx

### 复现地址：

- [ ] 文档官网源码本地运行存在异常。
- [x] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

https://colsrch.cn/posts/9eae9d7b/

### 截图

<details><summary>相关截图:</summary>

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by Colsrch** [comment]
![image](https://user-images.githubusercontent.com/58458181/114995791-c5920780-9ed0-11eb-998a-4d39b466d0fb.png)

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/06c8fa7d94a223ec3820123b5781ad39e2f26e91/source/js/app.js#L181
