### ISSUE TITLE
【寻求帮助】更换默认的 Markdown 渲染器之后部分页面 Pjax 失效

### ISSUE THREAD

**Issue by ymd45921** [volantis-x/hexo-theme-volantis#621]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

在增加 Markdown 渲染器 `hexo-renderer-syzoj-renderer` 后，包含 MathJax 数学公式的页面的 Pjax 跳转失效，对于解决这个问题没有头绪，希望可以得到主题原作者们的建议和帮助 ：）

从常规页面跳转到包含 MathJax 公式的页面，以及从这些页面跳转到任何其他页面，Pjax 均失效。

**背景**：

Hexo 默认使用的 Markdown 渲染器 `hexo-renderer-marked` 在渲染多行 Markdown 公式的时候会因为将换行符号 `\\` 提前转义而导致无法正确的渲染多行公式；而网络上可供参考的修改 `marked.js` 的方法对于新版而言已经全部失效（至少在我阅读过的范围内），而使用 `\\\\` 的方法又显得极其不优雅；所以选择了其他的可正常渲染多行数学公式的渲染器 `hexo-renderer-syzoj-renderer`。

在点击包含了 MathJax 公式的文章的链接之后，成功的触发了 `pjax:send` 后触发了 `pjax:error` 事件。

**关于同时保留 `hexo-renderer-marked` 的原因**：

本主题在 `ejs` 文件中使用了 `markdown()` 来渲染字符串中的 Markdown；如果移除了 `marked`，这一类的渲染将无法进行。

实际上，移除 `hexo-renderer-marked` 并不能改善这个问题。

**补充**：

（提出其他的可以渲染多行公式的建议也行）

### 主题版本

您当前使用的版本为：4.3.1

### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [x] 文档官网源码本地运行不存在异常。

复现地址及源码仓库地址：

- 仓库地址：https://github.com/45921/volantis-test/tree/syzoj-renderer
- 复现地址：https://volantis.shiraha.ml/

复现地址的实例站点中包含了一篇没有数学公式的文章和有数学公式的文章，可以进行对比。

在按照下面的描述更新官网 demo 的依赖之后，会产生同样的问题：

```bash
npm install hexo-renderer-syzoj-renderer
# yarn add hexo-renderer-syzoj-renderer

npm install
# yarn
```

注：本地测试时，可能是因为网络原因，`yarn` 安装的成功率较 `npm` 偏低。
注：本地测试时，先使用 `npm` 安装 `hexo-renderer-syzoj-renderer`，再使用 `yarn` 更新依赖。
注：本地测试 `demo` 仓库时，按照上述导入新依赖后可以复现这个问题。

### 截图

<details><summary>相关截图</summary>

无法截图，请访问复现地址：https://volantis.shiraha.ml/

</details>

### 浏览器、操作系统

- Chromium Edge 版本 90.0.818.41 (官方内部版本) beta (64 位)
- Windows 10 20H2 19042.867

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml
syzoj_renderer:
  highlighter: hexo
```

仓库地址：https://github.com/45921/volantis-test/tree/syzoj-renderer

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml
<无>
```

仓库地址：https://github.com/45921/volantis-test/tree/syzoj-renderer

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```
v14.16.0
6.14.8
```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```
hexo-site@0.0.0 D:\Workspaces\HexoBlog\BlogExamples\volantis-test
+-- hexo@5.3.0
+-- hexo-deployer-git@3.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.3.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-renderer-syzoj-renderer@1.0.0
+-- hexo-server@2.0.0
`-- hexo-theme-landscape@0.0.3
```

仓库地址：https://github.com/45921/volantis-test/tree/syzoj-renderer

</details>

**Comment by MHuiG** [comment]
可以尝试hexo-renderer-pandoc 

https://github.com/volantis-x/hexo-theme-volantis/issues/295#issuecomment-626501867

**Comment by ymd45921** [comment]
> 可以尝试hexo-renderer-pandoc
> 
> [#295 (comment)](https://github.com/volantis-x/hexo-theme-volantis/issues/295#issuecomment-626501867)

您好，非常感谢您的帮助；`hexo-renderer-pandoc` 确实可以在兼容 Pjax 的同时较好的适配 `marked` 无法胜任的多行公式的渲染；

但是它在渲染一些其他元素的场合下表现和 `marked` 不同：比如渲染图片会渲染出 alt 文本，不能自动地为文本中的链接加上超链接等（）所以可以的话还是想得到适配 `hexo-renderer-syzoj-renderer` 的建议啊……

再次感谢您的回复！

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/133881134-d3d32260-bfe2-4d97-8e62-8ea14fd2d845.png)

**Comment by MHuiG** [comment]
![image](https://user-images.githubusercontent.com/38281581/133881268-214231d1-9b53-4451-b777-010a6a8a670a.png)

![image](https://user-images.githubusercontent.com/38281581/133881679-a327f3fd-5c2e-459a-9aa5-b16c17d78e9e.png)

这个页面含有多个title @inkss

https://github.com/volantis-x/hexo-theme-volantis/blob/36221f46fc98604698dea2683a1d8ec4a763bbfd/layout/_plugins/pjax/index.ejs#L22

这里需要改成 

```js
"head title",
```

**Comment by inkss** [comment]
@MHuiG  Pjax 选择器里，`meta[name='description']",` `"meta[name='keywords']"` 被移除了，这个是特意如此还是遗漏啊？

**Comment by MHuiG** [comment]
> @MHuiG Pjax 选择器里，`meta[name='description']",` `"meta[name='keywords']"` 被移除了，这个是特意如此还是遗漏啊？

一开始就没有吧 https://github.com/volantis-x/hexo-theme-volantis/pull/393/files

<blockquote><img src="https://avatars.githubusercontent.com/u/31947043?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/hexo-theme-volantis/pull/393">Volantix inkss by inkss · Pull Request #393 · volantis-x/hexo-theme-volantis</a></strong></div><div>Pjax 评论兼容：gitalk && disqus
修改评论的判断逻辑及一些插件的加载判断
修复一些问题 #388 #370</div></blockquote>

**Comment by MHuiG** [comment]
话说 meta[name='description']", "meta[name='keywords']" 是给谁看的?

搜索引擎的话,倒是爬不到 pjax

![image](https://user-images.githubusercontent.com/38281581/133882960-f295b48b-61bb-47f0-ba25-3ed33058b996.png)

要不把这些也搞进去?

**Comment by inkss** [comment]
我在QQ里，使用它的分享，描述信息是读的这俩。
其它的话，og 开头的可以添加；article.tag 的不行，不是所有页面都有，而且还可能多个。

```
meta[property^='og']
```

**Comment by MHuiG** [comment]
QQ里的卡片描述信息是读的 og:title og:image og:description

https://ogp.me/

<blockquote><img src="https://ogp.me/logo.png" width="48" align="right"><div><strong><a href="https://ogp.me/">Open Graph protocol</a></strong></div><div>The Open Graph protocol enables any web page to become a rich object in a social graph.</div></blockquote>

**Comment by inkss** [comment]
噢噢噢噢

**Comment by inkss** [comment]
那还是添加吧，不然在QQ里跳到其它页面，分享时拉取的信息不对

**Comment by MHuiG** [comment]
实际上并不需要,  这些信息是独立爬取的,不是浏览时生成的

**Comment by MHuiG** [comment]
> 那还是添加吧，不然在QQ里跳到其它页面，分享时拉取的信息不对

下个版本加上吧，把og也加上pjax，pjax跳转时拉取的信息确实不对
另外可以关注一下这个issues ：https://github.com/next-theme/hexo-theme-next/issues/371

**Comment by StarCried** [comment]
我使用hexo-renderer-syzoj-renderer后最新版本的主题好像解决了pjax的问题，但是标签插件全部失效了。

**Comment by Tikas** [comment]
> 我使用hexo-renderer-syzoj-renderer后最新版本的主题好像解决了pjax的问题，但是标签插件全部失效了。

我们有留意到您的反馈，pjax 需要另几位大佬出来才能帮您解决，很抱歉，我自身的实力有限，在此只能等待解决方案。
