### ISSUE TITLE
移动端依次点击导航栏子菜单菜单不会消失

### ISSUE THREAD

**Issue by Colsrch** [volantis-x/hexo-theme-volantis#623]
## 如何复现这个问题

- [x] 在 Issues 中搜索不到相关问题。
- [x] 将主题升级至最新版本。您当前使用的volantis版本为：______5.0___________
- [ ] 官网也存在这个问题；或者下载主题官网源码运行，经过一定的步骤，可以复现这个问题。

**复现步骤**

1. https://colsrch.cn
2. 移动端依次点击导航栏菜单的子菜单
3. 

### 复现地址：

- [ ] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图:</summary>

![Screenshot_20210428_111609](https://user-images.githubusercontent.com/58458181/116341621-d701da80-a813-11eb-9766-e88c0b72cba9.jpg)

</details>

### 浏览器、操作系统

Edge浏览器

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by inkss** [comment]
wow

**Comment by Colsrch** [comment]
wow 这真是一个巨大的 `bug` 🤪
