### ISSUE TITLE
Google Analytics推送问题

### ISSUE THREAD

**Issue by zhanghuimeng** [volantis-x/hexo-theme-volantis#63]
换成这个主题之后，我的Google Analytics用户量就骤降了。然而检查网页发现，确实有相关的推送代码。后来我把根目录`_config.yml`中的`google_analytics_key`去掉，直接在`head.ejs`中加入以下推送代码（直接从Google Analytics上拿的全局网站代码）之后就好了：

```
  <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=my-google-analytics-key"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'my-google-analytics-key');
  </script>
```

如下图，换成material-x主题之后，访问量突然降低为原来的10%左右，加入以上代码之后就好了。

![总用户量变化](https://user-images.githubusercontent.com/26516581/55279177-84ae1100-5350-11e9-8b0c-21a6027125ce.png)

我的用户主要来自搜索，但在搜索结果中的点击次数并没有明显变化（如下图），所以几乎可以确定是网页本身推送的问题。

![搜索中点击量变化](https://user-images.githubusercontent.com/26516581/55279208-eec6b600-5350-11e9-9fc8-7f570771861c.png)

不知道是之前注入的代码有问题，还是我这边的配置有问题，注入失败了。之前的#46也是注入有问题，我有空用测试博客实验一下（不过访问量可能会有点困难）。

**Comment by xaoxuu** [comment]
抱歉，我之前没有测试过GA，现在我按照你贴的这段代码更新了一下，你再试一下好了没有

**Comment by zhanghuimeng** [comment]
好的，我更新之后测试两天，再把结果贴上来

**Comment by zhanghuimeng** [comment]
<img width="819" alt="user-cnt-later" src="https://user-images.githubusercontent.com/26516581/55559406-b6442500-5720-11e9-8d58-9e97fe0d0f05.png">

最近几天用户量回来了，我觉得这个issue可以关了。

之前的GA代码是[analytic.js](https://developers.google.com/analytics/devguides/collection/analyticsjs/)版本（但是有个目标链接写错了），现在用的是[gtag.js](https://developers.google.com/analytics/devguides/collection/gtagjs/)版本，本质上没有太大差别（事实上gtag的实现就是调用analytic.js），不过gtag是新出的库，看起来更轻量也更方便。
