### ISSUE TITLE
有序列表或无序列表内有数学公式，启动后，页面内没有有序列表或无序列表样式[如图所示]

### ISSUE THREAD

**Issue by hzleii** [volantis-x/hexo-theme-volantis#631]
![a](https://user-images.githubusercontent.com/38949031/119113885-24124e80-ba58-11eb-8e9f-60d653810e12.png)

**Comment by MHuiG** [comment]
我看了一下是正常的啊

![image](https://user-images.githubusercontent.com/38281581/133878846-7de18ac1-2762-4793-88f3-12b3b1572a30.png)

![image](https://user-images.githubusercontent.com/38281581/133878865-9224c948-20ee-4eb6-84ef-7920f4343e23.png)
