### ISSUE TITLE
暗黑模式使用问题&暗黑模式下waline评论框白色，评论内容不清晰&网站背景图片保持原状

### ISSUE THREAD

**Issue by hermitlsr** [volantis-x/hexo-theme-volantis#633]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

我在使用暗黑模式时，网站背景图片以及waline的评论框并未生效。其中：
1. 网站背景图片并未变暗或者如未设定背景图片时变黑；
2.  waline评论框仍呈现白色，作为对比valine的评论框是有黑色变化。
3. waline评论内容的文字颜色接近灰色与黑色背景难以区分。

补充：
1. 关于网站背景图片，由于直接使用主题配置文件中的backstretch：(posistion: fixed)进行设置，会将cover：中的background：设置的图片覆盖掉。而我希望cover部分的背景图片和网站下方的背景图片不一致，故而在"...\volantis\source\css\_layout\main.styl"文件中添加:
```
"#l_body {
  background-image: url(https://cdn.jsdelivr.net/gh/hermitlsr/blog-images/img/background1.png);
}"
```
2. 对于waline，我在其对应的script.ejs文件中加入了：
```
<style>
.v[data-class=v] .veditor {
    background-image: url(https://cdn.jsdelivr.net/gh/hermitlsr/blog-images/img/valine-bg.webp);
    background-size: contain;
    background-repeat: no-repeat;
    background-position: right;
}
</style>
```
valine中进行了同样的设置。

希望的效果，在暗黑模式下：
1. 网站背景会变暗或替换为全黑背景
2. waline评论框会变黑
3. waline评论内容的文字变为白色，方便辨认。

### 主题版本

您当前使用的版本为：Volantis5.0

### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

![问题呈现](https://7.dusays.com/2021/05/31/2e3fb828aa5cf.png)
![valine暗黑模式下的效果](https://7.dusays.com/2021/05/31/2cc29f41fcaae.png)
![waline暗黑模式下的效果](https://7.dusays.com/2021/05/31/8acfd76e471a8.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by inkss** [comment]
关于问题一，设计之初应该没有考虑过两个同时使用吧，不是很清楚。你就按照你现在的思路解决就是了。

关于 waline 的夜间模式，看它的实现似乎是自己用了一套颜色变量，和主题中的配置不搭，简单起见，你可以修改这个文件：

https://github.com/volantis-x/hexo-theme-volantis/blob/80d4d3194ac9e82d0d8719e74c2bb01c50a35fa3/source/css/_defines/func.styl#L119

在之后添加如下内容：


```styl
  --waline-white:#000 !important;
  --waline-light-grey:#666 !important;
  --waline-dark-grey:#999 !important;
  --waline-text-color:#888 !important;
  --waline-bgcolor:#1e1e1e !important;
  --waline-bgcolor-light:#272727 !important;
  --waline-border-color:#333 !important;
  --waline-disable-bgcolor:#444 !important;
  --waline-disable-color:#272727 !important;
  --waline-bq-color:#272727 !important;
  --waline-info-bgcolor:#272727 !important;
  --waline-info-color:#666 !important;
```

![image](https://user-images.githubusercontent.com/31947043/120254958-8a4f6a80-c2bd-11eb-808f-d15ee461cf5a.png)

**Comment by hermitlsr** [comment]
> 关于问题一，设计之初应该没有考虑过两个同时使用吧，不是很清楚。你就按照你现在的思路解决就是了。
> 
> 关于 waline 的夜间模式，看它的实现似乎是自己用了一套颜色变量，和主题中的配置不搭，简单起见，你可以修改这个文件：
> 
> https://github.com/volantis-x/hexo-theme-volantis/blob/80d4d3194ac9e82d0d8719e74c2bb01c50a35fa3/source/css/_defines/func.styl#L119
> 
> 在之后添加如下内容：
> 
> ```stylus
>   --waline-white:#000 !important;
>   --waline-light-grey:#666 !important;
>   --waline-dark-grey:#999 !important;
>   --waline-text-color:#888 !important;
>   --waline-bgcolor:#1e1e1e !important;
>   --waline-bgcolor-light:#272727 !important;
>   --waline-border-color:#333 !important;
>   --waline-disable-bgcolor:#444 !important;
>   --waline-disable-color:#272727 !important;
>   --waline-bq-color:#272727 !important;
>   --waline-info-bgcolor:#272727 !important;
>   --waline-info-color:#666 !important;
> ```
> 
> ![image](https://user-images.githubusercontent.com/31947043/120254958-8a4f6a80-c2bd-11eb-808f-d15ee461cf5a.png)

非常感谢，你的方法对于聊天框是奏效的。但是如果有自定义设置聊天框的背景图片的话，应该还需要另外的设置使得这个背景也有所变化，我这两天还在想如何解决这个问题。

**Comment by W4J1e** [comment]
> 关于问题一，设计之初应该没有考虑过两个同时使用吧，不是很清楚。你就按照你现在的思路解决就是了。
> 
> 关于 waline 的夜间模式，看它的实现似乎是自己用了一套颜色变量，和主题中的配置不搭，简单起见，你可以修改这个文件：
> 
> https://github.com/volantis-x/hexo-theme-volantis/blob/80d4d3194ac9e82d0d8719e74c2bb01c50a35fa3/source/css/_defines/func.styl#L119
> 
> 在之后添加如下内容：
> 
> ```stylus
>   --waline-white:#000 !important;
>   --waline-light-grey:#666 !important;
>   --waline-dark-grey:#999 !important;
>   --waline-text-color:#888 !important;
>   --waline-bgcolor:#1e1e1e !important;
>   --waline-bgcolor-light:#272727 !important;
>   --waline-border-color:#333 !important;
>   --waline-disable-bgcolor:#444 !important;
>   --waline-disable-color:#272727 !important;
>   --waline-bq-color:#272727 !important;
>   --waline-info-bgcolor:#272727 !important;
>   --waline-info-color:#666 !important;
> ```
> 
> ![image](https://user-images.githubusercontent.com/31947043/120254958-8a4f6a80-c2bd-11eb-808f-d15ee461cf5a.png)

inkss大佬永远滴神！
