### ISSUE TITLE
建议增加懒加载的动画配置

### ISSUE THREAD

**Issue by 2926295173** [volantis-x/hexo-theme-volantis#634]
## 需求描述

目前主题已经实现了懒加载图片，能不能实现下，就是懒加载的时候的弥补图配置，

现在就是懒加载的时候，会出现一片空白，很影响体验

**Comment by MHuiG** [comment]
https://github.com/volantis-x/hexo-theme-volantis/blob/5fc7bcb8c15cad9d2dcb0f1790f071bb6191e471/_config.yml#L497

这里有配置
