### ISSUE TITLE
建议5.0版本视频标签原生支持m3u8 视频标签原生支持

### ISSUE THREAD

**Issue by W4J1e** [volantis-x/hexo-theme-volantis#635]
## 需求描述
目前来说，要在volantis主题的博客里播放m3u8视频，需要额外引入一个hls.js，还需要使用dplayer。其实难度也不大，但是这样不支持pjax，所以要在pjax ban url中添加对应的链接。
如果视频标签 {% video %}能支持m3u8的话，就简化了许多。

## 参考链接
https://blog.csdn.net/HarryHY/article/details/103199482

**Comment by inkss** [comment]
参考着音乐那部分来估计就可以，大致秒了一眼文档论实现的话挺可行的。http://dplayer.js.org/zh/guide.html#api

**Comment by W4J1e** [comment]
> 参考着音乐那部分来估计就可以，大致秒了一眼文档论实现的话挺可行的。http://dplayer.js.org/zh/guide.html#api

差点搞忘了它俩的开发者都是DIYgod……

<blockquote><div><strong><a href="http://dplayer.js.org/zh/guide.html#api">指南 | DPlayer</a></strong></div><div>🍭 Wow, such a lovely HTML5 danmaku video player</div></blockquote>
