### ISSUE TITLE
每篇文章的小部件出现问题

### ISSUE THREAD

**Issue by Radiance7** [volantis-x/hexo-theme-volantis#64]
![image](https://user-images.githubusercontent.com/37700503/55287168-0a28d400-53d8-11e9-9363-5aac540c83b9.png)

**Comment by xaoxuu** [comment]
我不知道你这情况是怎么出现的，我用最新版运行了一下没有问题

**Comment by xaoxuu** [comment]
如果你更新之后还存在问题请对比这篇博客的源码看看是哪里修改出问题了：
https://github.com/xaoxuu/blog-example
