### ISSUE TITLE
建议增加双评论系统

### ISSUE THREAD

**Issue by hermitlsr** [volantis-x/hexo-theme-volantis#645]
## 需求描述

虽然博客评论系统做到够用即可，两个评论系统也会显得累赘，但是前两天我使用的某一个评论系统被人恶意评论不得不关停，而更换另一个评论系统，但评论数据并不互通，如果更换回去目前的评论也将无法展示。所以我希望能够有一个双评论系统，通过开关由用户选择使用某一个评论系统进行评论，当其中一个评论系统宕机时，也不会影响使用。这不是一个必要的需求，但如果可以加上自然是很高兴了。

**Comment by MCSeekeri** [comment]
其实如果我没记错的话,Volantis曾经就是双评论,但不知道为啥后来删掉了。

如果是数据不互通问题的话,常见的评论系统,比如Disqus,MiniValine都是可以做到数据互转的。

另外如果双评论的话…访客想看到所有评论就得手动切换…我个人感觉这个体验有点割裂…

**Comment by xaoxuu** [comment]
匿名评论系统避免不了低质量评论，建议使用非匿名的评论系统。

如 Vssue/Gitalk/utterances，它们的数据是通用的，即使以后不用评论系统了，也依然可以通过 github issues 页面访问数据。

**Comment by hermitlsr** [comment]
我之前用过waline，valine他们的数据是通用的（好像twikoo的数据也可以通过工具处理一致），但是像gitalk这些基于issue的就算是另一套体系了（包括基于utterances二次开发的beaudar），主要是我目前遇到是这种困境，waline和gitalk都在使用了，这两套评论也算各有优劣。或许也可以做成一个可选择的功能，既可双评论也可单评论。当然如果不做问题也不太大，也不是一个必须的需求，只是如果有的话对我这种情况要方便一些。

**Comment by xaoxuu** [comment]
beaudar看起来挺不错的，我打算换这个了
