### ISSUE TITLE
关于主页封面的背景图不随鼠标的移动而移动怎样设置

### ISSUE THREAD

**Issue by catbugdemo** [volantis-x/hexo-theme-volantis#648]
想请问下作者大大，我想设置主页的背景不会随鼠标的移动而移动这个怎样设置的，我没有找到在 hexo 的主 _config.yml怎样设置的

**Comment by xaoxuu** [comment]
这里设置为 `fixed`
https://github.com/volantis-x/hexo-theme-volantis/blob/ab330d1fb26a4c376c56c67330f302fc3a82b3cd/_config.yml#L550

**Comment by catbugdemo** [comment]
谢谢
