### ISSUE TITLE
Front-matter中的excerpt字段不起作用

### ISSUE THREAD

**Issue by zhanghuimeng** [volantis-x/hexo-theme-volantis#65]
使用中发现`excerpt`字段失效，不过#27中提到的`description`字段仍然有效。具体效果：

* `excerpt`坏了：[网页](https://zhanghuimeng.github.io/blog-example/excerpt-test-1/) [源码](https://github.com/zhanghuimeng/blog-example/blob/excerpt/source/_posts/2019-04-03-excerpt%E6%B5%8B%E8%AF%95.md)
* `<!--more-->`没问题：[网页](https://zhanghuimeng.github.io/blog-example/excerpt-test-2/) [源码](https://github.com/zhanghuimeng/blog-example/blob/excerpt/source/_posts/2019-04-03-excerpt%E6%B5%8B%E8%AF%952.md)
* `description`没问题：[网页](https://zhanghuimeng.github.io/blog-example/excerpt-and-description-test/) [源码](https://github.com/zhanghuimeng/blog-example/blob/excerpt/source/_posts/2019-04-03-excerpt%E5%92%8Cdescription%E6%B5%8B%E8%AF%95.md)

（更正：上述效果是出现在看首页时，文章实际内容都一样）

文档里只说`description`是“页面描述”，建议修改一下。

**Comment by xaoxuu** [comment]
哦，好像是我文档写错了😅不好意思
