### ISSUE TITLE
fancybox在部分移动端设备上无法使用

### ISSUE THREAD

**Issue by MCSeekeri** [volantis-x/hexo-theme-volantis#652]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述
在部分移动端设备上,gallery标签的fancybox有可能不加载
原因尚不明确,但Chrome,新版Edge的设备仿真可以正常加载,实机安装最新版Chrome也可正常加载

### 主题版本

您当前使用的版本为：5.0.0-alpha
### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [x] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 

https://sciadv.top/archives/a1b97160/
https://github.com/MCSeekeri/sciadv/blob/master/source/_posts/%E6%BC%AB%E7%94%BB/%E5%93%80%E5%BF%83%E8%BF%B7%E9%80%94%E7%9A%84%E5%B7%B4%E5%88%AB%E5%A1%94.md

### 截图

<details><summary>相关截图</summary>

![](https://bu.dusays.com/2021/08/09/c8af7ad95fbd8.jpg)
![](https://bu.dusays.com/2021/08/09/dbb24a6300a13.bmp)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by inkss** [comment]
更新了 fancybox 的版本，拉取 dev 的试试现在的呢？

**Comment by MCSeekeri** [comment]
> 更新了 fancybox 的版本，拉取 dev 的试试现在的呢？

可以使用了,在之前出错的设备上成功加载了,谢谢inkss大佬。
