### ISSUE TITLE
MathJaX适配问题

### ISSUE THREAD

**Issue by zhanghuimeng** [volantis-x/hexo-theme-volantis#66]
本来这个issue是因为我原来用的[hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it)插件渲染公式失败才提的，结果经过一通实验和**升级npm和node版本**，原来的问题不见了，[在material-x上使用KaTeX](https://www.micdz.cn/article/katex-on-material-x/)的方法反而出了问题，所以还是来报个bug。

详情参见[环境和mathjax导入测试](https://zhanghuimeng.github.io/blog-example/environment-and-mathjax-import/)和[源代码](https://github.com/zhanghuimeng/blog-example/tree/mkimport)。简单来说，就是[hexo-renderer-markdown-it-plus](https://github.com/CHENXCHEN/hexo-renderer-markdown-it-plus)和mathjax不适配，出现错位（即使关掉katex插件也是这样，如下图）：

![image](https://user-images.githubusercontent.com/26516581/55558888-995b2200-571f-11e9-8f37-856d2b63a6dd.png)

和katex也不适配，也有轻微错位：

![image](https://user-images.githubusercontent.com/26516581/55558959-bee82b80-571f-11e9-8fcd-3865a4fe71ff.png)

不知道是什么原因，升级大法也没用。

但是经我测试，[hexo-renderer-markdown-it](https://github.com/hexojs/hexo-renderer-markdown-it)对mathjax公式渲染支持还不错。

**Comment by xaoxuu** [comment]
测试的好详细好专业呀👍🏼我看用css能不能修复错位。
KaTeX比mathjax更好是吗？适合搭配什么渲染器来用？
不如你给我发一个md文件，里面写上需要适配的公式，我用example来测试怎么样？

**Comment by zhanghuimeng** [comment]
测试了很多，主要是因为[在material-x上使用KaTeX](https://www.micdz.cn/article/katex-on-material-x/)里的方法挂掉了，所以想写得尽量详细一些，看能不能把bug复现出来。

katex相比mathjax的主要优点是渲染快得多（速度比较可参见[Hexo 博客支持 KaTeX（回炉版）](http://lowrank.science/Hexo-KaTeX/)）（但是支持的公式稍微少一些）。很难说它适合搭配什么渲染器，不过大部分渲染器默认支持的都是mathjax（hexo-renderer-markdown-it-plus这种可能除外），所以katex需要特殊配置。也有人说把渲染器直接换成hexo-renderer-pandoc可以解决**一切**问题（参见[博客搭建及相关问题 - 数学公式](https://plmsmile.github.io/2017/10/16/24-hexo-problems/#%E9%85%8D%E7%BD%AE%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F)），但这是一个非常重量级的工具。

---

各种renderer渲染数学公式的时候容易出的问题包括：

1. 公式中`\\`换行无法渲染

这是因为`\\`会被转义成`"\"`。我用过的所有renderer都解决不了这个问题（最后我是用`{% raw %} ... {% endraw %}`解决的），但听说hexo-renderer-pandoc可以解决。

```latex
$$
\begin{eqnarray}
\nabla\cdot\vec{E} &=& \frac{\rho}{\epsilon_0} \\
\nabla\cdot\vec{B} &=& 0 \\
\nabla\times\vec{E} &=& -\frac{\partial B}{\partial t} \\
\nabla\times\vec{B} &=& \mu_0\left(\vec{J}+\epsilon_0\frac{\partial E}{\partial t} \right)
\end{eqnarray}
$$
```

比较有趣的一点是，如果同时使用hexo-renderer-markdown-it-plus和katex，在`hexo g`的时候会打印出大量与`\\`相关的错误信息，以及一些其他的错误信息：

```
$ hexo generate
INFO  [hexo-math] Using engine 'katex'
INFO  Start processing
LaTeX-incompatible input and strict mode is set to 'warn': In LaTeX, \\ or \newline does nothing in display mode [newLineInDisplayMode]
... （大概三四十行的样子）...
LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "，" used in math mode [unicodeTextInMathMode]
No character metrics for '，' in style 'Main-Regular'
```

2. 公式中的`_`和`*`被渲染成hexo斜体

这个bug在我用hexo-renderer-markdown-it的时候经常出现，在网上也看到有人说用hexo-renderer-marked的时候出现了，但我这里测试已经没有了。猜测hexo-renderer-marked的新版本对此进行了修正。其他renderer没测试过。

`{% raw %} ... {% endraw %}`同样可以解决此问题，网上还给出了很多修改渲染转义的方法。

```latex
$$R_{m \times n} = U_{m\times m}S_{m \times n}V_{n \times n}$$
```

3. 连续花括号

hexo-renderer-marked面对这种情况会直接崩溃，而且不是网页或者公式崩溃，是hexo崩溃，无法generate，十分烦人。hexo-renderer-markdown-it和hexo-renderer-markdown-it-plus都没问题。

```latex
$$\frac{1}{{(2\pi)}^\frac{D}{2}}$$
```

4. 行间公式的bug改好了，但是行内没改好

这其实不能算是一个bug，其发生原因大概是mathjax默认行内公式的delim没有`$`，所以单独设置`$`的时候需要重新配置转义之类的。（好像是这个原因，也有可能我说错了）

我目前知道的适配可能会出问题的公式就是这些，很可能不太全面。

**Comment by sxyugao** [comment]
@zhanghuimeng

我现在的博客用的也是 KaTeX，现在一般的公式还是能用的呀。

我的方案是按照 KaTeX 官网上的教程引用 js 和 css，不是像您一样使用 hexo-math。

**Comment by zhanghuimeng** [comment]
> @zhanghuimeng
> 
> 我现在的博客用的也是 KaTeX，现在一般的公式还是能用的呀。
> 
> 我的方案是按照 KaTeX 官网上的教程引用 js 和 css，不是像您一样使用 hexo-math。

其实我现在也没有用hexo-math了，而是用hexo-renderer-markdown-it-plus里带的katex，它本质上大概是把markdown-it这个renderer移植到了hexo下，然后自带了katex插件（本质上可能也是引用js和css？）

不过我发这个issue的本质原因是发现作者提供的hexo-renderer-markdown-it-plus这个公式解决方案可能有问题，如果你能更详细地说一下你是怎么解决的就好了。

**Comment by MicDZ** [comment]
经过实测，最新版本的hexo-renderer-markdown-it-plus公式渲染应该没有问题了

**Comment by MicDZ** [comment]
但是这种依赖第三方插件的方法还是不如自己手动安装katex

**Comment by MicDZ** [comment]
有条件还是应该自己安装katex，第三方插件不一定可靠
