### ISSUE TITLE
文章阅读统计数量错误

### ISSUE THREAD

**Issue by penndu** [volantis-x/hexo-theme-volantis#660]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

### 主题版本

您当前使用的版本为：________5.0_________

### 复现地址

- [ ] 文档官网源码本地运行存在异常。
- [x] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 ________https://dusays.com/friends/_________

### 截图

<details><summary>相关截图</summary>

![RC(SY U%7A BX4 $5Z`H(V4](https://user-images.githubusercontent.com/46226528/130467848-f3fc66e0-3927-4d68-8e1e-daefeae6726e.png)

![V4{UL3_Z7A5 }FL9TP24YU0](https://user-images.githubusercontent.com/46226528/130467858-41a7ca32-c5bc-4216-88d2-46b5451320bc.png)

![image](https://user-images.githubusercontent.com/46226528/130467893-e2513f0b-bea9-485a-805c-313325df3d2a.png)

</details>

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by inkss** [comment]
![Snipaste_2021-08-24_00-49-20](https://user-images.githubusercontent.com/31947043/130485883-4b5ea360-928f-4ea5-a06e-3fe86b1f26c3.png)

**Comment by penndu** [comment]
奇怪，我用的是waline做流量统计，后端用的自己的服务器和数据库。
