### ISSUE TITLE
滚动条会上下跳动

### ISSUE THREAD

**Issue by AutumnKite** [volantis-x/hexo-theme-volantis#663]
### 第一步：查阅文档 

- [x] 在 [Volantis](https://volantis.js.org) 文档中搜索关键词，并未找到相关内容。
- [x] 在 [Hexo](https://hexo.io/zh-cn/docs/) 官方文档中搜索关键词，并未找到相关内容。

### 第二步：测试原生代码 

打开终端，执行下面的命令：

```bash
git clone https://github.com/volantis-x/demo.git && cd demo && npm i && hexo s
```

结果是否能够正常运行？

测试结果是：A or B

- [x] A. 能正常运行，代表主题和当前环境配置都没有问题。
- [ ] B. 不能正常运行，代表主题或者环境配置有问题，建议在下方对应位置附上环境配置信息。

## 问题描述

如题，在滚动页面时，滚动条会上下跳动。用鼠标按住滚动条上下拉也会有这个问题，导致体验比较差。

文档官网就存在这个问题。

### 主题版本

您当前使用的版本为：5.0

### 复现地址

- [x] 文档官网源码本地运行存在异常。
- [ ] 文档官网源码本地运行不存在异常。请给出复现地址及源码仓库地址 _________________

### 截图

<details><summary>相关截图</summary>

</details>

### 浏览器、操作系统

Chrome 92.0.4515.159，Windows 10 19043.1165

### 配置文件 
<details><summary>配置文件</summary>

#### 站点配置文件

在这里粘贴 `blog/_config.yml` 中修改过的部分

```yml



```

#### 主题配置文件

在这里粘贴 `themes/volantis/_config.yml` 中修改过的部分

```yml


```

#### node.js & npm

在这里粘贴 `node -v && npm -v` 输出的信息

```


```

#### package.json

在这里粘贴 `npm ls --depth 0` 输出的信息

```

```

</details>

**Comment by MHuiG** [comment]
在问题没有修复之前, 你可以选择自行删除这几行,目前还在实验中

https://github.com/volantis-x/hexo-theme-volantis/blob/6c4f441c1491e9396f43b265a74991a35ba4b9b4/source/css/first.styl#L4-L9
