### ISSUE TITLE
content-visibility 有兼容性问题吧？

### ISSUE THREAD

**Issue by inkss** [volantis-x/hexo-theme-volantis#664]
## 日志报错

腾讯的前端性能监控抓到了一些 JS 错误：

- TypeError: undefined is not an object (evaIuating 'e.attributeStyleMap.set') @ (https://inkss.cn/blog/9a96536e/index.html:1:108545)        
- Error.message: undefined is not an object (evaIuating 'e.attributeStyleMap.set') \n  Error.stack: reserveSpace@https://inkss.cn/blog/9a96536e/index.html:1:108545\nhttps://inkss.cn/blog/9a96536e/index.html:1:108802\nforEach@[native code]\nhttps://inkss.cn/blog/9a96536e/index.html:1:108785

对方的 UA：

- Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Html5Plus/1.0  CSDNApp/4.14.0(iOS) AnalysysAgent/Hybrid

## Can i use

[![content-visibility](https://user-images.githubusercontent.com/31947043/130723652-f76b6de7-8df7-4937-bd63-001bcf5e01ea.png)](https://caniuse.com/?search=content-visibility)

**Comment by MHuiG** [comment]
？你什么时候见过css兼容性问题，控制台还会报错的，感觉是attributeStyleMap有兼容性问题

**Comment by inkss** [comment]
兼容这个是想说 content-visibility ios 全都不支持，而且需要的 chrome 版本很高才能有。这个错误的话倒是，加个判断就行。

**Comment by MHuiG** [comment]
safari 兼容不一直都很慢吗
