### ISSUE TITLE
material-x wiki 文件

### ISSUE THREAD

**Issue by Rogerspy** [volantis-x/hexo-theme-volantis#666]
你好，用了你之前的那个主题 material-x，因为做了比较大的改动所以就没有切换到 volantis 主题上来了。我想请问一下，之前的 material-x 主题 wiki 文件还在吗？可否发我一份？多谢多谢

**Comment by MHuiG** [comment]
你需要找到  你需要的版本 

https://github.com/volantis-x/hexo-theme-volantis/tags?after=2.6.3

然后下载源码

![image](https://user-images.githubusercontent.com/38281581/133869458-76f8e678-de5f-4de5-832d-d44bb10b7735.png)


<blockquote><img src="https://repository-images.githubusercontent.com/108073634/e60b3434-53b7-463d-9a7f-a0e1f5723368" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/hexo-theme-volantis">Tags · volantis-x/hexo-theme-volantis</a></strong></div><div>A Wonderful Theme for Hexo  https://vlts.cc  https://volantis.js.org - Tags · volantis-x/hexo-theme-volantis</div></blockquote>
