### ISSUE TITLE
提供背景固定功能

### ISSUE THREAD

**Issue by MeowBot233** [volantis-x/hexo-theme-volantis#668]
## 需求描述

在v4中将backstretch中position属性设置为fixed可以实现背景固定，不随网页滚动。
在v5中，backstretch被移除，新增的parallax并不能实现背景固定，希望可以恢复backstretch或者增加背景固定功能。

**Comment by MHuiG** [comment]
https://volantis-x.js.org/

https://github.com/volantis-x/volantis-x.github.io/blob/165b1d689970166b8ca529202a372c98dc4e3b75/_config.volantis.yml#L297-L299

<blockquote><img src="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/android-chrome-192x192.png" width="48" align="right"><div><img src="https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/favicon-16x16.png" height="14"> Volantis</div><div><strong><a href="https://volantis.js.org/">Volantis</a></strong></div><div>Volantis is a feature-rich and highly modular Hexo blog theme. Thanks to its powerful modularity, you can easily build a minimalist style blog, or you can build a large-scale comprehensive blog with m</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/1d6a48dfc57ede0e9e030a4f526607d1bd944a8188c4bdb1d0076e37210fe0b8/volantis-x/volantis-x.github.io" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/volantis-x/volantis-x.github.io">volantis-x.github.io/_config.volantis.yml at 165b1d689970166b8ca529202a372c98dc4e3b75 · volantis-x/volantis-x.github.io</a></strong></div><div>Volantis 开发测试仓库 | Volantis Test Repo For Development | 请不要PR到此仓库 | Do NOT PR To this Repo | https://volantis-x.js.org - volantis-x.github.io/_config.volantis.yml at 165b1d689970166b8ca529202a372c98...</div></blockquote>
