### ISSUE TITLE
文档评论

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#67]
https://xaoxuu.com/wiki/material-x/

**Comment by cwlrk** [comment]
标签那个标志显示为#号啊

**Comment by xaoxuu** [comment]
> @CWLboss
> 标签那个标志显示为#号啊

所有图标都可以自定义

**Comment by MichaelVector** [comment]
博主看看我的博客咋样，把我的链接也加进去吧
name: Michael Vector
avatar:   https://tuchuang-1258561688.cos.ap-chengdu.myqcloud.com/%E5%A4%B4%E5%83%8F.jpg
url:    https://michaelvector.github.io

**Comment by RaibFlee** [comment]
博主，博客不蒜子统计功能怎么用的？

**Comment by xaoxuu** [comment]
> @RaibFlee
> 博主，博客不蒜子统计功能怎么用的？

默认就开启了啊

**Comment by xaoxuu** [comment]
> @MichaelVector
> 博主看看我的博客咋样，把我的链接也加进去吧
> name: Michael Vector
> avatar:   https://tuchuang-1258561688.cos.ap-chengdu.myqcloud.com/%E5%A4%B4%E5%83%8F.jpg
> url:    https://michaelvector.github.io

已加

**Comment by RaibFlee** [comment]
博主，为什么写文章的时候，标题没有正常显示，前面还是有个#号

**Comment by RaibFlee** [comment]
博主搜索功能也用不了啊

**Comment by 82kg** [comment]
可以不要封面吗？ 或者 2秒后跳到正文

**Comment by xaoxuu** [comment]
> @RaibFlee
> 博主，为什么写文章的时候，标题没有正常显示，前面还是有个#号

你截个图看看

**Comment by 82kg** [comment]
不好意思，没仔细看文档

**Comment by RaibFlee** [comment]
![图片](https://user-images.githubusercontent.com/44354162/56505324-f0e5f400-654d-11e9-9cfe-12a005b6fff8.png)
标题就像这样不能正常显示，博主

**Comment by 82kg** [comment]
GOOD

**Comment by 82kg** [comment]
你好 博主，有个小问题，新浪分享的时候 提示  414 Request-URI Too Large，这要怎么解决啊

**Comment by xaoxuu** [comment]
> @RaibFlee
> ![图片](https://user-images.githubusercontent.com/44354162/56505324-f0e5f400-654d-11e9-9cfe-12a005b6fff8.png)
> 标题就像这样不能正常显示，博主

`#` 后面要加空格

**Comment by RaibFlee** [comment]
我那个空格忘加了，不好意思，但是博主我那个网站的搜索功能好像还是没用啊

**Comment by xaoxuu** [comment]
> @RaibFlee
> 我那个空格忘加了，不好意思，但是博主我那个网站的搜索功能好像还是没用啊

依赖包安装了没？ [# 手动安装](https://xaoxuu.com/wiki/material-x/#B-%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85)

**Comment by RaibFlee** [comment]
装了

**Comment by ResidualNight** [comment]
修改了基本配置，文章是我的，但基本配置（侧边栏、头像）还是博主https://xaoxuu.com/的。是哪里出错了吗？:-)

**Comment by ResidualNight** [comment]
修改了基本配置，文章是我的，但基本配置（侧边栏、头像）还是博主https://xaoxuu.com/
的。是哪里出错了吗？:-)

**Comment by ResidualNight** [comment]
还有就是在localhost:4000里运行正常（基本配置仍然不是我的）
但是同步到GitHub里就会出现这样https://residualnight.github.io/

**Comment by RaibFlee** [comment]
@xaoxuu
找到原因了，博主你配置文件里少了点东西，我这里就用不了搜索

**Comment by ZeusYang** [comment]
你好，感谢你的materialX主题。
我的博客：https://yangwc.com/，博客名YangWC，暗色的主题。

**Comment by ZeusYang** [comment]
你好，感谢你的materialX主题。
我的博客名YangWC，暗色的主题。
地址：https://yangwc.com/

**Comment by dingsheng123** [comment]
> @xaoxuu
> 找到原因了，博主你配置文件里少了点东西，我这里就用不了搜索

@RaibFlee 你好，想问下少了什么东西？我这搜索也使用不了。。。

**Comment by RaibFlee** [comment]
在根目录下的_config.yml添加
```
search:
  path: search.xml
  field: post
  content: true
```
@dingsheng123

**Comment by xaoxuu** [comment]
> @RaibFlee
> 在根目录下的_config.yml添加
> ```
> search:
>   path: search.xml
>   field: post
>   content: true
> ```
> @dingsheng123 

我的根目录`_config.yml`里面没有这一段

**Comment by xaoxuu** [comment]
> @ZeusYang
> 你好，感谢你的materialX主题。
> 我的博客名YangWC，暗色的主题。
> 地址：https://yangwc.com/

已经加到示例中，谢谢支持

**Comment by RaibFlee** [comment]
那我就不太清楚了，反正我这少了这段搜索就用不了
@xaoxuu

**Comment by TRHX** [comment]
博主，创建标签页面，应该是 layout: tag 而不是 layout: tags，写成 tags 不会生效哟

**Comment by chemicalfiber** [comment]
博主，“关于”页面应该放在哪个文件夹呢？我应用了您的主题之后，试着点了一下“关于”，但是浏览器显示找不到“/about/”，我也试着建立了一篇名为about的post，依然没用。那么这个“about”到底是目录还是一个文件呢？

**Comment by 82kg** [comment]
> @chemicalfiber
> 博主，“关于”页面应该放在哪个文件夹呢？我应用了您的主题之后，试着点了一下“关于”，但是浏览器显示找不到“/about/”，我也试着建立了一篇名为about的post，依然没用。那么这个“about”到底是目录还是一个文件呢？

source目录里 新建about文件夹，about文件夹内新建 index.md文件，内容参照博主给出的示例

**Comment by xaoxuu** [comment]
> @TRHX
> 博主，创建标签页面，应该是 layout: tag 而不是 layout: tags，写成 tags 不会生效哟

我写错了，稍后更新一下文档

**Comment by xaoxuu** [comment]
> @chemicalfiber
> 博主，“关于”页面应该放在哪个文件夹呢？我应用了您的主题之后，试着点了一下“关于”，但是浏览器显示找不到“/about/”，我也试着建立了一篇名为about的post，依然没用。那么这个“about”到底是目录还是一个文件呢？

见源码：https://github.com/xaoxuu/blog-example

**Comment by PHYSPAT** [comment]
请问为什么我的博客更新后顶部会有一堆 [object object]?
![](https://i.loli.net/2019/05/14/5cdad6f71a5bb84472.png)

**Comment by Johnliu520** [comment]
博主你的这个wiki 主题是否考虑开源？

**Comment by xaoxuu** [comment]
> @TLE666
> 请问为什么我的博客更新后顶部会有一堆 [object object]?
> ![](https://i.loli.net/2019/05/14/5cdad6f71a5bb84472.png)

`import`使用方法改了，详见：[#Import](https://xaoxuu.com/wiki/material-x/config/index.html#Import)

**Comment by xaoxuu** [comment]
> @weiaiming
> 博主你的这个wiki 主题是否考虑开源？

https://github.com/xaoxuu/hexo-theme-vuex

**Comment by PHYSPAT** [comment]
博主，请问封面背景怎么设置？

**Comment by PHYSPAT** [comment]
还有为什么我的博客标签和分类页面没有啊？需要手动增加吗？？
(tle666.github.io)

**Comment by xaoxuu** [comment]
> @TLE666
> 博主，请问封面背景怎么设置？

最新版默认就有了

**Comment by xaoxuu** [comment]
> @TLE666
> 还有为什么我的博客标签和分类页面没有啊？需要手动增加吗？？
> (tle666.github.io)

[#独立页面](https://xaoxuu.com/wiki/material-x/pages/index.html)

**Comment by jared0612** [comment]
你好，你是怎么解决gitalk评论因为文章名过长导致的错误的

**Comment by PHYSPAT** [comment]
> @xaoxuu
> > @TLE666
> > 还有为什么我的博客标签和分类页面没有啊？需要手动增加吗？？
> > (tle666.github.io)
> 
> [#独立页面](https://xaoxuu.com/wiki/material-x/pages/index.html)

终于好了，万分感谢！

**Comment by PHYSPAT** [comment]
为什么我的友链按照您上面的方法会 404 ?

**Comment by xaoxuu** [comment]
> @TLE666
> 为什么我的友链按照您上面的方法会 404 ?

也需要手动创建页面

**Comment by xaoxuu** [comment]
> @caixp
> 你好，你是怎么解决gitalk评论因为文章名过长导致的错误的

我没有解决，我不知道有这个问题

**Comment by PHYSPAT** [comment]
> @xaoxuu
> > @TLE666
> > 为什么我的友链按照您上面的方法会 404 ?
> 
> 也需要手动创建页面

我是这样的啊，算是手动创建了吧
[1](https://i.loli.net/2019/05/20/5ce2b6564935686532.png)
[2](https://i.loli.net/2019/05/20/5ce2b65675d9984073.png)
