### ISSUE TITLE
博文内容不加载，不知道为什么

### ISSUE THREAD

**Issue by git-life-everywhere** [volantis-x/hexo-theme-volantis#7]
![image](https://user-images.githubusercontent.com/15192691/45601479-3a161880-ba40-11e8-8d5c-49e774246d01.png)

**Comment by xaoxuu** [comment]
向下滑动一些也是空白吗？

**Comment by yangtao2o** [comment]
我的也出现了类似的问题，初始的时候会出现如上空白，往下滑动内容才会加载出来

**Comment by yangtao2o** [comment]
我发现我这边的原因是： `<!--more-->`的前面需要些正文内容，不然会被忽略掉，改完之后，就可以正常加载了

**Comment by xaoxuu** [comment]
@yangtao2o 是的，目前只能这样。
