### ISSUE TITLE
Valine 评论系统失效了

### ISSUE THREAD

**Issue by LiYanan2004** [volantis-x/hexo-theme-volantis#74]
cdn的那个js提示HTTPS不安全，连接不到

**Comment by LiYanan2004** [comment]
![image](https://user-images.githubusercontent.com/37542129/56450457-e44c7a80-6358-11e9-9e09-113aad0bf128.png)

**Comment by xaoxuu** [comment]
jsdelivr挂了，建议等等看

**Comment by xaoxuu** [comment]
#76
