### ISSUE TITLE
图标失效

### ISSUE THREAD

**Issue by mofiter** [volantis-x/hexo-theme-volantis#75]
忽然发现图标全部失效了，应该是都找不到，全部变成小方框了，这个需要怎么修改吗
![Snip20190420_2](https://user-images.githubusercontent.com/24542302/56450699-6ee1a980-635a-11e9-9aa4-3cbcbfb77eb6.png)

**Comment by xaoxuu** [comment]
是你网络问题吧

**Comment by mofiter** [comment]
并不是我网络的问题，我查看了 wiki 上使用主题的很多博客，都不显示图标了，我让别人访问这些博客，也不显示图标

**Comment by xaoxuu** [comment]
哦，是我那里有缓存的原因，我刷新了一下确实没有了

**Comment by xaoxuu** [comment]
#76 2019年4月20日：近期关于网页加载异常的问题
