### ISSUE TITLE
能否将<script>加到 <body>和<head>之间

### ISSUE THREAD

**Issue by LiYanan2004** [volantis-x/hexo-theme-volantis#77]
希望开发者支持一下功能，可以提升网站速度。 具体在这里：https://instant.page/
![image](https://user-images.githubusercontent.com/37542129/56454852-9c921700-6389-11e9-8f48-5a3674033025.png)

**Comment by xaoxuu** [comment]
用`import`即可

**Comment by LiYanan2004** [comment]
fastclick功能有什么用？？

**Comment by xaoxuu** [comment]
是针对移动端优化的

**Comment by xaoxuu** [comment]
instant.page我直接集成到主题里算了

**Comment by LiYanan2004** [comment]
好呀！太感谢开发者了！！

**Comment by xaoxuu** [comment]
已经更新了，这确实是个好东西，感谢分享🤝

**Comment by LiYanan2004** [comment]
哈哈哈哈，好的，感谢开发者这么快速的更新！🤝
