### ISSUE TITLE
问个排版的问题

### ISSUE THREAD

**Issue by MichaelVector** [volantis-x/hexo-theme-volantis#78]
小白开始学习博客，关于主题，怎么没有在官方文档里看到首页布局排版，我的首页博客文章全部都是完整打开状态，我看其他有的人只有五六行的高度，然后左下角有个阅读更多，实在找了很久不知道怎么改成简要版本，文章带个图或者说几句话，有个阅读更多才能看到完整文章。求大神解答下～

**Comment by xaoxuu** [comment]
[文档：页面配置 -> 文章摘要](https://xaoxuu.com/wiki/material-x/front-matter/index.html#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81)
