### ISSUE TITLE
还有个小问题请教，layout.less和_color.less

### ISSUE THREAD

**Issue by MichaelVector** [volantis-x/hexo-theme-volantis#79]
为什么修改了_layout.less和_color.less，然后重新hexo clean然后d -g后，运行hexo s什么都没变呢，git后也是一模一样啥都没变，颜色配置和布局设置都生效不了，什么问题呢求大神解答一下哈，实在找不到问题所在

**Comment by melodyjerry** [comment]
@MichaelVector  请问你是怎么解决的

**Comment by MichaelVector** [comment]
@melodyjerry 设置文档里最上方有个使用本地文件，注意下那里，如果链接是云端的，注销掉使用本地

**Comment by melodyjerry** [comment]
@MichaelVector ok，可以了

**Comment by xaoxuu** [comment]
从1.2.6版本开始就已经默认关闭了CDN，更新到最新版本就不会出现这种情况了。
