### ISSUE TITLE
问两个问题哈

### ISSUE THREAD

**Issue by MichaelVector** [volantis-x/hexo-theme-volantis#80]
之前用NEXT知道有个网页网页插件，Canvas-nest，这个插件怎么用代码插入呢，以后会植入这个主题吗，像bool一样开关的选项。
另外求问这个主题可以换背景吗，静态图片或者动态图片背景？

**Comment by xaoxuu** [comment]
可以

**Comment by MichaelVector** [comment]
还有个建议哈，这个页脚好难看的

![屏幕快照 2019-04-24 16 46 54](https://user-images.githubusercontent.com/11750854/56645663-b183e880-66b0-11e9-92d6-fcb016a15310.jpg)

或者植入卜算子计数，记访客量啊网页访问数量，或者就流行的本站已运行时间之类的

参考NEXT：

![屏幕快照 2019-04-24 16 49 51](https://user-images.githubusercontent.com/11750854/56645934-30792100-66b1-11e9-90d4-33f433c38ca6.jpg)
![屏幕快照 2019-04-24 16 50 33](https://user-images.githubusercontent.com/11750854/56645935-3111b780-66b1-11e9-9285-178c1f50eef5.jpg)
![屏幕快照 2019-04-24 16 50 45](https://user-images.githubusercontent.com/11750854/56645951-35d66b80-66b1-11e9-91e8-31232f854b1f.jpg)

个人觉得这个最好看：

![屏幕快照 2019-04-24 16 50 58](https://user-images.githubusercontent.com/11750854/56646000-47b80e80-66b1-11e9-99a6-ba582c4b2555.jpg)

虽然知道每个人喜好不一样，我的建议是页脚可以通过开关的方式可以自定义显示的选项是最好的啦，支持作者！希望可以做的更好！辛苦了！

**Comment by xaoxuu** [comment]
总字数我觉得没意义，我不会关心一个人的网站有多少个字。
访客数和人次我觉得显示一个就好了，两个都显示就啰嗦了。
❤️我不知道有什么含义。“|“用来分割多条信息，我选择了用逗号和句号组成一句通顺的话。
host by coding pages是coding免费用户必须打的广告，我也不关心一个人的网站是host到哪里，host到coding也有加载很慢的，host到github也有加载很快的。
theme by MaterialX则是给主题打广告，非强制的，我看到有的网友那里去掉了这个，留言板里就有人问主题是什么，所以这个信息也有一点意义，省的一个个回答了。本来我还想加上主题版本，觉得意义不够大就没有加。
运行时间，这个我觉得也没有意义，即使网站运行的再久，内容不符合口味或者满屏广告我一样会关掉再也不会打开。
阅读时长？这个我觉得更没有意义，一方面每个人的阅读速度都不一样，另一方面这又不是文章必须从上到下顺序匀速阅读，除非你的整个博客是一部连载的电子书。

**当视野内的无效信息过多的时候，有效信息就显得不那么容易找了。**
一般人面对一个陌生的网站的时候，不会有那么多耐心，废话太多、干扰信息太多都会影响阅读，从而导致被认为没有价值而关掉。
并且有些东西也会拖慢网页的加载速度。

<hr>

以上是我的个人看法也是主题的设计理念（简洁实用），当然，易于定制也是理念之一，所以后期更新我会加入选择。

**Comment by MichaelVector** [comment]
多谢回复！期待做得更好！

**Comment by inkss** [comment]
> 虽然知道每个人喜好不一样，我的建议是页脚可以通过开关的方式可以自定义显示的选项是最好的啦，支持作者！希望可以做的更好！辛苦了！

@MichaelVector  做成这个样子，满足强迫症

![image](https://user-images.githubusercontent.com/31947043/70388879-cd938a80-19f2-11ea-8008-b672bfbbfee9.png)

**Comment by MichaelVector** [comment]
> > 虽然知道每个人喜好不一样，我的建议是页脚可以通过开关的方式可以自定义显示的选项是最好的啦，支持作者！希望可以做的更好！辛苦了！
> 
> @MichaelVector 做成这个样子，满足强迫症
> 
> ![image](https://user-images.githubusercontent.com/31947043/70388879-cd938a80-19f2-11ea-8008-b672bfbbfee9.png)

大佬你这个怎么做的啊，我是觉得有些信息看个人可以选择性添加挺好的，这是你自己添加的吗？markdown写的？

**Comment by inkss** [comment]
可以参考下这个：
aaf719a56541c475c3ac53430822a85d7c1afd29

**Comment by inkss** [comment]
> 大佬你这个怎么做的啊，我是觉得有些信息看个人可以选择性添加挺好的，这是你自己添加的吗？markdown写的？

@MichaelVector ，他这个主要时修改 `footer.ejs` 这块儿，简单粗暴点就是直接往这儿加。

https://github.com/xaoxuu/hexo-theme-material-x/blob/412f13acea385e4d2180bab5b2fb4e0860b1d6c3/layout/_partial/footer.ejs#L23-L34

然后那个 `<%- __('footer.use') %> ` 是读国际化中的信息，所以也可以在这儿加，我一开始是直接改这里面的信息的，这儿可以用`<br>`啊什么的，各种换行。

https://github.com/xaoxuu/hexo-theme-material-x/blob/412f13acea385e4d2180bab5b2fb4e0860b1d6c3/languages/zh-CN.yml#L23-L29

或者，你可以参考参考我改的这个：[inkss](https://github.com/inkss/hexo-theme-material-x) ，因为写的太长的话，手机下的显示效果不太好看，所以我这儿是单独用样式文件控制了。

![show](https://user-images.githubusercontent.com/31947043/70612754-7dab0280-1c42-11ea-9adb-435f3eee1660.gif)

**Comment by xaoxuu** [comment]
现在增加了`copyright: x x x`字段用于网站页脚。
