### ISSUE TITLE
使用主题时links.ejs报错

### ISSUE THREAD

**Issue by ilittlemoe** [volantis-x/hexo-theme-volantis#82]
你好：

    这个问题我反复测试过，也看过几遍文档，下载过博客源码进行比对，但问题我依然无法排除。

以下是我运行`hexo clean && hexo g && hexo s`在hexo g步骤打印出来的信息：
```bash
INFO  Deleted database.
INFO  Deleted public folder.
INFO  Start processing
INFO  Files loaded in 595 ms
ERROR /home/用户名/Blog_20190518/themes/material-x/layout/links.ejs:20
    18|                   <% (group.items||[]).forEach(function(item){ %>
    19|                     <a class='friend-card' style='background:<%- item.backgroundColor %>; color:<%- item.textColor %>'
 >> 20|                       target="_blank" rel="external nofollow noopener noreferrer" href='<%- url_for(item.url) %>'>
    21|                       <div class='friend-left'>
    22|                         <img class='avatar' src='<%- theme.avatar_placeholder %>' data-echo='<%- url_for(item.avatar ? item.avatar : "https://img.vim-cn.com/a4/87a96e2e01b1180bba1e76e190df5220378c1a.png") %>'/>
    23|                       </div>

Cannot read property '0' of null
TypeError: /home/用户名/Blog_20190518/themes/material-x/layout/links.ejs:20
    18|                   <% (group.items||[]).forEach(function(item){ %>                    
    19|                     <a class='friend-card' style='background:<%- item.backgroundColor %>; color:<%- item.textColor %>'                                                            
 >> 20|                       target="_blank" rel="external nofollow noopener noreferrer" href='<%- url_for(item.url) %>'>                                                                
    21|                       <div class='friend-left'>                                      
    22|                         <img class='avatar' src='<%- theme.avatar_placeholder %>' data-echo='<%- url_for(item.avatar ? item.avatar : "https://img.vim-cn.com/a4/87a96e2e01b1180bba1e76e190df5220378c1a.png") %>'/>                                                             
    23|                       </div>                                                         

Cannot read property '0' of null                                                             
    at Object.urlForHelper (/home/用户名/Blog_20190518/node_modules/hexo/lib/plugins/helper/url_for.js:6:11)                                                                              
    at eval (eval at compile (/home/用户名/Blog_20190518/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:56:17)                                                                          
    at Array.forEach (<anonymous>)                                                           
    at eval (eval at compile (/home/用户名/Blog_20190518/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:48:26)                                                                          
    at Array.forEach (<anonymous>)                                                           
    at eval (eval at compile (/home/用户名/Blog_20190518/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:24:25)                                                                          
    at returnedFn (/home/用户名/Blog_20190518/node_modules/ejs/lib/ejs.js:653:17)            
    at Theme._View.View._compiled.locals [as _compiled] (/home/用户名/Blog_20190518/node_modules/hexo/lib/theme/view.js:125:48)                                                           
    at Theme._View.View.View.render (/home/用户名/Blog_20190518/node_modules/hexo/lib/theme/view.js:30:15)                                                                                
    at route.set (/home/用户名/Blog_20190518/node_modules/hexo/lib/hexo/index.js:394:29)     
    at tryCatcher (/home/用户名/Blog_20190518/node_modules/bluebird/js/release/util.js:16:23)
    at /home/用户名/Blog_20190518/node_modules/bluebird/js/release/method.js:15:34           
    at RouteStream._read (/home/用户名/Blog_20190518/node_modules/hexo/lib/hexo/router.js:134:3)                                                                                          
    at RouteStream.Readable.read (_stream_readable.js:462:10)                                
    at resume_ (_stream_readable.js:945:12)                                                  
    at processTicksAndRejections (internal/process/task_queues.js:81:17)                     
INFO  Generated: content.json
INFO  Generated: search.xml
INFO  Generated: index.html
......
```
这是我友链内容（/source/friends/index.md）：
```markdown
---
layout: links     # 必须
title: 我的朋友们   # 可选，这是友链页的标题
links:
  - group: 技术大佬
    icon: fas fa-user-tie
    items:
    - name:     # 博客名
      avatar:   # 头像链接
      url:      # 博客链接
      backgroundColor: '#3E74C9' # 卡片背景颜色
      textColor: '#fff'  # 卡片文字颜色
      tags:     # 标签
      - 标签1
      - 标签2
  - group: 分组2
    icon: fas fa-user-tie
    items:
    - name:     # 博客名
      avatar:   # 头像链接
      url:      # 博客链接
      backgroundColor: '#3E74C9' # 卡片背景颜色
      textColor: '#fff'  # 卡片文字颜色
      tags:     # 标签
      - 标签1
      - 标签2
---

这里可以写友链页面下方的文字备注，例如自己的友链规范、示例等。

```

下面是我的layout/links.ejs的内容，我对比过，里面似乎没有错误，都是一样的：
```
<div class='l_main<%- page.sidebar == false ? ' no_sidebar' : '' %>'>
  <article id="<%= page.layout %>" class="post white-box article-type-<%= page.layout %>" itemscope itemprop="blogPost">
    <%- partial('_partial/meta',{post:page, position:'header'}) %>
      <section class="article typo l_friends">
        <% if (page.links){ %>
          <% (page.links||[]).forEach(function(group){ %>
            <% if(group.items) { %>
              <div class='friends-group'>
                <% if(group.group) { %>
                  <h2 class='friend-header'>
                    <% if (group.icon) { %>
                      <i class="<%= group.icon %> fa-fw" aria-hidden="true"></i>
                    <%} %>
                    <%= group.group %>
                  </h2>
                <%} %>
                <div class='friend-content'>
                  <% (group.items||[]).forEach(function(item){ %>
                    <a class='friend-card' style='background:<%- item.backgroundColor %>; color:<%- item.textColor %>'
                      target="_blank" rel="external nofollow noopener noreferrer" href='<%- url_for(item.url) %>'>
                      <div class='friend-left'>
                        <img class='avatar' src='<%- theme.avatar_placeholder %>' data-echo='<%- url_for(item.avatar ? item.avatar : "https://img.vim-cn.com/a4/87a96e2e01b1180bba1e76e190df5220378c1a.png") %>'/>
                      </div>
                      <div class='friend-right'>
                        <p class="friend-name"><%- item.name %></p>
                        <% if(item.tags){ %>
                          <div class='friend-tags-wrapper'>
                          <% (item.tags||[]).forEach(function(tag){ %>
                            <p class="tags"><i class="fas fa-hashtag fa-fw" aria-hidden="true"></i><%= tag %></p>
                          <% }) %>
                          </div>
                        <% } %>
                      </div>
                    </a>
                  <% }) %>
                </div>
              </div>
            <%} %>
          <% }) %>
        <% } %>
        <br><hr>
        <%- page.content %>
      </section>
  </article>

  <%- partial('_third-party/comments') %>

</div>
<%- partial('_partial/side') %>
<%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
```
使用说明中的依赖我已经安装过了。

使用环境：
npm v6.9.0
hexo: v3.8.0
```hexo-cli: 1.1.0
os: Linux 4.19.42-1-MANJARO linux x64
node: 11.15.0
v8: 7.0.276.38-node.19
uv: 1.28.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 67
nghttp2: 1.36.0
napi: 4
llhttp: 1.1.1
http_parser: 2.8.0
openssl: 1.1.1b
cldr: 35.1
icu: 64.2
tz: 2019a
unicode: 12.1
```
node v11.15.0

**Comment by xaoxuu** [comment]
直接用实际中的友链页的md文件也会报错吗

Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: ilittlemoe <notifications@github.com>
发送时间: Saturday, May 18, 2019 4:08:47 PM
收件人: xaoxuu/hexo-theme-material-x
抄送: Subscribed
主题: [xaoxuu/hexo-theme-material-x] 使用主题时links.ejs报错 (#82)


你好：

这个问题我反复测试过，也看过几遍文档，下载过博客源码进行比对，但问题我依然无法排除。



以下是我运行hexo clean && hexo g && hexo s在hexo g步骤打印出来的信息：

INFO  Deleted database.

INFO  Deleted public folder.

INFO  Start processing

INFO  Files loaded in 595 ms

ERROR /home/revive/Blog_20190518/themes/material-x/layout/links.ejs:20

    18|                   <% (group.items||[]).forEach(function(item){ %>

    19|                     <a class='friend-card' style='background:<%- item.backgroundColor %>; color:<%- item.textColor %>'

 >> 20|                       target="_blank" rel="external nofollow noopener noreferrer" href='<%- url_for(item.url) %>'>

    21|                       <div class='friend-left'>

    22|                         <img class='avatar' src='<%- theme.avatar_placeholder %>' data-echo='<%- url_for(item.avatar ? item.avatar : "https://img.vim-cn.com/a4/87a96e2e01b1180bba1e76e190df5220378c1a.png") %>'/>

    23|                       </div>



Cannot read property '0' of null

TypeError: /home/revive/Blog_20190518/themes/material-x/layout/links.ejs:20

    18|                   <% (group.items||[]).forEach(function(item){ %>

    19|                     <a class='friend-card' style='background:<%- item.backgroundColor %>; color:<%- item.textColor %>'

 >> 20|                       target="_blank" rel="external nofollow noopener noreferrer" href='<%- url_for(item.url) %>'>

    21|                       <div class='friend-left'>

    22|                         <img class='avatar' src='<%- theme.avatar_placeholder %>' data-echo='<%- url_for(item.avatar ? item.avatar : "https://img.vim-cn.com/a4/87a96e2e01b1180bba1e76e190df5220378c1a.png") %>'/>

    23|                       </div>



Cannot read property '0' of null

    at Object.urlForHelper (/home/revive/Blog_20190518/node_modules/hexo/lib/plugins/helper/url_for.js:6:11)

    at eval (eval at compile (/home/revive/Blog_20190518/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:56:17)

    at Array.forEach (<anonymous>)

    at eval (eval at compile (/home/revive/Blog_20190518/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:48:26)

    at Array.forEach (<anonymous>)

    at eval (eval at compile (/home/revive/Blog_20190518/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:24:25)

    at returnedFn (/home/revive/Blog_20190518/node_modules/ejs/lib/ejs.js:653:17)

    at Theme._View.View._compiled.locals [as _compiled] (/home/revive/Blog_20190518/node_modules/hexo/lib/theme/view.js:125:48)

    at Theme._View.View.View.render (/home/revive/Blog_20190518/node_modules/hexo/lib/theme/view.js:30:15)

    at route.set (/home/revive/Blog_20190518/node_modules/hexo/lib/hexo/index.js:394:29)

    at tryCatcher (/home/revive/Blog_20190518/node_modules/bluebird/js/release/util.js:16:23)

    at /home/revive/Blog_20190518/node_modules/bluebird/js/release/method.js:15:34

    at RouteStream._read (/home/revive/Blog_20190518/node_modules/hexo/lib/hexo/router.js:134:3)

    at RouteStream.Readable.read (_stream_readable.js:462:10)

    at resume_ (_stream_readable.js:945:12)

    at processTicksAndRejections (internal/process/task_queues.js:81:17)

INFO  Generated: content.json

INFO  Generated: search.xml

INFO  Generated: index.html

......

这是我友链内容（/source/friends/index.md）：

---

layout: links     # 必须

title: 我的朋友们   # 可选，这是友链页的标题

links:

  - group: 技术大佬

    icon: fas fa-user-tie

    items:

    - name:     # 博客名

      avatar:   # 头像链接

      url:      # 博客链接

      backgroundColor: '#3E74C9' # 卡片背景颜色

      textColor: '#fff'  # 卡片文字颜色

      tags:     # 标签

      - 标签1

      - 标签2

  - group: 分组2

    icon: fas fa-user-tie

    items:

    - name:     # 博客名

      avatar:   # 头像链接

      url:      # 博客链接

      backgroundColor: '#3E74C9' # 卡片背景颜色

      textColor: '#fff'  # 卡片文字颜色

      tags:     # 标签

      - 标签1

      - 标签2

---



这里可以写友链页面下方的文字备注，例如自己的友链规范、示例等。



下面是我的layout/links.ejs的内容，我对比过，里面似乎没有错误，都是一样的：

<div class='l_main<%- page.sidebar == false ? ' no_sidebar' : '' %>'>

  <article id="<%= page.layout %>" class="post white-box article-type-<%= page.layout %>" itemscope itemprop="blogPost">

    <%- partial('_partial/meta',{post:page, position:'header'}) %>

      <section class="article typo l_friends">

        <% if (page.links){ %>

          <% (page.links||[]).forEach(function(group){ %>

            <% if(group.items) { %>

              <div class='friends-group'>

                <% if(group.group) { %>

                  <h2 class='friend-header'>

                    <% if (group.icon) { %>

                      <i class="<%= group.icon %> fa-fw" aria-hidden="true"></i>

                    <%} %>

                    <%= group.group %>

                  </h2>

                <%} %>

                <div class='friend-content'>

                  <% (group.items||[]).forEach(function(item){ %>

                    <a class='friend-card' style='background:<%- item.backgroundColor %>; color:<%- item.textColor %>'

                      target="_blank" rel="external nofollow noopener noreferrer" href='<%- url_for(item.url) %>'>

                      <div class='friend-left'>

                        <img class='avatar' src='<%- theme.avatar_placeholder %>' data-echo='<%- url_for(item.avatar ? item.avatar : "https://img.vim-cn.com/a4/87a96e2e01b1180bba1e76e190df5220378c1a.png") %>'/>

                      </div>

                      <div class='friend-right'>

                        <p class="friend-name"><%- item.name %></p>

                        <% if(item.tags){ %>

                          <div class='friend-tags-wrapper'>

                          <% (item.tags||[]).forEach(function(tag){ %>

                            <p class="tags"><i class="fas fa-hashtag fa-fw" aria-hidden="true"></i><%= tag %></p>

                          <% }) %>

                          </div>

                        <% } %>

                      </div>

                    </a>

                  <% }) %>

                </div>

              </div>

            <%} %>

          <% }) %>

        <% } %>

        <br><hr>

        <%- page.content %>

      </section>

  </article>



  <%- partial('_third-party/comments') %>



</div>

<%- partial('_partial/side') %>

<%- partial('_partial/footer', null, {cache: !config.relative_link}) %>



使用说明中的依赖我已经安装过了。

使用环境：
npm v6.9.0
hexo: v3.8.0

os: Linux 4.19.42-1-MANJARO linux x64

node: 11.15.0

v8: 7.0.276.38-node.19

uv: 1.28.0

zlib: 1.2.11

brotli: 1.0.7

ares: 1.15.0

modules: 67

nghttp2: 1.36.0

napi: 4

llhttp: 1.1.1

http_parser: 2.8.0

openssl: 1.1.1b

cldr: 35.1

icu: 64.2

tz: 2019a

unicode: 12.1



node v11.15.0

―

**Comment by ilittlemoe** [comment]
@xaoxuu  
哈哈，解决了，感谢你的提醒，我没有想过要用真实链接，现在已经解决了。

建议在文档中说明一下这个情况帮助别人更好理解，我弄了好久总是不成功，就差重新安装hexo了。

最后谢谢你的回复～

**Comment by ilittlemoe** [comment]
@xaoxuu

**Comment by xaoxuu** [comment]
好的，我有时间了更新一下

Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: ilittlemoe <notifications@github.com>
发送时间: Saturday, May 18, 2019 4:31:26 PM
收件人: xaoxuu/hexo-theme-material-x
抄送: Mr. X; Mention
主题: Re: [xaoxuu/hexo-theme-material-x] 使用主题时links.ejs报错 (#82)


@xaoxuu<https://github.com/xaoxuu>

―

**Comment by ilittlemoe** [comment]
@xaoxuu  

那个……

你好！
我这边links又出现了问题
https://www.skroot.cc/image/dMB4

它只能竖着显示，我找了links.ejs发现不是它的问题，links/index.md的内容我也尝试修改过，还是竖着的。

**Comment by xaoxuu** [comment]
可能是你DIY的时候哪里修改的样式影响到了那个页面的布局，你检查一下
