### ISSUE TITLE
LaTeX数学公式渲染错误

### ISSUE THREAD

**Issue by Milarodvia** [volantis-x/hexo-theme-volantis#83]
我在应用博主的主题时渲染LaTeX数学式出现错误qwq
截图：
![1.png](https://i.loli.net/2019/05/20/5ce22e940a9b981435.png)
![5ce22e944915974890.png.png](https://i.loli.net/2019/05/20/5ce22e944915974890.png)
![2.png](https://i.loli.net/2019/05/20/5ce22e94634f775984.png)
先前已经有一位大佬提过了这个issue，但是还没有得到解决qwq
希望博主可以修复一下。

**Comment by Milarodvia** [comment]
我的博客地址：https://milarodvia.github.io

**Comment by xaoxuu** [comment]
你看看这个能解决你的问题不 #66

**Comment by Milarodvia** [comment]
> 你看看这个能解决你的问题不 #66

看不太懂qwq，有没有什么直接的解决方案吗qwq

**Comment by xaoxuu** [comment]
你在有公式的文章的front-matter中添加这行试试：
```
mathjax: true
```
