### ISSUE TITLE
可以进入首页，但是点击文章后弹出下载界面

### ISSUE THREAD

**Issue by z-traveler** [volantis-x/hexo-theme-volantis#85]

**Comment by xaoxuu** [comment]
是不是哪个依赖缺失了或者配置文件里的参数冲突？有没有试过重新安装呢？
可以参考这个源码： https://github.com/xaoxuu/blog-example

**Comment by LxnChan** [comment]
根目录配置文件permalink行最后添加“.html”看看能不能解决你的问题
