### ISSUE TITLE
valina评论失效

### ISSUE THREAD

**Issue by wzono** [volantis-x/hexo-theme-volantis#86]
1. 已在根目录配置文件配置key&id
2. 主题配置文件启用了valina

遇到的问题：
1. 在本地评论区一直处于loading状态
2. 控制台无报错
3. network中没有看到valina相关请求

**Comment by xaoxuu** [comment]
现在还是不能用吗？

**Comment by wzono** [comment]
我切换到了github的评论，没有试valina了

**Comment by 82kg** [comment]
前阵子 valina 的域名出问题了。旗下所有的服务都受影响了
