### ISSUE TITLE
音乐播放插件问题

### ISSUE THREAD

**Issue by LDlornd** [volantis-x/hexo-theme-volantis#87]
修改了歌单的 ID 后，在本地服务器上跑页内歌单一直是默认歌单没有变怎么解决？

**Comment by LDlornd** [comment]
知道了，它的配置文件里面有两处和音乐播放插件有关，好像是以 sidebar 处的配置为准，而我只修改了 music 的那一处。

**Comment by melodyjerry** [comment]
@LDlornd 请问你是怎么设置音乐的。我的配置里面修改了音乐那块，但是博客什么都没有显示
