### ISSUE TITLE
是否可以文章分类列表加到手机端的导航里？

### ISSUE THREAD

**Issue by 1kuxyz** [volantis-x/hexo-theme-volantis#89]
现在手机端的右上角的导航只能添加链接，能不能把文章的分类列表加进去，类似分类小部件那样，这样在手机端浏览时，可以方便跳转到不同文章分类，就不用想现在每次到要拉到底部的分类小部件选择。

**Comment by xaoxuu** [comment]
好建议👍🏼我后续更新想办法加入这个选择
谢谢！

Outlook<https://aka.ms/qtex0l> for iOS
________________________________
发件人: 一库xyz <notifications@github.com>
发送时间: Tuesday, July 2, 2019 3:40:59 PM
收件人: xaoxuu/hexo-theme-material-x
抄送: Subscribed
主题: [xaoxuu/hexo-theme-material-x] 是否可以文章分类列表加到手机端的导航里？ (#89)


现在手机端的右上角的导航只能添加链接，能不能把文章的分类列表加进去，类似分类小部件那样，这样在手机端浏览时，可以方便跳转到不同文章分类，就不用想现在每次到要拉到底部的分类小部件选择。

**Comment by xaoxuu** [comment]
不打算做这个功能了，分类少的话可以手动添加链接，分类多的话显示不下。
