### ISSUE TITLE
请问基本配置import字段放在哪个文件里面

### ISSUE THREAD

**Issue by yinuxy** [volantis-x/hexo-theme-volantis#91]
如果你发现 无法使用 或者效果与示例有较大区别，可以使用hexo官方提供的用于单元测试的博客应用本主题查看样式是否正常，对比_config.yml文件排查问题。

## 下载单元测试：

Hexo官方的单元测试博客： [https://github.com/hexojs/hexo-theme-unit-test](https://github.com/hexojs/hexo-theme-unit-test)。
如果你的系统是macOS，则可以使用hexo.sh脚本一键完成测试。

## 提问前请先认真阅读文档

文档：[https://xaoxuu.com/wiki/material-x/](https://xaoxuu.com/wiki/material-x/)

**Comment by xaoxuu** [comment]
根目录的

Outlook<https://aka.ms/qtex0l> for iOS
________________________________
