### ISSUE TITLE
搜索用不了

### ISSUE THREAD

**Issue by LxnChan** [volantis-x/hexo-theme-volantis#93]
搜索框里输入内容，然后搜索，可以弹出框框，进度条一直在停。什么都不显示。

**Comment by BedrockDigger** [comment]
用的是哪种搜索服务？

**Comment by xaoxuu** [comment]
请看[文档](https://xaoxuu.com/wiki/material-x/#B-%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85)

**Comment by axinhouzilaoyue** [comment]
我按文档设置了，也下载了插件。可还是什么都搜索不出来
