### ISSUE TITLE
示例博客

### ISSUE THREAD

**Issue by xaoxuu** [volantis-x/hexo-theme-volantis#97]
## 开源博客

| 博客        | 链接                      | 源码                                       |
| :---------- | :------------------------ | :----------------------------------------- |
| Example     | https://mxclub.github.io/ | https://github.com/xaoxuu/blog-example     |
| appx online | https://appx.online/      | https://github.com/appx-online/appx.online |

## 特别DIY示例

| 博客         | 链接                 | 说明 |
| :------------ | :-------------------- | :----- |
| 搅拌糖 | https://blog.treelo.xin/ | 动态背景、鼠标点击动画、看板娘 |
| YuGao's Blog | https://sxyugao.top/ | 实现了ajax |
| YangWC | https://yangwc.com/ | 暗色主题 |
| LiYanan2004 | https://liyanan2004.github.io | 可切换主题 |
| codercc | https://www.codercc.com/ | 导航栏二级菜单、左图右文的文章列表、轮播图 |
| 泠泫凝 | https://arlxn.xyz | 卡片半透明、点击特效 |
| 孤独与诗 | https://createdestruction.github.io/ | 动态背景 |
| Steven_MengのBlog | https://stevenmhy.tk |

### 新版本

| 博客         | 链接                 |
| :------------ | :-------------------- |
| MicDZ's blog | https://www.micdz.cn |
| Mark's blog | https://mark-thinkpad.gitee.io/ |
| yangtao's blog | https://istaotao.com |
| ZYMIN | https://zymin.cn/ |
| 香蕉博客 | https://tohot.top/ |
| TRHX'S BLOG | https://itrhx.com/ |
| Michael Vector | https://michaelvector.github.io/ |
| 预见未来 | https://lijunkui.netlify.com/ |
| P_Wang's Blog | https://tle666.github.io/ |
| wxwoo's blog | https://wxwoo.top |
| Wiyeelu | https://wiyeelu.github.io |
| CRainyDay | https://crainyday.gitee.io/blog/ |
| TRHX | https://itrhx.com/ |
| FutureApple | https://www.pghk.tk/ |
| xyhthink | https://www.xyhthink.com/ |
| Melody Player | http://melodyplay.cn/ |
| Root's Blog | https://tangyanqiong.com/ |
| 一起2一起3 | https://www.172173.com |
| IntPtr.Zero | https://intptrzero.github.io/ |
| cwxyr | https://sublimerui.top/ |
| fordes123 | https://fordes123.github.io/ |
| yanliang | https://gyl-coder.top |
| 海露-XShell.CN | https://www.xshell.cn |
| candysky | www.candysky.top |
| BFDZ | https://www.bfdz.ink |
| Shan San | https://shansan.top/ |
| 王大可 | https://blog.1314.io/ |
| ChrAlpha | https://chralpha.com |
| Linhk1606's Blog | https://orzlhk.codes/ |

### 旧版本

| 博客         | 链接                 |
| :------------ | :-------------------- |
| MainGuo | https://blog.mainguo.top |
| gltjk | https://blog.gltjk.com |
| Amblizer's Mainframe | https://amblizer.xyz |
| Digcore | https://www.digcore.cn/ |
| Sparky_14145's blog | https://www.sparky-14145.com |
| 贾程序员 | https://mofiter.com/ |
| Loser007 | http://www.loser007.com/ |
| Tony Ren's blog | https://tonyrenhk.github.io/ |
| Alice | https://zhengjiameng.github.io/ |
| 小肥羊 | https://lucksheep.github.io/bgzy/ |
| 萌焰博客 | https://yanhuang0815.github.io |
| zerbo's blog | https://blog.zerbo.cn/ |
| weijiajin's blog | https://weijiajin.com |
| lightsmile's Blog | http://www.iamlightsmile.com/ |
| 红发 | https://hgneer.github.io/ |
| main's blog | https://www.intmian.com/ |
| codelearn.club | https://codelearn.club/ |

如果你使用了 **Material X** 主题，欢迎在下方留言告诉大家，我会抽时间归纳到这里~

由于人数较多，有时候我通过死链检测工具检测到有链接无法访问了，会直接从列表中删除。如果你的链接恢复正常了，可以留言告诉我，我从git记录里恢复一下。

**Comment by IntPtrZero** [comment]
https://intptrzero.github.io/

**Comment by MujeyF** [comment]
https://mujeyf.cn

**Comment by PancakeCN** [comment]
作者大大，麻烦添加一下我的博客呀(๑´ㅂ`๑) ，自己精心修改了很多~
https://sublimerui.top/

**Comment by fordes123** [comment]
https://fordes123.github.io/

**Comment by ZhaoTim** [comment]
http://zhaomeicheng.com 小透明路过（只是换了个背景图）

**Comment by gaoyanliang** [comment]
https://gyl-coder.top

**Comment by hailou** [comment]
https://www.xshell.cn

**Comment by LxnChan** [comment]
大佬好：
自您添加本站（https://arlxn.xyz）到示例页已有一段时间，部分特性已经得到更改，请您在方便的时候进行修改。
已删除的特性：live-2d、幻灯片背景
新加入特性：文章摘要卡片半透明、作者卡片动态签名/自定义内容、动态线条背景、鼠标点击特效、Google Ads（已停用）

**Comment by candyboyou** [comment]
www.candysky.top

**Comment by BFDZ** [comment]
我的博客 https://www.bfdz.ink/ 
已升级新版本，请大佬改一下示例

**Comment by xuqil** [comment]
wiki系统怎么添加，最需要的就是这个功能

**Comment by wsqstar** [comment]
https://blog.1314.io/ 
感觉大佬的这个非常不错啊！

**Comment by wsqstar** [comment]
> wiki系统怎么添加，最需要的就是这个功能

vuepress 可以满足你的需求嘿嘿嘿

**Comment by xaoxuu** [comment]
@xuqil https://github.com/xaoxuu/hexo-theme-vuex

**Comment by iChrAlpha** [comment]
直接丢链接：https://chralpha.com

**Comment by Han-Yu-Meng** [comment]
https://stevenmhy.tk/ 自己乱魔改了一点

**Comment by melodyjerry** [comment]
怎么实现卡片半透明？？？？

**Comment by Reqwey** [comment]
https://linhk1606.github.io (新域名为https://orzlhk.codes)

Version 1.2.6

**Comment by Reqwey** [comment]
@xaoxuu 我的网站又改域名了，新的域名是https://blog.lhkstudio.me (*^_^*)

**Comment by qiangzii** [comment]
https://blog.atuo.store

**Comment by 233213fedf** [comment]
http://sarahaza.liil.cc/
改的不咋地(ノ￣▽￣)

**Comment by Robin-zero** [comment]
大佬，我用的 Material X，没怎么修改！
R 喵呜的小窝
http://www.rshow.top/

**Comment by wztlink1013** [comment]
使用你的主题，效果很不错，自己域名已备案，https等、望采纳 
[](https://wztlink1013.com)

**Comment by wztlink1013** [comment]
使用你的主题，效果很不错，自己域名已备案，https等、望采纳
[尼采般地抒情](https://wztlink1013.com)

**Comment by wztlink1013** [comment]
使用你的主题，效果很不错，自己域名已备案，https等、望采纳
[https://wztlink1013.com](https://wztlink1013.com)

**Comment by xaoxuu** [comment]
以后示例博客建议自助写在文档中，排版更好看一些，也更方便查阅。

效果以及添加方法：https://xaoxuu.com/wiki/volantis/examples/

**Comment by wztlink1013** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        好的，谢谢！
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2550374815
                            
                    
                        
                            
                                    2550374815@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年2月26日 22:56，Mr. X<notifications@github.com> 写道： 


以后示例博客建议自助写在文档中，排版更好看一些，也更方便查阅。

效果以及添加方法：https://xaoxuu.com/wiki/volantis/examples/



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
